### ISSUE TITLE
✈Travel issues for Prizren, Kosovo

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#102]
Originally in #89. 

## コソボまで安く安全に確実に辿り着くミッション
- yuisekiはアジア圏しか旅行したことがない
- トランジットとかしたことない
- 航空便もすごい値段でビビっている
- 早めに航空便を確保しておかないともっと高くなりそう
- 選択肢が多すぎるので、誰かについていく形にしたい
- みなさんのプランをお伺いしたい
- 特にこだわりはないが、「最大のレアな経験が得られる移動」だと嬉しい

**Comment by smellman** [comment]
- 航空券はExpediaで探している
  - https://www.expedia.co.jp/Flights-Search?d1=2023-06-22&d2=2023-07-04&flight-type=on&fromDate=2023%2F6%2F22&leg1=from%3A%E6%9D%B1%E4%BA%AC%20%28NRT%20-%20%E6%88%90%E7%94%B0%E5%9B%BD%E9%9A%9B%E7%A9%BA%E6%B8%AF%29%2Cto%3A%E3%83%97%E3%83%AA%E3%82%BA%E3%83%AC%E3%83%B3%2Cdeparture%3A2023%2F6%2F22TANYT&leg2=from%3A%E3%83%97%E3%83%AA%E3%82%BA%E3%83%AC%E3%83%B3%2Cto%3A%E6%9D%B1%E4%BA%AC%20%28NRT%20-%20%E6%88%90%E7%94%B0%E5%9B%BD%E9%9A%9B%E7%A9%BA%E6%B8%AF%29%2Cdeparture%3A2023%2F7%2F4TANYT&mode=search&options=cabinclass%3Aeconomy&passengers=children%3A0%2Cadults%3A1%2Cseniors%3A0%2Cinfantinlap%3AY&toDate=2023%2F7%2F4&trip=roundtrip
  - 日付を変えると安い日が出たりするので注意が必要
- ExpediaではPrizrenの宿はほぼ全滅している
 - Booking.comはまだ空きがある
 - アパートなども借りられるので2人ぐらいなら一緒の宿にしてしまうという手がある。
 - イタリアに比べるとどれも安いという印象はある。

**Comment by hfu** [comment]
私もアパートを中心に少し調べてみました。
まだ選べる状態にある一方、複数人で使えるほどの大規模のものは多くはなく、今回は学事暦の関係から学生さんの参加も多くはないであろうことも考えると、地域を合わせることはあれ、宿は別にしつつ、行程を揃えたり、夕食で集まったり、といったところで連携していくのかなと思いました。結果的に、フィレンツェのときのパターンと近いのかなと思っています。

**Comment by hfu** [comment]
# 移動ロジ
- プリシュティナ・ルート（バスでプリズレン）
  - 空港近くかプリシュティナに宿がある
  - 空港から直接プリズレンに行くバスもある
- プリズレンは宿が少なくなってきている（Expedia はもう売り切れている感じ。booking.com にはまだある。）

**Comment by ShogoHirasawa** [comment]
## 古橋先生 + 平澤の宿泊場所
- 会場から徒歩20分程度の場所にAirbnbで宿を確保。国交相メンバー（3人）もここに泊まるかも？
https://maps.app.goo.gl/SmGvAWtsEtFusvfT8?g_st=ic

## 皆様に質問
プリティシュナ国際空港から会場までのバスの情報ってどこで確認できるでしょうか？もしご存知の方がいれば、共有していただけると助かります🙇‍♂️

**Comment by smellman** [comment]
> All international flights to Kosovo arrive at the Prishtina International Airport. From Prishtina International Airport there is a Public transport bus line from Prishtina International Airport to the Bus Station in Prishtina. Bus lines from Prishtina Bus Station to Prizren travel every 20 minutes (5 EUR).
https://2023.foss4g.org/tourism
空港からの情報だけど、たぶんプリティシュナからでもあると思います。
詳細分かったらまた連絡します。

**Comment by hfu** [comment]
My travel was approved in my office, and I am starting to prepare the travel. Unfortunately, I will be the only person to travel to Kosovo from my office (GSI).

**Comment by hfu** [comment]
## In/Out of @hfu 
In: 2023-06-25 Sun
Out: 2023-07-01 Sat

**Comment by hfu** [comment]
おおむね、このイシューで共有できる情報は共有できたかなと思っていますし、確定した現場情報は別途 Messenger のチャンネルで進めてもいいかなと思いますので、このイシューはいったんクローズします。必要であればリオープンしてください。
