### ISSUE TITLE
Prepare for Monthly meeting in November

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#11]
- [x] Decide the way to collaborate - shall we use Google Slides?
- [x] Ask Objective Owners and other participants for their input. 
- [x] Edit and finalize the Google Slide.
- [x] Present in the Monthly VTC.

**Comment by ubukawa** [comment]
Thank you @hfu for your leadership.
I will report UN Deployment progress. But, its schedule is now up to the ICT colleagues in UNGSC, and I cannot introduce our schedule with specific date.

About the hackathon report, I know the number of the submission, etc, but need to check what I can report here.
(Kyoung-Soo may report it on the other agenda, but let me check, and I will get back to you....)

**Comment by hfu** [comment]
Thank you, @ubukawa. My idea is that we keep our report simple and short. Let's proceed on Google Slides.

**Comment by hfu** [comment]
I dropped UN EC Hackathon to avoid duplication.

**Comment by ubukawa** [comment]
Thank you @hfu . 
I am sorry to be late, but Kyoung-Soo will mention about the hackathon at the any other business.
(It will be a general report of the hackathon. If there is anything you would like to add, you can jump in. Thank you!)

**Comment by hfu** [comment]
Presentation finished.
