### ISSUE TITLE
FOSS4G Presentation acceptance

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#110]
FOSS4G presentation の状況について共有しましょう。

**Comment by hfu** [comment]
私の提案はこんな感じでアクセプトされました。
@yuiseki 引き続きよろしくお願いします！

![ 2023-04-03 19 45 13](https://user-images.githubusercontent.com/18297/229488222-455b821e-7702-47bd-9df1-541fa24bb6a6.jpg)

**Comment by smellman** [comment]
僕もAcceptされました。30分のトークです。
4/6ぐらいにはまずは飛行機を取っておきたいと考えています。
@yuiseki 一緒に行く予定にするなら別途作戦会議しましょう。

**Comment by hfu** [comment]
情報共有はできたのでクローズします。
