### ISSUE TITLE
🌱Community name card

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#115]
イベント参加時のコミュニケーションに役立つ「コミュニティ名刺」が欲しい

備忘録的にIssueにしておきます！

**Comment by hfu** [comment]
私の名刺の裏面は次のようにしています。ご参考まで。

**Comment by hfu** [comment]
Maybe I shoud update the URL from https://github.com/unopengis/7 to https://unopengis.github.io/smartmaps.

**Comment by hfu** [comment]
Maybe it is good time to think about this! Let's discuss in #167.

**Comment by hfu** [comment]
知って関わる人を増やすのが目的
我々は何者なのか
コミュニティが存在すること、参加ができること
名刺サイズかな
「プリントパック」が速い
hfu が一案つくってここで相談
日曜日の夕食で共有

**Comment by hfu** [comment]
## Minor update on layout

<img width="475" alt="スクリーンショット 2023-06-07 22 43 31" src="https://github.com/UNopenGIS/7/assets/18297/f3b45548-2059-4fbd-9fcd-940937ee91ec">

**Comment by yuiseki** [comment]
@hfu 私の方でも提案をしたいと考えています。hfuさんが使っているフォントの名前を教えていただきたいです

**Comment by yuiseki** [comment]
私なりの叩き台を作ってみました

### 表
[![Image from Gyazo](https://i.gyazo.com/0dda90f518b2895bc5917ca1860889d0.png)](https://gyazo.com/0dda90f518b2895bc5917ca1860889d0)

### 裏
[![Image from Gyazo](https://i.gyazo.com/2e96cf6f5863db0969f5ba402d7dd402.png)](https://gyazo.com/2e96cf6f5863db0969f5ba402d7dd402)

**Comment by yuiseki** [comment]
私が注意しているポイントを言語化してみます：

- 「真の黒 `#000000` 」は慎重に使う
  - 「真の黒」は目立ちすぎるため、特別に強調したい場合のみ使うようにします
  - 例えば https:///un.org/en/ でも、ファーストビューで「真の黒」が使われているのは「United Nations」という文字列のみです
  - 上の叩き台では、「UN Open GIS Initiative Smart Maps Group」という文字列のみ、「真の黒」を使っています
  - それ以外は、デジタル庁のWebサイトにあわせて `#343434` にしてみました
  - https:///un.org/en/ に併せて `#696969` にするのも良いかもしれません
- ある程度行間があったほうが読みやすいので、行間を確保しています
- 文字列の伝えようとする情報の意味に応じて、フォントサイズを変えています
  - 見出しは大きく、内容は小さく
- 情報を過度につめこまない、埋め尽くさないようにしています
  - 一般的に、あえて効果的な空白があったほうが洗練されて見えます

**Comment by hfu** [comment]
素晴らしい！ありがとうございます！！

今判断するとしたら、@yuiseki さんの案をそのままいただきたいです。

**Comment by yuiseki** [comment]
@hfu @smellman Googleカレンダーを作る際に教えていただいたメールアドレス宛で、Canvaのプロジェクトに招待しました。ご確認ください。

閲覧専用のリンクもこちらで共有しておきます
- 表面
  - https://www.canva.com/design/DAFlM7LRWDg/IzOTphhuSHYPyuy2Gw3kWw/view?utm_content=DAFlM7LRWDg&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink
- 裏面
  - https://www.canva.com/design/DAFlNMX34WU/zf_Qoiam_-AxPvbIqyTLiQ/view?utm_content=DAFlNMX34WU&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink

**Comment by yuiseki** [comment]
ちょっとアップデートしてみました

## 表面

[![Image from Gyazo](https://i.gyazo.com/37cb71f2817f1498673a28238f18e15b.png)](https://gyazo.com/37cb71f2817f1498673a28238f18e15b)

## 裏面

[![Image from Gyazo](https://i.gyazo.com/f249fdb33c609ef3f9dc33311a2ed319.png)](https://gyazo.com/f249fdb33c609ef3f9dc33311a2ed319)

## レイアウトの意図の解説

[![Image from Gyazo](https://i.gyazo.com/db0b523eb3a8ba58fc39cf45576fcb5c.png)](https://gyazo.com/db0b523eb3a8ba58fc39cf45576fcb5c)

**Comment by hfu** [comment]
@yuiseki This is the best UN Open GIS logo image I have! 
![unopengis](https://github.com/UNopenGIS/7/assets/18297/2d47efa5-13da-4a9e-a80e-443581538acd)

**Comment by hfu** [comment]
テキストの黒色の件、テストしてみました。一行目から、`#000000`, `#343434`, `#696969` です。

<img width="974" alt="スクリーンショット 2023-06-14 21 50 47" src="https://github.com/UNopenGIS/7/assets/18297/fb42d809-41d1-47b4-b776-ff57140669d9">

フォントは UN Web サイト標準の Roboto です。

**Comment by hfu** [comment]
## フォントについて
デザインが強い場合には Futura を使いますが、Future は地の文には強すぎる感じがします。
地の文については、UN Web サイト標準の Roboto を使うことが多いです。印象としては Noto Sans とほとんど同じなのかなと思っています。

**Comment by hfu** [comment]
## HackMD プレゼントの関係
Hack MD プレゼンについても、フォントやフォント色などここでの成果を反映してみようと思いましたが、私にはうまく手掛かりがつかめませんでした。 https://hackmd.io/@hfu/2023-06-29

**Comment by hfu** [comment]
@yuiseki https://github.com/UNopenGIS/7/issues/115#issuecomment-1583816649 から引かれている Gyazo のファイルを Issues にドラッグドロップして貼り付けて頂くことは可能でしょうか。（私のエンタープライズ環境からは、Gyazo ドメインにアクセスできないようです。）

githubusercontents.com の画像は私のエンタープライズ環境からも取れるので、今日のうちにカード印刷を開始することが可能になります。

**Comment by yuiseki** [comment]
了解です！後ほどメンションする形で送ります！

**Comment by yuiseki** [comment]
@hfu こちらでお願いします！


![UN Smart Maps Community Name Card (Front) (1)](https://github.com/UNopenGIS/7/assets/25507/18775cad-9b96-46ec-a372-b58a3f9b5d33)

![UN Smart Maps Community Name Card (Back) (1)](https://github.com/UNopenGIS/7/assets/25507/13e0e550-1285-4eab-bc7a-5e40147b7a29)
