### ISSUE TITLE
😴Smart Maps are about Geospatial Situational Awareness

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#122]
As introduced by Ki-Jouone in #92.

**Comment by yuiseki** [comment]
Share your background knowledge on Situational Awareness

- https://en.wikipedia.org/wiki/Situation_awareness
- https://ja.wikipedia.org/wiki/%E3%82%B7%E3%83%81%E3%83%A5%E3%82%A8%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%A2%E3%82%A6%E3%82%A7%E3%82%A2%E3%83%8D%E3%82%B9

**Comment by hfu** [comment]
We can talk about situational awareness in respective activities including MUNDO.
