### ISSUE TITLE
🌱How to welcome and on-board new participants

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#124]
We may need to clarify how new participants can 'enter' our DWG. 

Should they introduce their GitHub ID so that @hfu or other colleagues can invite them to the repository or the group?

**Comment by albertkun** [comment]
@hfu I think this is a very good issue, because as part of the on-boarding process we can ask what sub-group they would like to volunteer join or the skills they would like to contribute!!

**Comment by hfu** [comment]
I am closing this issue because this issue is to be considered as a part of guidance (指南) of Smart Maps Dojo.
