### ISSUE TITLE
🔥🎧2023-05-26/25 Smart Maps International Meetup #2

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#125]
The second Smart Maps International Meetup. The first one was #92. 

See #129 for agenda and logistical issues. 

I appreciate if you assign yourself if your are participating in the international meetup. Thanks!

**Comment by hfu** [comment]
# Tentative agenda

## 1. Self-introduction by new participants (if there are)

## 2. Presentations
- @albertkun on Documentation
- tbd.

## 3. Upcoming events

## 4. AOB

**Comment by hfu** [comment]
@yuiseki Would you like to make some casual presentation on MUNDO? The meetup can be an opportunity to rehearse our presentation in Kosovo.

**Comment by yuiseki** [comment]
@hfu Thanks for the suggestion! We will definitely do so! I will further refine MUNDO for the presentation!

**Comment by yuiseki** [comment]
@hfu My apologies, I forgot to mention that from May 10 to May 13 I have to attend RubyKaigi2023 as part of my duties! Therefore, I will not be able to attend on these dates... Instead, I will prepare a short demo video of about 3 minutes that describe MUNDO, and I wonder if it would be possible for @hfu to play it for me in this meetup?

**Comment by hfu** [comment]
@yuiseki Thank you for sharing. Yes, I will play the video if you kindly prepare one.

**Comment by hfu** [comment]
As discussed in #137, let's reschedule the 2nd International Meetup to a new time where all presenters (@albertkun, @yuiseki, and @hfu) can join.

**Comment by hfu** [comment]
How about just shifting one week from the standard "2nd Friday" rule? i.e.,

- 2023-05-19T13:00/14:00+09:00 for Tokyo @yuiseki
- 2023-05-18T21:00/22:00-08:00 for Los Angeles @albertkun 

Please let me know your availability.

**Comment by albertkun** [comment]
@hfu Yes, that works for me! Thank you!

**Comment by yuiseki** [comment]
@hfu I can join you on that schedule! Thanks for arranging the dates!

**Comment by hfu** [comment]
Thanks! Let's do it on 2023-05-19/18. 
I am introducing this data in the upcoming UN Open GIS monthly.

**Comment by albertkun** [comment]
Great! Thank you for suggesting a date @hfu! I hope you have a great Golden Week @hfu @yuiseki!

**Comment by hfu** [comment]
Added a slide for UN Open GIS monthly as discussed.
https://hackmd.io/@hfu/7-202304#/3

<img width="1122" alt="スクリーンショット 2023-05-03 7 04 58" src="https://user-images.githubusercontent.com/18297/235796076-482eb29d-18c7-43e4-9cc9-caa5b01e5611.png">

**Comment by hfu** [comment]
## Things to be decided. 
- [ ] As discussed in #137 and #139, each presentation will be **15 minutes**. 
- [ ] @hfu will be announcing this event in UN Open GIS MS Teams after consulting with the UN Open GIS Bureau.

**Comment by hfu** [comment]
# Invitation to Smart Maps International Meetup 2
## What is this event? 
This event is an open online event where UN Open GIS DWG 7 members share their progress so that participants can share knowledge and information. 

## When is this event?
- 2023-05-19T13:00/14:00+09:00 for Tokyo
- 2023-05-19T09:30/10:30+05:30 for New Delhi
- 2023-05-19T06:00/07:00+02:00 for Rome
- 2023-05-19T00:00/01:00-07:00 for New York
- 2023-05-18T21:00/22:00-08:00 for Los Angeles

## How can I participate?
Online (URL is to be issued). Registration is not required, but we appreciate if you could let us know by replying by chat, etc.

## Program
1. Welcome by Hidenori, DWG 7 Lead
2. Introduction by new participants
3. Documentation by Albert 
4. Model UN by Yui
5. Smart Maps Bazaar by Hidenori
6. Anything you would like to share

**Comment by hfu** [comment]
@albertkun and @yuiseki, I drafted an invitation as above (https://github.com/UNopenGIS/7/issues/125#issuecomment-1539402553). Any comments or advice?

**Comment by hfu** [comment]
After internal checking and confirmation, we can share the invitation via UN Open GIS MS Teams and DWG 7 Documentation web site.

**Comment by albertkun** [comment]
> @albertkun and @yuiseki, I drafted an invitation as above ([#125 (comment)](https://github.com/UNopenGIS/7/issues/125#issuecomment-1539402553)). Any comments or advice?
The agenda and details look great! 

## Minor suggestions for `Next Actions` agenda item 6

- **Upcoming events** - I really liked your point yesterday about how DW7 is "event driven" so I think for the "Next Actions" it would be great to mention upcoming events, specifically the Walking Tour and [Foss4g meetup](https://github.com/UNopenGIS/7-docs/issues/12) (if that is still a good idea). For participants, this might be a good way to connect the Smart Maps Bazaar Walking Tour presentation too and give them an action item- alternatively, to save time, we can instead use the documentation site's events page for this purpose.

- **Join the community?** - For another next steps maybe we can also encourage more people to use Matrix/GitHub Discussions to contribute!

**Comment by hfu** [comment]
I am consulting with UN Open GIS Bureau. No negative response so far, and I believe we can go ahead. 

@yuiseki Thanks for setting up our open google calendar. I am adding a schedule for this international meet up today.

@albertkun Could we set up a page in the Documentation site? It would be great if I can share the link to the meetup event page in the Documentation site.

@hfu will be issuing a Zoom link today and update the invitation text.

**Comment by albertkun** [comment]
@hfu Yep! I created a general page for all the community meetings:

- English: https://unopengis.github.io/7-docs/get-involved/community-meetings/
- Japanese: https://unopengis.github.io/7-docs/ja/get-involved/community-meetings/

I'll go ahead and update with individual meeting pages when we start to archive them?

**Comment by hfu** [comment]
I created a Zoom link for this meetup: 

https://us02web.zoom.us/j/82394161790?pwd=Zjg1REJlTUV1MTVDK0VqcG1UZ2E3Zz09
meeting id: 823 9416 1790
passcode: 900913

I am updating the invitation using this link.

**Comment by albertkun** [comment]
@hfu thank you! Should I post the page with the Zoom link? Also, do we still want to include the message `Registration is not required, but we appreciate if you could let us know by replying by chat, etc.` If so, how should interested people reply, do we link to the GitHub issues?

**Comment by hfu** [comment]
@albertkun How about including the zoom link and remove it after the actual session? 
I am also wondering about the replacement of the 'chat'. I was thinking about Telegram and WhatsApp in addition to GitHub, but GitHub Issue would be a best one. We like our potential participants to have a GitHub account rather than Telegram or WhatsApp account.

**Comment by hfu** [comment]
@KyoungEom Thank you for encouragement. We are planning to have upcoming *Smart Maps Bazaar Walking Tour* to cover  time zones of New York and Rome.

**Comment by hfu** [comment]
I posted the invitation on the UN Open GIS MS Teams 🚀

<img width="994" alt="スクリーンショット 2023-05-11 22 12 14" src="https://github.com/UNopenGIS/7/assets/18297/c7306e51-5967-47d5-88c6-4d6b6cbfde30">

**Comment by albertkun** [comment]
@hfu Sure! I'll remove the link after the session, and maybe replace it with a Zoom recording?

Unfortunately, I don't have Telegram or WhatsApp, but I'd be more inclined to use Telegram if we must! :)

Definitely, I agree GitHub Account would be best!

**Comment by albertkun** [comment]
Perhaps if there's more interest from New York, maybe moving future meet ups to 11:30am JST? This would mean the following:

    2023-XX-18T19:30/21:00-08:00 for Los Angeles
    2023-XX-19T22:30/23:30-07:00 for New York
    2023-XX-19T04:30/05:30+02:00 for Rome
    2023-XX-19T08:00/09:00+05:30 for New Delhi
    2023-XX-19T11:30/12:30+09:00 for Tokyo

If we go with this, sorry to India and especially Rome 😭

**Comment by albertkun** [comment]
@hfu OK that sounds good! Also, I am the same in that I would use Matrix more often 👍 Thanks for sharing the issue! I'll go ahead and update the web site to link to it later today!

**Comment by hfu** [comment]
@albertkun Thanks! Let's keep the time for the International Meetup as it is. Instead let's make our Smart Maps Bazaar Walking Tour aimed for New York, Africa, and European audience. In addition, let's try to provide video recordings. 

Inspired by the message by KyoungEom, I think maybe we can use the phrase "Smart Maps Team". Which do you think is more natural and convenient to use?: 

- Smart Maps Group
- Smart Maps Team

**Comment by albertkun** [comment]
@hfu I like the idea of providing recordings! I know Zoom has a 60 day recording policy, meaning if we want to keep it longer we'd have to upload onto YouTube or another service.

I like both Smart Maps Team and Smart Maps Group! Team sounds a bit easier to say. I can ask my students later today what they like if you want to get a researched opinion from youth! 😂

**Comment by hfu** [comment]
@albertkun Preference to Matrix would be one of our strong points. We like to use cool open source software in its original form or in combination with web maps technology - especially vector tiles. Today I talked with @miya0001 about Apache Druid and Apache Hadoop. I am also trying to test InfluxDB.

**Comment by ubukawa** [comment]
Dear team,
Warm greetings. I am happy to see your great activities!
From this month, I started working in the Cabinet Office, and I may not be able to often join the working group activities.
My sincere apology that I cannot join the meeting.

However, I keep monitoring our discussion as much as possible.
In particular, I would like to work with the land registration maps in Japan, and am interested in documentation and MUNDO progress, because they will be related to my tasks in my new position.

All the best!!

**Comment by albertkun** [comment]
@ubukawa As per #152 we moved the date to next week. Hopefully you can join us for the international meet up on 2023-05-26 if time permits with your new position in the Cabinet Office! 😊

**Comment by albertkun** [comment]
@hfu Can we make sure that the correct Zoom link is used!! 

Here it is:

https://ucla.zoom.us/meeting/register/tJcoc-mvrTovG920aIcgb-64RaKdVWKTb1Ik

**Comment by hfu** [comment]
@albertkun Yes, I confirmed the link is up to date. Thanks👍. 

<img width="453" alt="スクリーンショット 2023-05-24 4 30 00" src="https://github.com/UNopenGIS/7/assets/18297/be901f6e-2c26-414b-b76d-0577f83ce8c6">

**Comment by hfu** [comment]
@yuiseki Thank you for pinning the issue. I didn't know about this functionality.

**Comment by hfu** [comment]
## Presentation from @hfu 
https://hackmd.io/@hfu/smi2

**Comment by hfu** [comment]
## Hotwash by @hfu 
- I had a problem with WiFi connection. I needed to move in the last minutes and so my background and video direction was bad. (Thank @albertkun for introducing the way to fix the video direction!) 
- Time keeping was not too big problem for us. I am confortable with the meetup format. 
- It was a great opprotunity to practice demos and presentations. I see that our community is **event-driven" and we can learn a lot by having meetings. I think we will be better by having more meetups.
- Thanks for your time!

**Comment by albertkun** [comment]
The zoom recording is only available for 120 days:

https://ucla.zoom.us/rec/share/GO9TVLRntG68hbjA0p4Ofd5y3NBzmnR9osdsJVmlX5Kt6zvbDAjCOgBucLkkpaJA.X_zLWS-98-dGIDT1

(this recording should be available at 2023-5-25 3pm JST) 

We can download and host on YouTube or another platform!

(If we post on YouTube or we I have time I can also edit the recording so that @hfu's camera is not flipped!)

**Comment by hfu** [comment]
@albertkun Thank you for the recording things. We do have a UNVT account on YouTube https://www.youtube.com/@unitednationsvectortiletoo1443 so we can use it as a temporary solution before we use YouTube more strategically. 

I really appreciate if you could edit the video a little bit to make nice. I am happy to remain flipped 🙃 but some trimming and possibly adding titles would make our video feel somewhat professioal. What do you think?

I am also happy to host the edited video file on IPFS. It would be a great opportunity the experiment. 

## Additional hotwash
- It was great to have more participants from Japan. We had less international participants. I think what we should to have a better on-boarding process and add more reasons to participate in the meetup. We can discuss in #159.

**Comment by hfu** [comment]
## Some things which came to my mind
- I appreciate cool NLP-based inputs by @yuiseki. That is why I describe our mission as *test new technologies for future geospatial operations*. 
- We are an open community of practice gatherd [because it is fun to program](https://en.wikiquote.org/wiki/Linus_Torvalds).

**Comment by hfu** [comment]
Maybe we can describe us "crossover professionals" because most of us made a crossover from ICT to geospatial. ;-)

**Comment by hfu** [comment]
@albertkun I would like to ask for your advice on the video. Can we download the video file from Zoom so that we can (edit and) upload? Or shall we share the Zoom recording link on https://unopengis.github.io/smartmaps/get-involved/community-meetings/international/2023-05-26 so that we can invite friends to watch the video? 

> The following Zoom recording is only available for 120 days:
> 
> https://ucla.zoom.us/rec/share/GO9TVLRntG68hbjA0p4Ofd5y3NBzmnR9osdsJVmlX5Kt6zvbDAjCOgBucLkkpaJA.X_zLWS-98-dGIDT1
> 
> (it will be available at 2023-05-26 3pm JST)
> 
> We can download the recording and host on YouTube or another platform!
> 
> (If we post on YouTube or we I have time I can also edit the recording so that @hfu's camera is not flipped!)

**Comment by albertkun** [comment]
@hfu Yes, we can download the video off of Zoom and upload to probably the YouTube channel mentioned below:

> We do have a UNVT account on YouTube https://www.youtube.com/@unitednationsvectortiletoo1443 

Should we think about 1) making a new UN Smart Maps YouTube channel or 2) rebranding UNVT to UN Smart Maps? 

I'll defer to your decision!

**Comment by hfu** [comment]
@albertkun Thank you! I think 1) would be simpler and more likely to be set up better. Could you possibly set up the channel?

**Comment by albertkun** [comment]
Sure @hfu, I have no problem setting it up later tomorrow! Do we have a general email address? If not, should we create a UN Smart Maps Gmail account? It might be easier than having me use a personal Gmail account!

**Comment by hfu** [comment]
Thank you so much, @albertkun! It would be wise to create a UN Smart Maps GMail account because we do not still have a general email address for UN Smart Maps Group.

**Comment by albertkun** [comment]
@hfu The Google account was created and DM'd to you over Matrix! Also, here's the YouTube channel (no content yet):

https://www.youtube.com/@UNSmartmaps
