### ISSUE TITLE
🌱Metaverse - how can we start working on it? 

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#126]

**Comment by hfu** [comment]
Thank you, @yuiseki for assigning yourself. Let's talk in meetups and possibly int'l meetups.

**Comment by santoshgaikwad23** [comment]
I suggest to have a introductory session on Metaverse in GIS by some expert from the group to educate the other members who are not aware about it. This will help in building up the use cases.

**Comment by hfu** [comment]
## Some potentially related information
- https://www.ogc.org/press-release/ogc-announces-new-geo-for-metaverse-domain-working-group/
- https://www.linuxfoundation.org/press/open-metaverse-foundation

**Comment by yuiseki** [comment]
I took the term metaverse to include augmented reality.
And I found some great use cases and application examples of GIS and augmented reality to share:
- https://twitter.com/uezochan/status/1600687221505683456
  - > キャラクターがARで道案内してくれるアプリ #ARキャラナビ をリリースしました🎉
  - > ポーズや表情をつけてスナップ撮影もできます📸
  - > VRM形式に対応。みんなのkawaii🥰アバターにいろんなところに連れていってもらおう！🐾
  - Translated:
  - > We've released #ARCharaNavi, an app that gives you directions with AR characters 🎉.
  - > You can take snapshots with poses and expressions 📸.
  - > VRM format supported. Let's have your kawaii🥰 avatar take you to various places! 🐾

**Comment by yuiseki** [comment]
I feel it is worth mentioning here that Apple has announced Vision Pro. Vision Pro is focused on AR, not VR, and could be a further advancement of HoloLens. Please continue to share any news with us here at Issue.

**Comment by hfu** [comment]
#274
