### ISSUE TITLE
Housekeeping: Add more milestones

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#128]
Add more milestones to this issues so that we will have more clear idea about the timeline and schedule. 
To be done by @hfu, but comments welcome.

**Comment by albertkun** [comment]
In terms of milestones, I'd like to get a prototype for #119's Documentation by next International Meetup (#125 )!

**Comment by hfu** [comment]
Wow, that is great. May I ask @albertkun to make a casual presentation of Documentation SWG in #125? 

I also drafted the 'standard' agenda of international meetups on #129.

**Comment by hfu** [comment]
I also added a milestone for Int'l Meetup in May. :-)

**Comment by albertkun** [comment]
> Wow, that is great. May I ask @albertkun to make a casual presentation of Documentation SWG in #125?
> 
> I also drafted the 'standard' agenda of international meetups on #129.

Sure, I would be happy to give a presentation! Of course, if someone else would like to present the Documentation website, I am more than happy to facilitate! 😄

**Comment by hfu** [comment]
@albertkun Thank you. I updated #125. 

For I have added milestones to open issues, I close this issue now.
