### ISSUE TITLE
🗒Typical (standard) agenda for Smart Maps International Meetup

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#129]
# Suggested agenda

1. Self-introduction by new participants
2. Casual presentations by participants
3. Upcoming events and opportunities
4. AOB and the way forward

- Presentation will be by invitation or by submitting issues here with 'meetup' labels.
- @hfu organizes the suggested agenda before each meetup. 
- Meetup participants are encourage to 'assign' themselves to the GitHub issue of the international meetup. 

# Date and Time
- Ahmedabad 09:30/10:30 Second Friday of each month
- Bangkok 11:00/12:00 Second Friday of each month
- Los Angeles 21:00/22:00 Second Thursday of each month
- Tokyo 3:00/14:00 Second Friday of each month

# Meeting Room
We no longer use Teams for international meetups. Instead we are using Zoom with help from @albertkun. 

<strike>
https://teams.microsoft.com/l/meetup-join/19%3ameeting_Y2U4YmZlYTItNzAwYy00NjVmLWFhYWMtNGM3MDE4NmRlNTVk%40thread.v2/0?context=%7b%22Tid%22%3a%22cdec79b4-6c91-4d03-bccf-b473d5a597a2%22%2c%22Oid%22%3a%221bd03f32-5b15-482f-a430-fd6dda338eb3%22%7d

Conference ID: 444 050 512 719
Passcode: CRMtn6
</strike>
Comments welcome!

**Comment by hfu** [comment]
We should move this information from an Issue to some Document once we make a rough consensus.

**Comment by hfu** [comment]
@albertkun 
We want to send this information to the Documentation site in future. We will be closing this issue then.

**Comment by albertkun** [comment]
@hfu Ok, sounds good! I will move this over to the documentation site soon. I have created an international meet up page (not uploaded yet). Will the MS Teams link stay the same for all future meetings?

**Comment by hfu** [comment]
Merged to the Documentation site as in https://github.com/UNopenGIS/smartmaps/commit/4fab8286bb0cbec0eee39e859afc9656f13a9c05.
