### ISSUE TITLE
Add "Smart Maps Core" Objective

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#13]
Smart Maps Core may include tools like: 
- unvt/charites
- unvt/equinox

**Comment by hfu** [comment]
```mermaid
graph TD;
    Core-->UN_Operation;
    Core-->GSI_Operation;
    Core-->UNVT_Portable;
    Core-->Smart_Campus;
    Core-->Spatial_ID;
    Core-->Sensor_Integration
```

**Comment by yuiseki** [comment]
Since you have been assigned to me, I will write my opinion.

From my experience, I suggests that Smart Maps Core should consider including tools outside of the organization like followings:
- tippecanoe
- tilemaker
- openmaptiles
- vt-optimizer

Or should the scope of Smart Maps Core be clearly defined?

**Comment by hfu** [comment]
As in our [Project Document](https://github.com/UNopenGIS/7/wiki/Project-Document), an Objective can be described under the following format. 

## Objective 7: Core
### short description
### overview
### key initiatives
### key performance indicators
### owner
### participants

We can think about our Objective from the perspective of "who does what" in addition to the scope. 

We might want to **document** how we can make use of these existing open-source tools for our purposes. Or we might want to **package** them into a handy package like unvt/equinox. It will depend on how participants would like to make use of their resources for Smart Maps / UN Open GIS Initiative.

**Comment by hfu** [comment]
Core を立ち上げるかどうかは全体の流れやコミュニティの設計にも関わってくると理解するに至ったので、priority を変更しました。

**Comment by yuiseki** [comment]
> We can think about our Objective from the perspective of "who does what" in addition to the scope.

This is a very reasonable comment!

I would like to immediately suggest the following:

-----

## Objective 7: Core

### short description

Support all other objectives through understanding and utilizing the OSS and Open Data that is the Core of Smart Maps

### overview

We understand and contribute to a number of OSS and Open Data that are essential to Smart Maps. We will research and prepare other objectives to take advantage of OSS and Open Data. These OSS and Open Data may be held by several disparate organizations or individuals, but we understand and coordinate their interests.

### key initiatives

- Understand and document how important each OSS and Open Data is to Smart Maps, including how to use it
- Actively contribute to important OSS and Open Data

### key performance indicators

- Number of OSS and Open Data we utilized
- Number of OSS and Open Data we have contributed

### owner

I nominate @smellman

### participants

- hfu?
- yuiseki?

-----

For the time being, how about using the above as a starting point?
Any feedback would be greatly appreciated!

**Comment by hfu** [comment]
Hello @ubukawa, my understanding is that `docker` is not still something to avoid, and we also need to wait a little bit more before `podman` is ready for broader use cases. With that said, I tend to try `podman` before I try `docker` when necessary. 

I welcome you as a possible contributor for "Smart Maps Core" objective as long as you are thinking about creating UNVT installer for WSL. :-)

**Comment by hfu** [comment]
## Owner and participants
### Owner
@smellman, do you agree to be the owner of the "Smart Maps Core" objective? No pressure. 

### Participants
It would be nice if we have @yuiseki, @ubukawa, and @hfu as initial participants to this Objective. 

What do you think?

**Comment by smellman** [comment]
@hfu OK, no problem.

**Comment by hfu** [comment]
#28 の結果を受けて、次の内容で Project Document に転記します。

## Objective 7: Core

### short description

Support all other objectives through understanding and utilizing the OSS and Open Data that is essential to Smart Maps.

### overview

We understand and contribute to a number of OSS and Open Data that are essential to Smart Maps. We will research and prepare OSS and Open Data for other objectives to take advantage of. These OSS and Open Data may be held by several disparate organizations or individuals, but we understand and coordinate their interests. Depending on the situation, we may develop new OSS ourselves.

### key initiatives

- **Understand** and **document** how important each OSS and Open Data is to Smart Maps, including how to utilize it
- **Package** OSS and Open Data for ready-to-use
- **Contribute** to relevant OSS and Open Data

### key performance indicators

- Number of OSS and Open Data we utilized
- Number of OSS and Open Data we contributed

### owner

Taro Matsuzawa (@smellman)

### participants

- Yui Matsumura (@yuiseki)
- Taro Ubukawa (@ubukawa)
- Hidenori Fujimura (@hfu)

**Comment by hfu** [comment]
転記しました！
https://github.com/UNopenGIS/7/wiki/Project-Document#objective-7-core

イシューとしてはクローズします。
Project Document も少し掃除するようにします。
