### ISSUE TITLE
🌱Matrix, qiita, or dev.to - chat or microblogging for DWG 7 (伝習所 revisited)

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#130]
A new issue from https://github.com/UNopenGIS/7/issues/120#issuecomment-1509371467

## DWG 7 Matrix
We have a Matrix public space at 
https://matrix.to/#/#denshujo:matrix.org

The issue is that I failed to make the public space active. As a (casual) developer, I would like to have a space to share what I am doing and small IT tips. I thought it would motivate developers to move forward by proving the idea that we are not alone. 

## Alternatives: qiita and dev.to
- We have a lot of great technology blog entries by @ubukawa from https://qiita.com/T-ubu
- Mine is https://qiita.com/hfu
- Some challenge with Qiita would be that Qiita is a little bit Japan domestic. Advertisements are in local language. 
- I sometimes tried dev.to at https://dev.to/hfu, but with no good success. 

Appreciate your comments and advice.

**Comment by albertkun** [comment]
I agree that keeping any space active will be challenge, but I think having a central location for volunteers like the Documentation site (#119) can drive participation! 

I'd like to include the Matrix link (or anything else we decide using in this thread) on the Documentation site!

**Comment by hfu** [comment]
Thank you, @albertkun. I agree it would be great to have "Introduction" and "General" space for International DWG7 volunteers. 

I also agree that it would be great to have a central location that encourages participation. 

I feel that we are in a right track!

**Comment by hfu** [comment]
No next actions for this issue.
