### ISSUE TITLE
Demonstration and presentation of MUNDO in Int’l Meetup 2023-05

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#131]
- #125

**Comment by yuiseki** [comment]
### Prompt

> 国連のワーキンググループで、私達が開発しているソフトウェアをプレゼンテーションするチャンスがあります。
> このソフトウェアは国連平和維持活動の地理空間情報に関するものです。
> あなたが聴衆だとして、どのような内容を期待しますか？私に質問してください。

### GPT-3.5

> 素晴らしい機会ですね！国連平和維持活動における地理空間情報に関するソフトウェアについて、以下のような質問が思い浮かびます：
> 
> 1. このソフトウェアはどのように平和維持活動に貢献するのでしょうか？
> 2. ソフトウェアはどのような種類の地理空間情報を扱うことができるのでしょうか？
> 3. ソフトウェアの開発にあたり、どのような技術やツールが使用されましたか？
> 4. ソフトウェアはどのように運用され、どのような利用者が想定されていますか？
> 5. ソフトウェアが導入された場合、どのような効果が期待されますか？
> 6. ソフトウェアのセキュリティについて、どのような対策が講じられていますか？
> 
> これらの質問は、聴衆にとって理解を深める上で役立つ情報を提供してくれるでしょう。また、開発者の方々がどのような取り組みをされたかについても興味深いと思います。

**Comment by yuiseki** [comment]
### Prompt to follow above chat

From:
- https://github.com/yuiseki/mundo-maps/blob/main/README.md

> I will be giving a presentation to a UN working group on software we are developing.
> The software is called MUNDO; MUNDO is an acronym for "Model United Nations Development and Operations"
> 
> What is MUNDO?
> MUNDO is a Model United Nations focusing on UN peacekeeping operations and the UNDP.
> mundo-maps is focusing simulates the development and operation of geospatial information systems in the United Nations.
> mundo-maps is based on FOSS and open data like OpenStreetMap, ReliefWeb.
> 
> Why we need to build MUNDO?
> The United Nations actively promotes the development of open source software.
> However, much of the actual data from the UN is confidential and not publicly available.
> It is also not clear what kind of software and data the UN is looking for.
> Therefore, MUNDO explores the requirements of the UN by conducting a Model UN based on Open Data.
> The goal is to develop more useful OSS through these simulations.
> 
> How MUNDO is works?
> mundo-maps retrieves OpenStreetMap data through the Overpass API.
> You can define your concerns in a YAML file to retrieve data from OpenStreetMap.
> To know what is possible, look at the overpass.yml files in the ./missions/:missonName/ directory.
> OpenStreetMap has a policy of not handling temporary information.
> Temporary information is, for example, incidents, accidents, disasters, conflicts, etc.
> mundo-maps can overwrite OpenStreetMap data as needed.
> You can specify an OpenStreetMap ID to overwrite temporary information and display it on the map.
> 
> As above, MUNDO project aims to enhance geospatial situational awareness in UN international development and peacekeeping operations.
> 
> あなたが聴衆だとして、以上の内容に感想や質問はありますか？


### GPT-3.5

> MUNDO sounds like an interesting project that has the potential to contribute to UN peacekeeping operations and UNDP initiatives. I have a couple of questions regarding the presentation:
> 
> 1. Could you provide more information on how MUNDO can enhance geospatial situational awareness in UN international development and peacekeeping operations?
> 2. How does MUNDO handle conflicts between the data retrieved from OpenStreetMap and the confidential data from the UN?
> 3. Can MUNDO be used for other purposes besides UN peacekeeping and UNDP initiatives?
> 
> Thank you for sharing this information about MUNDO. I look forward to learning more about this project.

**Comment by hfu** [comment]
素晴らしいですね。MUNDO が
- 何であるのか　→　**非常にシンプルな**仕組みとルールの**ソフトウェア**
- 何を目指しているのか　→　国連に限らず、地方自治体やNGO団体などにおいても、**シチュエーションアウェアネスの強化**のために活用することができるはずのもの
が明確に示された気がします。

**Comment by yuiseki** [comment]
`mundo-maps` の `README.md` を徹底的に洗練する作戦を進めています。
いきなり英語で書くよりも、まず日本語でしっかりと書いてみるべきだと思って、 `README.ja.md` を書いてみました。

https://github.com/yuiseki/mundo-maps/blob/main/README.ja.md

もし良かったら、この `README.ja.md` をさらに洗練するために、目を通していただき、助言や質問を頂きたいです。
よろしくお願いします。

**Comment by hfu** [comment]
@yuiseki 見てみました！一点あるとすれば、次のとおりです。

- 「機密事項である」という形容は、「情報管理されている」という形容に変えた方が、よりそれっぽいかもしれません。英語で言えば、classified です。その情報が何らかの「だいじなひみつ」であるかによらず、アクセスを制限されているという意味であると理解しています。機密事項、というのは情報の**内容**に関するというニュアンスがあるきがしますが、管理情報、というのは情報の**扱い**に関します。

**Comment by yuiseki** [comment]
迅速なフィードバックありがとうございます！助かります！早速アップデートしてみます

**Comment by yuiseki** [comment]
I've updated README.md of the `mundo-maps`.

https://github.com/yuiseki/mundo-maps/blob/main/README.md

@albertkun When you have several minutes, clould you check out above markdown?

**Comment by albertkun** [comment]
> @albertkun When you have a few minutes to spare, I would like you to check out the markdown above 🙏

Looks great!! Your English is much better than my Japanese! 🥇😄 The markdown looks great, but I have just a small suggestion:
- In the `readme.md` it would be great to have a `Getting Started` section, maybe at the bottom? I notice you put some of the `npm` commands in the `How Does it Work?` section, but I think it would be helpful to add the following sections:
  - **Prerequisites** section for the software needed to run, like `node.js`, `npm`, etc.
  - **Sample project** section where you provide a sample command-line code (`npm run fetch-overpass`, etc.) and `overpass.yaml` for one of the situations you provided, like `Display medical facilities in the Republic of South Sudan.`

I think for presentation purposes the `readme.md` is great!

**Comment by hfu** [comment]
This is a part of #125. Also this issue itself is not active.

@yuiseki Do you want to keep this issue open, or can we close this issue?

**Comment by yuiseki** [comment]
Thanks for confirming. Let's close this Issue!
