### ISSUE TITLE
What do you think about the Daylight Map Distribution?

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#134]
What do you think about the Daylight Map Distribution? Let's discuss. 
https://daylightmap.org/

**Comment by smellman** [comment]
I downloaded it but I forget process it.
I will try convert it to mbtiles next week.

**Comment by yuiseki** [comment]
I just now realized that this is a very interesting project!
I will definitely try out a few things during Golden Week.

**Comment by hfu** [comment]
Added Daylight Map Distribution to https://github.com/UNopenGIS/smartmaps/blob/main/docs/resources/index.md. 
Let's say we close this issue. Thanks!
