### ISSUE TITLE
🎧2023-05-08T13:00+09:00 / 2023-05-07T21:00-08:00 Working meeting for Documentation

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#137]
As discussed in https://github.com/UNopenGIS/7/issues/119#issuecomment-1517336945

**Comment by smellman** [comment]
I will join after my company's weekly meeting.

**Comment by albertkun** [comment]
@hfu thank you for this issue! I have a couple questions:

1. Where should we meet for this? I've created a Zoom meeting for it here:

- https://ucla.zoom.us/j/96422987449

  - Alternatively, we can also meet on https://matrix.to/#/#denshujo:matrix.org or Microsoft Teams.

2. Once we have all interested people in the [documentation repository](https://github.com/UNopenGIS/7-docs/]), should we think about transferring documentation related issues over to there?

**Comment by albertkun** [comment]
> I will join after my company's weekly meeting.

Great! Looking forward to seeing you at the meeting!

**Comment by hfu** [comment]
@albertkun @yuiseki @smellman @ubukawa For some urgent business issue, I will not be able to join the meeting in 20 minutes. I am terribly sorry for my absence in this very short notice...

**Comment by albertkun** [comment]
@hfu No problem! Thank you for letting us know! We will start with a brainstorming session while we wait for you to join!

**Comment by albertkun** [comment]
@hfu We just finished the meeting and @yuiseki @ubukawa @smellman came up with this whiteboard for the layers that @yuiseki mentioned in #119 !

![Action Priority Matrix Page-1- 1682657669967](https://user-images.githubusercontent.com/8574425/235061523-1a43b81c-4979-4ce1-a1c6-1aa1ed579bb0.png)

**Comment by hfu** [comment]
Again please excuse me for my absence.

Unless my absence is a blocker, I would like to focus on preparing for UN Open GIS Monthly meeting on Wednesday first. We may be able to hold another working meeting for documentation before the next international smart maps meetup #125. 

I am also planning Smart Maps online Seminar as in #106.

**Comment by albertkun** [comment]
@hfu No problem!!

We definitely would like to have your input as the lead on the WG 7, but totally understand the need to focus on the UN Open GIS Monthly meeting! I think it would be nice if we could meet before the #125 as I would not want to present a Documentation site that hasn't gotten your review. 😓 

I'd love to help in with the Smart Maps online Seminar and will follow-up in #106!

**Comment by hfu** [comment]
@albertkun Thank you again for your suggestion. Yes, let's try to meet before #125. 

For the next week is a holiday season (ゴールデンウィーク) in Japan, may I suggest meeting in the same time on 2023-04-30 (Sun in LA) / 05-01 (Mon in Tokyo)? I thought Mon/Tue would be better but I am otherwise engaged. 

Or we can also think about postponing #125 for a week or so. 

Please let me know what you think. 🙂

**Comment by albertkun** [comment]
Thank you for your reply @hfu! So sorry, but I already have something scheduled for Sunday evening! :( I definitely want you to enjoy Golden Week, so please let me know which of these options works best for your holiday schedule:

A. 2023-04-30 (Sun in LA) / 05-01 (Mon in Tokyo) before 12pm JST (before 8pm LA time)
B. 2023-05-07 (Sun in LA) / 05-08 (Mon in Tokyo) at the same time
C. 2023-05-11 (Thu in LA) / 05-12 (Fri in Tokyo) at the same time, but this would mean we postpone #125 for a week and instead use that time to meet up for the documentation.

I hope one of these options works for you, if not please let me know any other alternatives! 🙏  Thank you very much!

**Comment by hfu** [comment]
Thank you, @albertkun. This reminded me that @yuiseki won't be available in #125. Let's reschedule both meetings based on Option B and C instead of A. Let me confirm the calendar of upcoming events.

**Comment by albertkun** [comment]
Thank you too @hfu! Since @yuiseki won't be available on #125, then perhaps it would be good to aim for `B.` or a separate time, instead of the second Friday (option `C`). Just in case, I'll keep my calendar open for both! I hope you have a great Golden Week holiday season next week!

**Comment by hfu** [comment]
@yuiseki What do you think? When is the best time for you to have the international meetup which includes a presentation about MUNDO? 

Regarding the Documentation meeting, let's say we take Option B.

**Comment by yuiseki** [comment]
@hfu @albertkun I am available for Option A and Option B. I am unable to attend Option C, as RubyKaigi 2023 will be held from May 10 to May 13.

**Comment by hfu** [comment]
Updated the title to the new time for the (2nd) Documentation meeting. We can discuss the time for 2nd International meetup on #125.

**Comment by albertkun** [comment]
Thank you for setting on the time! If it is alright, I went ahead a made a Zoom meeting:

## Meeting Link
- https://ucla.zoom.us/j/96974786542

Feel free to let me know if you'd like to change and use MS Teams or something else!

**Comment by hfu** [comment]
Thank you, @albertkun. Let's meet on Zoom above.

**Comment by albertkun** [comment]
Thank you for the productive meeting @hfu! 

Here is the whiteboard we created:

![Documentation Concept Action_Priorities Page-1](https://user-images.githubusercontent.com/8574425/236745339-d7133198-1ad7-44b3-9d8f-2c242b34029b.png)

[Documentation Concept Action_Priorities.pdf](https://github.com/UNopenGIS/7/files/11418230/Documentation.Concept.Action_Priorities.pdf)

I will add new items to the [7-docs issues board](https://github.com/UNopenGIS/7-docs/issues)!

**Comment by hfu** [comment]
Thanks @albertkun. 
I created separate issues (#143 and #144) and am closing this issue.
