### ISSUE TITLE
😎Check https://versatiles.org/ out!

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#138]
Looks great and cool! They have `versatile` format in place of `mbtiles` format.

- https://versatiles.org/

ベルリンのデータジャーナリストの方々のプロジェクトみたい。すごいですね。

versatiles フォーマットは mbtiles と同様に、サーバの裏側で動くような設計みたい。PMTiles のように直接アクセスにも対応しているというわけではないように見えます。結果的に、サーバ側動的機能が必須になるようです。Rust 文化圏のようです。

- https://github.com/versatiles-org/versatiles-rs

**Comment by albertkun** [comment]
Oh, this is great!! I love `rust-lang`!!!!

**Comment by hfu** [comment]
Let's continue watching. I close this as an issue because information sharing was successful.
