### ISSUE TITLE
Consider enabling GitHub Discussions

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#14]
We may want to activate GitHub Discussions on this repository.

## Why

The reason I suggested using a chat tool in #10 is that I want a place where I can discuss issues and pull requests before I make them.
GitHub Discussions may be perfect for this purpose (though I haven't used it much myself...)

## What GitHub Discussions are like

[![Image from Gyazo](https://i.gyazo.com/495b6e4092bb0a4d0e870522ee198445.png)](https://gyazo.com/495b6e4092bb0a4d0e870522ee198445)

## How

Click this area and click `Get Started` button.

[![Image from Gyazo](https://i.gyazo.com/086a8b05c010a4468c23eb968db06145.png)](https://gyazo.com/086a8b05c010a4468c23eb968db06145)

(I already have the authority to do this, but I created the Issue because I thought it should be consulted)

**Comment by hfu** [comment]
Thanks! Let's do this and see what happens.

**Comment by hfu** [comment]
Here we go! Let's continue there. 
https://github.com/UNopenGIS/7/discussions
