### ISSUE TITLE
I have accomplished giving TRIDENT the ability to be a GeoAI

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#141]
## https://trident.yuiseki.net/

I have previously introduced TRIDENT as an UN dedicated interactive document exploration and humanity assistance system.

https://github.com/UNopenGIS/7/issues/119#issuecomment-1523549921

A week has passed since that time. I have made significant changes to the specifications of TRIDENT, making it dedicated to UN resolution retrieval and question answering. In addition, I made it able to handle geospatial information.

As a result, it is now possible as follows:

### Where is the Permanent Mission of Japan to the United Nations?

[![Image from Gyazo](https://i.gyazo.com/5d639d8fe8d36ff6fb2625d0f38d5e94.png)](https://gyazo.com/5d639d8fe8d36ff6fb2625d0f38d5e94)

### Where is the headquarter of WHO?

[![Image from Gyazo](https://i.gyazo.com/de763290583b5fae503cbde305bfe61b.png)](https://gyazo.com/de763290583b5fae503cbde305bfe61b)

### Where is the headquarter of the World Bank?

[![Image from Gyazo](https://i.gyazo.com/8eb71e38005762e3f6ec40a82ec77564.png)](https://gyazo.com/8eb71e38005762e3f6ec40a82ec77564)

### How it works

- When user enters a question, TRIDENT will
  - Retrieve the UN resolution that is semantically similar to the question
  - Generate a answer with reference to the above UN resolution
  - Show that answer to user
- When user request related places, TRIDENT will
  - Generate several query of the Overpass API
  - Repeat the request until the Overpass API responds with the expected result
  - Show response from Overpass API to user as a map
- There is two steps of generation exist
  - Generation may be inaccurate, so TRIDENT's reply, which is being generated over and over again, is also becoming more inaccurate

### Related Studies and what's new

- Most important idea: Generating the query of the Overpass API using OpenAI API then request it to Overpass API
  - This idea was basically already tried as `ChatGeoPT`
  - https://github.com/earth-genome/ChatGeoPT
  - https://medium.com/earthrisemedia/chatgeopt-exploring-the-future-of-talking-to-our-maps-b1f82903bb05
- I have made significant improvements to the ChatGeoPT prompts, allowing the generation of Overpass API queries that work as expected, even for specific domains
- And I am combining the ChatGeoPT approach with a question and answer technique called RetrievalQA
- Note that
  - TRIDENT is not using `gpt-3.5-turbo` or `gpt-4`
  - TRIDENT using `text-embedding-ada-002` and `text-davinci-003`, two of cheapest LLM on the OpenAI API
  - It doesn't have to be the most advanced LLM to have this much performance
- However,
  - TRIDENT can best respond to questions in English
  - Japanese and other languages obviously cause accuracy problems
- ChatGeoPT even accomplished summarizing Overpass API responses based on user questions
  - TRIDENT has not yet gone that far
  - I think it might be possible to give the LLMs the GeoJSON as is and have them summarize it appropriately according to user requests

## Help wanted

- I feel TRIDENT is a new technology that has clearly advanced
- However, it is difficult to come up with specific needs or use cases where this technology can be most useful
  - If you can imagine a need, use case, or improvement for this approach, I'd love to hear about it!
- I don't know the definition of the GeoAI, but I feel TRIDENT is an GeoAI itself
  - I would like to have this presented at the UN Open GIS Inisiative Monthly Meeting
  - Please let me know what you think

**Comment by hfu** [comment]
Wow, this looks nice! With that said, Permanent Mission of Japan to the United Nations has moved. Now it is on 3rd Avenue. 
https://www.un.emb-japan.go.jp/itpr_en/aboutus.html

**Comment by yuiseki** [comment]
Since #156 was created, this Issue is out of date, so let me close it.
