### ISSUE TITLE
📝Capacity building for `Documentation` outside of Smart Maps Group

### ISSUE THREAD

**Issue by albertkun** [UNopenGIS/7#142]
### Objective

There could be a usefulness for a Documentation site outside of the DW7. 

Let's explore what that would look like and what steps are needed!

**Comment by hfu** [comment]
Yes, Prof. Li suggested that other DWGs in UN Open GIS Initiative can make use of GitHub, including https://github.com/unopengis. Let's explore this possibility as an extra opportunity for us. 

We will be able to report to the UN Open GIS montly meeting, when we get something to share with broader community.

**Comment by hfu** [comment]
#274
