### ISSUE TITLE
2023-05-22: next Working meeting for Documentation

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#143]
As discussed in https://github.com/UNopenGIS/7/issues/137#issuecomment-1537808199. 
When is convenient for you? Please let me know.

**Comment by albertkun** [comment]
> As discussed in [#137 (comment)](https://github.com/UNopenGIS/7/issues/137#issuecomment-1537808199). When is convenient for you? Please let me know.

Thank you for creating the issue! 2023-05-22 would probably work best! Also because I think it's a good idea to try and keep the momentum going!

**Comment by hfu** [comment]
2023-05-22 works for me too. Let's' proceed inviting more friends with the fixed date of 2023-05-22. 

@albertkun Could you possibly create an event page on the Documentation site and set up a Zoom link? Let's go ahead.

**Comment by albertkun** [comment]
> 2023-05-22 works for me too. Let's' proceed inviting more friends with the fixed date of 2023-05-22.
> 
> @albertkun Could you possibly create an event page on the Documentation site and set up a Zoom link? Let's go ahead.

@hfu Yes! Here is the requested links:

|                                                  |Link|
|----------------------------------|-----|
|Community Meeting Page | https://unopengis.github.io/7-docs/get-involved/community-meetings/|
|コミュニティミーティング|https://unopengis.github.io/7-docs/ja/get-involved/community-meetings/|
|Zoom Link| https://ucla.zoom.us/j/93249046195

**Comment by hfu** [comment]
Updated the URLs: 

|                                                  |Link|
|----------------------------------|-----|
|Community Meeting Page | https://unopengis.github.io/smartmaps/get-involved/community-meetings/|
|コミュニティミーティング|https://unopengis.github.io/smartmaps/ja/get-involved/community-meetings/|
|Zoom Link| https://ucla.zoom.us/j/93249046195

**Comment by albertkun** [comment]
Thank you! I changed the Zoom registration link to: https://ucla.zoom.us/meeting/register/tJUrcO-pqjsiEtQZccTcBHfbeISlnexdxe4Z#/registration

**Comment by hfu** [comment]
I am sharing my take from this meeting on #157. Thanks for meeting!
