### ISSUE TITLE
📝Smart Maps Calendar (member invitation, and Documentation link)

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#145]
As discussed in #139. I appreciate @yuiseki for preparing the shared calendar.

**Comment by albertkun** [comment]
What format is the shared calendar in? If we want to share it publicly and it is an open standard, like `.ical` or `.dav` we can probably connect it directly to our documentation! 😄

**Comment by yuiseki** [comment]
This is `.ical` URL of the our shared calendar.

@hfu @smellman I've sent invite. Please check your mail box of the Gmail.

https://calendar.google.com/calendar/ical/f4287ffe010843e55344f352ed82b5e05fc754f923bf7b52320cf9580d492889%40group.calendar.google.com/public/basic.ics

@albertkun I can also invite you if you tell me your Gmail address.

**Comment by hfu** [comment]
@yuiseki Thank you! It worked for me, and I added several events in a split of [worse is better](https://en.wikipedia.org/wiki/Worse_is_better). Please feel free to modify the entries.

**Comment by hfu** [comment]
Let's close this issue after we coordinated with @albertkun regarding invitation and Documentation.

**Comment by albertkun** [comment]
thank you @yuiseki ! I actually don't use Google Account for many things, but feel free to invite me: albertchemy86@gmail.com!

**Comment by hfu** [comment]
Are there further steps to follow? Do you think we can add some links from Documentation site?

**Comment by albertkun** [comment]
@hfu good question.. The zoom link automatically has the calendar invite for our virtual meetings, theres still the issue of putting the calendar data publicly. We can close this one and I'll add a calendar issue to the Smart Maps repo!

**Comment by hfu** [comment]
@albertkun Thanks!
