### ISSUE TITLE
📝Link with mapping projects

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#147]
As discussed #140. 

It would be a great opportunity for DWG 7 to connect with various OSM Kaizen projects such as UN Mappers because we can possibly expand our community and also we can contribute to the Kaizen of our data source. 

Especially promising for AI (trident) and MUNDO, among others.

**Comment by hfu** [comment]
It would help involving young generations, too.

**Comment by hfu** [comment]
Maybe we can start by adding links to HOT and UN Maps at https://github.com/UNopenGIS/smartmaps/blob/main/docs/resources/index.md. Then we can close this issue. Any volunteeers?

**Comment by albertkun** [comment]
@hfu Ok, I went ahead and added them under `Resources` -> `Mapping Projects`:

![image](https://github.com/UNopenGIS/7/assets/8574425/54a8387d-63e1-499a-a546-537e8644a1fb)

I also added HOT OSM Tasking manager under `Get involved` -> `Volunteering` -> `External Mapping Projects`:

![image](https://github.com/UNopenGIS/7/assets/8574425/f1f57dc5-50f7-49f7-ae5e-1b19ea209af4)

The Japanese translations are up too!

**Comment by hfu** [comment]
@albertkun I like it! 

.@darkensiva a.k.a. Slayer, voting member of HOT is my friend, and I have been wondering how we UN Smart Maps can link with HOT. It is great to link with HOT. I think @mapconcierge and @yuiseki, among others, would like it. 

We can add UN Mappers https://mappers.un.org when time allows. Ah, UN Mappers are successful in securing their domain name under un.org! See also: #151.

**Comment by albertkun** [comment]
@hfu Thank you! Great! I think it is a good place holder for now! We can organize it better once we get more groups! Worse is better than nothing! 😄

**Comment by hfu** [comment]
We are so close to close this issue. This is a typical *good first issue* now.
