### ISSUE TITLE
Smart Maps Name Guideline

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#149]
While working on Documentation, I see several different names are used. Should we starndardize the use of the names. 

# Name of our group
## What is used
- Domain Working Group 7 on Smart Maps
- DWG 7 on Smart Maps
- DWG 7
- DW7

As I understand, "DWG" is the term used in Open Geospatial Consortium. https://www.ogc.org/about-ogc/committees/dwg/

They normally use the form of "Something DWG". 

## My recommendation
- **Smart Maps DWG**

What do you think? @albertkun, @yuiseki, @smellman, @mapconcierge, @miya0001

As we are more used to the term Smart Maps, maybe it would be a good time to use a single standardized name. 

In Japanese language, I propose ”スマートマップ作業部会".

**Comment by yuiseki** [comment]
In the Open Geospatial Consortium, indeed, the recommended naming convention appears to be better. However, in UN Open GIS, a different notation seems to be consistently used; in UN Open GIS, it may be important to indicate that there are multiple (D)WGs with numbers.

I am not that particular about what we call ourselves, but it may or may not be important to indicate by name that we are part of UN Open GIS.

2023-02
[![Image from Gyazo](https://i.gyazo.com/b1de7f73b1c55ef5b2d1931a7a971133.png)](https://gyazo.com/b1de7f73b1c55ef5b2d1931a7a971133)

2023-03
[![Image from Gyazo](https://i.gyazo.com/f01cdfe9da1def3604311470e76af855.png)](https://gyazo.com/f01cdfe9da1def3604311470e76af855)

2023-05 (late 04)
[![Image from Gyazo](https://i.gyazo.com/7f0ed97181b01c7d29d689aec3afe2d2.png)](https://gyazo.com/7f0ed97181b01c7d29d689aec3afe2d2)

**Comment by hfu** [comment]
Thank you, @yuiseki for organizing the facts. As I understand, UN Open GIS Initiative does not have strict naming standard and that is why sometimes DWG is used while other times WG is used. 

I am proud to have the number 7 for our group, but on the other hand the number 7 is meaningful only inside the initiative. 

According to these fact, may I suggest a simpler name: 

- **Smart Maps Group**

Some times we can call ourselves UN Open GIS Smart Maps Group (DWG 7), or even UN Open Smart Maps Group (DWG 7). What do you think?

**Comment by hfu** [comment]
I would say **Smart Maps Group** would be a standard alias or a nick name for the UN Open GIS Initiative Domain Working Group 7 on Smart Maps.

**Comment by hfu** [comment]
@albertkun, thank you for your input. I am updating the proposal incorporating your input. 

Yes, I also think 7 is an attractive number and we can make use of this number to symbolize us and our efforts. 

Our logo policy is [worth is better](https://cs.stanford.edu/people/eroberts/courses/cs181/projects/2010-11/WorseIsBetter/index.php/Worse-is-better.html) ;-) i.e. Our initial idea is that a bad logo is better than no logo. So, we always welcome further proposals to thinka about. 

Practical note: we use `Futura` font since UNVT. This is also not a hard rule.

**Comment by hfu** [comment]
# Name guideline proposal
## Principles
1. We would like to keep our names simple and so easy to remember and understand. 
2. We want to make our text short as possible. For this reason, we prefer short names. 
3. We would like to take our priviledge to make use of UN brand where appropriate. On the other hand, we want to be considerate not to assume the name of the UN. We do not want anyone to feel cheated. 

## Guideline proposal
1. We normally use **UN Smart Maps** when it is appropriate. We want to make this our brand. 
2. We add specific words after **Smart Maps** to identify something under our activitiy. For example: **Smart Maps Meetup**, **Smart Maps Bazaar**, and **Smart Maps Group**. It is OK to use UN as a prefix. However, we also wanto to keep our names short, preferably less than 3 words. 
3. We also add **DWG** and **7** when it is necessary or appropriate. But we still want our brand simple and easy to remember. That is why we normally use **UN Smart Maps**.

**Comment by hfu** [comment]
I am now consulting with UN Open GIS Bureau for their confirmation 👍🏻

**Comment by hfu** [comment]
I received 👍🏻 from @KyoungEom on the UN MS Teams in consulting with UN Open GIS Bureau. 
I believe we can go ahead using **UN Smart Maps** as *our standard brand*. 

@albertkun Do you think we can set up a page for the *Name Guideline* on our Documentation site? 

I think we can close this issue after we place this *Naming Guideline* on a persistent place.

**Comment by albertkun** [comment]
Good morning @hfu! Yes, I will do that under `About` -> `Brand Guidelines`!

**Comment by albertkun** [comment]
Regarding the naming convention, I think it's great! Trying to keep is short and simple is a good policy! I also never heard of the `worse-is-better` policy! Thank you for sharing that! 

About `Documentation` and guideline 3., should the website be `UN Smart Maps Documentation` or `Smart Maps Documentation`?

I strongly agree with guideline 4.: keeping the maps plural is important, I think it helps indicate we are pushing for open usage of tools and data, so it is not just one "smart map"!

Sorry I cannot give feedback on 6. though, which I am assuming would be 国連スマート地図 vs. UNスマート地図, right?

**Comment by albertkun** [comment]
> Practical note: we use `Futura` font since UNVT. This is also not a hard rule.

Should we replace the `Roboto` font on the website with `Futura`? If yes, is there a link to the font I can use? Thank you!

**Comment by albertkun** [comment]
> I received 👍🏻 from @KyoungEom on the UN MS Teams in consulting with UN Open GIS Bureau. I believe we can go ahead using **UN Smart Maps** as _our standard brand_. 
> 
> @albertkun Do you think we can set up a page for the _Name Guideline_ on our Documentation site?
> 
> I think we can close this issue after we place this _Naming Guideline_ on a persistent place.

I have created the `brand` page here:

| |Link|
|-|----|
|Brand|https://unopengis.github.io/7-docs/about/brand|
|ブランド|https://unopengis.github.io/7-docs/ja/about/brand|

The Japanese site still needs to be translated though, but I think we can close this issue!

**Comment by hfu** [comment]
@albertkun 
Thank you for creating a page. I updated these pages and am closing this issue.

**Comment by albertkun** [comment]
@hfu You are welcome! Sorry about the state of the Japanese page! I didn't have time to translate it 😓

**Comment by hfu** [comment]
> Should we replace the Roboto font on the website with Futura? If yes, is there a link to the font I can use? Thank you!
I do not think there are easily accessible Futura fonts on the web. Let's keep on using Roboto as it is a UN standard, too.

**Comment by hfu** [comment]
> About Documentation and guideline 3., should the website be UN Smart Maps Documentation or Smart Maps Documentation?

I think the web site is for `UN Smart Maps` and the Documentation project can be called `Smart Maps Documentation`. https://unopengis.github.io/smartmaps/ would be a sole unified Documentation project for `UN Smart Maps`. What do you think?

**Comment by hfu** [comment]
We currently have brand guidelines below, due to the change of the repository name. 

- https://unopengis.github.io/smartmaps/about/brand/
- https://unopengis.github.io/smartmaps/ja/about/brand/
