### ISSUE TITLE
Participate in Smart Maps International Meetup 2

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#152]
Please drop your name here so that Smart Maps Team can know your name! 

# Invitation
[English](https://unopengis.github.io/smartmaps/get-involved/community-meetings/international/2023-05-26) / [Japanese](https://unopengis.github.io/smartmaps/ja/get-involved/community-meetings/international/2023-05-26)

**Comment by hfu** [comment]
@albertkun @yuiseki Due to urgent and important issue in my work, there is possibility that I cannot make it to the international meetup this Friday/Thursday. My guess is the possibility is 50:50. 

Could you advise me on how we move. My suggestion would be: 

1. Postpone the meeting one week. The risk is that we cannot annoounce all participants because we haven't introduce the registraton yet. 
2. Meet as planned. The risk is that I cannot attend. I need to ask you to chair the meeting on my behalf.

As of now I am thinking that we take the option 1 to postpone the meeting. I think we need to announce the postpone probably within 12 hours. 

Sorry again for this trouble.

**Comment by albertkun** [comment]
@hfu Thank you for letting us know! I agree that we should go with option 1 to postpone, as I think it is important to have you there!

Side note, this does make me want to  think of a better way of how to make announcements and/or get people to sign-up so we can let people know right away! Once you confirm, I will change the date on the Smart Maps website!

**Comment by yuiseki** [comment]
@hfu @albertkun Understood. I also thought option 1 was a good idea.
I wanted some time to rethink the MUNDO presentation a bit, so it's a bit appreciated for me.

**Comment by yuiseki** [comment]
For participant registration and communication, a quick option would be to use Doorkeeper or perhaps Google Forms. It seems that the spirit of worse is better is needed here as well!

**Comment by albertkun** [comment]
@yuiseki I haven't used Doorkeeper, but that sounds good! 

Alternatively, if we are using Zoom, we can also use the "Registration" setting. This will allow us some benefits:

1. If we change the meeting times, everyone will be notified as part of the Calendar invite.
2. We can create a recurring Zoom meeting so people don't have to register multiple times.
3. We don't need to send a separate link for the meeting (i.e. sending MS Teams or a Zoom link for each meeting)
4. I think customize questions, such as "GitHub Username"

**Comment by hfu** [comment]
Thank you!! First of all, I am announcing the postpone in MS Teams. Then I will edit the Documentation site. Will just add `strike` tags.

**Comment by albertkun** [comment]
@hfu I have made a branch on the documentation site and pull request:

https://github.com/UNopenGIS/smartmaps/pull/16

1. Edit the `[2023-05-26-potential-meeting-change](https://github.com/UNopenGIS/smartmaps/tree/2023-05-26-potential-meeting-change)` branch and merge to `main` 

or

2. Merge this [pull request](https://github.com/UNopenGIS/smartmaps/pull/16) and then edit on `main`

**Comment by hfu** [comment]
@albertkun 

> Once you confirm, I will change the date on the Smart Maps website!

Oh, thanks! Could you please `strike` the day first, and then update the date once we decided a new date?

Also, I am thinking about **deleting** the Zoom link (from UN Open GIS MS Teams announcement) so that less people attend on this Friday by mistake. I appreciate if you could do so on Documentation site.

**Comment by albertkun** [comment]
@hfu sorry I am actually on my phone and won't be able to incorporate the changes. If you want to edit them, please go ahead and do so on the `main` branch and we can just delete this one and the pull request without merging!

**Comment by hfu** [comment]
I updated the invitation in UN Open GIS MS Teams! 

<img width="989" alt="スクリーンショット 2023-05-17 21 36 07" src="https://github.com/UNopenGIS/7/assets/18297/1e554222-db07-469a-aac5-698c6ef45f26">

**Comment by yuiseki** [comment]
@hfu Yes, I'm available in 2023-05-26T13:00/14:00+09:00!

**Comment by hfu** [comment]
@yuiseki Thanks! I am updating to 2023-05-26T13:00/14:00+09:00.

**Comment by albertkun** [comment]
@hfu Sure, I can offer my Zoom account for the meet ups! I'll make it a recurring meeting, but which option should we choose for registration? One time or each time?

Additionally, the pull request has a merge conflict because that PR deletes the files I changed on my phone last night 😔 let me know if you have any issues with it! Once we confirm the time change, I'll be happy to merge it as well!

**Comment by hfu** [comment]
Thank you, @albertkun. (I am back at last!) 
I think we can go with **one time** registration.

**Comment by albertkun** [comment]
@hfu Done! Only issue is, I'm not sure if I can assign co-hosts outside of my organization. :(

**Comment by hfu** [comment]
Let's say we can close this issue because we are using Zoom for registration, too. 
Merging into #125.

**Comment by albertkun** [comment]
Sounds good!
