### ISSUE TITLE
📝Additional communication channels (add Mastodon?)

### ISSUE THREAD

**Issue by albertkun** [UNopenGIS/7#155]
### Purpose

On top of existing communication channels (GitHub issues, Matrix, etc.) it might be good to explore creating `UN Smart Maps` Social Media (SNS) accounts and groups on places like **LinkedIn**, **Mastodon**, **Twitter**, etc. 

I think this could help us to build and identify our community members!

### Potential Action Items

- [ ] Decide on what Social Media platforms to pursue

**Comment by hfu** [comment]
I am interested in the use of Mastodon. Is there anyone who has experience with it?

**Comment by albertkun** [comment]
@hfu I have experience with Mastodon! Unlike Twitter or other SNS, it is Federated, so we can either 

A) create an account on a node
B) host a node instance ourselves! 



A)  We can choose a node, like https://social.opensource.org, and we can create an `unsmartmaps` account there. With this example, our full account would be `social.opensource.org/@unsmartmaps`

B) We find a [hosting solution (or host ourselves) ](https://docs.joinmastodon.org/user/run-your-own/) then we can use the domain name, like `social.un.org/@smartmaps`

**Comment by hfu** [comment]
Thank you, @albertkun. I think we continue to think about having a Mastodon account by considering what content we can provide from the account.

**Comment by hfu** [comment]
How about Telegram? I appreciate your comments.

**Comment by hfu** [comment]
I think we can concentrate on GitHub Issues and possibly GitHub Discussions for the time being. Happy to reopen this issue when we have new ideas! 

#274
