### ISSUE TITLE
🤖TRIDENT: Smart Maps Assistant

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#156]
## Backgrounds

- TRIDENT is an unofficial UN dedicated interactive information retrieval and humanity assistance system
  - I have first introduced at https://github.com/UNopenGIS/7/issues/119#issuecomment-1523549921
- TRIDENT functions as an experimental minimal GeoAI
  - I have previously introduced at https://github.com/UNopenGIS/7/issues/141
- **I am not trying to create a GeoAI that is as smart as a human**
  - First, it is important to get people to understand the limitations of current AI and the OpenStreetMap and Overpass APIs by actually touching them
  - Secondly, even if it's not perfect, I believe that people might use it in ways I can't imagine and that it could help others

## So, what's new?

- I developed a completely different AI specifically for GeoAI
  - It is very difficult to develop from scratch, so I developed it as an extension of TRIDENT
  - For convenience, I call it `TRIDENT GeoAI`
    - TRIDENT GeoAI is the nickname for `Interactive geospatial situation awareness empowerment system`
- TRIDENT GeoAI is a full-fledged GeoAI with features and performance that surpass TRIDENT
- TRIDENT GeoAI may even surpass `mundo-maps`! **(!)**

As a result, it is now possible as follows:

### "Show UN facilities in New York."

[![Image from Gyazo](https://i.gyazo.com/cbc52a8f67167de0bcce494377674056.jpg)](https://gyazo.com/cbc52a8f67167de0bcce494377674056)

### "Show military installations in South Sudan."

[![Image from Gyazo](https://i.gyazo.com/5f8d8a0d8e5bb03dd00b0fb287a99221.png)](https://gyazo.com/5f8d8a0d8e5bb03dd00b0fb287a99221)

#### "Add hospitals to this map." **(!)**

[![Image from Gyazo](https://i.gyazo.com/0bc2c90bfd970778621622fa26359790.png)](https://gyazo.com/0bc2c90bfd970778621622fa26359790)

#### "Furthermore, add schools and shelters." **(!)**

[![Image from Gyazo](https://i.gyazo.com/18e95169a41e48b036176b4eb5135a95.png)](https://gyazo.com/18e95169a41e48b036176b4eb5135a95)

#### "Show only military installations, after all." **(!)**

[![Image from Gyazo](https://i.gyazo.com/9dbc2ad215d5146147c2cd58dcf38678.png)](https://gyazo.com/9dbc2ad215d5146147c2cd58dcf38678)

### "Show military installations in Kosovo and Serbia." **(!)**

[![Image from Gyazo](https://i.gyazo.com/155b2aa8b20f547bcb91978e5ac33353.png)](https://gyazo.com/155b2aa8b20f547bcb91978e5ac33353)

#### "Add hospitals and airports to this map." **(!)**

[![Image from Gyazo](https://i.gyazo.com/63eea227408bf786f81bdfdf9c52d856.png)](https://gyazo.com/63eea227408bf786f81bdfdf9c52d856)

### 「台東区のお寺と神社を表示して」 **(!)**

[![Image from Gyazo](https://i.gyazo.com/e292b0e8ec850dcd70f10d61486d9aba.jpg)](https://gyazo.com/e292b0e8ec850dcd70f10d61486d9aba)

#### 「駅も追加して」 **(!)**

[![Image from Gyazo](https://i.gyazo.com/8e2a5b2e2e688ce9ed248802b77e4114.jpg)](https://gyazo.com/8e2a5b2e2e688ce9ed248802b77e4114)

## Key findings

- Being able to chat with maps is really fun!!!!!
- Chatable maps provide a fast view of geospatial information from around the world
- ...To be honest, I am surprised myself!
  - TRIDENT GeoAI is, of course, not perfect, but it still sometimes performs better than I could have imagined.
- Wouldn't TRIDENT GeoAI be sufficient to create maps that can be made customisable by extracting concerns from OpenStreetMap, as is done with mundo-maps?
- Rather, TRIDENT GeoAI is far easier and more flexible!

### How it works

- It's too complicated to explain here, so let me leave it out
- See this prompts
  - https://github.com/yuiseki/TRIDENT/blob/main/src/utils/langchain/chains/geoai/prompts.ts

## Future Issues

- Clearly, requests to the Overpass API should be strongly cached
- Clearly, a message should be displayed when an error occurs
- Clearly, a warning should be displayed when the Overpass API response is too huge
- I want to give them the ability to respond to even more ambiguous instructions and dynamically create more diverse maps
- I want to give them the ability to create maps based on UN resolutions and ReliefWeb information
- Also, I want to be able to give a unique URL to the map created by the interaction so that it can be shared
- I would like to hear any requests you may have after actually touching TRIDENT GeoAI!

**Comment by hfu** [comment]
#274
