### ISSUE TITLE
🖐️Can we shift the regular time slot for the Documentation team meeting?

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#162]
As we discussed in #157 with @yuiseki and @smellman. 

Some of us has a regular schedule conflict with the current regular schedule of the Documentation team meeting. Can we shift one hour or change the weekday? 

Let me know what you think.

**Comment by albertkun** [comment]
@hfu Thank you for letting me know! Let's try to shifting the time by 1 hour! Does that mean 2pm JST or Noon JST?

**Comment by hfu** [comment]
@yuiseki Do you have any preference or a suggestion?

**Comment by yuiseki** [comment]
Sorry for the delay in responding. I am available for the time slot starting at 12pm JST.

**Comment by albertkun** [comment]
No problem! Thank you @yuiseki! @hfu can we confirm our shift to 12pm JST (one hour ahead)?

**Comment by hfu** [comment]
Sure, let’s go with 12.

**Comment by albertkun** [comment]
@hfu updated on the Documentation site! I'll go ahead and shift it on the zoom invite too!

**Comment by hfu** [comment]
Thanks @albertkun. I confirmed at https://unopengis.github.io/smartmaps/get-involved/community-meetings/documentation/2023-06-19.

**Comment by albertkun** [comment]
You are welcome! Thank you! I changed both the English and Japanese sites!
