### ISSUE TITLE
🏬Smart Maps Assistant - NLP rebranding, updating MUNDO

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#163]
@yuiseki Many thanks for your input in #125. 

I just thought it would be great to rebrand MUNDO in harmony with our recent 'brand guideline' because of recent progress by @yuiseki in natural language processing (NLP). 

A reference to Model UN would be great, but I also think it can be awkward that we use Spanish word 'mundo' not knowing Spanish well. 

I would suggest the followings as a brainstorming idea. 

- [ ] Smart Maps Chat
- [ ] Smart Maps Intelligence

What do you think? 

Footnote: I think it would be great if we could avoid misunderstanding that there is some duplicate of effort between UN Open GIS GeoAI and the work by @yuiseki. 

In Smart Maps Group we are rebranding often because we believe [worse is better](https://en.wikipedia.org/wiki/Worse_is_better). "Smart Maps Bazaar" was rebranded from "InterPlanetary Operations".

**Comment by yuiseki** [comment]
@hfu Thank you for the rebranding suggestion!

#### If it is permissible to use the name of `Smart Maps`, I suggest the name `Smart Maps Assistant`.

-----

The process of my consideration is as follows:

I have been trying to figure out if there is a name that would be a perfect fit with ChatGPT.
I like the name "**Smart Maps Assistant**" among those suggested by ChatGPT.

The idea that `AI, especially LLMs, are human assistants` is becoming widely accepted in society.
I also believe that the idea that `humans make decisions and take action, and AI assists them`, is a good one.

I also came up with another name: "Smart Maps Copilot".
However, the word "Copilot" is used only by Microsoft (and GitHub, a Microsoft subsidiary), so I think that impression is too strong.

-----

I did not know that `mundo` means `world` in Spanish! 😆

**Comment by hfu** [comment]
@yuiseki Many thanks for your thoughtful input as always. 

Let's go ahead with **Smart Maps Assistant** by gradually rebranding your powerful activities in UN Smart Maps. 🚀

I am thinking about creating a list of Smart Maps XXX brands probably in gh:unopengis/smart-maps-denkmal with a small GitHub Page :-)

**Comment by hfu** [comment]
#164 has also be done. https://unopengis.github.io/smart-maps-denkmal/

**Comment by hfu** [comment]
Close this issue with thanks because we got a rough consensus in #161.
