### ISSUE TITLE
🗽2023-06-08 UN Open GIS Monthly

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#170]
UN Open GIS Monthly meeting was announced as below: 

Please be informed that Monthly VTC of UN Open GIS is scheduled on Thursday, 8 June 2023 at 3:00 PM (Rome time) 9:00 AM (New York time).

[Proposed agenda]
1. Opening by Co-Chairs (Prof. Ki-Joune Li, Prof. Maria Brovelli and Kyoung-Soo Eom)
2. Introduction of new members
3. Open Q&As and discussions
4. Working Group report 
. DWG-1 Hybrid GIS platform (Timur, Zeeshan, Epa/Rodwell, Akbar, #Cung);
   .. Integration of Azure AD with GeoServer/GeoNode (Timur, Eddy)
  .. Mobile GIS Solutions, including integration with Azure AD (Epa/Rodwell, Zeeshan, Cung)
.. UNMISS Story Map (Zahurul/Akbar/Debasish, Timur, Eddy): 
. DWG-2 Capacity Building (Ivan, Susan, Diego);
. DWG-5 Geo-AI & Analytics (Zhongxin, Maria, Andrea, #Cung)
. DWG-6 OpenDroneMap & 3D (Catalina, Davide, #Cung)
. **DWG-7 Smart Maps (Hidenori, Diego, #Timur)**
5. Any other business (AOB)
. Conference/coordination meeting on One UN Geospatial Situation Room at UNEP, Nairobi (13-15 June 2023)
. **Smart Maps International Meetup 3, online (16 June 2023)**
. FOSS4G 2023 in Prizren, Kosovo (26 June - 2 July 2023)
. AI for Good Global Summit in Geneva (6-7 July 2023)
. **Smart Maps Bazaar Walking Tour, online (12 July 2023, TBC)**

**Comment by hfu** [comment]
# Report items
- announcement: branding, vision and mission
- new activities
  - documentation
  - journal and denkmal
  - Smart Maps Assistant
- schedule including invitation to upcoming events
  - Smart Maps Meetup Pacific 3 2023-06-16
  - Smart Maps Meetup Offline
  - FOSS4G Presentation - Smart Maps, Smart Maps Assistant and Smart Maps Bazaar
  - Smart Maps Meetup Atlantic 1 2023-07-12

Wow, that is a lot! 
@yuiseki do you want me to report something about Smart Maps Assistant in the monthly meeting? If so, please share with me talking points or a single slide.

**Comment by yuiseki** [comment]
@hfu Yes, I would love to be introduced to the Smart Maps Assistant as well. 🥰 

## Following is a progress report on the Smart Maps Assistant:

- I have previously introduced a project called `MUNDO` , building maps of UN peacekeeping missions based on open data.
- Also, I have previously introduced a question answering AI called `TRIDENT` , that has learned all UN resolutions.
- After that, based on the above projects, I was looking for ways to use AI more directly in the GIS field.
- As a current achievement, I can introduce `Smart Maps Assistant` , an AI that generates maps based on natural language interaction with the humans.
- We humans can now talk with digital world maps!
- You can try `Smart Maps Assistant` right now at the following URL
  - https://trident.yuiseki.net/
- I followed hfu's suggestion and rebranded `TRIDENT` to focus on the `Smart Maps Assistant` .
- Also, I will be rebranding the question answering AI that has learned all UN Resolutions as separate from `TRIDENT` .
- `Smart Maps Assistant` is a project that has just begun and is limited in performance and accuracy.
  - Nevertheless, I strongly feel that it has the potential to be an innovative technology
  - I will be concentrating on improving the performance, accuracy and functionality of the `Smart Maps Assistant` .
- Remarks: Of course, all the projects I mentioned are free and open source software.

The above report is subjective to me, and I hope that @hfu will summarize the report based on this in a more appropriate manner. 🙏 

## Screenshots:

### PC
[![Image from Gyazo](https://i.gyazo.com/635e5089d804c108fb0bee10769a3128.png)](https://gyazo.com/635e5089d804c108fb0bee10769a3128)

### Smartphone
[![Image from Gyazo](https://i.gyazo.com/873b730cffdaa8d0611018cb2fe22ef9.jpg)](https://gyazo.com/873b730cffdaa8d0611018cb2fe22ef9)

**Comment by hfu** [comment]
## Atlantic and Pacific time
<img width="655" alt="スクリーンショット 2023-06-03 23 25 09" src="https://github.com/UNopenGIS/7/assets/18297/a7b049ca-d61c-4d3e-bf55-d18a72c9b0cb">
<img width="699" alt="スクリーンショット 2023-06-03 23 25 02" src="https://github.com/UNopenGIS/7/assets/18297/be831bb1-3340-4aaa-a86f-03d56c9a059c">

**Comment by hfu** [comment]
## Atlantic and Pacific time in a more flat landscape format
<img width="933" alt="スクリーンショット 2023-06-05 4 50 16" src="https://github.com/UNopenGIS/7/assets/18297/037ebf31-4341-443e-84b2-cdc79371148a">
<img width="948" alt="スクリーンショット 2023-06-05 4 50 03" src="https://github.com/UNopenGIS/7/assets/18297/fdde2446-3855-4934-a389-676981e56dcb">

**Comment by hfu** [comment]
<img width="1024" alt="スクリーンショット 2023-06-05 5 11 13" src="https://github.com/UNopenGIS/7/assets/18297/c8cf160c-8f23-4515-956c-10b806855c3e">

**Comment by hfu** [comment]
@yuiseski Thanks for your input. Following is my draft slides. 

<img width="1075" alt="スクリーンショット 2023-06-06 6 14 44" src="https://github.com/UNopenGIS/7/assets/18297/11d6302d-e15d-4595-afee-e3ef583feda2">

<img width="1079" alt="スクリーンショット 2023-06-06 6 14 55" src="https://github.com/UNopenGIS/7/assets/18297/d576eb62-68b4-4757-b995-e9e87f023d06">

**Comment by hfu** [comment]
## Bazaar Server to bring to Kosovo

![image](https://github.com/UNopenGIS/7/assets/18297/3bdd2d06-b378-4c21-ad0f-537a88234d1a)

**Comment by hfu** [comment]
## Draft presentation
https://hackmd.io/@hfu/2023-06#/

**Comment by hfu** [comment]
@yuiseki I realized the following points: 

1. Smart Maps Group (SMG) does not have enought time to explain the details. 
2. It would be great if we have an opportunity to explain the details in Kosovo or Meetup Monthly. 
3. So, I would like to touch each point in very simple way so that we can save time and also seek future presentation opportunities. 

In Japanese, 木曜日の短時間ですべて説明するのはもったいないし長くなるので、木曜日のプレゼンではそれぞれのポイントにごく簡単に触れることにします。

Please let me know if you have any comments!

**Comment by yuiseki** [comment]
@hfu Understood! No problem!

**Comment by hfu** [comment]
<img width="1077" alt="スクリーンショット 2023-06-08 21 15 00" src="https://github.com/UNopenGIS/7/assets/18297/8d2f5607-beb1-4b83-9407-f726b37d7dbf">

**Comment by hfu** [comment]
https://hackmd.io/@hfu/2023-06#/
Done!

**Comment by hfu** [comment]
## メモ
- Ki-Joune は OGC の会場にいる。カメラと脳のインタフェースの興味をお持ちのよう。
- Hybrid GIS チームは作業が完了している様子。GeoNode 4 へのアップデートも含めて終了している。
- GeoAI Challenge については ToR のアップデートもする。大気汚染や気候変動という単語も出てきた。
- FOSS4G 2023 での会場調整については、Vicky が尽力してくれるようだ。
