### ISSUE TITLE
ℹCalendar till the end of FOSS4G 2023

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#176]
|Mon|Tue|Wed|Thu|Fri|Sat|Sun|
|:-:|:-:|:-:|:-:|:-:|:-:|:-:|
|2023-06-12|2023-06-13T12:30/12:55+09:00 Meetup Weekly|2023-06-14|2023-06-15|2023-06-16T13:00/14:00+09:00 Meetup Monthly|2023-06-17|2023-06-18|
|2023-06-19T12:00/13:00+09:00 Documentation Meetup|2023-06-20T12:30/12:55+09:00 Meetup Weekly|2023-06-21|2023-06-22|2023-06-23|2023-06-24|2023-06-25|
|FIXME|FIXME|FIXME|FIXME|FIXME|FIXME|FIXME|

**Comment by hfu** [comment]
I am moving these information to Smart Maps Calendar and FOSS4G participants' Messenger calendar. 

- [ ] Smart Maps Calendar https://calendar.google.com/calendar/u/0?cid=ZjQyODdmZmUwMTA4NDNlNTUzNDRmMzUyZWQ4MmI1ZTA1ZmM3NTRmOTIzYmY3YjUyMzIwY2Y5NTgwZDQ5Mjg4OUBncm91cC5jYWxlbmRhci5nb29nbGUuY29t
- [ ] FOSS4G participants' calendar https://calendar.google.com/calendar/u/0?cid=NTY3NDM3MTQ2OTNlZWQyN2FiMjJlYTJlOWNkZDJjOTJmNDc1ZWE3NWZmZTI3YWFiZWVkNTBmZWI4ZDFlZmRjN0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t

**Comment by hfu** [comment]
Finish copied information here to Google Calendar.

**Comment by smellman** [comment]
@hfu I can't add information to FOSS4G participants' calendar, please add me taro@georepublic.de

**Comment by hfu** [comment]
@smellman Thanks! I just sent an invite for you now.

**Comment by smellman** [comment]
@hfu Thanks!
