### ISSUE TITLE
2023-06-16/15: Smart Maps Meetup Monthly 3

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#180]
# Smart Maps Meetup Monthly 3

## What is this meetup?

This event is an open online event where UN Smart Maps Group share their progress so that participants can share knowledge and information.

## When is this meetup?
We are meeting every 3rd Friday. This time the meetup will be:

2023-06-15T21:00/22:00-08:00 for Los Angeles
2023-06-16T00:00/01:00-07:00 for New York
2023-06-16T06:00/07:00+02:00 for Rome
2023-06-16T09:30/10:30+05:30 for New Delhi
2023-06-16T13:00/14:00+09:00 for Tokyo

## How can I participate?

Join via the this [Zoom link](https://ucla.zoom.us/meeting/register/tJcoc-mvrTovG920aIcgb-64RaKdVWKTb1Ik).

### Opening

Welcome by Hidenori, Smart Maps Lead (2 min)
Introduction by new participants (8 min)

### Presentation

UNVT Portable by @ShogoHirasawa (15 min)
presentation file: https://docs.google.com/presentation/d/1z8HPDOGJ6IiFZJbP6q_J4ufJaovyDT5bhGkxyKxmeIs/edit?usp=sharing
Discussion (10 min)

### Closing - next actions

Introduction of upcoming events (20 min)
How to keep in touch (5 min)

**Comment by albertkun** [comment]
@hfu I noticed that the times were off for India and Japan so I changed them 

from:
```
2023-06-26T09:30/10:30+05:30 for New Delhi
2023-05-26T13:00/14:00+09:00 for Tokyo
```


to:
```
2023-06-16T09:30/10:30+05:30 for New Delhi
2023-06-16T13:00/14:00+09:00 for Tokyo
```

**Comment by hfu** [comment]
@albertkun Thanks for correcting the mistake. We are planning the Smart Maps Meetup Offline by checking the schedule of FOSS4G participants around us. We will be deciding the detail in the Smart Maps Meetup Weekly tomorrow.

**Comment by hfu** [comment]
Here is my slides! 
https://hackmd.io/@hfu/2023-06-16#/

**Comment by yuiseki** [comment]
My apologies. I am unable to attend due to sudden work commitments. Please record it for us. 🙏

**Comment by albertkun** [comment]
@hfu Thank you for sharing!!

@yuiseki awww! You will be missed! 😢

**Comment by hfu** [comment]
- #187
- Next session: It would great to have speakers from different countries. 
  - India: maybe in future. 
  - Thailand: @hfu will consult separately.

**Comment by albertkun** [comment]
@hfu @yuiseki here is today's recording: https://ucla.zoom.us/rec/share/16CCjqkKmu-gEE748jUNMhAuzNKbzU7TDzCmA4-UfIjPjlZJkiXz-4khGLPFFRmq.NonlnGTEaNs0A26E

**Comment by smellman** [comment]
@albertkun @hfu @yuiseki I upload into youtube with transcript via zoom https://youtu.be/2jTztGo5jzQ

**Comment by smellman** [comment]
@albertkun Could you try "Complete video verification"?
It is need to add external link in youtube description.
https://support.google.com/youtube/answer/9891124?sjid=8471457152853336942-AP&co=GENIE.Platform%3DDesktop&oco=1
