### ISSUE TITLE
📝Presentations by ShogoHirasawa

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#182]
1. https://talks.osgeo.org/foss4g-2023/talk/B9DDED/ 2023-06-29T11:00–11:30 (30 min)
2. https://talks.osgeo.org/foss4g-2023/talk/7PLC3D/ 2023-06-28T14:10–14:15 (5 min)

**Comment by ShogoHirasawa** [comment]
Workshop image:
![image](https://github.com/UNopenGIS/7/assets/29940264/1a654e7e-a1cc-4a37-a3c3-98f00da00175)

**Comment by hfu** [comment]
Congratulations! We have done it well.
