### ISSUE TITLE
2023-07-21/20: Smart Maps Meetup Monthly 4

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#188]
# Smart Maps Meetup Monthly 4

## What is this meetup?

This event is an open online event where UN Smart Maps Group share their progress so that participants can share knowledge and information.

## When is this meetup?
We are meeting every 3rd Friday. This time the meetup will be:

2023-07-20T21:00/22:00-08:00 for Los Angeles
2023-07-21T00:00/01:00-07:00 for New York
2023-07-21T06:00/07:00+02:00 for Rome
2023-07-21T09:30/10:30+05:30 for New Delhi
2023-07-21T13:00/14:00+09:00 for Tokyo

## How can I participate?

Join via the this [Zoom link](https://ucla.zoom.us/meeting/register/tJcoc-mvrTovG920aIcgb-64RaKdVWKTb1Ik).

### Opening

Welcome by Hidenori, Smart Maps Lead (2 min)
Introduction by new participants (8 min)

### Presentation

TBD

### Closing - next actions

Introduction of upcoming events (20 min)
How to keep in touch (5 min)

**Comment by albertkun** [comment]
@hfu The next Smart Maps Monthly meet up is up on the documentation: https://unopengis.github.io/smartmaps/get-involved/community-meetings/

**Comment by hfu** [comment]
We will be with Khun Pongsakorn Udombua san as the guest speaker!

# Proposed Agenda
## Opening
- Welcome by Hidenori, Smart Maps Lead (2 min)
- Introduction by new participants (8 min)

## Presentation
- [Decision Support System for Disaster Management](https://disaster.gistda.or.th/) using full of vector tile services (25 min)

## Closing - next actions
- Introduction of upcoming events (20 min)
- How to keep in touch (5 min)

**Comment by hfu** [comment]
Khun Pongsakorn kindly confirmed the agenda. 

@albertkun Could you please release this information on the Documentation site, too?

**Comment by albertkun** [comment]
Yes, I will go ahead and do that!

**Comment by albertkun** [comment]
@hfu It is done!

**Comment by hfu** [comment]
@albertkun Thanks! I will make use of this in Kosovo.

**Comment by hfu** [comment]
Screenshot of Khun Pongsakorn’s GISTDA website. 

<img width="1298" alt="スクリーンショット 2023-06-25 14 56 20" src="https://github.com/UNopenGIS/7/assets/18297/9313154e-33a9-486e-b11f-22a802eaa281">

**Comment by albertkun** [comment]
Wow! Looks exciting!!!

**Comment by hfu** [comment]
@albertkun Sorry for missing the Documentation meeting on Monday, which was "Marine Day" holiday in Japan. Let's make use of the rest of the Monthly meetup time for sharing information and discussion for active projects including the Documentation project. I updated the agenda. 

# Proposed Agenda
## Opening
- Welcome by Hidenori, Smart Maps Lead (2 min)
- Introduction by new participants (8 min)

## Presentation
- Pongsakorn Udombua: [Decision Support System for Disaster Management](https://disaster.gistda.or.th/) using full of vector tile services (25 min)

## Closing - next actions
- Casual information sharing and discussion regarding active projects (15 min)
  - @albertkun
  - @hfu 
  - @yuiseki
- Next Monthly meetup? The next one is 2023-08-18 (5 min)
- How to keep in touch (5 min)

**Comment by hfu** [comment]
It is today (in our time zone)! Please join.

**Comment by hfu** [comment]
I am preparing my presentation at https://hackmd.io/@hfu/rJ0HIrvch#/

Here are some photos I will be using. 

![IMG_9146](https://github.com/UNopenGIS/7/assets/18297/3f5d29e3-56f0-4a77-87cb-ff7bee8dbfc9)

**Comment by hfu** [comment]
![kalaja](https://github.com/UNopenGIS/7/assets/18297/e73221e0-771c-4674-b9a2-ad8c9260df7b)

**Comment by albertkun** [comment]
@hfu Sounds good! Will see you there! Looking forward to the presentations!!

**Comment by yuiseki** [comment]
> Casual information sharing and discussion regarding active projects

I will share my items in advance.

### `Smart Maps Assistant` by @yuiseki 

- Smart Maps Assistant is an AI system that can interactively visualize geospatial information using LLMs
- Presentation and demonstration of Smart Maps Assistant at FOSS4G2023 was successfully finished!
- I am currently working on two approaches for Smart Maps Assistant
  - The first is PostGIS support
    - The goal is to add the ability to generate PostGIS queries based on natural language and visualize the execution results
    - Smart Maps Assistant currently can only handle OpenStreetMap information that can be obtained via the Overpass API
    - PostGIS support should enable analysis of information that is not available in OpenStreetMap and that cannot be done with the Overpass API
    - At this point in time, I'm still learning about PostGIS myself, but it's going well!
      - In my own study, ChatGPT's GPT-3.5 has also helped me write SQL queries for geospatial information analysis for PostGIS
  - The second is to move to a open source large-scale language model
    - Smart Maps Assistant heavily depends on the OpenAI API as the base large language model
    - This should be replaced with open source to remove dependence on proprietary software
    - I believe this is possible because the field of open source large language models is very active and growing!
    - Currently, I was in the process of investigating the license of the large open-source language models
    - But in the meantime, a new open source large language model called LLaMA 2 has been released!
    - LLaMA 2 is open source in terms of license, so I will investigate LLaMA 2 in the future

**Comment by albertkun** [comment]
@yuiseki Happy to lend any support on PostGIS questions!

         
>         * PostGIS support allow us to enable analysis of information that is not available in OpenStreetMap and that cannot be done with the Overpass API
>         * Currently, I'm still learning about PostGIS myself, but it's going well!
>

**Comment by smellman** [comment]
I upload the video,. https://www.youtube.com/watch?v=wCygwM13ZOc

**Comment by hfu** [comment]
Thank you, @smellman !

**Comment by hfu** [comment]
Let's move on to #219.

**Comment by albertkun** [comment]
Thank you so much @smellman ! I hope we can meet in Japan! 😄
