### ISSUE TITLE
batctl (B.A.T.M.A.N.) による、多数のRaspberry Piのメッシュネットワーク化

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#190]
正確さと速さのために日本語で書くことをお許しください。

私は本日、多数のRaspberry Piでメッシュネットワークを構築する実験に成功しました。

![c73ef037c05e4ea7c3f88a68af036e27](https://github.com/UNopenGIS/7/assets/25507/8e48bbc0-4e4d-4e3a-8b51-031b45c70150)
↑今回構築したメッシュネットワークの実物

[![Image from Gyazo](https://i.gyazo.com/960d2e7965eee2f4e4eb6158afb22991.jpg)](https://gyazo.com/960d2e7965eee2f4e4eb6158afb22991)
↑今回構築の成功したメッシュネットワークの概念図

メッシュネットワークは、アドホックネットワークやマルチホップネットワークとも呼ばれることがあります。

メッシュネットワークの最大の利点は、災害を初めとした厳しいデジタル通信資源制約環境下においても、バケツリレーによってデジタル通信を可能にすることができるということです。
近年、Starlinkが厳しいデジタル通信資源制約環境下におけるデジタル通信を支援していますが、それらは依然として高価なもので、また、その意思決定も気まぐれに左右されたものです。
もしも、多数のRaspberry Piによって、安価かつ機動的にメッシュネットワークを構築することができれば、デジタル通信資源制約環境下において役に立てるかもしれない、と考えます。

日本語で書いた手順書は以下です：
- https://scrapbox.io/yuiseki/Raspberry_Pi_4_Model_Bのメッシュネットワーク化
  - https://scrapbox.io/yuiseki/Raspberry_Pi_4_Model_B_メッシュネットワーク_ゲートウェイ化
    - https://scrapbox.io/yuiseki/Raspberry_Pi_4_Model_B_メッシュネットワーク_ブリッジ化
      - https://scrapbox.io/yuiseki/Raspberry_Pi_4_Model_B_メッシュネットワーク_ノード化

今後の予定として、Raspberry Piによるメッシュネットワークのさらなる動作確認と、技術的な可能性の検証をして、手順および結果を英語で提供したいと考えています。

本日時点では、私の実験にも、上記の手順書にも、メッシュネットワークをどのようにSmart Mapsに役立てられるかという観点は含まれていません。
しかし、何らかの形で、きっと役に立てるのではないかと感じています。
このようなメッシュネットワークがSmart Mapsにおいてどのように役立てるかどうかについて、ぜひ、ご意見やフィードバックをいただけるとありがたいです。よろしくお願いします。

**Comment by hfu** [comment]
公式なネットワークを使わないときのカジュアルな地理空間情報の共有、例えばワークショップでのデータの共有、などに使えそうな気がするという印象を受けました。会場のWiFiに原理的に負担をかけないということなのかなと思っており、それも魅力的です。

このメッシュネットワーク技術と IPFS （スマート地図バザール）を組み合わせるとどうなるだろう、と思いました。

**Comment by yuiseki** [comment]
フィードバックありがとうございます！
たしかに、イベントなどでの閉じたネットワーク内でデモすることができれば、この技術が日常的にも有用であることが示せそうですね。また、メッシュネットワーク内のノードを分散ストレージにできないかという点は、私も気になって調べています。

-----

今日、新しい進捗があったので共有します。

現在、私は以下のような構成のネットワーク環境下から、この書き込みをしています。

[![Image from Gyazo](https://i.gyazo.com/bc41e8f0b17ee86b5dd76f2436313615.jpg)](https://gyazo.com/bc41e8f0b17ee86b5dd76f2436313615)

昨日の時点からの差分は以下です：
- ブリッジはメッシュネットワークを構成するうえで本質的なものではなく、不要であり、除去できる
- ゲートウェイは、SPOFにならないように、冗長構成にすることができる
- ノードは、Wi-Fi APとして、Wi-Fiクライアントの上流インターネット等への接続を受け止めるように構成できる

batctl (B.A.T.M.A.N.) と hostapd を組み合わせることで、広い範囲でのロバストなWi-Fiネットワークを構成することができそうです。

-----

ChatGPTにメッシュネットワークがどう活用できるかを検討させてみましたが、やはり、分散ストレージやセンサーネットワークをアピールしてきますね。

このメッシュネットワークとIPFSとの組み合わせを試してみるのは、どうなるのか興味深い気がしてきました。

また、メッシュネットワークは容易に多数のネットワーク端末を非常に広い範囲に散らばらせることができるので、必要に応じて必要なだけセンサーネットワークを展開するといった方向でも有用性がないだろうかと考えています。
地理的に分散した（設置場所を変更したり持ち運ぶことも簡単にできる）多数のRaspberry Piに、カメラやGPSセンサーやその他の各種センサーを接続して何ができるかを想像してみたいです。

**Comment by yuiseki** [comment]
このProjectも一旦Iceboxにしようかと思うのでひとまず閉じます
