### ISSUE TITLE
What is the best options for on-site online demo in a conference?

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#199]
FOSS4G のような会議でのオンサイト・オンラインデモについて、2023-06-27の経験を踏まえて考えてみましょう。

# シナリオ分類
```mermaid
mindmap
  root((on-site demo))
    No demo
      Screenshot
      Movie
    Presenter only
      Use Internet service
        through venue's WiFi
        using presenter's own WiFi
      Use localhost
    Participants, too
      Use Internet service
        Via venue's WiFi
        On presenter's own WiFi
          need access to local service, which may be costly. 
          might confuse venue's WiFi
      Use a server on site
        Via venue's WiFi
          Hidenori's UNVT Portable Bazaar
        On presenter's own WiFi
          Shogo's UNVT Portable
          B.A.T.M.A.N?
            Can audience participate easily? Maybe not...
```

**Comment by hfu** [comment]
@yuiseki メッシュネットワークの可能性について、コメントいただけると嬉しいです。

**Comment by hfu** [comment]
![image](https://github.com/UNopenGIS/7/assets/18297/1ca10d37-d6de-4484-9be5-48ca7f745409)

**Comment by yuiseki** [comment]
まず、以下は既に検証済みのアイデアです：

- 一台のRaspberry PiにWi-Fiドングルを刺して、Wi-FiクライアントかつWi-Fi AP化する
- このWi-Fi APの上流は、状況に応じて自在に切り替えることができるようにする
  - 会場の無線LAN
  - 会場の有線LAN
  - ホットスポット化したスマホの無線LAN
  - etc
- デモやワークショップにおいては、全員がこのRaspberry PiのWi-Fi APに接続する

私がFOSS4G 2023に持っていった赤色のRaspberry Piは、こういう状態でセットアップ済みのものでした。
私の赤色のRaspberry Piは、起動すると自動的に、FOSS4G 2023の会場のWi-Fi、ホテルのWi-Fi、ホットスポット化したスマホ等、いずれかのインターネットへの経路を探索して、有効なものに接続するようになっていました。

-----

次に、すべてを有線LAN化する、というのは、最も確実で良いアイデアだと思います

- そもそも、Wi-Fiは13チャンネルしかないので、
  - 何も考えずに同じチャンネルでWi-Fi APを立ち上げると、確実に輻輳が発生するでしょう
  - うまくやったとしても、13個以上のWi-Fi APを立ち上げると、輻輳が生じる可能性が高まります
- 有線LANであれば、こうした問題は生じません
- ただし、無線LANを使わなければ、スマートフォンでアクセスすることができません
- また、多くのPCも、有線LAN端子を持っていません

-----

上記を総合すると、最もロバストネスな形態として、以下のようなネットワーク構成が考えられます

- Raspberry Piを一台用意する。このRaspberry Piは、以下を持つ
  - USB Wi-Fiドングル
  - USB 有線LAN端子
    - 上記の写真のような有線LANハブ
- Raspberry Piの内蔵のWi-Fiと内蔵の有線LANは、上流回線の確保に専念する
- USBで拡張されたWi-Fiドングルまたは有線LAN端子＋有線LANハブは、下流の他のRaspberry Piをぶら下げるために使う
- このRaspberry PiはSPoFであるため、予備も用意しておく


-----

その他、考えの共有です

- Raspberry Piが性能的に10台以下のWi-Fiクライアントしか接続できないということはないのではないかと思います
  - 市販の家庭用Wi-Fi APはRaspberry Piよりも遥かに低いCPUとメモリ性能ですが、10台以下しか接続できないということは無いはずです
- 同様に、Raspberry PiのWi-Fiの通信範囲が教室一部屋よりも狭いということもないのではないかと思います
- メッシュネットワークが有効であるのは、非常に広い範囲でバケツリレー的に通信をしたいようなシチュエーションです
  - インターネットに繋がる上流の回線が不安定な場合には、メッシュネットワークも不安定になるはずです

**Comment by hfu** [comment]
ありがとうございます。本件、いったん閉じます。
