### ISSUE TITLE
感想文を書こう！（FOSS4G 2023 参加者）

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#200]
アサイン先の3名で感想文を共有できればと思っています。
もちろん、よろしければ @mapconcierge や @ShogoHirasawa もどうぞ！

**Comment by hfu** [comment]
# これまでの作業の成果
## 個別要素についての振り返り
- Smart Maps Assistant は高い関心を生んだ。
- Smart Maps Bazaar は on-site デモを成功させることができた。実践の形について次の課題が明らかになった。
- Smart Maps Documentation および Smart Maps Card があったことは頼もしかった。
- UNVT Portable もやはり魅力的なコンテンツである。実践の形を考えていく段階に差し掛かっていると思う。

## 全体の方向性
- この先半年（あるいは四半期）の方向性を明らかにし、動きを揃えると投資対効果が高まると思う。

# これからの見通し
## 国連オープンGIS
- 継続する方向であることが明らかになった。

## FOSS4G Asia 2023, FOSS4g 2025
- 東アジアでこれら２つの会議が実施される方向になることを踏まえ、関係者の連携強化が試みられている。
- FOSS4G 2023 は広島開催という案が出ているという噂である。結果的にグローバルアジェンダに積極的に振っていくという方向は出しやすく、国連スマート地図グループとしてはそうなればありがたいことであると考えている。

## 国連スマート地図
- 直前に検討を始めていた通り、実施段階というキーワードで進めていくことになりそう。国連オープンGISのパイロットプロジェクトを立ち上げるという話もいただいており、自分たちが何をできるかを整理した上で、想定ユースケースの提案を複数持って行って検討してもらうことになるだろう。
- 2023-07-12 の Quarterly をイベントドリブンでこなしていくことになる。
- 2023-07-21 の Monthly with Khun Pongsakorn も楽しみである。（この回でもコソボについて短いレポートをした方がいいかもしれない。）
- 2023-Winter の JICA 国家測量研修での UNVT 研修枠は、実践段階の国内練習として活用できそう。

### 国土地理院での実践強化
国土地理院での実践強化については、次のことが考えられるように思える。

1. 組織内および上級管理者からの理解を増進し、中長期的には何らかの予算化ができないかブレストしてみるべき時である可能性がある。
1. 現在テレワーク環境に置かれている Raspberry Pi サーバを、国土地理院で使用している公衆回線に繋ぎ変えることができないか検討するべきである。そうすることで、さらに多数機を同時使用することがしやすくなるはずである。
1. 上記の移設先は国家測量研修の研修室と近いので、そのまま研修環境の充実に繋げることができるであろう。

# その他調整中のこと
- Meetup Monthly か Quarterly で話してくれないか bdon に頼んでみて、好意的な反応をいただいている。少人数で bdon の話を聞くのはもったいないので、何らかの拡大版にするか、少なくともなるべく多くの人に声をかけたい。時間帯の問題がなければ、どちらかというと Monthly で話してもらう方が良いと思う。 
- vmx や日本国内の詳しい人を読んでいけるようなスキルと体制を整えていくという方向性を考えても良いように思える。

# 実践の技術的内容について
## 大きな分かれ道
- [ ] 引き続き三次元データを取り扱うか、ニーズが明らかな二次元ベースマップに立ち戻るか。
- [ ] Raspberry Pi の使用を継続するか、それともより運用グレードのサーバを視野に入れていくか。

## 私の判断
- パイロットプロジェクトの具体的実践シナリオを我々側で考えることができない以上、野心は高い方が良いということで三次元データは維持するべきと考える。
- 運用グレードのサーバをサインしてくれるまでの信頼を我々か勝ち得ていないので、限界を知った上で Raspberry Pi で進むべきである。

## ユースケースの特定に向けて
1. Raspberry Pi サーバがはまるユースケースはかなり狭い。オフラインキャッシュと普通のサーバとの間に挟まれた狭いユースケースを狙いに行く必要がある。
2. オフラインキャッシュを常識的な形で作り込むだけのタレントとリソースは、現在我々グループにはない。
3. オフラインキャッシュを意識しながら、オフラインキャッシュと差別化できる何らかのユースケースを考える必要がある。
4. データは、既存のオープンデータでいくのだろう。

# 思いつき
## Brave のこの機能を使えばオフラインキャッシュになるのでは？

<img width="696" alt="スクリーンショット 2023-06-30 15 02 40" src="https://github.com/UNopenGIS/7/assets/18297/6f3ed567-b272-411d-845d-f7eb0f3cc341">

**Comment by smellman** [comment]
感想 by @smellman

# Workshop

- UNVT PortableのRaspberry PiのインストーラがWindowsで動かない人が居るとか罠が結構あった。
  - 次回はインストール済みのSDカードを配るなどすると良さそう

# Presentation

- 幅広いテーマが扱われていてとにかく体感が良い。
  - 知識のアップデートのために毎年来たい。
- Cloud Nativeはもはや基底路線ではという感じ。
  - ipfsがこの流れに乗れたら最高だと思った。
- QGIS + Offlineも新しい流れだと思った。

# 良かった事

- bdonなど著名な方々に挨拶することができたり、逆に声をかけてもらったりしてすごく嬉しかった。
- FOSS4G2025の日本誘致が現実味が出てきた。かなり好感触。
- 特に井口さんと技術的な濃い話が出来て気分が高まった。
  - 戦友みたいな人がいるのはやはり良い。

# 良くなかった事

- 国連の集まり(飲み会の方)で人見知りが発生してしまい、なかなか話せなかった。
  - Community Cardをうまく使いこなす事ができれば、もうちょっと話せていたかも。
- 自分の発表はちょっと人が少なすぎた。大きな部屋だったのにもったいない(^^;
- 疲れてると発表聞きながら寝てしまう事があるので、ちゃんと休憩が必要。

**Comment by hfu** [comment]
We will be closing this issue soon.
