### ISSUE TITLE
Project Collaborative Web Mapping - in Smart Maps Bazaar

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#206]
<img width="1079" alt="image" src="https://github.com/UNopenGIS/7/assets/18297/2b1cc074-6488-4f1e-ba8a-6768557389db">

**Comment by hfu** [comment]
@yuiseki vmx の実装って、ブラウザで動く ipfs ライブラリを使っていたのでしたっけ。そういうアプローチができる場合には、スマートフォン展開も考えうるのかなと思ったので、vmx の仕事をよく理解しなければならないと思いました。

**Comment by yuiseki** [comment]
@hfu 以下のリポジトリがvmxさんの実装の全体です
https://github.com/vmx/colleemap

要点
- ブラウザだけで完結しているわけではない
- Wi-Fi AP + Webサーバー化は必須、ここはSPoF
- Wi-Fi AP + WebサーバーさえあればスマホやPC同士がp2pで繋がって、IPFSも含めた様々な通信がdecenterizedで動く
- ただし、同一のWi-Fi APに繋がっている端末同士でしか繋がらないので、結局は物理層が中央集権化する
- B.A.T.M.A.N.によるメッシュネットワーク化でSPoF、中央集権化を潰せるかもしれない？

**Comment by yuiseki** [comment]
> 「スマートフォン同士が p2p でつながる」というところはどのように実現しているのでしょうか

WebRTCです。
WebRTCは、スマートフォンに限らず、Webブラウザ同士をp2pで接続することを実現できます。
現在の主要なWebブラウザはWebRTCをサポートしているので、スマートフォンでもPCでも、WebRTCによって、p2pで接続することができます。
libp2pは、Webブラウザの場合はWebRTCを使い、他のランタイムの場合には他の通信方式を使うように抽象化されているライブラリのようです。

**Comment by vmx** [comment]
I've read through the comments thanks to Google translate.

Currently  WebRTC and WebTransport protocols are implemented in Kubo. This means that in the future, you'd be able to directly connect to a Smart Maps Bazaar server from the browser. You should then be able to further replicate the data directly from one browser to another as the Colleemap prototype shows.

I imagine Colleemap not being uses as "all users are constantly connected and see each others updates", but rather as "users mapping things while being completely offline and exchange their data once they come together".

**Comment by hfu** [comment]
#274
