### ISSUE TITLE
FOSS4G 2023 レトロスペクティブ yuiseki

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#207]
## 野望

- FOSS4G 2024では、GIS + AIをテーマにしたワークショップand/orプレゼンテーションをしたい
- UN peacekeeping, UN development, または他のUN agenciesの、現場に行きたい
  - #206 #203 を通じてそのチャンスが得られるかもしれない？
  - 参考：現在の国連ミッション
    - [![Image from Gyazo](https://i.gyazo.com/dc50c22a9fdf8ae586048c938fbdd3f2.jpg)](https://gyazo.com/dc50c22a9fdf8ae586048c938fbdd3f2)
- 関さんのように、UNHQに招待されるくらいにまでビッグになりたいｗ

## 行動計画

- 短期的（7月～8月末）には、
  - 着実な行動として、
    - Smart Maps Assistant（以下、TRIDENT）をHOTOSM向けに実用化することを最優先する
      - HOTOSMに対応できれば、他のユースケースにも対応可能になるはず、ということを意識しながら開発していく
    - HOTOSMの衛星画像解析・地図製作支援AIである https://github.com/hotosm/fAIr への貢献を試みる
    - HOTOSM技術チームとUN Open GISの相互連携が強化できるように、自分が窓口になる
  - 投機的な行動として、
    - SMASH、PMTiles、IPFS、libp2p、B.A.T.M.A.N.などを組み合わせた何かを試行錯誤してみる
      - Smart Maps Bazaar 2.0のような位置づけになるか？
      - キーワード: smart, portable, stand alone, robustness, replication, redundancy, diversity, fault tolerance, decentralized, distributed, plurality
- 中長期的（7月～年末）には、
  - TRIDENTをパイロットプロジェクト向けに実用化していく
  - TRIDENTで使っているOpenAI APIを、独自のFOSSなLLMsに置き換える（TRIDENT Base Modelと呼称）
    - TRIDENT Base ModelをGPU 1個で動くようにする
    - TRIDENT Base ModelをMac Book 1台で動くようにする
    - TRIDENT Base ModelをRaspberry Pi 1台で動くようにする

## 行動計画の背景

- HOTOSMは目標が具体的であり、リソースが明確であり、広く開かれた、透明性の高いコミュニティのようだ
- HOTOSMには、私が挑戦してみたかった技術的な挑戦が山積みのようだ
- HOTOSMは、fAIrのように、AIを公平かつ透明性の高い形で活用することをすでに実践している
- HOTOSMのメンバーは、私が手伝えるかもしれない技術的な貢献のアイデアを最も具体的に示してくれた
- HOTOSMは既にUNOCHAと連携している（たぶん）
  - 他のUN agenciesとの連携も拒絶されることはないだろう
- 私にGIS分野のスペシャリストとして公共事業や人道支援の具体的な経験や実績がないのは減点ポイントだ
  - HOTOSMにおいてTRIDENTを実戦投入することで具体的なユースケースに対応できることを確認することができるはずだ
  - HOTOSMの、特に技術チームとのつながりを高めていくことで、こうした経験や実績が積めるはずだ

-----

FOSS4G 2023への参加を通じての自分の現在の考えを書いてみました。

@hfu フィードバック、コメントなどあればお願いしたいです！

**Comment by hfu** [comment]
HOTOSMとの連携は有望だと思います。我々が既に持っているネットワークのなかでも、HOTOSMと懇意にされているかたもおられると理解しています。

他方で、HOTOSMは資金の回し方とかもうまいプロ集団と拝察していますので、彼らから見た我らのバリューというのをある程度整理して、話がかみ合うように調整すると円滑になるかもしれないと思いました。

**Comment by yuiseki** [comment]
このIssueは情報共有とフィードバックを頂くことが目的であり、フィードバックはいただけたので、閉じます。ありがとうございました！！
