### ISSUE TITLE
FYI: Raspberry Pi上でもLLMsは動く

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#208]
## Why?

- Open GISやFOSS4Gを掲げているのでOpenAIに依存するのはダサい

## How?

- llama.cpp という、GPUを使わずに機械学習モデルを動かす仕組みがある
  - Raspberry Piでビルド、実行できる
- 速度は遅く、精度は低い
  - とはいえ、天文学的に遅いわけではない
  - 特定の用途にチューニングすることができるはずである
- FOSSと言えるのかはライセンスなどが良くわかっていないので断言できない

## Log

https://scrapbox.io/yuiseki/Raspberry_Pi_4_Model_Bでorca_mini_3bを動かしてみる

**Comment by hfu** [comment]
@hfu is catching up on this. 

- domain name: m352
- TODO

**Comment by hfu** [comment]
We may be closing this issue soon, moving to the next step.

**Comment by yuiseki** [comment]
OK, Let's close this issue!
