### ISSUE TITLE
2023-07-27T09:00-04:00 🎧UN Open GIS Monthly

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#213]
As announced by @KyoungEom, Monthly VTC of UN Open GIS is scheduled on **Thursday**, 27, July 2023 at 3pm Rome time and 9am New York time. 

Let's discuss how Smart Maps Group should report to the initiative.

**Comment by hfu** [comment]
I will be on a trip this time. I think I will be able to connect from the hotel, but I am not sure I can talk on behalf of Smart Maps Group (SMG). 

@yuiseki Are you possibly able to talk on behalf of me? I will be creating the reporting slide anyway. 

I will be sharing the draft agenda developed by Kyoung-Soo below:

**Comment by yuiseki** [comment]
@hfu Sure! Thank you for giving me a chance to talk at UN Open GIS Monthly. Cloud you sharing your presentation slides and, if possible, the main points you should talk about?

**Comment by hfu** [comment]
Thank you so much, @yuiseki. I will be preparing presentation slides and talking points!

**Comment by hfu** [comment]
@yuiseki As we discussed in #217, I am thinking about how best I can share our draft presentation slide. 

First, I chose the wilder option to import the slides to https://hackmd.io/@hfu/smr-2023-07#/1 only to find it is hard to have all the contents in each slide. 

Which do you think is better to receive the presentation file? 

1. HackMD - we may need to work on the layout. 
2. Google Slides - I will import the existing PPT file into Google Slides (when I am back home.) 

I attach the PPTX file here. 

[2023-07-27-smart-maps-report.pptx](https://github.com/UNopenGIS/7/files/12157737/2023-07-27-smart-maps-report.pptx)

**Comment by hfu** [comment]
@yuiseki I uploaded the PPTX file to Google Slides and shared with you at your Google account. Please check if it works for you.

**Comment by hfu** [comment]
@yuiseki Google Slides でシェアした方のスライドを最小限アップデートしました。また、コソボで会った Data Clinic の二人に、LinkedIn 経由で PDF 版を事前共有しました。反応あったら共有します。

**Comment by yuiseki** [comment]
@hfu お返事が遅れてすみません。Google Slidesは私の方でも正常に閲覧できています！アップデートありがとうございます！

**Comment by hfu** [comment]
@yuiseki Congratulations on your successful presentation for the UN Open GIS Monthly meeting. I really appreciate your efforts for the Smart Maps Group! 🙏

**Comment by KyoungsooEom** [comment]
@yuiseki I would also like to join Hidenori to congratulate you on your excellent presentation.
