### ISSUE TITLE
2023-08-09: 🎧Smart Maps Quarterly (last steps)

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#214]
Thanks to advice from @KyoungEom and Timur, I am developing final documents for the meetup on 2023-08-09. 

Let's develop the (Living) Meetup Concept for 2023-08-09 at https://hackmd.io/Jr706TLVQGC8Tk7E1GpJ1A. 

I will be continuously consulting with UNGIS members on UN MS Teams, but I will be sharing the results on this issue.

**Comment by KyoungsooEom** [comment]
@hfu, grateful if you could invite me (personnel email: kyoung.eom@hotmail.com).

**Comment by hfu** [comment]
Thank you, @KyoungsooEom for your input. 

## (Living) Meetup Concept Note
I revised the data access permission so that everyone can access https://hackmd.io/Jr706TLVQGC8Tk7E1GpJ1A now. 

## Teleconference preparation
I am thinking about hosting the Meetup on Microsoft Teams by our Ministry. Please let me know if there are any possible technical challenge with this. Please kindly test the connection. 

https://teams.microsoft.com/l/meetup-join/19%3ameeting_Mjg4NzRjMTQtNDIyYy00NmNmLThkOWYtNWU1ZTEzYjc3NTU3%40thread.v2/0?context=%7b%22Tid%22%3a%22cdec79b4-6c91-4d03-bccf-b473d5a597a2%22%2c%22Oid%22%3a%221bd03f32-5b15-482f-a430-fd6dda338eb3%22%7d

Meeting ID: 487 122 043 702
Passcode: yqJrKS

**Comment by hfu** [comment]
I found that someone from the hosting side has to be there to keep the link above accessible. I will be keeping there for several tens of minutes, but will be offline from the meeting after that. Sorry about that.

**Comment by hfu** [comment]
See also: https://github.com/UNopenGIS/7/issues/217#issuecomment-1654616483 (internal discussion about the concept of the pilot project proposal.) 

Our proposal will be a "small but long-run project that some technology enthusiast would feel they would like to help voluntarily". We are rather technology enthusiasts than coordinators. 

We will be discussing the presentation materials online on GitHub in a asynchronous mode before the actual session.

**Comment by hfu** [comment]
I decided to use Zoom for the meetup. I will be back with the link soon.

**Comment by hfu** [comment]
## Teleconference link
I created the link to the meeting. 

Zoom Meeting
https://us02web.zoom.us/j/82862812293?pwd=VGpOYXFoZUVEMHFzVWVaQjNWWjNtUT09

Meeting ID: 828 6281 2293
Passcode: 690231

**Comment by albertkun** [comment]
@hfu i updated the smart maps website, both English and Japanese with these details:

EN - https://unopengis.github.io/smartmaps/events/2023-08-09
JP - https://unopengis.github.io/smartmaps/ja/events/2023-08-09/

**Comment by hfu** [comment]
@albertkun Thanks! I also added some final touches. I believe these are fully ready.

**Comment by hfu** [comment]
Pending UN Open GIS bureau clearance, I will be sharing the information page on UN Open GIS Team on Monday.

**Comment by hfu** [comment]
As @KyoungsooEom suggested to use UN MS Teams for the meeting, please wait for further announcement regarding teleconference URL.

**Comment by albertkun** [comment]
@hfu Thank for the update! I see that you updated the Smart Maps website already. I appreciate it!

**Comment by hfu** [comment]
As discussed in #221 we would like to share the presentation file from https://docs.google.com/presentation/d/1OwuZeywXDsbAmpsuYT3m70hp4psQag7O8nfHJZNzvrs/edit?usp=sharing. 

Please note that the slides are still under development.

**Comment by hfu** [comment]
Slide preparation is somewhat complete, pending the flier on slide 44. 

Excuse me for not consulting with you well, but I would like to use the 1st proposal as below. 

![image](https://github.com/UNopenGIS/7/assets/18297/96185948-06d9-4215-8df7-436c9fe6a13b)

Comments and advice welcome!

**Comment by hfu** [comment]
#231 の結果、情熱ある人たちとの対話が始まっているので、その対話を大切にしながら進めていきましょう、という方向性で一致したので、このイシューは閉じることにします。
