### ISSUE TITLE
2023-08-16 🎉 Meet Albert in Tokyo!

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#215]
As discussed in #188 
See: https://hackmd.io/@MXxudfFtSvSvSonMo4L3qQ/SyT0kFwqn#/4
Ideally: 2023-08-14 - 2023-08-16

**Comment by albertkun** [comment]
Happy to visit Tsukuba if it's convenient for the participants too! :)

**Comment by albertkun** [comment]
@hfu That works for me! I will be staying near Nippori station, which is close to Asakusa!

**Comment by yuiseki** [comment]
Wow! I live in Taito ward where Asakusa is located! My house is close to Nippori station!

**Comment by hfu** [comment]
We discussed on this in #217. 

Let's pursue the following plan first. Feedback welcome. 

- 2023-08-16 evening time
- Somewhere in Taito ward

**Comment by albertkun** [comment]
Sounds good to me! Should we meet for dinner or an izakaya? Just to note... I am vegetarian! 😅

**Comment by hfu** [comment]
@smellman @yuiseki It is now good time to decide who will be the 幹事 for the meeting. I will be glad to, but I have no good local knowledge about Taito ward. Any volunteer idea? Maybe we can fix the time first so that we can plan ahead in the weekend.

**Comment by yuiseki** [comment]
@albertkun @hfu @smellman As I wrote above, I live near Asakusa in Taito-ku, Tokyo, and would like to invite you all to my house if you like!

You all can come to my house at the following time:
2023-08-16T17:00/22:00+09:00 for Tokyo

I will also share information and photos of my room:
https://gyazo.com/collections/9287430172a7a52441bf9314a17f02bd/list

What do you think about this idea?

**Comment by albertkun** [comment]
@yuiseki not a bad idea! Your place looks really nice too!!! 

BUT... So sorry.. That is the same time as the semi-final for the [FIFA Women's World Cup ](https://www.fifa.com/fifaplus/ja/tournaments/womens/womensworldcup/australia-new-zealand2023/articles/the-route-to-the-womens-world-cup-final-2023-bracket-fifa-football-soccer-australia-new-zealand-ja), which I am actually cheering for Japan to win (even though Mana Iwabuchi (岩渕 真奈) isn't playing this year :( )! 

Of course, this is subject to change depend on how Japan performs. 😅

**Comment by hfu** [comment]
@yuiseki It would be great to meet in your place. Thank you for your kind offer. 

@albertkun and all, I suppose it would be great that UN Smart Maps Group in Tokyo watch FIFA Women's World Cup in the meet, if it is not too problematic for yuiseki's place. 

I also think that it would be important to take a casual **group photo** because it would help up introduce ourselves. From this perspective, should we invite some other Group members in Tokyo?

**Comment by albertkun** [comment]
@hfu Oh that would be really great to watch it together if @yuiseki and other's don't mind!!

Maybe we can advertise this as the UN Smart Maps Women's World Cup Japan Watch Party. Just kidding!

And yes, I think a casual group photo would be great, as well as inviting other Group members if @yuiseki does not mind!

**Comment by yuiseki** [comment]
@hfu @albertkun 
I have a 50" Android TV in my room, so if there is a way to watch the FIFA Women's World Cup on a Japanese TV station or Online live streaming Android TV, it would provide the best experience!
At the moment, I can watch YouTube Premium, Netflix, and Amazon Prime Video on my Android TV in my room.
I just had 8 friends over to my room last week to watch the Sumida River Fireworks Festival, so I think I can manage to comfortably accommodate up to about 8~10 people.
Everyone is welcome to come in my room!

**Comment by albertkun** [comment]
@yuiseki Thank you so much for offering! I think watching the match on your 50' screen would be amazing and unforgettable experience for me!! I believe the games are streaming on NHK:

https://www.nhk.jp/p/ts/R1L4LN9X9L/schedule/

Not sure if that link work, but let me know if we need to find another stream!

If there is anything you'd like for me to bring to your house (food/snacks/etc.), please let me know as well!

**Comment by albertkun** [comment]
@hfu @yuiseki really sorry, but there might be a chance that I have to delay my travel because of an expired passport. I made an appointment to expedite a renewal. 🤞 If it is OK with everyone, can I post an update on Tuesday morning 2023-08-15 8am JST. I apologize again for the inconvenience! 😭

**Comment by hfu** [comment]
No problem for me, @albertkun. Looking forward to the update and I hope a good luck regarding the renewal process.

**Comment by albertkun** [comment]
@hfu Thank you for the flexibility! I will keep you all posted!

**Comment by albertkun** [comment]
@hfu @yuiseki Because of the results today, we do not need to watch the Women's World Cup.. 😭 😭

**Comment by hfu** [comment]
Or we can still watch the semi-final though Japan is not there. 🙂 But we might want to focus on our team's face-to-face meeting. 🙂

**Comment by hfu** [comment]
@albertkun Are you coming to Tokyo tomorrow or postponing your visit? I just would like to confirm your availability.

**Comment by albertkun** [comment]
@hfu @yuiseki  ok, i think i should be able to make it! so shall we all meet tomorrow? I will be landing at 3pm!

**Comment by albertkun** [comment]
Sorry for the late reply, I was rebooking my flights 🙏🙏 looking forward to seeing everyone! Do we know how many people are coming? 👀

**Comment by yuiseki** [comment]
@hfu @smellman If you come to my room tomorrow, I would like you to assign yourself to this Issues.

**Comment by hfu** [comment]
@yuiseki @smellman I confirmed the place now, thanks to @yuiseki. 

- Should I, or is it OK to, bring some food and drinks to the place? My suggestion is that the hosting side (yuiseki, smellman, and hfu) bring some casal food. In my case I would buy some food and drinks in the local supermarket and bring it. Do you have any alternative idea? 
- We will be bringing vegetarian food. 
- I am wondering whether I should go without alcohol beause I am wondering I should take the bus, or take the train and my car. How about you? :-)

**Comment by albertkun** [comment]
Actually, SO SORRY, I don't drink either... But please feel free to!

So sorry for my restrictions. I have a good reason for it all! 😭

**Comment by albertkun** [comment]
Also, thank you @hfu for all the preparation. If I can help in bringing anything, please let me know! I will be checking in at my hotel in Nippori at around 4pm!

**Comment by yuiseki** [comment]
話が難しくなってきたので日本語で書かせて下さい 🙇‍♀️ 

- 私の家には5pm **以降** に来て下さい
  - 5pmまでは私はリモートワークで仕事をしています
  - 5pmを少し過ぎるくらいに来るようにしていただきたいです
- 私の家には水、お茶、アイスコーヒー、炭酸水がたくさんありますので、好きなだけお飲み下さい
- 私の家にはウイスキー、ジン、クラフトビール、焼酎があります。これらも好きなだけお飲み下さい
  - それ以外のアルコールを飲みたい場合には、自分で買ってきてください
- 私の家にはマトモな食べ物がありません！
  - ドリトス（Doritos）というチップスだけは、山ほどあります
  - 各自で食べたいものをスーパーマーケットやコンビニで買ってきてください
  - Uber Eatsで探して注文することもできます！
  - 調べたところ、ベジタリアン向けには、Uber EatsでSUBWAYのAvocado & Veggieを注文することができます
    - https://www.subway.co.jp/menu/sandwich/2287.html

**Comment by hfu** [comment]
No worry, @albertkun. Just come to the place and we can share the food and drinks. In case it is difficult to come to the place, also please let us know. 

@yuiseki Thank you for practical guidance. It is really helpful for me. I will get something to eat and drink before coming to your place.

Thank you everyone for your flexibility!

**Comment by albertkun** [comment]
@hfu Thank you! Sure! I have just arrived at the hotel and am just settling down. I will head over in a little bit! According to @yuiseki it seems as though we should arrive after 5pm! So, I will aim for 5:15pm! If you need me to bring anything, please let me know!

**Comment by yuiseki** [comment]
I finished my work today! You are welcome to come at any time!

**Comment by albertkun** [comment]
お疲れ様でした！haha, already?

**Comment by albertkun** [comment]
Thank you for the great time @hfu @yuiseki @smellman ! It was the nicest welcome to Japan! ✨ Good luck with work tomorrow and looking forward to seeing everyone at Friday's meet up! 🌞

**Comment by smellman** [comment]
https://www.dropbox.com/scl/fi/ifswti1i5w2fdrsp7d413/IMG_2929.jpg?rlkey=i8vfho039hbgljsq5a1y9txo1&dl=0
I share a group photo.

**Comment by albertkun** [comment]
@smellman thank you!! It is a great photo with good memories! ❤️

**Comment by hfu** [comment]
Thank you, @smellman for the photo. 
I am including the photo in the presentation for the UN Open GIS Monthly tomorrow. 

I mark this issue as successfully completed. Thank you all.

**Comment by albertkun** [comment]
> https://www.dropbox.com/scl/fi/ifswti1i5w2fdrsp7d413/IMG_2929.jpg?rlkey=i8vfho039hbgljsq5a1y9txo1&dl=0 I share a group photo.

I liked the photo so much, I hope you do not mind if I use it for my linked.in profile picture!

https://www.linkedin.com/in/albertkun/

But...

@hfu @smellman @yuiseki if you are not OK with it, I will promptly remove it!
