### ISSUE TITLE
💡 🎤 Ideas: Guest Speaker for Smart Maps Meetup Monthly

### ISSUE THREAD

**Issue by albertkun** [UNopenGIS/7#216]
### Potential Guest Speakers
- Kazuya-san
- Not sure if relevant but: Guest from Cal-ITP (https://www.calitp.org/) California Integrated Travel Project to discuss transportation data (https://github.com/cal-itp)

**Comment by hfu** [comment]
@albertkun We discussed on this at #217 and here is our suggestion: 

1. Kazuya in August
2. Guest from Cal-ITP in September

What do you think? I am coordinating with Kazuya based on this line. I will update.

**Comment by hfu** [comment]
# Other guests we want to invite
Let's also discuss who we want to invite. (Or let me know if anyone want to speak!) 

@yuiseki Do you have any idea about inviting our new friends we contacted after Kosovo (as introduced in #217)?

**Comment by hfu** [comment]
@albertkun By the way, I have some friends who are interested in public transportation. I would like to invite them as 'special guest audience' so that we can expand our network. Maybe we can discuss on 2023-08-16 #215.

**Comment by albertkun** [comment]
@hfu yes, i think Kazuya would be great for August! Can we get a quick bio/discussion on his talk? I will have my colleague include that in the flier she is making and on the website!

Having attended the `Cal-ITP` presentation their focus was mainly on transportation data analysis, ETL pipelines, and technology stacks, so me and my colleague think that the `Mobility Standards` group (that was involved in Cal-ITP), https://github.com/MobilityData/ would be great to invite to talk about open data standards (instead of the tools). What do you think? They can talk about why open data standards is important and how the open data standard they created for transit (GTFS) is being used! I think this can translate well to geospatial data and the vector tile toolkit.

**Comment by albertkun** [comment]
> @albertkun By the way, I have some friends who are interested in public transportation. I would like to invite them as 'special guest audience' so that we can expand our network. Maybe we can discuss on 2023-08-16 #215.

That is amazing! Yes, I hope your friends interested in transportation can join us! I am very passionate about transportation as well!

In terms of other speakers, I can my colleague @yohman to present on his research on Fukushima and spatial ethnography!

**Comment by hfu** [comment]
## August, September, and onward
Meanwhile I am following formalities with Kazuya's office. Let's say we decided to ask Kazuya for August. 

For September and onward, I think we would like to follow 3 options by @albertkun. It feels like that the Monthly is a great opportunity to broaden view and (broader) community. Let's keep up in this direction. 

## Kazuya's presentation
This is information I have now. 

1. His presentation will be 30 minutes: 15 minutes about [Virtual Shizuoka](https://www.pref.shizuoka.jp/machizukuri/1049255/1052183.html) and 15 minutes for its use cases. 
2. He is currently working for Shizuoka Prefectural Government - Department of Crisis Management. 
3. I will be consulting with Kazuya about a quick bio and will get back to you here soon.

**Comment by hfu** [comment]
@albert Here is a quick bio of Kazuya, confirmed by him: 

> Kazuya Sato (he/him) is a Physical Geographer. Since 2017, he has been working with the Shizuoka Prefectural Government, serving in various departments, including the Transportation Infrastructure Department, as well as the Crisis Management Department. Additionally, he has been seconded to the Shizuoka Economic Research Institute.

**Comment by albertkun** [comment]
Thank you @hfu !! I went ahead and passed the information onto my mentee! I'll go ahead and make a bios page for Kazuya on the Smart Maps page as well, and will track it here https://github.com/UNopenGIS/smartmaps/issues/35

**Comment by hfu** [comment]
I am closing this because we are following a new monthly meetup style.

**Comment by albertkun** [comment]
Sounds good! Thank you!
