### ISSUE TITLE
mosaic: ベクトルタイルを再構築するための Rubyコマンド（構想）

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#218]
[mosaic: ベクトルタイルを再構築するための Rubyコマンド（構想）](https://qiita.com/hfu/items/7025946c38f9f9b4b86e)

今回、実演より先に説明をしてみようということで説明を生成してみました。

思ったよりも長くなりました。ツールを作るとき、このくらいのことを確かに実際には考えてから手をつけているのですね。

結果的に、実演だけすれば伝わるというものではない、ということについて私が理解を深めたような気がします。

**Comment by yuiseki** [comment]
ざっと目を通して、いわゆるDesign Docと呼ばれるものに近い文書なのかなという印象を受けました。

- https://myenigma.hatenablog.com/entry/2021/07/25/140308
- https://qiita.com/yoshii0110/items/32f93e0c8d24cb3207f7

たしかに、ソフトウェアプロジェクトについて、これくらい意図を言語化しておくことは重要そうですね。

**Comment by hfu** [comment]
https://github.com/unvt/mosaic

**Comment by hfu** [comment]
ズームレベルが14を超えるような大規模になってくると、エラーハンドリングをしないと全国ダウンロードはうまくいかないので、時間を見つけてそのあたりに取り組んでいきます。

**Comment by hfu** [comment]
PMTiles 配信の主流化が進んできたので、少しアプローチを変えられる状況になってきたように思います。
#274
