### ISSUE TITLE
2023-08-18/17: 🎧Smart Maps Meetup Monthly 5

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#219]
# Smart Maps Meetup Monthly 5

## What is this meetup?

This event is an open online event where UN Smart Maps Group share their progress so that participants can share knowledge and information.

## When is this meetup?
We are meeting every 3rd Friday. This time the meetup will be:

2023-07-17T21:00/22:00-08:00 for Los Angeles
2023-07-18T00:00/01:00-07:00 for New York
2023-07-18T06:00/07:00+02:00 for Rome
2023-07-18T09:30/10:30+05:30 for New Delhi
2023-07-18T13:00/14:00+09:00 for Tokyo

## How can I participate?

Join via the this [Zoom link](https://ucla.zoom.us/meeting/register/tJcoc-mvrTovG920aIcgb-64RaKdVWKTb1Ik).

### Opening

Welcome by Hidenori, Smart Maps Lead (2 min)
Introduction by new participants (8 min)

### Presentation

TBD (will update here)

### Closing - next actions

Introduction of upcoming events (20 min)
How to keep in touch (5 min)

**Comment by smellman** [comment]
2023-08-17T21:00/22:00-08:00 for Los Angeles
2023-08-18T00:00/01:00-07:00 for New York
2023-08-18T06:00/07:00+02:00 for Rome
2023-08-18T09:30/10:30+05:30 for New Delhi
2023-08-18T13:00/14:00+09:00 for Tokyo

**Comment by hfu** [comment]
@albertkun @smellman @yuiseki Due to the conflict of schedule of our guest speaker, it would be great to start the meet up 30 minutes earlier than usual. Is it OK for you? 

If not possible, I am afraid some important contents will be skipped from the presentation, but it is still possible to start at regular time. 

Please let me know what you think.

**Comment by albertkun** [comment]
Sure! But would an hour be better then? As 30 minutes is kind of harder to remember! Just my opinion though!

**Comment by hfu** [comment]
Thanks @albertkun, that is a good point. I confirmed that 1-hour early start is a possible option for our guest speaker this time. 

@yuiseki @smellman Are you OK with starting 1-hour earlier? I am a little afraid that it is inside your working hours. I hope it is also OK for both of you. 

@k96mz Please let me know if this also fits with your schedule if you are coming to the meeting the next time, too.

**Comment by smellman** [comment]
@hfu I'm OK because starting 1-hour earlier is "not" inside my working hours.
Also I will leave at 13:00 because I have weekly meeting in this time.

**Comment by albertkun** [comment]
@hfu once the shift is confirmed, I will go ahead and update the zoom meeting!

**Comment by yuiseki** [comment]
@hfu I, too, am OK with moving it earlier an hour.

**Comment by hfu** [comment]
Thanks! Then let's say the change is confirmed. 

@albertkun Please update the zoom meeting.

**Comment by hfu** [comment]
@smellman Thanks for letting me know it would be lunch time this time, 'not' inside working hour.

**Comment by albertkun** [comment]
@hfu ok, I updated the event on Zoom as well as added it to the Smart Maps website:

EN:
https://unopengis.github.io/smartmaps/get-involved/community-meetings/international/2023-08-18/

JP:
https://unopengis.github.io/smartmaps/ja/get-involved/community-meetings/international/2023-08-18/

Note that the links will soon change to when I refactor the `events` (https://github.com/UNopenGIS/smartmaps/issues/34)
`https://unopengis.github.io/smartmaps/ja/events/2023-08-18/`

**Comment by k96mz** [comment]
@hfu Sorry for my late reply. I will participate in the meeting.

**Comment by hfu** [comment]
@albertkun Thank you so much for updating the event page. I appreciate the future refactoring plan. One additional reason is that we no longer call the monthly meetup "International Meetup" but "Meetup Monthly" after adding quarterly Atlantic time events (which now we call "Meetup Quarterly"). 

@k96mz Thank you for letting us know you will be coming. 

I will be announcing this change to our friends from Thailand, too.

**Comment by hfu** [comment]
Yes, I announced Khun Prasong and Khun Pongsakorn about the time change this time.

**Comment by hfu** [comment]
## Program
### Opening

Welcome by Hidenori, Smart Maps Lead (2 min)
Introduction by new participants (8 min)

### Presentation

Virtual Shizuoka, Kazuya (30 min)

### Closing - next actions

How best we can facilitate monthly meetup (Hidenori and Albert, 10min)
Introduction of upcoming events (5 min)
How to keep in touch (5 min)

![flier](https://user-images.githubusercontent.com/8574425/259316173-84f7d874-289e-41a8-b60e-1d40201345a7.png)

**Comment by hfu** [comment]
- point cloud for game development
- point cloud for automation
- point cloud for disaster 
- "experiment field" - I like this idea!
- disaster response in international collaboration
- OpenDroneMap collaboration - easier acquisition technology - compared with "heavier" technologies.

**Comment by hfu** [comment]
We decided to consult with @albertkun and the community regarding how we facilitate the monthly meet up from the next time!

**Comment by hfu** [comment]
If I may I would like to introduce our session in #230 by using the image below. 

![image](https://github.com/UNopenGIS/7/assets/18297/c6dc9738-73be-4ab0-8643-150d6d4a3952)

**Comment by albertkun** [comment]
@smellman here is the recording for the latest UN Smart Maps Pacific meeting!

https://ucla.zoom.us/rec/share/NJfY0x85Aip_5LKxMCSu84Gfi26H_ZSgwjmxgVstGRMdMcqYDpOqNkzRymbOFv65.3TYIPx-Sj1h0JWZz

**Comment by smellman** [comment]
I upload today's video.
https://www.youtube.com/watch?v=lZPZOWLOeRk

**Comment by albertkun** [comment]
@smellman thank you very much!

**Comment by ka2sato** [comment]
Huston, Huston, this is Kazuya speaking,　I uploaded the slides by using slide share.
https://www.slideshare.net/kazuyasato37051579/unsmartmapmeetup2023aug18pptx
<iframe src="https://www.slideshare.net/slideshow/embed_code/key/DZnEA4RvX9EPa5?hostedIn=slideshare&page=upload" width="476" height="400" frameborder="0" marginwidth="0" marginheight="0" scrolling="no"></iframe>

**Comment by albertkun** [comment]
@ka2sato Copy that. This is mission control, we have received confirmation of your slides via slide share. Will update you when it goes live. Thank you. Houston over! 😄

**Comment by ka2sato** [comment]
I forgot to attach links to Virtual Shizuoka.
[Virtual Shizuoka Links.docx](https://github.com/UNopenGIS/7/files/12505938/Virtual.Shizuoka.Links.docx)
