### ISSUE TITLE
First release of Overture Maps Data: 2023-07-26-alpha.0

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#220]
https://overturemaps.org/download/

- Techcrunch: Meta, Microsoft and Amazon release open map dataset to rival Google Maps, Apple Maps
  - https://techcrunch.com/2023/07/26/meta-microsoft-and-amazon-release-open-map-dataset-to-rival-google-maps-apple-maps/
- Engadget: Amazon, Microsoft-led group shares data for open alternative to Google Maps
  - https://www.engadget.com/amazon-microsoft-led-group-shares-data-for-open-alternative-to-google-maps-160001416.html

**Comment by hfu** [comment]
Wow, they are using DuckDB #212 at https://github.com/OvertureMaps/data#3-duckdb-sql 🦆

**Comment by hfu** [comment]
#274
