### ISSUE TITLE
Change example locations for Smart Maps Monthly meetup time

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#222]
## Problem
Currently, we announce the date and time of Smart Maps Meetup Monthly as below: 

```
We are meeting every 3rd Friday. This time the meetup will be:

2023-08-17T20:00/21:00-08:00 for Los Angeles
2023-08-17T23:00/00:00-07:00 for New York
2023-08-18T05:00/06:00+02:00 for Rome
2023-08-18T08:30/09:30+05:30 for New Delhi
2023-08-18T12:00/13:00+09:00 for Tokyo
```

## Proposal
- [ ] Drop New York because the time is not really good for participation. However, @k96mz is so passionate to participate. 
- [ ] Drop Rome because the time is not really good for participation.
- [ ] Add Bangkok because we actually have participants from Bangkok. 
- [ ] Or, we can just 'out-source' these local time announcement to some external service. 

What do you think? 

I assign @albertkun with me because it is also related to Documentation.

**Comment by hfu** [comment]
@albertkun Thanks! Yes, from our recent experience, we may want to rebrand these 3 series of meetups. 

Regarding "out-sourcing" I was just thinking about putting a link to an external service like https://www.timeanddate.com/worldclock/meetingdetails.html?year=2023&month=8&day=9&hour=2&min=0&sec=0&p1=248&p2=137. What do you think?

**Comment by albertkun** [comment]
@hfu  this sounds good! the draft flier includes the new times:

![image](https://github.com/UNopenGIS/7/assets/8574425/b3c327b6-342d-4ff5-90f2-cb9ecee8d9e6)

The issue is being tracked here:

https://github.com/UNopenGIS/smartmaps/issues/33

**Comment by hfu** [comment]
Yes, let's go with [IST](https://24timezones.com/taimuzon/ist), [THA](https://24timezones.com/taimuzon/tha), [JST](https://24timezones.com/time-zone/jst), and [PST](https://24timezones.com/time-zone/pst) for the time being. 

Um, isn't it [PDT](https://24timezones.com/time-zone/pdt) in Los Angeles now? @albertkun

**Comment by hfu** [comment]
#274
