### ISSUE TITLE
Let's understand: IBM NASA Geospatial and `Prithvi`

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#226]
https://huggingface.co/ibm-nasa-geospatial

What is this? What is the potential use of this in Smart Maps? Let's discuss.

**Comment by hfu** [comment]
画像から画像を作るタイプのモデルなのかなと思いました。

**Comment by yuiseki** [comment]
これはAIと地理空間情報の関係という文脈において、極めて画期的で重要なものです！！！
私や他の研究者たちやHOTOSMのfAIrチームがやろうとしていたことが全部ひっくり返るレベルです！！

- https://huggingface.co/ibm-nasa-geospatial/Prithvi-100M
  - このモデルはViT (Vision Transformer)と呼ばれるアーキテクチャのAIです
  - データには[Harmonized Landsat Sentinel-2](https://hls.gsfc.nasa.gov/)を使っています
  - このモデルは**時系列の**人工衛星画像データを入力とし、ファインチューニングによって任意の特徴（火災、洪水、土地被覆分類など）を検出することができる、ベースモデルです
  - 人工衛星画像データはBlue, Green, Red, Narrow NIR, SWIR 1, SWIR 2チャンネルを含むGeoTIFFフォーマットファイルである必要があります
    - 時系列で複数のGeoTIFFファイルを入力することができます
- https://huggingface.co/ibm-nasa-geospatial/Prithvi-100M-burn-scar
  - このモデルはPrithvi-100Mを火災領域のセグメンテーションのためにファインチューニングしたモデルです
  - オンラインでのデモがあります
    - https://huggingface.co/spaces/ibm-nasa-geospatial/Prithvi-100M-Burn-scars-demo
- https://huggingface.co/ibm-nasa-geospatial/Prithvi-100M-sen1floods11
  - このモデルはPrithvi-100Mを洪水領域のセグメンテーションのためにファインチューニングしたモデルです
  - オンラインでのデモがあります
    - https://huggingface.co/spaces/ibm-nasa-geospatial/Prithvi-100M-sen1floods11-demo
- https://huggingface.co/ibm-nasa-geospatial/Prithvi-100M-multi-temporal-crop-classification
  - このモデルはPrithvi-100Mを土地被覆分類のためにファインチューニングしたモデルです
  - オンラインでのデモがあります
    - https://huggingface.co/spaces/ibm-nasa-geospatial/Prithvi-100M-multi-temporal-crop-classification-demo
- ファインチューニングのためのソースコードはPythonで書かれており、GitHubでオープンソースとして公開されています
  - https://github.com/NASA-IMPACT/hls-foundation-os/tree/main

**Comment by hfu** [comment]
@yuiseki ありがとうございます！勉強になる！

**Comment by hfu** [comment]
これ、 @ubukawa さんにとっても興味深い話かもしれませんね。パワーがあるチームで大規模に使うと、割と成果を出しやすい技術になるかもしれません。我々のコミュニティもうまく使っていただければ。

**Comment by hfu** [comment]
#274
