### ISSUE TITLE
Make our presentation file to public - what is the best way?

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#239]
## The issue
We would like to publish our presentation file, such as the presentation file for #214 (https://docs.google.com/presentation/d/1OwuZeywXDsbAmpsuYT3m70hp4psQag7O8nfHJZNzvrs/edit?usp=sharing), in an organized way. 

## How we  address the issue
I appreciate advice from @albertkun from Documentation perspective. 

I do not think this is urgent. Let's think about it when we have time.

**Comment by albertkun** [comment]
@hfu Thank you for asking me about this issue! 

## Overall recommendation 

### A) Automation! 😄 

In specific, if we are going to host the presentations on the Smart Maps website, I would suggest creating the `markdown` file for the documentation through the use of GitHub Actions. I currently do something similar for this icon repository with a simple bash script in the GitHub Actions workflow:

https://github.com/LACMTA/metro-iconography/blob/main/.github/workflows/update-svgs.yml

Digging deeper, I have two suggestions, depending on the type of presentation you wish to host:

### Online presentations 
#### Examples
- Google Slides
- hack.md
- canva

In this case, I would recommend either a CSV file, Google Sheet, or hosted table in a database that can be read to generate the markdown content. The columns in the file should contain metadata like, author, presentation date, etc., and this can be used to automatically create the markdown file. The flow could look like this:

```mermaid
flowchart TB

A[`Google Sheets` or `CSV` file] -->|Add info to `table`|B(Round)
B[ `cron job`/`github actions] -->C{Was `table` changed?}
C --> |Yes| D[Update `index.md`]
C --> |Yes| E[Create new `.md` file]
C --> |No| F[Do nothing]
```

### Offline 
In this case, I would either recommend hosting the file in a folder `presentations` in a [git-lfs](https://git-lfs.github.com/) enabled repository that can then trigger a workflow to generate the content based on the file name. There would be no metadata in this case. 

The flow would look like this:

```mermaid
flowchart TB

A[Upload file to `presentations` folder] -->B
B[ `cron job` or `github actions] --> C{Did `folder` change?}
C -->|`Yes`| D[Update **Presentations** `index.md`]
C --> |`Yes`| E[Create new `.md` file]
C --> |`No`| F[Do nothing]
```

### B) Alternative to automation
Manually updating the `presentations` and the `index.md` file on the documentation website! This would mean going to each link and adding the content there! Could be an interim solution as it would be the quickest.

Feel free to let me know what you think would be the best going forward!

**Comment by hfu** [comment]
@albertkun Thank you! It looks to me Automation of Online Presentations would be the best option!

**Comment by albertkun** [comment]
Ok, that sounds good! 

Do you have a preference on whether we use a static csv file, database, or Google Sheet?

**Comment by hfu** [comment]
I definitely like static. Can we use a static CSV file?

**Comment by albertkun** [comment]
@hfu yes we can! we should probably decide what fields we would like to use. Here is some suggestions:

|Column|Data Type|Description|Example
|--------|-----------|------------|-----------
Name | String | Who gave the presentation| Albert Kochaphum
Date | Date | When the presentation was given | 2023-08-2023
Link  | String | Link to the presentation | https://hackmd.io/@MXxudfFtSvSvSonMo4L3qQ/SyT0kFwqn#/1
Topic| String| Keywords for the presentation| documentation, UN Smartmaps

**Comment by hfu** [comment]
I like the simplicity of your suggestion. 

## Discussion question
1. regarding `name` how should we handle a presentation done by two or more persons? e.g. the last UN Smart Maps Quarterly presentation was both developed and delivered by yuiseki and hfu. 
2. maybe we can discuss whether the `name` should be of file owner or the actual presenter. 
3. The result of the discussion may depend on how we should handle the `name`. If we can handle `name` as just annotation or metadata, we can keep `name` as flexible as possible, like free text annotation. If we use `name` to sort or categorize decks, there should be a standard. 
4. My suggestion is that we can keep the meaning of `name` as flexible, and we use only `date` to sort the decks. We may use `topic` as tags. 

## FYI: example from speakerdeck
<img width="1339" alt="image" src="https://github.com/UNopenGIS/7/assets/18297/4cc85d3a-cae0-46cd-8164-0e81bb7dcbea">

**Comment by albertkun** [comment]
Regarding multiple names, we can include as many names as long as it is in quotes like the following:

`"Hidenori F. and Yuiseki M."`

**Comment by hfu** [comment]
Kaz Sato-san from Shizuoka prefecture kindly offered me that he can provide his presentation material for #219. He said he can provide the material when we are ready.

**Comment by albertkun** [comment]
@hfu Thank you for letting me know! I am gradually working on the presentation automation (of course, it is a bit slow since I am still traveling around Tokyo..) However, here is the link to `presentations.csv` where you can add the link to Kaz's presentation:

https://github.com/UNopenGIS/smartmaps/blob/main/presentations.csv

As a reminder, the format is:
|Column|Data Type|Description|Example
|--------|-----------|------------|-----------
Presentation title| String| Name of the presentation or meeting | UN Smart Maps Pacific 5 Documentation Update
Name | String | Who gave the presentation| Albert Kochaphum
Date | Date | When the presentation was given | 2023-08-20
Link  | String | Link to the presentation | https://hackmd.io/@MXxudfFtSvSvSonMo4L3qQ/SyT0kFwqn#/1
Topic| String| Keywords for the presentation| documentation, UN Smartmaps

**Comment by hfu** [comment]
#274
