### ISSUE TITLE
Proposal: Live Translations during Smart Maps Pacific 

### ISSUE THREAD

**Issue by albertkun** [UNopenGIS/7#248]
In the spirit of open communication, I would like to suggest we try Zoom auto caption features for participants fluent in other languages (specifically Japanese). This is available as follows: https://support.zoom.us/hc/en-us/articles/6643133682957-Enabling-and-configuring-translated-captions

Thoughts?

**Comment by hfu** [comment]
I like this idea!

**Comment by albertkun** [comment]
Unfortunately, this requires an additional add-on that cost money so we cannot use this. :(

**Comment by hfu** [comment]
@albertkun Many thanks for clarifications.
