### ISSUE TITLE
ReliefWebによるコンゴ民主共和国の初期調査の情報共有

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#251]
- Related: #250
- ReliefWebには全世界の人道危機・人道支援関連の比較的新しい情報がオープンに公開されている
- ReliefWebを使ってコンゴ民主共和国の最近の人道的問題に関する状況を知ることには有用なはず
- ReliefWebのコンゴ民主共和国のページ
  - https://reliefweb.int/country/cod
  - Situation Reportのみで絞り込む
    - https://reliefweb.int/updates?advanced-search=%28PC75%29_%28F10%29
  - UN Documentのみで絞り込む
    - https://reliefweb.int/updates?advanced-search=%28PC75%29_%28F11%29

### いくつかのレポートを見た雑感
- 国連システムの人道支援活動アクター
  - MONUSCO
  - UNOCHA
  - UNHCR
  - UNICEF
  - WHO
  - WFP
- 国連システム外の国際人道支援活動アクター
  - USAID（米国国際開発庁）
  - IFRC（赤十字）
  - FEWS NET（飢餓早期警報システムネットワーク）
- 他のアクター
  - M23
  - ルワンダ
  - 東アフリカ共同体
  - 南アフリカ開発共同体
  - アフリカ連合平和安全理事会
- Situation Reportの多くはフランス語である
- 紛争、武力衝突は、ほとんど常時、広い範囲で発生している模様である
  - ナイロビ・プロセスと呼ばれる和平交渉プロセスが存在している
- それに加えて、洪水、地滑り、疫病などの人道的問題も発生している
- 難民と国内避難民が多数発生している
- 飢餓の危険が高まっている地域がある

### Situation Reportをいくつか見てみる

- https://reliefweb.int/report/democratic-republic-congo/democratic-republic-congo-complex-emergency-fact-sheet-5-fiscal-year-fy-2023
  - 初版発行 2023 年 8 月 4 日
  - ソース：USAID
  - コンゴ民主共和国の人口
    -  1 億 230 万人
  - 援助を必要とする人口
    - 2,640 万人
  - 国内避難民数
    - 620万人
  - 近隣諸国のコンゴ難民と亡命希望者の数
    - 100万人
  - コンゴ民主共和国に避難する難民および亡命希望者の数
    -  523,528 人

- https://reliefweb.int/report/democratic-republic-congo/democratic-republic-congo-humanitarian-highlights-7-1-31-july-2023
  - 初版発行 2023 年 8 月 8 日
  - ソース：UNOCHA
  - 言及されている課題
    - マシシ領内でコンゴ軍と武装集団M23が衝突
    - 洪水が発生
    - コレラの流行に対する対策が必要
    - 麻疹の流行に対する対策が必要
    - ポリオの流行に対する対策が必要

### UN Documentをいくつか見てみる

- https://reliefweb.int/report/democratic-republic-congo/options-adapting-configuration-monusco-and-future-united-nations-configuration-country-beyond-current-mandate-mission-report-secretary-general-s2023574-enarruzh
  - S/2023/574
  - 初版発行 2023 年 8 月 2 日
  - 要約
    - MONUSCOはもっと他の国連アクターと連携するべしという国連安保理決議第2666号（2022年）に対応したレポート
    - 2021年11月のMouvement du 23 mars（M23）の復活により、コンゴ民主共和国とルワンダの関係が悪化した
    - 2022年6月にウガンダとの国境にある主要貿易都市ブナンガナのM23占領
    - 地域の緊張はさらに高まり、コンゴ民主共和国はルワンダとのすべての二国間協定を停止した
    - それ以来、コンゴ民主共和国とルワンダの間の緊張は高いままとなっている
 

- https://reliefweb.int/report/democratic-republic-congo/united-nations-organization-stabilization-mission-democratic-republic-congo-report-secretary-general-s2023451
  - S/2023/451
  - 初版発行 2023 年 6 月 19 日
  - 要約
    - 国連安保理決議第2666号（2022年）第43項に従った、MONUSCOの国連事務総長報告書レポート
    - 2023 年 3 月 21 日から 6 月 19 日までのコンゴ民主共和国の動向を対象
    - 5月22日、独立国家選挙委員会によるは有権者登録プロセスに透明性と信頼性が欠けていると問題になっている
    - 5月20日、大統領立候補者4名が、混沌とした選挙プロセスに反対するデモを組織した
    - 5月25日、野党指導者4人が、信頼できる選挙を求める抗議活動を組織した
    - 3月22日、アフリカ連合平和安全理事会は、北キブ州キンシャサとゴマへの2日間の訪問を終了
      - コンゴ民主共和国大統領は、コンゴ民主共和国東部におけるルワンダの侵略を非難
      - コンゴ民主共和国とルワンダの間の緊張は依然として高い
    - 4月3日、コンゴ民主共和国東部に東アフリカ共同体地域軍の全面展開を発表
    - 4月27日、コンゴ民主共和国政府と東アフリカ共同体の代表団はキンシャサで東アフリカ共同体地域軍の地位協定の更新について協議
      - 同日、地域軍の司令官ジェフ・ニャガ少将が身の安全への懸念を理由に辞任
    - 4月27日、MONUSCOはM23戦闘員の事前収容と武装解除を支援するというコンゴ民主共和国政府からの要請に同意
      - 5月8日、アンゴラ大統領ジョアン・ロレンソは、アンゴラは、特別検証メカニズムのスタッフを保護し、マニエマ県のM23の駐屯地を確保するために、コンゴ民主共和国東部に500人の軍隊を派遣する用意があると主張
    - 5月8日、南アフリカ開発共同体(SADC)の臨時首脳会議は、コンゴ民主共和国東部の平和と安全を回復するため、SADC待機軍の一部としてSADC軍を派遣することを承認した

**Comment by hfu** [comment]
#274
