### ISSUE TITLE
ReliefWebによるレバノンの初期調査の情報共有

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#252]
- Related: #250
- ReliefWebには全世界の人道危機・人道支援関連の比較的新しい情報がオープンに公開されている
- ReliefWebを使ってレバノンの最近の人道的問題に関する状況を知ることには有用なはず
- ReliefWebのレバノンのページ
  - https://reliefweb.int/country/lbn
  - Situation Reportのみで絞り込む
    - https://reliefweb.int/updates?advanced-search=%28PC137%29_%28F10%29
  - UN Documentのみで絞り込む
    - https://reliefweb.int/updates?advanced-search=%28PC137%29_%28F11%29

### いくつかのレポートを見た雑感
- 国連システムの人道支援活動アクター
  - UNFIL
  - UNRWA（国連近東パレスチナ難民救済事業機関）
  - UNOCHA
  - UNHCR
  - UNICEF
  - WHO
  - WFP
- 国連システム外の国際人道支援活動アクター
  - USAID（米国国際開発庁）
  - IFRC（赤十字）
  - Mercy Corps
- 他のアクター
  - イスラエル
    - イスラエル国防軍
  - ヒズボラ
  - 国境なき緑
- UN Documentがアラビア語でも提供されている
- 誤情報や扇動がUN Documentに明記されるほどの問題になっている
- ブルーラインと呼ばれる境界線があり、その付近で度々衝突が発生している
- 難民キャンプで戦闘が発生してしまっている
- コレラの発生状況が深刻なようだ
- 多数の難民がレバノン国内におり、食糧不安に直面すると予測されている
- レバノン国民も食糧不安に直面すると予測されている

### Situation Reportをいくつか見てみる

- https://reliefweb.int/report/lebanon/lebanon-civil-unrest-2023-ain-al-helwe-dref-operation-mdrlb014
  - 初版発行 2023 年 8 月 11 日
  - ソース：IFRC
  - 言及されている課題
    - 南レバノンの難民キャンプ、アイン・エル・ヒルウェ・キャンプでは、敵対グループ間の致命的な衝突が2023年7月29日土曜日から続いており、キャンプ住民の半数以上が自宅から避難し、12人以上が死亡、60人以上が負傷した
    - 記事の執筆時点でも内戦は依然として激しく、自動機関銃、ロケット推進手榴弾、中型砲が複数の勢力によって使用されている

- https://reliefweb.int/report/lebanon/unrwa-calls-immediate-cessation-fighting-ein-el-hilweh-camp-fighting-leaves-13-killed-and-dozens-injured
  - 初版発行2023 年 8 月 3 日
  - ソース：UNRWA
  - 言及されている課題
    - アイン・エル・ヒルウェのパレスチナ難民キャンプでは、パレスチナ武装勢力間で４日間にわたる暴力が発生し、13人が死亡した

### UN Documentをいくつか見てみる

- https://reliefweb.int/report/lebanon/implementation-security-council-resolution-1701-2006-during-period-21-february-20-june-2023-report-secretary-general-s2023522-enar
  - S/2023/522
  - 初版発行 2023 年 7 月 13 日
  - 要約
    - レバノンとイスラエルの間で恒久的な停戦に向けた進展はなかった
    - 内容が薄すぎる。書き途中？

- https://reliefweb.int/report/lebanon/implementation-security-council-resolution-1701-2006-during-period-3-november-2022-20-february-2023-report-secretary-general-s2023184-enar
  - S/2023/184
  - 初版発行2023 年 3 月 10 日
  - 要約
    - 12月14日、国連レバノン暫定軍（UNIFIL）の車列がベイルートのラフィク・ハリリ国際空港に移動中、作戦地域外のアキビアで攻撃され、平和維持要員1名が死亡、他3名が負傷した
      - 事件後、一部の地元メディアは、平和維持軍が事件現場にいることは許されず、レバノン軍の同行が必要であるという誤った主張を流布した
      - イスラエルの国連常任代表は、1月31日付の書簡（ S/2023/74 ）で、「UNIFILは扇動的なレトリックと扇動にさらされている…この扇動は最終的に 2022 年 12 月 14 日の悲劇的な事件につながりました」と述べた

**Comment by hfu** [comment]
このイシューは、私が咀嚼して追いついたらクローズするつもりです。
#255 から参照できる重要ストック情報としてストックしておければと思っています。

**Comment by hfu** [comment]
ありがとうございました。イシューとしてはクローズとします。
Ain al-Hilweh の話を少しみてみましたし、https://www.youtube.com/watch?v=2HhGpdT7e0M などをみて、我々がサポートする潜在的なクライアントのイメージを高めてみました。
Situational awareness のための地図というよりも、service に従事されている expats のためのウェブ地図を提供するというようなイメージで当座行きたいと思います。
