### ISSUE TITLE
Rethink the documentation meeting

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#253]
## Problem statement
- we could set up a regular monthly documentation meetings. 
- we fail to gather in the scheduled documentation meetings several times. 

## Possible solution
- set up an issue for each scheduled monthly documentation meeting, preferable with tentative agenda.

**Comment by albertkun** [comment]
@hfu Thank you for this! As part of the automation I am working on (sorry for the delay, as I have been traveling and will be able to do some work when I get to Tokyo starting tomorrow!) There will be a nightly cron job that automatically creates/edits a GitHub Issue from the shared Google Calendar. My question is, where should the single source of truth be:

a) GitHub Issues -> Creates the Google Calendar Events
b) Google Calendar -> Creates/Modifies the GitHub issues

Though I would love to go with a) I feel like Google Calendar might be easier to work with for events. But, I defer to you!

**Comment by hfu** [comment]
@albertkun Thank you. For myself, I am not able to follow Google Calendar events from our office. If we have an issue for each documentation meeting, it would be great to share the agenda before hand and thus remind all of us about the event. 

I suppose the GitHub issue on the meeting is somewhat unstructured and flexible to additional inputs or even splitting into separate issues. 

What do you think is the easiest way to connect a calendar item and unstructured issue(s)? I think that would be a preferable solution on this issue.

**Comment by hfu** [comment]
I think we are successful in somewhat merging Monthly (Pacific) meeting and Documentation (Core Strategy) meeting. 

#274

**Comment by albertkun** [comment]
I agree! And the new format works well I think! :)
