### ISSUE TITLE
2023-08-25T17:00+09:00: A chat with UNIFIL GIS

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#254]
I am consulting with UNIFIL GIS regarding a right starting time for meetings. I am consulting using the following candidates considering the fact that it may be tricky to use the time within working hours. 

1. First preference; 16:00 in Beirut time, 22:00 in Tokyo time.
2. Second preference; 10:00 in Beirut time, 16:00 in Tokyo time. 

@yuiseki Your participation is very important because they are interesting in LLM. Do you have any preference or comments regarding starting time. Please excuse me for providing these candidates without your confirmation. I needed to keep the conversation with UNIFIL GIS in a timely manner. I believe we can still be flexible regarding the choice of starting time. 

Regarding the date, 2023-08-25 would be the earliest possible slot.

**Comment by yuiseki** [comment]
@hfu No problem at all! I deeply appreciate you giving me this rare opportunity to speak with UNIFIL GIS.

I am available on 2023-08-25 at 22:00 in Tokyo time with no problem.
I am unavailable on 2023-08-25 at 16:00 in Tokyo time as I am attending another business meeting.
And, I am available on 2023-08-25 at 17:00 in Tokyo time without any problem.

I am excited about the rare opportunity to speak with UNIFIL GIS about LLMs, so please don't hesitate at all!!

**Comment by hfu** [comment]
@yuiseki Thanks! I will be consulting with UNIFIL GIS to have a meeting from 2023-08-25T17:00+09:00.

**Comment by hfu** [comment]
I have sent the invite as below: 

As discussed on UN Microsoft Teams (MST) chat, UN Smart Maps Group (SMG) in UN Open GIS Initiative is happy and proud to have a chat with UNIFIL GIS regarding prospective pilot project making use of Large Language Models (LLMs) or any other technologies which UN Smart Maps Group can contribute. 

For a better participation, we are happy to start from 11:00 rather than 10:00. I hope it is acceptable for UNIFIL side. Otherwise let's reschedule back to 10:00, but I will be the only participant from SMG in that case. 

I suggest the following tentative agenda: 

>>>
1. Self-introduction by participants (All) 2. Status and challenges of UNIFIL GIS (Shazia?) with feedback from SMG (Hidenori and Yuiseki)
  - if there are any information to be shared; otherwise, we can skip this item and move to item 3. to discuss on how LLM can be used in UNIFIL operations, using our imagination collectively. 
3. Discussion (All)
  - e.g., any questions and concerns related to the use of LLMs exploring opportunities for collaboration. 
4. Next steps (Alll)
  - action items
  - scheduling next meeting
(target meeting time: 40 min.; maximum meeting time: 60 min.) <<<

**Comment by yuiseki** [comment]
My personal memo for MTG:

## Self-introduction
- Name
  - Yui Matsumura
- Job title
  - Product manager and Software engineer of Gyazo at Helpfeel, Inc
    - Gyazo, of which I am the product manager, is one of the largest SaaS in the world that can handle screenshots, screen records and photos
- Specializing
  - software-related intel (images, geospatial, LLMs & computer network)
- Me and UN Open GIS
  - I am a participant in Domain Working Group 7
  - I began my volunteer work on geospatial information systems in the public interest through my participation in sinsai.info, a disaster information collection platform that played one of the most important roles in Japan's response to the 2011 Great East Japan Earthquake
  - I have been interested in and contributing to OpenStreetMap and UNVT (United Natiins Vector Tile Toolkit) for some time, and was approached to participate
  - I have both personal and professional experience in utilizing LLMs
    - I have released 6 personally developed SaaS based on LLMs
      - One of them is a fusion of LLMs and GIS
    - I managed a project to integrate LLMs into one of the world's largest software products, Gyazo, for which I am a product manager, and I achieved it
      - Gyazo currently utilizes a wide variety of LLMs for both still image and video content

## Applying LLMs (seeds of discussion)
- What specific scenarios or tasks would be effective in the combined application of LLMs and GIS?
- What are some past projects and success stories of combining LMs and GIS?
- What are the most significant challenges or issues encountered in combining these technologies?

## Operating LLMs (seeds of discussion)
- Basic requirements and infrastructure for operating LLMs
- Recommended platforms and tools for implementing and operating LLMs
- Do you need training or support in applying or implementing LLMs?

**Comment by hfu** [comment]
# Meeting note
target meeting time: 40 min.; maximum meeting time: 60 min.

## Self-introduction by participants (All)
- [ ] Hidenori
- [ ] [Yuiseki](https://github.com/UNopenGIS/7/issues/254#issuecomment-1691281271)
- [ ] Shazia
- [ ] Arik

## Status and challenges of UNIFIL GIS (Shazia?) with feedback from SMG (Hidenori and Yuiseki)
if there are any information to be shared; otherwise, we can skip this item and move to item 3. to discuss on how LLM can be used in UNIFIL operations, using our imagination collectively.

## Discussion (All)
e.g., any questions and concerns related to the use of LLMs exploring opportunities for collaboration.

## Next steps (Alll)
- [ ] action items
- [ ] scheduling next meeting - or communicate using email

**Comment by hfu** [comment]
## Hidenori's self-introduction
- [ ] Leading Smart Maps Group, UN Open GIS Initiative.
- [ ] Working for Geospatial Information Authority of Japan.
- [ ] Web map expert for years.

### A comment about pilot project phase
- Phase A: open service with open data only, but useful for UNIFIL GIS. 
- Phase B: service with custom data too, closed service if necessary. 

Phase A is always easier option to us, and would also be a good start. 
Depends on the use case. We want to keep flexible with UNIFIL GIS requirement.

**Comment by hfu** [comment]
## Minutes
- Meeting was limited to 2023-08-25T17:00/17:30+09:00 due to a constraint on schedule. 
- We will meet again in the first week of September with Ayako, too. 
- Shazia confirmed that https://chat.openai.com and https://trident.yuiseki.net can be accessed from inside. 
- Use case: Search embassies and international organization offices in Lebanon using LLM in different langauges including Indonesian, Malaysian, Arabic, English, French, German, Italy, Hindi, etc. 
- Phase B is only possible if an on-premise server is built inside. 
- SMG can provide software or image for use inside, using open-source LLM. 

## Open issue
- initial target area - we can just decide and start; e.g. ベイルート県+山岳レバノン県+南レバノン県+ベッカー県+ナバティーエ県. See also: [レバノンの県](https://ja.wikipedia.org/wiki/%E3%83%AC%E3%83%90%E3%83%8E%E3%83%B3%E3%81%AE%E7%9C%8C)
- project proposal format.

**Comment by hfu** [comment]
# Top 10 military contributors 
I found it at https://public.tableau.com/views/UNIFIL/Toptcc?:embed=y&:toolbar=n&:loadOrderID=1&:display_count=y&publish=yes&:origin=viz_share_link via https://peacekeeping.un.org/en/mission/unifil

**Comment by yuiseki** [comment]
## Language for Top 10 military contributors of UNIFIL

[![Image from Gyazo](https://i.gyazo.com/a18f0a512fc4a6408866951fb0cbdc37.png)](https://peacekeeping.un.org/en/mission/unifil)

- Indonesia
  - Indonesian
- India
  - Hindi
- Italy
  - Italian
- Ghana
- Nepal
  - Nepali
- Malaysia
  - Malaysian
- France
  - French
- Spain
  - Spanish
- China
  - Chinese
- Ireland
  - Irish



## Check list for the initial proposed use cases:

MEMO by yuiseki: 
- 英語を基準言語とする
- ChatGPT GPT-3.5とDeepLで両方翻訳させて、比較する
- DeepLの選択肢にない言語は、ChatGPT GPT-3.5のみを採用する
- ChatGPT GPT-3.5へのプロンプトは以下とする

```
`Show embassies in Lebanon.`というフレーズを◯◯語で表示して
```

###  Search embassies in Lebanon
  - in different langauges including:
    - [ ] English
      - [ ] DeepL: `Show embassies in Lebanon.`
    - [ ] Indonesian
      - [ ] GPT-3.5: `Tampilkan kedutaan di Lebanon.`
      - [ ] DeepL: `Menunjukkan kedutaan besar di Lebanon.`
    - [ ] Hindi
      - [ ] GPT-3.5: `लेबनान में दूतावासों का प्रदर्शन करें।`
    - [ ] Italian
      - [ ] GPT-3.5: `Mostra le ambasciate in Libano.`
      - [ ] DeepL: `Mostra le ambasciate in Libano.`
    - [ ] Nepali
      - [ ] GPT-3.5: `लेबनानमा दूतावासहरू देखाउनुहोस्।`
    - [ ] Malaysian
      - [ ] GPT-3.5: `Tunjukkan kedutaan-kedutaan di Lebanon.`
    - [ ] French
      - [ ] GPT-3.5: `Afficher les ambassades au Liban.`
      - [ ] DeepL: `Afficher les ambassades au Liban.`
    - [ ] Spanish
      - [ ] GPT-3.5: `Mostrar embajadas en Líbano.`
      - [ ] DeepL: `Mostrar embajadas en Líbano.`
    - [ ] Chinese
      - [ ] GPT-3.5: `显示在黎巴嫩的大使馆。`
      - [ ] DeepL: `显示驻黎巴嫩大使馆。`
    - [ ] Irish
      - [ ] GPT-3.5: `Taispeáin ambasadóirí i Líbáin.`
    - [ ] Arabic?
    - [ ] German?


### Search international organization offices in Lebanon
  - in different langauges including:
    - [ ] English?
    - [ ] Indonesian?
    - [ ] Hindi?
    - [ ] Italian?
    - [ ] Nepali?
    - [ ] Malaysian?
    - [ ] French?
    - [ ] Spanish?
    - [ ] Chinese?
    - [ ] Irish?
    - [ ] Arabic?
    - [ ] German?

**Comment by hfu** [comment]
@yuiseki ありがとうございます。私も似たようなアプローチで、Smart Maps for UNIFIL で取り扱う言語のカテゴリについて検討していました。イシューを改めて共有しますね。
