### ISSUE TITLE
Smart Maps for UNIFIL: Assistant に与える典型的なプロンプトまたは例示

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#259]
Smart Maps Assistant に与える典型的なプロンプトまたは例示を早期に共有することにより、その多言語化作業を Volunteering Opportunities として早期に切り出して @albert の Documentation Site から募集できるかもしれないと思いました。

また、UNIFIL サイドとの打ち合わせの際にも、この辺りは UNIFIL GIS と協議しやすく、また協議していくべき事項であるように思います。

## イメージ
- インドネシア大使館はどこにありますか。
- UNRWAオフィスをすべて表示してください。

**Comment by yuiseki** [comment]
私の感覚では、MUSTである #255 を達成するためには、このIssueも、MUSTあるいはSHOULDではないかと思います。

## 問題の発覚

まず最初に、発覚した問題を共有します：

### 問題点の再現方法

いま試してみましたが、以下の一連のプロンプトに、Smart Maps Assistantは期待通りに答えられていません。

- `レバノンを表示してください`
- `インドネシア大使館はどこにありますか。`

[![Image from Gyazo](https://i.gyazo.com/eb24ab4ad11746e43ca357c8470ccf98.png)](https://gyazo.com/eb24ab4ad11746e43ca357c8470ccf98)

### 問題点の明示

- Surface layerによるユーザーとAIの対話で、**日本のインドネシア大使館の所在地を、勝手に答えてしまっている**
  - 文脈に従った場合、また、情報を受け取るユーザーの立場に立った場合、これはハルシネーションであって、問題がある
- Inner layerおよびDeep layerによって構築される地図は、期待通りに動いている
  - Surface layerによる対話と、Inner layerおよびDeep layerによって構築される地図が、著しくズレているため、問題がある


## このIssueの重要性

- このIssueは、
  - Smart Maps GroupがUNIFIL GISにPilot projectを通じて貢献していく上で、とても重要です
  - UNIFIL GISが、Smart Maps Assistantのようなシステムに対して、何を期待あるいは要求しているのかを明確にしていく上で、とても重要です
- 結局のところ、**具体的なプロンプトを明確に例示して貰うことさえできれば、我々は、それに答えられるようにシステムを開発・改善していくのみです**
  - `Search embassies in Lebanon` というプロンプトは、やや曖昧です
    - 本当にレバノンにあるすべての外国の大使館を探したいのか？
    - それとも、あるユーザーの母国の大使館が探したいのか？
  - `Search international organization offices in Lebanon` というプロンプトは、やや曖昧です
    - 本当にレバノン国内のありとあらゆる国際機関を探したいのか？
    - どんな人が、どんな状況で、どんな国際機関を探したいのか？
  - ……のように、細部を探る余地が大いにあると思います
- 私たちSmart Maps Groupは、UNIFIL GISを、ChatGPTのようなAI Assistantのようなものだと思ってみて、色々な質問をしてみて、こうした細部を探ることによって、一番大きな・効果的なニーズや要求を、より正確に・より明確に、知る必要があります
- そして逆に、UNIFIL GISに、私たちSmart Maps Groupを、ChatGPTのような（ある程度性能に制約のある）AI Assistantのようなものだと思って、現地の要求をよりより明確に・より正確にプロンプトとして入力していただければ、私たちはそれらの期待や要求に、よりうまく答えられるはずです
- **ただし、私たち人間は、ChatGPTとは違います**
  - ここが興味深いポイントです
  - ChatGPTが便利な側面の一つには、どんなに細かいことをどんなに繰り返し聞いても、それなりに答えてくれる、ということがあります
  - 私たち人間は、無限に詳細な質問に対する応答を繰り返すことにはストレスを感じるので、実際には、お互いをChatGPTのようなAI Assistantとみなすことはできません
  - それでも、私は、ベイズ統計学の側面から、この考え方が興味深いと考えています
    - ポーカー（テキサスホールデム）においては、ディーラーのカードが一枚づつめくられていくにつれて、プレイヤーが取るべき最適な行動（プレイ）は、常に変化していきます
    - お互いに時間制限や回数制限があることに注意しつつ、お互いを与えられたプロンプトに素直に応答するChatGPTのようなAI Assistantとみなして、最も自分に必要な情報を絞り込むことができるようなプロンプトをお互いに入力する・させるように意識することは、悪くないコミュニケーションになるはずです

**Comment by hfu** [comment]
いいですね！

多分、Smart Maps for UNIFIL の場合には、スタディ・エリアを限定し、その限定されたスタディエリアをシステム強制的に対象にするのが良いように思います。（色々な理由から、スタディ・エリアを限定することはかなり効果的であると思っています。）

スタディ・エリアの仮案についても、別イシューで提示してみますね。

**Comment by hfu** [comment]
また、プライオリティの高い親イシューの子イシューには親イシューのプライオリティが継承されるというのは確かにおっしゃる通りだと思います。プライオリティを変更しました。

**Comment by hfu** [comment]
#274
