### ISSUE TITLE
Smart Maps for UNIFIL: show no maps? 

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#264]
UNIFIL GIS の方より、地図のセンシティビティについて間接的に注意喚起がありました。

我々 SMG は、地図のセンシティビティ問題に最大の理解と共感を示す意思がありますし、その問題に対して一義的に対応しておられる UNIFIL GIS の皆様に最大限の敬意を示しますし、また、UNIFIL GIS と SMG で作業の重複と理解または誤解されるようなことは必ず避けたいと思っています。

この観点から、次の措置を考え得ると思いますが、御意見ありますか。

- [ ] 我々のプロトタイプは地図を表示することはない。検索結果を表示することはあるかもしれないが、ベースマップを表示することは避ける。
- [ ] ベースマップは将来的に UN の GIS スタッフが適切な情報管理のもとに適切なユーザーに対して提供するかもしれないが、我々が代替のデフォルト・ベースマップを提供するということが誤解を生みうるということであればそれを避けることに躊躇しないということである。
- [ ] ベースマップの代替としては、例えば写真を使うということは考えられる。
- [ ] いずれにせよ、初期段階で国連のエンタープライズネットワークに関与していくということは、能力上も信頼醸成上も適切ではないと考えている。
- [ ] 我々は外部貢献者であるからこそオープンに実施するのであり、オープンに実施するにあたり誤解の余地があるプラクティスがあるのであれば、そのプラクティスを実施しないことで対応することにしたい。

@yuiseki さん、この方針でいかがでしょうか。

**Comment by yuiseki** [comment]
@hfu 異論はありません！我々は外部からお邪魔させて頂いて、貴重な時間を割いて頂いて、現地のsituationやrequirementを教えて頂いているという立場であるので、業務の妨げになるようなことは絶対に避けるべきである、ということを、常に前提として意思決定し行動するようにしましょう。私も肝に銘じておきます。

**Comment by hfu** [comment]
@yuiseki ありがとうございます。作業に使うとすれば、ですが、これから、オープンに使える画像タイルを探しましょう。

他方で、試しに UN の SALB にレバノンのデータはあるかなと調べてみました。想像どおり、ありませんでした。
https://salb.un.org/en/data/lbn

我々のたどるべき作業順序を冷静に見極めつつ、できるところ、やりたいところから順に積み上げていければと考えた絵います。

**Comment by hfu** [comment]
#274
