### ISSUE TITLE
✰2023-10-20/19: Smart Maps Strategy Meeting: Seek synergy of Documentation and Strategy

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#270]
As disccued in #247 and according to @albertkun:

> we can rebrand the "Documentation" meeting into a core-group meeting where we can discuss about the logistics/direction of the group: we can use the the time to talk about items such as the "core mission statement", "marketing", etc. and we can coordinate the short term and long term goals/events with those that are interested/have the capacity to contribute. Let me know what you think!

I think this is a brilliant idea to seek the synergy of Documentation and Direction/Mission/Marketing. Let's discuss how we can best implement this idea!

**Comment by hfu** [comment]
As in https://github.com/UNopenGIS/7/issues/247#issuecomment-1714951754, we will be calling the meeting "Core Committee". 

One thing we could consider is that there is already "Smart Maps Core" objective led by @smellman. :-)

**Comment by albertkun** [comment]
@hfu Thank you pointing this out! Is the repository connected to it: https://github.com/UNopenGIS/77 ? (I see it is also owned by @smellman ! )

We can rename "Core Committee" to "Leadership Committee" if it will avoid confusion! I wanted to avoid "leadership" since I want anyone to be welcomed to join. :)

Even with a name change, the function of the group is the same, which is: "to determine what events/activities/goals the smart maps group should prioritize".

Let me know if what you think!

**Comment by hfu** [comment]
Thanks for sharing. What came to mind was that we may call it Strategy Meeting or something.:-)

**Comment by albertkun** [comment]
@hfu I think strategy meeting is a good name for it! How frequent should we set up the meeting? Should it be once a month?

**Comment by albertkun** [comment]
@hfu I think strategy meeting is a good name for it! How frequent should we set up the meeting? Should it be once a month? 

> As disccued in #247 and according to @albertkun:
> 
> > we can rebrand the "Documentation" meeting into a core-group meeting where we can discuss about the logistics/direction of the group: we can use the the time to talk about items such as the "core mission statement", "marketing", etc. and we can coordinate the short term and long term goals/events with those that are interested/have the capacity to contribute. Let me know what you think!
> 
> I think this is a brilliant idea to seek the synergy of Documentation and Direction/Mission/Marketing. Let's discuss how we can best implement this idea!

**Comment by hfu** [comment]
@albertkun We discussed the scheduling issue with @yuiseki and @k96mz in #271. 

How about having a Strategy Meeting just after each session of UN Open GIS Monthly meeting? That would help us better follow up the Monthly meeting and so contribute to a better strategy. 

**12:00/13:00+09:00** on **Wednesday** or **Friday** would be easy of us. Or, we can make use of **12:00/13:00+09:00** on **Tuesday** overriding UN Smart Maps Weekly of the week. 

What do you think?

**Comment by albertkun** [comment]
@hfu I think having the meeting after the UN Open GIS Monthly Meeting would be good. We can aim for 12:00/13:00+09:00 on Wednesdays (same day as the meeting, right?).

Also, I noticed you are on the schedule for the UN Open GIS Workshop at FOSS4G Asia, would it be possible for me to be involved too? Perhaps this is something we can address in our strategy meeting!

**Comment by hfu** [comment]
@albertkun It looks obvious irregular, but we are having UN Open GIS Monthly Meeting tomorrow as in #281. 

Any thought about how we do our Smart Maps Strategy Meeting? One challenge would be that we are having Pacific Meetup on 2023-10-20 with Yoh. Maybe we should take time as required and think about having the next Strategy Meeting. 

What do you think?

**Comment by albertkun** [comment]
@hfu Good point! How about we schedule them the Friday after the Meetup Pacific? We can then review the previous meet up, plan for the next, and strategize the long term goals.

What do you think?

**Comment by hfu** [comment]
@albertkun Thanks! Let's schedule the meeting on after Pacific 7. 

## Background: Pacific 7 time
2023-10-20T11:30/12:30+09:00 = 2023-10-19T19:30/20:30-07:00

## Plan A: Just after Pacific 7
2023-10-20T13:00/14:30+09:00 = 2023-10-19T21:00/22:30-07:00

- Pros: easier to make it to the meeting
- Cons: shorter lunch/dinner time. Less participants because of working hours in Japan

## Plan B: ...
Hmm, there may not be Plan B. I check the possibility for "Japan night time" only to realize that 22:00+09:00 is 06:00-07:00. If we see "Japan morning time", 09:00+09:00 is 17:00-07:00. 

## How about other participants? 
I personally secured my schedule for Plan A. 

How about @yuiseki, @smellman, @mapconcierge among others? Are you able to join 2023-10-20T13:00/14:30+09:00?

**Comment by albertkun** [comment]
I think that **Option A** would probably be the best plan if the people interested on the Japanese side can make it! Plus we can invite people from the Meet Up Pacific to join too!

**Comment by yuiseki** [comment]
I am available at 2023-10-20T13:00/14:00+09:00. But I will be leaving at 14:00 due to another appointment.

**Comment by hfu** [comment]
@yuiseki thanks for the input. 

@albertkun How about having the strategy meeting 2023-10-20T13:00/13:55+09:00 basically following the Plan A? On which meeting platform do we meet? 

I have added the schedule to the SMG's Google Calendar.

**Comment by albertkun** [comment]
@hfu If it isn't an issue, we can probably use Zoom and I'll update the times on there!

@yuiseki Thank you for chiming in! We'll see you then! :)

**Comment by hfu** [comment]
@albertkun Thank you so much. Could you arrange a Zoom meeting and link it to the Google Calendar schedule? We may also want to share the link with broader audience though. 

Thank you for moving thing forward. I am also thinking that it would be a great time to think about our strategy. We have many great ideas but they are not well organized yet.

**Comment by albertkun** [comment]
@hfu sorry for the late reply! I missed the notification! Sure, I changed the link already, but would it be OK to use the same meeting link as the meet up? Ni worries if not, the core meeting is available just in case!

**Comment by hfu** [comment]
@albertkun OK. Let's use the same link as the meet up. I am thinking about organizing my ideas about the strategy. I will be back with you here in the issue if I create something about it.

**Comment by albertkun** [comment]
@hfu Sounds good! Here are the slides for tomorrow! Feel free to make any changes:

### Edit
https://hackmd.io/@unsmartmaps/meetup-pacific-8/edit

**Comment by hfu** [comment]
For those who have trouble in retrieving the zoom link for today's meetup (like me), I dare to share the zoom link tentatively here.

https://ucla.zoom.us/w/93540731519?tk=QDfLxoBvaWaCcbbsGfjeG1dn5I_iMx5I5MtczbJxXMs.DQMAAAAVx3ZKfxZoMkNmMWEtWlJhbUpaZUVPaENjMFBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA&pwd=OG91Q2FPQktpUWF1YldVNVRMT294UT09

I will remove this comment when the event is done.

**Comment by hfu** [comment]
This is how I see the current status of the project: 

![image](https://github.com/UNopenGIS/7/assets/18297/d6b2504c-f09f-49f8-9429-a33741d2a8f8)

**Comment by hfu** [comment]
Thank you!
