### ISSUE TITLE
🎮Bootstrap UNVT Portal

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#272]
As introduced in https://hackmd.io/@hfu/2023-09-12#/5 🚀

**Comment by hfu** [comment]
このプロジェクトに UNVT Portal という名前をつけて差し支えないか、UNVT Portable の名付け親である @mapconcierge に念のためご了解を頂けるとうれしいです。

UNVT Portal のロゴ ver. 0 を作ってみました。

![image](https://github.com/UNopenGIS/7/assets/18297/1bcce865-2501-41ed-9b9d-671bfc362c88)

**Comment by hfu** [comment]
@yuiseki @smellman グローバルIPを持ったサーバへのアクセスに際しては公開鍵認証で良いでしょうか。もしそうであれば、後ほど、公開鍵の受け取り方を相談したいと思っています。

**Comment by yuiseki** [comment]
@hfu 私がGitHubに公開しているSSH公開鍵の一覧を以下のURLから取得可能です

https://github.com/yuiseki.keys

同じように松澤さんのSSH公開鍵の一覧は以下のURLから取得可能です

https://github.com/smellman.keys

これを活用していただけると管理等が楽になるかもしれないと思います

**Comment by yuiseki** [comment]
UNVT PortableとUNVT Portalは、実際のところ、だいぶ紛らわしい名付けになってしまっているとは思います。
ただ、とりあえずアイデアを実行してみることのほうが重要で、名前はあとから変更しても全然良いはずだとも思います。

**Comment by hfu** [comment]
メモ：ジャンプホストの公開鍵
`ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMOiJhPKVynN2fOQWTt1f7Whd2GhQW2ek7Im2TU2UcRo`

**Comment by hfu** [comment]
細かい話をマニュアルにメモ中。
https://hackmd.io/ErD3l_UgTjyifDaYp0P5ag?edit

**Comment by hfu** [comment]
本日8機を追加し、17機体制にしました。
他方で、2023-10-28/29にいったん電源喪失する見込みであり、そのころにリブートが必要です。また、追加の2機ほど、mDNSで引けない機械があります。

機械のリストは UNVT Portal に入ってから`rake -T`でとれます。
`rake -T | wc -l` で機械の数を数えています。

**Comment by yuiseki** [comment]
`m326` に `yuiseki` というユーザーを作らせて貰って、そこで作業しています。
共用マシンであることを充分に認識して、秘密情報は一切置かないようにしています。

`m326` で起動したWebサーバーに私の自宅からアクセスしたくて、試行錯誤していたら、できるようになりました。
方法を共有します。

## 自分を `docker` グループに追加

- ユーザー `yuiseki` では以下のコマンドがパーミッションエラーになる

```bash
docker ps
```

- ユーザー `yuiseki` を `docker` グループに追加する

```bash
sudo gpasswd -a $(whoami) docker
```

- 一旦シェルからexitして入り直す

```bash
docker ps
```

- 今度は上記のコマンドがエラーなしで動くはず

## Node.jsをインストール

- apt経由で入れるとNode.jsのバージョン追随が面倒なのでnvmを使う
- https://github.com/nvm-sh/nvm

```bash
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
```

- 一旦シェルからexitして入り直す
- Node.js v20をインストール

```bash
nvm install 20
```

## `tmux` などで適当に画面を2つに分割する

## `osm-regional-pmtiles-builder` を準備して、起動

```bash
git clone https://github.com/yuiseki/osm-regional-pmtiles-builder.git
cd osm-regional-pmtiles-builder
npm ci
make start
```

- `osm-regional-pmtiles-builder` を起動したまま、以下を実行

## `docker` 経由で `cloudflared` の Quick Tunnelを使う

```bash
docker run --add-host=host.docker.internal:host-gateway cloudflare/cloudflared:latest tunnel --url host.docker.internal:8080
```

- 上記のコマンドを実行時に `https://ランダムな文字列.trycloudflare.com/` が表示されるので、それを開く

## `m326` で動いているNode.jsのhttp-serverに、yuisekiの自宅からアクセスできた 🎉

[![Image from Gyazo](https://i.gyazo.com/176768a7adcb947a44ae901bc8622bc4.png)](https://gyazo.com/176768a7adcb947a44ae901bc8622bc4)

## 備考

- いまはhttp-serverもcloudflaredも止めました
- 起動するたびにランダムに文字列が変わらないようにするためには、Cloudflareにユーザー登録して秘密情報を `m326` に置く必要がある
  - YAGNIの精神で、必要になるまではやらない
- この方法はかなり強力な反面、セキュリティ的にはリスクもありそう？
  - たぶんSSHポートもexposeできてしまう？

**Comment by hfu** [comment]
@yuiseki 面白いです！ありがとうございます！

**Comment by hfu** [comment]
Continue to #294 

#274

**Comment by hfu** [comment]
UNVT Portal の運用に関しては、PMTiles の discussion 運用にも倣う形で、 https://github.com/UNopenGIS/7/discussions/306 で進めていきましょう。
