### ISSUE TITLE
2023-10-20/19: Smart Maps Meetup Pacific 7

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#275]
- [x] Guest Speaker - TBD
- [x] @albertkun, is it possible to update the title of the Zoom event information? It still is "UN Smart Maps International Meetup". It would be great to update it to "UN Smart Maps Meetup Pacific".

**Comment by albertkun** [comment]
@hfu yep, I went ahead and updated it to `UN Smart Maps Meetup Pacific`! I will try to see if we can get @yohman to speak about his research on Fukushima!

**Comment by hfu** [comment]
Thank you, @albertkun and excuse me for my following up on this late. Let's move on.

**Comment by albertkun** [comment]
@hfu no problem, yes let's move forward then! I'll confirm this week for the guest speaker and make the flier!

**Comment by albertkun** [comment]
@hfu Speaker is requesting if we can do an hour at 11am JST? If not, noon can still work! Let me know!

**Comment by hfu** [comment]
Thank you, @albertkun. 11am JST works for me and I think it would be good to try with 11am this time though I am a little bit afraid there may be someone who cannot make it. But I feel that it would always be great to try a new thing.

**Comment by albertkun** [comment]
@hfu Ok, thank you for the reply! I will confirm for 11am JST then and try to make the flier this weekend!

**Comment by albertkun** [comment]
@hfu actually, can you do 11:30am? That way our Indian colleagues can join at 8am instead of 7:30am! If you are OK with that change, here are the fliers! 
![unsmartmaps-flyer-2023-10-20](https://github.com/UNopenGIS/7/assets/8574425/dfa38dee-9de7-48b7-b77f-457c8671c026)
![unsmartmaps-flyer-papersize-2023-10-20](https://github.com/UNopenGIS/7/assets/8574425/6aade3a1-f487-4275-bb1a-c96bacf75f3e)

**Comment by hfu** [comment]
Yes! Let's try with 11:30am! So, we are good for going ahead in circulating the flier, right? 
I am so excited to have @yohman in the meetup!

**Comment by albertkun** [comment]
@hfu in that caes, yes we are good to circulate the flier! I am also very excited to have him in the meeting! He hopes that @mapconcierge can join us as he knows him! :)

**Comment by albertkun** [comment]
@hfu sorry, quick fix on the landscape image, there was a typo in the talk title!

![unsmartmaps-flyer-2023-10-20](https://github.com/UNopenGIS/7/assets/8574425/bd36675c-a309-40c4-95d8-059d05a916bc)

**Comment by hfu** [comment]
For those who have trouble in retrieving the zoom link for today's meetup, I dare to share the zoom link tentatively here. 

https://ucla.zoom.us/w/93540731519?tk=QDfLxoBvaWaCcbbsGfjeG1dn5I_iMx5I5MtczbJxXMs.DQMAAAAVx3ZKfxZoMkNmMWEtWlJhbUpaZUVPaENjMFBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA&pwd=OG91Q2FPQktpUWF1YldVNVRMT294UT09

I will remove this comment when the event is done.

**Comment by hfu** [comment]
@albertkun has kindly prepared slides for the Meetup: https://github.com/UNopenGIS/7/issues/270#issuecomment-1769763073. Thank you!

**Comment by albertkun** [comment]
@hfu uh oh, is there an issue with the zoom link??

**Comment by hfu** [comment]
Thank you!
