### ISSUE TITLE
Arrange a meeting with UNIFIL

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#285]
@hfu will be contacting Shazia to arrange a meeting UNIFIL.

**Comment by yuiseki** [comment]
@hfu 私は17:00-18:00の場合は仕事上の予定が入っている可能性が高くなってしまっているので事前の調整が必要です。18:00以降であれば確実です。

**Comment by hfu** [comment]
@yuiseki ありがとうございます。日本時間の18時以降をベースに調整していきましょう。

東京・ベイルート間の時差を次のサイトでチェックしてみました。
https://www.timeanddate.com/worldclock/meetingtime.html?iso=20231023&p1=248&p2=34

UNIFILサイドのランチタイムを回避するとすれば、日本時間で20時、21時、22時のいずれかで開始するのが良いと思いました。私の生活パターンだと、第一希望22時、第二希望21時、第三希望20時というところですが、yuisekiさんの優先順はどのようになりますか。

他方で、私の第一希望である22時は、UNIFIL側で「遅すぎる、都合が悪い」ということになるのかもしれません。21時か20時で調整することになるかもしれません。

**Comment by yuiseki** [comment]
@hfu 20時、21時、22時のいずれでもOKです。この３つであれば、特に優先順位はありません。 よろしくお願いします 🙏

**Comment by hfu** [comment]
https://twitter.com/UNIFIL_/status/1718282975933079577 の情報もあり、しばらくの間、本件を進めるのは困難かもしれません。

See also: #289

**Comment by hfu** [comment]
UNIFIL 方面に取材したところ、次のような情報が得られました。

- UNIFIL側からのデータ提供・データ共有は以前に増して困難な状況であり、UN Open GISのアプローチを適用しやすい状況ではない。
- 中近東の混沌とした状況は長期化すると思われるので、オペレーションレベルではなく、中長期スタンスで見るのであれば、ミッションではないところ、例えば ESCWA に話を振ってみることはできる。

ESCWA というヒントは頂きましたが、Smart Maps Group 全体としては、GRF の文脈もあり、経済社会系のほかにも人道系に機会を求めていくという選択肢は生じえるかもしれません。他方で、いずれにせよ情報管理に関する各分野のカルチャーは最大限に尊敬し、郷に入れば郷に従えの原則で遵守していく必要があると思います。（逆に言えば、郷が合わなければ郷を変えてみる、というのが Smart Maps Group が持っている強みだと思います。）

**Comment by hfu** [comment]
#274
