### ISSUE TITLE
INFO: UN Innovation Toolkit

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#290]
I checked out the UN Innovation Toolkit (UNIT) operated by United Nations System Staff College (UNSSC). External person like me can sign in UNIT. 

My first diagnosis result was "Strategist": https://un-innovation.tools/profile/share/5c864fd3f98eeb1afc9cc80a

**Comment by yuiseki** [comment]
Thanks for information.
My diagnosis result was "Motivator": http://un-innovation.tools/profile/share/5c864fd4f98eeb1afc9cc80c
