### ISSUE TITLE
Stramline internal communication

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#3]
After the [Project Document](https://github.com/UNopenGIS/7/wiki/Project-Document) is drafted, let's think about streamlining DWG7 internal communication. 

# Open communication
Because [We prefer open collaboration](https://github.com/UNopenGIS/7/wiki/Project-Document#community-promises), we need nice open communication channels. 

- [ ] Do we need an open Gitter channel? Or shall we re-vitalize [GitHub Teams](https://github.com/orgs/unvt/teams/members)?

# Project Kanban
- [x] I use project kanban internally at https://github.com/orgs/UNopenGIS/projects/1/views/1. (I make it public right now.)

# Communication among all objective owners
- [x] UN Teams Group for all leads and objective owners (Diego, Hidenori, Taro, Taichi, Santosh, Takayuki).
- [x] LinkedIn Group of all objective owners (Hidenori, Taro, Taichi, Santosh, Takayuki), we use English here as the common language.
- [x] Facebook Group of Japanese-speaking objective owners (Hidenori, Taro, Taichi, Takayuki).

# Communication among members
- We use existing channels, too.

**Comment by hfu** [comment]
# Open communication
Because [We prefer open collaboration](https://github.com/UNopenGIS/7/wiki/Project-Document#community-promises), we need nice open communication channels. 

- [ ] Do we need an open Gitter channel? Or shall we re-vitalize [GitHub Teams](https://github.com/orgs/unvt/teams/members)?

# Communication among all objective owners
- [ ] UN Teams Group for all leads and objective owners (Diego, Hidenori, Taro, Taichi, Santosh, Takayuki).
- [ ] LinkedIn Group of all objective owners (Hidenori, Taro, Taichi, Santosh, Takayuki), we use English here as the common language.
- [ ] Facebook Group of Japanese-speaking objective owners (Hidenori, Taro, Taichi, Takayuki).

# Communication among members
- We use existing channels, too.

**Comment by ubukawa** [comment]
Thank you @hfu  for your great efforts!

First of all, I confirmed the project document and it properly captures my activity (objectives). Thank you.

Regarding the communication methods, I may use MS Teams for my own project because it could contain some internal information, but I am happy to use open communication in terms of sharing the progress of our activity every month.
To me, any platform would be fine. I think GitHub would be easy.

Thank you!

**Comment by hfu** [comment]
We started the LinkedIn group without Takayuki because Takayuki has no LinkedIn account yet.

**Comment by hfu** [comment]
LinkedIn Group is now created.

**Comment by hfu** [comment]
UN Teams Group has been created by @ubukawa. Thanks!

**Comment by hfu** [comment]
Gitter Channel has been created at https://gitter.im/unvt/community. Thanks, @smellman, and @yuiseki for your encouragement. Also, thanks to @mapconcierge for joining the channel already.
