### ISSUE TITLE
Create new GitHub repository `UNopenGIS/77` for DWG7 Objective 7

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#31]
https://github.com/UNopenGIS/7/wiki/Project-Document#objective-7-core

New objective, `UNopenGIS DWG7 Objective 7: Core` has announced at project document above and introduced to Co-Chairs of UNopenGIS.

So I propose to create a repository like `UNopenGIS/77` for Objective 7.
That is similar to repositories below.
- https://github.com/UNopenGIS/74
- https://github.com/UNopenGIS/76

I can think of many tasks I would like to list about Objective 7.
I would like some place to write them down.
Also I would like to request to triage them to @smellman, Objective Owner of Objective 7.

Please let me know if you ( @hfu ) have any concerns about doing this.
For example, "It is still too early to do."

**Comment by yuiseki** [comment]
For reference, I would like to list the following tasks

- Understand and document of the activities of key organizations involved in OSS GIS
  - There seem to be a great number of organizations. I think this is confusing for everyone. I would like a brief overview of these.
  - They seem to be creating their own learning content. It would be worthy just to understand these and introduce them appropriately to meet the demand.
- Understand of examples of vector tile map construction workflows
  - For large scale cases
  - For small scale cases
  - Document the industry standard software used there

**Comment by hfu** [comment]
Thanks for the suggestion! 

I created https://github.com/unopengis/77 and invited @smellman, @yuiseki, @ubukawa, and @hfu as its admin!
