### ISSUE TITLE
🖐️2023-11-17T12:00/13:00+09:00: Pacific and Strategy meeting (Show and Tell)

### ISSUE THREAD

**Issue by albertkun** [UNopenGIS/7#315]
@hfu Just checking in, will there be a show and tell this week for the UN Smart Maps Meetup Pacific?

I've updated the events page on the UN Smart Maps page:

https://unopengis.github.io/smartmaps/events/

It automatically pulls from the Google Calendar at 00:00 UTC. We can adjust when necessary!

### Meeting Link
https://ucla.zoom.us/j/93540731519?pwd=OG91Q2FPQktpUWF1YldVNVRMT294UT09

**Comment by hfu** [comment]
Thanks. We discussed on this in the weekly meeting today ( #311 ). 

I am relatively free on 2023-11-17 and will probably able to participate. 

Some will be able to participate depending on the start time. 

So, what we can do first is to decide the time.

**Comment by hfu** [comment]
I am free 10:00/13:30 and 16:00/17:00 +09:00 on 2023-11-17.

**Comment by albertkun** [comment]
we can do 12:00 - 13:30 if that works for people! Other wise we can try a later time, though given the time change in USA, that would mean around 11pm - midnight my time, which normally isn't an issue but I am visiting family at home in SF 😓 ! No problem either way though, I would like to see more participation! :)

**Comment by hfu** [comment]
Thanks! Let's do it on 12:00/13:00+09:00 Fri in Tokyo time which is 19:00/20:30-8:00 Thu. 

Please check: https://www.timeanddate.com/worldclock/converter.html?iso=20231117T030000&p1=248&p2=224

**Comment by albertkun** [comment]
Ok, sounds good! I'll update it on the Google Calendar! 👍

**Comment by hfu** [comment]
@albertkun Thanks! Let's move on 👍🏻 

@smellman @yuiseki @k96mz and all, are you coming to the meeting?

**Comment by smellman** [comment]
I have my company meeting every 13:00+09:00 Fri.
I can join until this time.

**Comment by k96mz** [comment]
I will attend the meeting😀

**Comment by hfu** [comment]
@albertkun I am not sure about the Zoom link. What zoom link are we using?

**Comment by hfu** [comment]
What I can bring and show will be...

## Base addresses from San Francisco's Enterprise Addressing System (EAS)
In vector tiles (PMTiles) and on IPFS. 

- [With PMTiles Viewer](https://protomaps.github.io/PMTiles/?url=https%3A%2F%2Fsmb.optgeo.org%2Fipfs%2FQmYsNiPd72agz3s9FdfihZFiRUVUaPYMHqV9FiizyMDgQ9#map=11.37/37.7688/-122.4424)
- [Repository](https://github.com/amx-project/sf)

## My Mind Map (for upcoming presentations and sessions)
... I will scan it and upload it here soon.

**Comment by hfu** [comment]
@albertkun I think we will be using the Zoom link for "UN Smart Maps International Meetup" with a date of today. 

The link for myself: https://ucla.zoom.us/w/93540731519?tk=QDfLxoBvaWaCcbbsGfjeG1dn5I_iMx5I5MtczbJxXMs.DQMAAAAVx3ZKfxZoMkNmMWEtWlJhbUpaZUVPaENjMFBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA&pwd=OG91Q2FPQktpUWF1YldVNVRMT294UT09
We already know that you will be me in the meeting if you follow the link above 😄

**Comment by albertkun** [comment]
@hfu Thanks for the reminder! Here's the meeting link:
https://ucla.zoom.us/j/93540731519?pwd=OG91Q2FPQktpUWF1YldVNVRMT294UT09

**Comment by hfu** [comment]
@albertkun Thank you!I will follow the link above to participate in the meeting today. 

My mind map as promised: 
[20231117082920.pdf](https://github.com/UNopenGIS/7/files/13385124/20231117082920.pdf)
Maybe good for the strategy meeting part.

**Comment by hfu** [comment]
JPEG version of my mind map for an easier access. 

![mind-map](https://github.com/UNopenGIS/7/assets/18297/d9e585ea-3d26-4b1c-a891-49b26b5dab00)

**Comment by k96mz** [comment]
https://k96mz.github.io/20231115shinsui/

I made a map showing "predicted flood area" and "actual flood depth".
Red: predicted flood area
Blue: actual flood depth caused by typhoon in 2018

**Comment by hfu** [comment]
Thank you all, it was an easy, fruitful, and so successful meetup!
