### ISSUE TITLE
@hfu's slide "monolith" for this winter

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#324]
Attached is my slide deck for #304, #305, #298, and #300. After now I will "fork" slide decks for each opportunity. 

[2023_Smart_Maps_presentations.pdf](https://github.com/UNopenGIS/7/files/13466573/2023_Smart_Maps_presentations.pdf)

Please let me know if you have any comments, suggestions, or questions. 

@yuiseki, @smellman, @albertkun, @mapconcierge, @ShogoHirasawa, @ubukawa, @miya0001 and all

**Comment by hfu** [comment]
I will be closing this issue next week.

**Comment by hfu** [comment]
## できていること
- 配色を中心とするデザインはシステムができつつある。 @albertkun と @yuiseki に感謝。
- Microsoft PowerPoint を Windows と Mac で併用しているので、フォントは今回 Source Sans Pro の Regular と SemiBold で固めた。
  - Source Sans は Google の Noto Sans / Roboto と同じものを Adobe ブランドで出す時の名前であるように理解している。

## 改善していくべきこと
- 話者が伝えたいことを伝えるのではなく、聴衆が聞きたいことを伝える必要がある

**Comment by albertkun** [comment]
@hfu Looks good! Thank you for sharing!! Do you think we should have a pinned `Introduce` yourself post in https://github.com/unopengis/7/issues for new people who would be interested?

**Comment by hfu** [comment]
@albertkun Wow, that is a great idea. Could you create that issue for us?

**Comment by albertkun** [comment]
Sure, what questions should we ask? I'm thinking:

1) Name (preferred name, alias and pronouns)
2) Current location of employment
3) Skills/Expertise
4) What would you like to get from the group?

I'm open to changing these!

**Comment by hfu** [comment]
@albertkun Thank you for #325! I included a slide for this: 

<img width="981" alt="image" src="https://github.com/UNopenGIS/7/assets/18297/bf828d9d-3597-469c-8022-838779e710fa">

**Comment by hfu** [comment]
Because this is not actually an issue, I am closing this issue before end of 2023-12. Thanks!

**Comment by hfu** [comment]
I will be closing this with connection to #343.
