### ISSUE TITLE
Introductions! 

### ISSUE THREAD

**Issue by albertkun** [UNopenGIS/7#325]
Thank you for your interest in UN Smart Maps! Please feel free to introduce yourself below with the following information!

- Name (preferred name, alias and pronouns)
- Current location of employment
- Skills/Expertise
- What would you like to contribute?

**Comment by smellman** [comment]
- Taro Matsuzawa (@smellman)
- Tokyo
- GIS Engineer / Python / Ruby / TypeScript / JavaScript / UNIX
- unvt/charites, UNOpenGIS/7 and QGIS!

**Comment by hfu** [comment]
- Hidenori Fujimura (Hidenori, he/him, @hfu)
- Tsukuba - a science city 60km from Tokyo
- design and implementation of web maps / ruby / unix / javascript
- take the lead of the group / adopt open geospatial data into cloud-native

**Comment by kshitijrajsharma** [comment]
Kshitij raj sharma 
Product owner - Map data access services , Humanitarian OpenStreetMap Team 
Skills : Feature extraction from satellite / Drone image , Backend development , Architecture design , Postgres and Spatial Data management 
Where would I like to contribute : Wherever my expertise fit , may be on feature extraction that is presented on foss4g asia slide ?

**Comment by smjtheoff** [comment]
- Pongsakorn Udombua (@smjtheoff)
- Bangkok, Thailand
- Large Scale Microservices Infrastructure, CDN, Containers, OGC API, Blockchain / All in GeoSpatial Domain
- Cloud-Native, Massive API Services

**Comment by mapconcierge** [comment]
- Taichi Furuhashi (Taichi, he/him, @mapconcierge )
- Tokyo / Saitama / Kanagawa
- GIS Engineer / OSM mapper / drone / digital fabrication 
- unvt/portable, UNOpenGIS/7

**Comment by asahina820** [comment]
- Hinako Iseki（Asahina, she/her, @asahina820）
- Tokyo, Japan
- GIS Engineer / Python / JavaScript / React / MapLibre GL JS
- UN Smart Maps Documentation, learning, and so on!

**Comment by hfu** [comment]
I am closing this. Thank you for introductions!
