### ISSUE TITLE
Confirm pledges to Global Refugee Forum 2023

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#327]
Following the upcoming Seoul Declaration from FOSS4G Asia 2023, @Kenyat1989 is so kind to propose draft pledges from UN Smart Maps Group to the [Global Refugee Forum 2023](https://www.unhcr.org/global-refugee-forum-2023) to be held during 2023-12-13/15 in Geneva, Switzerland. @Kenyat1989 will be joining the Forum and offered to take care of our possible pledges in addition to his team's pledges. 

He offered the following two proposals. What do you think? UN Smart Maps Group can discuss this in the Community Sprint. We need to fix the pledges early next week. 

# Proposal 1
## Pledge Entity Name
The Watanave Hidenori Laboratory at the University of Tokyo, the UN Smart Maps Group, UN Open GIS Initiative, and Eukarya Inc.

## Details
The Watanave Hidenori Laboratory at the University of Tokyo, the UN Smart Maps Group, the UN Open GIS Initiative, and Eukarya Inc. have pledged to enhance the accessibility of Free and Open Geospatial Technology and Data for refugees. 
Drawing inspiration from the Seoul Declaration at FOSS4G Asia 2023, this initiative aims to increase refugee participation in FOSS4G conferences and similar events, particularly for those facing travel challenges. 
The pledge includes establishing support systems for visa procedures, providing scholarships to enable around 30 refugees to attend FOSS4G 2025, and offering online participation options for those unable to travel. 
This effort aims to create an inclusive environment where refugees can actively engage and collaborate with the FOSS4G community, fostering a sense of belonging and contribution within the geospatial technology field.

# Proposal 2
## Pledge Entity Name
UN Smart Maps Group, UN Open GIS Initiative

## Details
The UN Smart Maps Group and UN Open GIS Initiative have committed to a pledge to empower refugees through geospatial information technology over the medium to long term. 

This initiative involves providing refugees with essential web and Geographic Information System (GIS) skills, utilizing tools like UNVT (United Nations Vector Tile) Portable/Portal powered by Raspberry Pi. The program is designed to facilitate learning in environments even remote from the internet and power grids, emphasizing the potential for offline digital skills training. 
By doing so, it seeks to explore the possibility of refugees becoming digital talents who can contribute to the public good. The pledge also focuses on disseminating this technology to a broader audience, underlining a commitment to preventing the creation of more refugees. 

KPI for this initiative includes implementing digital skills training for 100 refugees by 2027 and establishing a system capable of responding to crisis situations, thereby contributing to the prevention and resolution of refugee issues.

**Comment by hfu** [comment]
I would like to get inputs from @yuiseki because of her experience with UN Smart Maps Agent and other UN-related activities. Are you or anyone in the UN Smart Maps Group interested in taking actions along with this line?

**Comment by yuiseki** [comment]
@hfu Of the two Proposals, I found Proposal 2 in particular to be concrete, realistic, and engaging for us! I am happy to help in any way I can!

**Comment by hfu** [comment]
We are making progress in https://discordapp.com/channels/1180387931614085130/1181813551837487175. 
I close this issue here.
