### ISSUE TITLE
[IDEA] Test mago 3DTiler

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#329]
[mago 3DTiler](https://github.com/Gaia3D/mago-3d-tiler) was released in FOSS4G Asia 2023. Why don't we test it?

**Comment by yuiseki** [comment]
I saw a very interesting X post and demo video that I would like to share.

- https://twitter.com/endofcap/status/1736198344777818524
- https://www.youtube.com/watch?v=XAqE-8VczNk

Gaia3D seems to be developing something called `magoGPT` that places and manipulates 3D models on maps with natural language instructions.
The source code does not seem to be publicly available yet, but I am very curious to see how it is realized.

**Comment by hfu** [comment]
I tested mago 3D Tiler with Open Nagasaki LiDAR data. It looks like there are some interoperability issues with Open Nagasaki LiDAR data.
