### ISSUE TITLE
How @mapconcierge is training students with GitHub

### ISSUE THREAD

**Issue by mapconcierge** [UNopenGIS/7#330]
<a href="https://youtu.be/9DZSty2KsJ8?si=g-ZpkhlCSLV3gRVZ"><img src="https://github.com/UNopenGIS/7/assets/416977/3050ae9a-e3e7-41c4-8f94-ca422b17b8fb" width="600" /></a>

https://youtu.be/9DZSty2KsJ8?si=g-ZpkhlCSLV3gRVZ

**Comment by hfu** [comment]
Closing with thanks.
