### ISSUE TITLE
Discord for UN Smart Maps community

### ISSUE THREAD

**Issue by smellman** [UNopenGIS/7#331]
I just create discord server: https://discord.gg/B2uCGWGmZ5

**Comment by smellman** [comment]
![qr20231202150400984](https://github.com/UNopenGIS/7/assets/135112/aff6bac3-7fa8-409c-9092-08ad0393d2bb)
Invite QR code.

**Comment by hfu** [comment]
I close this issue because the links are already integrated with our web site at https://unopengis.github.io/smartmaps/get-involved/join thanks to @albertkun.
