### ISSUE TITLE
[idea] Open style.json for modern web map design system?

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#332]
Wouldn't it be nice to apply new modern web map design system as in https://x.com/dbabbs/status/1729550439400476719?s=46&t=f8vcjeJOLjOap3CynrX6Cw on open web maps such as OpenStreetMap, UN Maps, or GSI Maps vector tiles? 

What is a good way to share web map design system among open web maps? 

Hint: charites :-)

**Comment by albertkun** [comment]
I like this idea! Maybe as a starting point we can draw from Diego's presentation on UN Maps and use their basemaps as the base styling if it is available!

**Comment by hfu** [comment]
#404 にマージしていくことにして、本件自体はクローズします。

#274
