### ISSUE TITLE
Update Raspberry Pi OS to bookworm (UN Smart Maps Bazaar)

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#333]
In #302 @smellman found that UN Smart Maps Bazaar nodes use older version of Raspberry Pi OS (bullseye). 

We can and should update it to bookworm. 

@hfu will be updating it by installing from Raspberry Pi Imager again.

**Comment by hfu** [comment]
この作業を、@yuiseki の https://github.com/yuiseki/unvt-pi-gen ベースで進めていきたいと思っています。

関連： #367

**Comment by yuiseki** [comment]
[unvt-pi-gen](https://github.com/yuiseki/unvt-pi-gen) の元になっている [pi-gen](https://github.com/RPi-Distro/pi-gen) の最新版は既に bookworm になっていました（その結果、妙なハマりポイントがあって困りました 😅 が、unvt-pi-genではすでに解決済みです（これまで通りだとダメで、[このおまじない的な二行](https://github.com/yuiseki/unvt-pi-gen/blob/cfb6191a8e430f91e762cb163182e8fdf0839fc7/Makefile#L60-L61)がないと動かない））

**Comment by yuiseki** [comment]
## 重要
- [このコミット](https://github.com/RPi-Distro/pi-gen/commit/8dd23cbc1d01b2a89f560c98f5e5b8ef2e71fbf3)で、 `pi-gen` からWiFi関係の設定をする能力が消滅しています
- Debian 12 Bookwormから、wpa_supplicantが消滅したことが原因のようです
- `unvt-pi-gen` で、別の方法で対応できないか試行錯誤していますが、現時点で `unvt-pi-gen` を使うと `WPA_ESSID` や `WPA_PASSWORD` を指定していても起動直後にWiFiに自動で繋がらないという問題のある状態になってしまっています

**Comment by yuiseki** [comment]
最新の `unvt-pi-gen` で起動直後にWiFiに自動で繋がるようにできました

**Comment by hfu** [comment]
時間の経過に沿って、私の手元の Raspberry Pi も bookworm に切り替わりつつあります。
#274
