### ISSUE TITLE
FOSS4G-Asia 2023 振り返り (for UN Smart Maps Weekly #334)

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#335]
FOSS4G 2023 Kosovo に際に行った #200 のスタイルで振り返りをしましょう。

まずこのチャンネルでは日本語でやりましょう。それをベースに #334 で議論してから、必要に応じて英語でも整理していくことにしましょう。（ @albertkun もこの issue に参加いただける場合には、遠慮なく英語で書いていただければと思います。）

現場、オフラインを問わず、参加した皆さんの感想を集約しましょう。

> @smellman, @mapconcierge, @ShogoHirasawa, @hfu

**Comment by albertkun** [comment]
このissueが興味があるけど、日本語で大丈夫かも！基本的なFOSS4G-Asiaの感想は「いい人といい考えてと繋ぐ」と思います！もちろんいいソフトが紹介した！特にmago3dとurbanaのアプリがすごく良かったと思います！

**Comment by hfu** [comment]
@albertkun ありがとう！mago3d は私もよくわかるけど、urbana について少し教えてくれますか。

「いい人といい考えてと繋ぐ」、つまり「人と考えを繋ぐ」という感想、本質を捉えていて素晴らしいと思います。

**Comment by hfu** [comment]
I close this issue because #334 is done.
