### ISSUE TITLE
GRF 2023 Pledge development

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#336]
As discussed in [Discord](https://discord.com/channels/1180387931614085130/1181813551837487175/1182661825528070154): 

# Pledge Entity Information
## Name of entity submitting this form
The OpenGeoCommunity for GRF2023, led by the UN Smart Maps Group of the UN Open GIS Initiative

## Country
Japan

## Institutional (departmental) general email address
unsmartmaps@gmail.com

## Submitting entity type
Civil Society Organizations

# Contact Information
## Salutation
Mr.

## First Name
Hidenori

## Last Name
Fujimura

## Position
Lead, UN Smart Maps Group, UN Open GIS Initiative

## Email
unsmartmaps@gmail.com

**Comment by hfu** [comment]
I updated the email address based on https://discord.com/channels/1180387931614085130/1181813551837487175/1183079274907971705

**Comment by hfu** [comment]
Let's move on to the content. 

# Linked to the Multi-stakeholder pledge
## Multistakeholder pledge
[Closing the Digital Gender Gap](https://globalcompactrefugees.org/pledges-contributions/multistakeholder-pledges-2023/multistakeholder-pledge-closing-digital-gender)

- [ ] We need to understand what specifically the Digital Gender Gap is. 

# Pledge
## Pledge description
The OpenGeoCommunity for GRF2023, led by the UN Smart Maps Group of the UN Open GIS Initiative, The UN Smart Maps Group and UN Open GIS Initiative have committed to a pledge to empower refugees through geospatial information technology over the medium to long term. 

This initiative involves providing refugees with essential web and Geographic Information System (GIS) skills, utilizing tools like UNVT (United Nations Vector Tile Toolkit) Portable powered by Raspberry Pi. The program is designed to facilitate learning in environments even remote from the internet and power grids, emphasizing the potential for offline digital skills training. 
By doing so, it seeks to explore the possibility of refugees becoming digital talents who can contribute to the public good. The pledge also focuses on disseminating this technology to a broader audience, underlining a commitment to preventing the creation of more refugees. 

KPI for this initiative includes implementing digital skills training for 100 refugees by 2027 and establishing a system capable of responding to crisis situations, thereby contributing to the prevention and resolution of refugee issues.

To enhance this pledge, the following contributions can be integrated:
Training Documentation for Web Mapping: Developing comprehensive training materials specifically for web mapping would be crucial in equipping refugees with the necessary skills to utilize GIS technologies effectively.
Tools for Localization in Local Languages: Providing tools that support localization in various local languages, such as Arabic. This is particularly important as it ensures that the training and resources are accessible to refugees from different linguistic backgrounds, broadening the initiative's impact.

These contributions aim to enhance the accessibility and effectiveness of the training provided to refugees, ensuring that they can fully leverage the potential of geospatial technologies. By focusing on localization and comprehensive training documentation, the initiative can be more inclusive and impactful, catering to the diverse needs of refugees across different regions.

## Expected impact of the pledge in one sentence
Bridging Digital Divides: Offline Web and GIS Skills Training for Refugees;
This pledge aims to empower refugees by providing them with essential offline digital and GIS skills, potentially transforming them into digital talents who contribute to the public good and aid in preventing and resolving refugee issues.

## Target population(s)
- Refugees
- Stateless person
- Host communities

## Number of targeted beneficiaries (if known)
100

## Timeline for implementations
4 year

## When would you like your pledges to made public?
December 8th

**Comment by hfu** [comment]
As far as I understand our pledges are already released with help from @Kenyat1989. Thanks again. 

@albertkun and @yuiseki, do you think SMG need to have the Seoul Declaration and our pledges on the UN Smart Maps website?

**Comment by albertkun** [comment]
Yes, I think it would be helpful to have the pledges on the website!

**Comment by hfu** [comment]
@albertkun Thanks! So let's create separate issues for having the Declaration and Pledges on the web site. Do you prefer having these issues on unopengis/smartmaps or unopengis/7? 

By the way, I feel that it is also a good time to think about contributors page to the web site. We may need to think about the format and the rule. The rule maybe something like: contributor information will be reflected to the web site if the draft gets more than 2x👍 on Discord.

**Comment by albertkun** [comment]
I think issues related to website content should be on the Smart Maps website repository (not 7), to avoid clutter! I'll try to manage that board and close more issues too! 

And yes, contributors would be great in addition to partner organizations (eukarya, osgeo, etc.)! Should the same rule should apply for adding partners to that page?

**Comment by hfu** [comment]
Our finding from UN Open GIS Initiative web site is that the partner list tend to [get long too easily](http://unopengis.org/unopengis/about/about05.php) and does not reflect the actual contribution. From this background I think we may need some rule like a casual 👍 vote on Discord.

**Comment by hfu** [comment]
Delegated to the documentation project. 

- https://github.com/UNopenGIS/smartmaps/issues/79
- https://github.com/UNopenGIS/smartmaps/issues/80
