### ISSUE TITLE
`charites-ai`, AI that can generate json files according to Mapbox style specification based on natural language instructions 

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#337]
# https://github.com/yuiseki/charites-ai

## Help wanted!

- このAIはYAMLファイルにコメントを書くことによって性能が向上します
- 例：
  - https://github.com/yuiseki/charites-ai/blob/main/styles/layers/background.yml
  - https://github.com/yuiseki/charites-ai/blob/main/styles/layers/boundary-land-disputed.yml
  - https://github.com/yuiseki/charites-ai/blob/main/styles/layers/boundary-land-level-2.yml
  - https://github.com/yuiseki/charites-ai/blob/main/styles/layers/boundary-land-level-4.yml
- このような形式でYAMLファイルにコメントを追加する作業を手伝ってくださる方を募集します
  - styles/layers/*.yml を編集して、https://github.com/yuiseki/charites-ai にPull Requestを送ってください

[![Image from Gyazo](https://i.gyazo.com/b26f7803974e840f5706cf5ae6c7d1e6.gif)](https://gyazo.com/b26f7803974e840f5706cf5ae6c7d1e6)

**Comment by hfu** [comment]
Wow, it would be a great mix of YAML and natural language. It feels like "[literate programming](https://www-cs-faculty.stanford.edu/~knuth/lp.html)" to me. I like the idea behind.

**Comment by yuiseki** [comment]
`charites-ai` は本日、 `charites-ai Agent` に成長しました。

どのようなスタイルの地図を作るか計画を立てる能力と、実際にその計画を実行に基づいて地図を作成する能力があります。

デモ動画：
[![Image from Gyazo](https://i.gyazo.com/a51ad0747883363f6a19298efe19c7ec.gif)](https://gyazo.com/a51ad0747883363f6a19298efe19c7ec)

**Comment by yuiseki** [comment]
情報共有の役割は果たしたので一旦閉じます
