### ISSUE TITLE
[IDEA] PMTiles from UCDP Georeferenced Event Dataset (GED) Global version 23.1

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#338]
As a demonstration of [make-world](https://discord.com/channels/1180387931614085130/1183207177687674930) concept, I should create PMTiles from [UCDP Georeferenced Event Dataset (GED) Global version 23.1](https://ucdp.uu.se/downloads/index.html#ged_global)

**Comment by hfu** [comment]
<img width="1052" alt="image" src="https://github.com/UNopenGIS/7/assets/18297/80aa6855-879c-41c4-8d87-9f806be5dafa">

First implementation was done at https://github.com/optgeo/uppsala-conflict

**Comment by hfu** [comment]
The size of a.pmtiles is 130MB. This means we need UN Smart Maps Bazaar in place of GitHub Pages :-)

**Comment by hfu** [comment]
Uploaded to UN Smart Maps Bazaar. 

https://protomaps.github.io/PMTiles/?url=https://smb.optgeo.org/ipfs/Qmeguu9vsViuKh5m4rc1zhCsYuzwjMxEwa7YYRvKrgGQ5C

**Comment by hfu** [comment]
Visualizing the data [on Observable](https://observablehq.com/d/a50225205b32b8bf). 

![image](https://github.com/UNopenGIS/7/assets/18297/a929feed-5df7-4811-93cb-4d0ebcb9e848)

This is my possible input in #372.

**Comment by hfu** [comment]
Specification information: https://ucdp.uu.se/downloads/ged/ged231.pdf

**Comment by hfu** [comment]
#274

**Comment by yuiseki** [comment]
pg_tileservで、UCDP GED（ウプサラ紛争データプログラム 地理参照事件データセット）をベクトルタイルとして配信する｜yuiseki 
https://zenn.dev/yuiseki/articles/11fd2339a4cf5d
