### ISSUE TITLE
[IDEA] Minecraft for Smart Maps

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#341]
> Imagine growing up with your mother telling you to stop playing video games, and then discovering that you have acquired such a useful skill that the United Nations hires you as a video game expert. 
> 
> That’s exactly what happened to Eugenio Gastelum, who grew up in Mexico playing Minecraft through the night with his friends and now uses his gaming skills to help the United Nations redesign urban spaces. “It’s the best job in the world,” he says, describing his journey from gamer to game-changer.
> 
> Minecraft is not only the best-selling video game of all time, it is also a surprisingly effective way to visualize a three-dimensional environment and design urban spaces. Block by Block is an organization that allows Minecraft players to turn neglected urban spaces into vibrant places that improve quality of life for local residents. Thanks to Minecraft people of all ages, backgrounds and education levels can quickly change their environments by integrating the game into urban design plans
> 
> From Kathmandu to Kosovo, Minecraft and Block by Block give neighborhood residents the training, tools and platforms to participate and contribute their ideas in a collaborative process that helps develop inclusive, sustainable cities.
> 
> Thanks to Block by Block partnering with UN-Habitat to use Minecraft, people of all ages, backgrounds, and education levels can quickly change their environments by integrating the game into urban design plans.

https://youtu.be/Z56RnWWnkig?si=2ulH6mmXCR3xBOPq

**Comment by yuiseki** [comment]
In Japan, we have seen examples of GIS and Minecraft being used by some local governments. Is it possible to learn GIS skills while playing with Minecraft?

**Comment by smellman** [comment]
Tajima-san(friend both @yuiseki and I) used Minecraft to calculate AR function. I think it is possible to learn GIS with Minecraft.

**Comment by hfu** [comment]
I also think it is worth exploring the possibility in UN Smart Maps Group. 

What come to my mind is that we can make use of Minecraft as an alternative to MapLibre GL JS, Cesium, or other client library. 

We might want to discuss on our UN Smart Maps Discord. I will rename this issue to focus on the use of Minecraft.

**Comment by yuiseki** [comment]
I have done some research and will share the information:

Most Practical Findings:
- https://www.worldpainter.net/
- https://qiita.com/satoshi7190/items/aff245342b2a8f8a4587
- https://note.com/cgisj_inside/n/n4325cd7769c1
- https://zenn.dev/takunology/scraps/46bab227305e79
- http://meduro.blog.fc2.com/blog-entry-17.html
- http://minecraft.ologies.net/2014/10/minecraft-tokyo/
- https://github.com/ashtanmistal/minecraftUBC


Interestingly, Esri has published several articles on how to create Minecraft worlds using ArcGIS:
- https://www.esri.com/arcgis-blog/products/city-engine/3d-gis/minecraft-gis-magic/
- https://proceedings.esri.com/library/userconf/geodesign16/papers/geo_24.pdf

Even more interestingly, I discovered that the GSI is conducting research on supporting geography and geology learning through Minecraft!
- https://www.gsi.go.jp/chirijoho/chirijoho-e31006.html
- https://www.gsi.go.jp/common/000220240.pdf
- https://www.gsi.go.jp/common/000228111.pdf
- https://www.gsi.go.jp/common/000235846.pdf
- Moreover, this is a KAKEN project!
- https://kaken.nii.ac.jp/ja/grant/KAKENHI-PROJECT-18K18548/
- https://kaken.nii.ac.jp/ja/file/KAKENHI-PROJECT-18K18548/18K18548seika.pdf

**Comment by hfu** [comment]
@yuiseki Thank you very much for the information. In UN Smart Maps Group, I would like to share the uses a kind of "open world" where users can make use of the "world" for their purposes or just for fun. Some shortcomings of the KAKEN project was that the educator site had (to have) very specific educational purposes and they (needed to) evaluate based on its specific educational purposes. In UN Smart Maps Group we have a little bit more freedom and that is a good thing!

**Comment by hfu** [comment]
#274
