### ISSUE TITLE
HackMD Team

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#343]
I created a HackMD team for UN Smart Maps Group.

Here is the invitation: https://hackmd.io/join/B1DUmu8L6

I sent invites to @albertkun, @smellman, @yuiseki, and @mapconcierge separately. 

Feel free to ask anything regarding how we use this team.

**Comment by hfu** [comment]
- I am thinking about using this to share slides which can be reused or can be used to develop documentation.

**Comment by hfu** [comment]
- The slide style is now under development. https://hackmd.io/@smartmaps/BJaFi1_Ia#/ Thank you, @albertkun for your help.

**Comment by albertkun** [comment]
Looks good! Only feedback is that the logo might be a little small! Also, did you want it to be on the left side? Or are you ok with the logo on the right?

**Comment by hfu** [comment]
I added https://github.com/UNopenGIS/smartmaps/issues/78 and close this issue. Thanks.
