### ISSUE TITLE
[enquete] To what extent do you use AI in your software development? | [アンケート] みなさんはソフトウェア開発にどの程度AIを使用していますか？

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#356]
## 概要

- LLMsを初めとしたAIがソフトウェア開発に与えるインパクトに関して認識に差があるように感じている
- ソフトウェア開発支援AIはほとんどが有料、あるいは自分でOpenAI APIを契約してAPI Keyを登録する必要があったりして、使うことにハードルがある
- また、所属している組織によっては、業務で利用する際に申請が必要だったり、許可が降りない場合もある
- しかし、ソフトウェア開発支援AIは、ソフトウェア開発・運用そのもの、そしてソフトウェア開発の学習・教育・訓練にも大きな影響を与えることは間違いないと私は認識している
- この認識の差について相互理解を深めるために、使ったことのあるソフトウェア開発支援AIについてのアンケートへのご協力をお願いしたいです
- 以下にテンプレートを用意したので、コピー&ペーストして、使ったことのあるソフトウェア開発支援AIにチェックをつけてこのIssueにCommentしてください
- また、私が知らないソフトウェア開発支援AIをご存知でしたら、ぜひ教えてください

## Template | テンプレート
```
- [ ] DeepL
- [ ] ChatGPT Plus
- [ ] OpenAI API
- [ ] VSCode + [GitHub Copilot](https://docs.github.com/en/copilot/quickstart)
- [ ] VSCode + [GitHub Copilot Chat](https://docs.github.com/en/copilot/github-copilot-chat/about-github-copilot-chat)
- [ ] [Cursor](https://cursor.sh/)
- [ ] [Warp](https://www.warp.dev/) (currently, macOS only)
- [ ] [CodeRabbit](https://coderabbit.ai/)
- [ ] [CodiumAI PR-Agent](https://github.com/Codium-ai/pr-agent)
- [ ] [Sourcegraph](https://sourcegraph.com/)
- [ ] [v0 by Vercel](https://v0.dev/)
- [ ] [makereal by tldraw](https://makereal.tldraw.com/)
- [ ] [coffee by Coframe](https://github.com/Coframe/coffee)
- [ ] [E2B Sandbox](https://e2b.dev/)
```

**Comment by yuiseki** [comment]
- [ ] DeepL
- [ ] ChatGPT Plus
- [ ] OpenAI API
- [ ] VSCode + [GitHub Copilot](https://docs.github.com/en/copilot/quickstart)
- [ ] VSCode + [GitHub Copilot Chat](https://docs.github.com/en/copilot/github-copilot-chat/about-github-copilot-chat)
- [ ] [Cursor](https://cursor.sh/)
- [ ] [Warp](https://www.warp.dev/) (currently, macOS only)
- [ ] [CodeRabbit](https://coderabbit.ai/)
- [ ] [CodiumAI PR-Agent](https://github.com/Codium-ai/pr-agent)
- [ ] [Sourcegraph](https://sourcegraph.com/)
- [ ] [v0 by Vercel](https://v0.dev/)
- [ ] [makereal by tldraw](https://makereal.tldraw.com/)
- [ ] [coffee by Coframe](https://github.com/Coframe/coffee)
- [ ] [E2B Sandbox](https://e2b.dev/)

**Comment by hfu** [comment]
- [ ] DeepL
- [ ] ChatGPT Plus
- [ ] OpenAI API
- [x] VSCode + [GitHub Copilot](https://docs.github.com/en/copilot/quickstart)
- [ ] VSCode + [GitHub Copilot Chat](https://docs.github.com/en/copilot/github-copilot-chat/about-github-copilot-chat)
- [ ] [Cursor](https://cursor.sh/)
- [ ] [Warp](https://www.warp.dev/) (currently, macOS only)
- [ ] [CodeRabbit](https://coderabbit.ai/)
- [ ] [CodiumAI PR-Agent](https://github.com/Codium-ai/pr-agent)
- [ ] [Sourcegraph](https://sourcegraph.com/)
- [ ] [v0 by Vercel](https://v0.dev/)
- [ ] [makereal by tldraw](https://makereal.tldraw.com/)
- [ ] [coffee by Coframe](https://github.com/Coframe/coffee)
- [ ] [E2B Sandbox](https://e2b.dev/)

**Comment by smellman** [comment]
- [x] DeepL
- [x] ChatGPT Plus
- [x] OpenAI API
- [x] VSCode + [GitHub Copilot](https://docs.github.com/en/copilot/quickstart)
- [x] VSCode + [GitHub Copilot Chat](https://docs.github.com/en/copilot/github-copilot-chat/about-github-copilot-chat)
- [ ] [Cursor](https://cursor.sh/)
- [ ] [Warp](https://www.warp.dev/) (currently, macOS only)
- [ ] [CodeRabbit](https://coderabbit.ai/)
- [ ] [CodiumAI PR-Agent](https://github.com/Codium-ai/pr-agent)
- [ ] [Sourcegraph](https://sourcegraph.com/)
- [ ] [v0 by Vercel](https://v0.dev/)
- [ ] [makereal by tldraw](https://makereal.tldraw.com/)
- [ ] [coffee by Coframe](https://github.com/Coframe/coffee)
- [ ] [E2B Sandbox](https://e2b.dev/)

**Comment by hfu** [comment]
#274
