### ISSUE TITLE
meetup の運営を Lean Coffee の方法に近づけるアイディア

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#36]
meetup の運営について、Lean Coffee の方法に合わせるためには dot voting に該当する機能を実現する必要があります。

話題 Kanban https://github.com/orgs/UNopenGIS/projects/2/views/1 に入れているアイディアについては、全部 unopengis/7 の issue に変換して、dot voting の代わりに、その話題に興味がある人は、その issue に self-assign する ということでどうでしょうか。その話題を実際に話す人は、その issue をオープンした人、ということになります。

**Comment by yuiseki** [comment]
> Lean Coffee の方法に合わせるためには dot voting に該当する機能を実現する必要があります

これはAgreeです。


> 話題 Kanban https://github.com/orgs/UNopenGIS/projects/2/views/1 に入れているアイディアについては、全部 unopengis/7 の issue に変換して、

これもやったほうが良さそうですね。理由は後述します。


> dot voting の代わりに、その話題に興味がある人は、その issue に self-assign する ということでどうでしょうか

Issueにself-assignするのではなくて、Issueに 👍 でReactionしていくほうがよりdot votingっぽい気がするので、以下のような方法をご提案します。

- 話したい・聞きたい話題があったらIssueをOpenし、 `Meetup` ラベルをつけて、`Projects/2` のStatus `To Discuss` に追加する
  - Lean Coffeeでいうところの、付箋を書き出すステップに相当
- 話したい・話せる話題にはIssueでself-assignする
  - このステップはLean Coffeeにはないので、いらないかもしれない？
  - Assigneesはあくまでタスク管理上の担当者という用途に残しておいたほうが良いかも？
- 話したい・話せる・気になる・聞きたいなど、とにかく興味のある話題にはIssueに 👍 でReactionする
  - Lean Coffeeでいうところの、dot votingステップに相当
- Meetup当日は、Issueに `Meetup` ラベルがついているなかで 👍 が多い順でStatusを `Discussing` に変更して、話を聞いていく


「 `Meetup` ラベルがついているなかで 👍 が多い順」のIssueは、以下のURLで見ることができます：
https://github.com/UNopenGIS/7/issues?q=is%3Aissue+is%3Aopen+label%3Ameetup+sort%3Areactions-%2B1-desc


先週のMeetupの時点では、GitHub Projectsの各アイテムにReactionボタンが無かったような気がしていて、
たしかにこれだとGitHub Projects上ではdot votingはできないな…と思っていたのですが、
実は、GitHub Projects上で新規に追加したアイテムはDraftという扱いでReactionやComment等ができず、
一方で、GitHub IssuesをGitHub Projectsにアイテムとして追加すると、IssueなのでReactionやCommentができるんですね。

GitHub IssuesはReactionでソートする機能があるので、まさにdot voting的なことをするのに向いているのではないかと思って、上記の方法を提案します。

「GitHub Issuesを 👍 順でソートして意思決定する」というのは、OSS開発のトリアージでも、たまに使われている様子を見ます。

**Comment by hfu** [comment]
これはいいですね！これでいきたいです。
来週火曜日の meetup で本件話したいと思ったので、本件に 👍 を入れました🙂。

**Comment by hfu** [comment]
本件については、概ね共有も済んだので、クローズとします。
本件の方法論を文書化してどこかに置いておく方がナイスだとは思っています。
