### ISSUE TITLE
Placemark is now open source ❤️‍🔥

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#370]
Wow. What do you think we can do? > @yuiseki @smellman @albertkun @miya0001 

https://macwright.com/2024/01/19/placemark-oss.html

**Comment by yuiseki** [comment]
Related links:
- https://github.com/placemark/placemark
- https://www.placemark.io/
- https://www.placemark.io/documentation-index
- https://www.placemark.io/format-matrix

**Comment by yuiseki** [comment]
ざっと見た素朴な感想：
- Placemarkプロジェクトはかなり巨大で複雑
- Dockerをなるべく使わないという強い意志があるらしく、Docker構成がない
  - Placemarkをローカルで自力で開発環境構築したり独自でデプロイする場合はそこをなんとかしなければならない
- Prismaは未だに Geolocation/Spatial types support を完了していないはずである
  - https://github.com/prisma/prisma/issues/1798
  - にも関わらずPlacemarkはPrismaで実装されているので、Prismaを使いつつPostGISのGeolocation/Spatial typesを扱うノウハウが学べるかもしれない
- Node.js/Typescriptで膨大なファイルフォーマットをサポートすることができているのは興味深い。このあたりも学べるかもしれない
- GIS関係だと、以下のnpm packageに依存している
  - deck.gl
  - tmcw/togeojson
  - turf.js
  - d3.js
  - fast-json-patch
  - fflate
  - flatbush
  - flatgeobuf
  - geometric
  - mapbox-gl
    - oh...
  - mproj
  - pg
  - polygon-clipping
  - polylabel
  - proj4
  - rbush
  - topojson
  - xlsx
- GIS以外の依存関係を見る限りでも、最新の洗練され信頼できるnpm packageを選び抜いている様子から、天才が気合いで作り上げたサグラダファミリアという印象を受けた

**Comment by yuiseki** [comment]
うおーすごい。ここだけでも宝の山だ
- https://github.com/placemark/placemark/tree/main/app/lib/convert

**Comment by yuiseki** [comment]
私のローカル開発環境では以下の変更で `docker compose up` でPlacemarkが動くようになった

https://github.com/placemark/placemark/pull/16

**Comment by hfu** [comment]
Tom MacWright: It took me two years to build Placemark, and now I'm releasing it all for free
https://www.youtube.com/watch?v=LGq1mI3U6CI

**Comment by hfu** [comment]
Congratulations! I noticed that [your pull request](https://github.com/placemark/placemark/pull/16) was merged! 
![image](https://github.com/UNopenGIS/7/assets/18297/1895aafb-389c-48a5-9297-30736f8c745a)

I believe I should try to run placemark on our Raspberry Pi ;-)

**Comment by hfu** [comment]
A free instance of /play is now up at https://play.placemark.io/.

For us, it helps us understand Placemark as a potential tool we can make us in our community. 

See also: https://github.com/placemark/placemark/issues/39.

**Comment by hfu** [comment]
定着したのでクローズします。
