### ISSUE TITLE
2024-04-19: 👥ジオ展 (geoten) 2024

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#375]
As discussed in #369. I am sharing the logistical information. 

- 2024-04-19T10:00/17:00 展示/プレゼンテーション
- 2024-04-19T18:00/20:00 懇親会（出展団体限定）
- 会場は浅草橋ヒューリックホール
- 主催は「ジオ展実行委員会」＝マップボックス・ジャパン合同会社・株式会社MIERUNE、協力は365y株式会社

@hfu is not likely to make it to the event, because is otherwise engaged...

**Comment by hfu** [comment]
#378 で議論したとおり、Smart Maps で何かを出すというのはジオ展全体の混み具合を考慮して遠慮することになりました。別件で参加をする中で適宜 Smart Maps ついても活動してくるという方向になってきています。

**Comment by yuiseki** [comment]
この日、仕事の休みをとって参加することに決めました（会場が近所だし、去年は参加できなかったのでどんな様子か見てみたかったため）

**Comment by hfu** [comment]
It was a great event! Thanks especially to @asahina820 and @smellman for your hard work for Geoten 2024!
