### ISSUE TITLE
[INFO] USAID Geospatial Strategy

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#377]
USAID の最初の Geospatial Strategy が出ています。2024-2028 をターゲットとするもののようです。
ワクワクしますね。

https://www.usaid.gov/geospatial-strategy

HOT や FieldPaper など、我々が親しんでいる技術も出てきています。

@Kenyat1989 @mapconcierge @yuiseki @k96mz

**Comment by hfu** [comment]
関連しては、JICAの2021年[Society5.0 時代における地理空間情報の整備と利活用に係る情報収集・確認調査報告書](https://openjicareport.jica.go.jp/pdf/12341905_01.pdf)があるかなと思いました。

**Comment by mapconcierge** [comment]
![IMG_1510](https://github.com/UNopenGIS/7/assets/416977/aaf1987e-2b0f-4bf3-b824-978e7b1578bf)

モバイルの重要性が高まっているように見えますね。

**Comment by hfu** [comment]
@mapconcierge ありがとうございます。**エンタープライズ**もキーワードであるように見えますね。エンタープライズということについて、改めて考えてみたいと思いました。

**Comment by hfu** [comment]
このストラテジーでも Community of Practice（実践のコミュニティ、実践共同体）が取り扱われていたので、別途 #388 も立てました。
