### ISSUE TITLE
能力構築の悩み（教えるサイド）

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#38]
特に JICA プロジェクトなどで、UNVT を教えた経験や苦労について話してみる。

## 思っていること
- 聳え立つ学習曲線
- ゴールとの関係では正しさを確信している
- しかしゴールとの距離は 6000km

**Comment by yuiseki** [comment]
「能力構築」という言葉の指すスキルの前提と具体的なゴールを自分はちゃんと把握していないのですが、
以前お伺いした雰囲気だと、以下のようないくつかの壁が考えられると感じました：

- *nixターミナル上での作業に充分に慣れていない
- インターネット、HTTP、Webをはじめとした通信の仕組みに充分に慣れていない
- デジタル地図データの扱いに充分に慣れていない
  - 特にベクトルタイルというデータ構造に慣れていない

このなかでも、上二つは、正直に言うとあまりにスコープが広すぎるので、前提として慣れていてほしいですが、
現実としては慣れていない方も多いということが悩みポイントなのかなと感じています。


私としては以下を提案してみたいです：

- *nixターミナル上での作業に関して、
  - 何度でも繰り返しの試行錯誤ができる状態にする
    - Docker、あるいはGitHub Codespacesなどにより、破壊しても使い捨て可能な開発環境を用意し、安全な砂場で失敗を繰り返す
  - 自分で自分を助けられる状態にする
    - *nixの設計思想について、概要をざっと理解する（それによってわからないことをググれるようにする）
      - ※具体的に良いカリキュラムは思いつきません。すみません
      - 『UNIXという考え方』という書籍はオススメですが、読むのに数時間掛かります
    - `man` , `whatis` , `tldr` など、コマンドについてざっくり知り、理解を深めるためのメタ的なコマンドを一番最初にセットアップし、使いこなせるようにする
- インターネット、Web、HTTPについての概論は先にざっと理解しておいた方がいい
  - ※具体的に良いカリキュラムは思いつきません。すみません
  - 『ネットワークはなぜつながるのか』や『Webを支える技術』という書籍はオススメですが、読むのに数時間掛かる上、日本語版しかありません
- デジタル地図データ、ベクトルタイルに慣れる
  - これは、このプロジェクトが最もフォーカスするべき点だと思います
  - この点に関しては、私が以前参加した、総務省主催の「Geospatial Hackers Program」のカリキュラムが非常によくできていた記憶があります。いまでも、そのときに教えていただいた知識が役に立っています
    - 参考リンク： https://prtimes.jp/main/html/rd/p/000000013.000035440.html
  - 古橋先生 @mapconcierge は当時の「Geospatial Hackers Program」の講師のお一人で、私も色々と教えていただきましたし、また、学生を指導する教員でもあるので、知見（あるいは同じような悩み？）をお持ちなのではないかと思いますが、いかがでしょうか

**Comment by smellman** [comment]
* 『UNIXという考え方』という書籍はオススメですが、読むのに数時間掛かります
    * これは断然に同意。時間がかかるが、でもUNIXという考え方がないと厳しいというのは毎回JICAの講義で言ってる。
    * とにかくUNIXを学べというのがJICAでのスタンスだけど、5時間程度でそれをちゃんとやるのは厳しい。
* インターネット、Web、HTTPについての概論は先にざっと理解しておいた方がいい 
    * JICAの講義では前提にしている。GETリクエストが何なのか、REST APIが何なのかは必要なところだけは講義に含めている。
*  デジタル地図データ、ベクトルタイルに慣れる 
    * そろそろJICAの講義でラスタータイルの扱いをやめたいところ。
    * ラスタタイルが役立つ部分としてhillshideなどがあるが、何処まで役に立つかという点では分かりづらい。
    * UNIXにフォーカスをする点ではgdalを扱えれば良いだけなので、補足情報ぐらいでも良さそうな気がしてる。
    * そもそもQGISを扱うの自体に問題は無いか。
        * QGISはgdal/ogrのフロントエンドと捉えたら必要なコマンドは導出出来る。では導出するためのテクニックだけ学べば良いのでは。
 
ちょいずらずらとならべましたが、とりあえず悩んでることをならべました。

**Comment by hfu** [comment]
私も少し考えてみました。

- 実世界において「UNIX, Web, Tile」ということの理解が浅いことによって低いレベルの実現に陥っているプロジェクトが多いことは技術的事実。
- 他方で、「なぜ Windows Server で運営してはだめなのか。その方が運用者に優しいのは明らかではないか。」「コマンドラインでは直感的ではない。デスクトップ GIS で取り扱えるのが最小限の前提であろう。」といった理論がまかり通る文化圏に対して、「まずは UNIX とウェブだ。それが分かればなぜタイルなのかは自明だ。」といった金言を提供しても、理解されることは少ない。
- 課題は、**知識の体系化**にもあるが、**パターンの形式知化**を進める、ということも課題にできるかもしれない。つまり**何をするのか**ではなく、**どうするのか**ということを記述してみるということである。
- **クラウド**は、UNIX とウェブに内包されている、というか UNIX のウェブ対応みたいなところがあるんですよね。オブジェクトストレージを使う、ということは、多分 UNIX とウェブの合作で生まれた知恵なのだな、と思います。（もちろん、ハードウェアに近い低レイヤの知識があれば、さらにビジネスモデルへの配慮をもてば、なぜオブジェクトストレージなのか、ということについてはより深く理解できるのだろうとは思います。）

いい感じに問題が耕せていると思います。

ということで、私が「UNIX、ウェブ、タイル 〜時を超えたウェブ地図の原則〜」という本を書けばいい、ということなのだなと思います。（解説：冗談ですよ。）

## UNIX、ウェブ、タイル 〜時を超えたウェブ地図の原則〜

1. スケールを活用すること
2. 敷き詰めること、あるいは、敷き詰めないこと
3. 時間を味方にすること
4. リソースとサービスの二重構造で考えること
5. 縦割りを打破すること〜相互運用性

**Comment by hfu** [comment]
「UNIXという考え方」を読んでいない私が、オーム社さんが提供している9定理の記述だけを頼りに、Scrapbox で思考を耕してみる試みを開始してみました :-)

https://scrapbox.io/unopengis7/UNIX%E3%81%A8%E3%81%84%E3%81%86%E8%80%83%E3%81%88%E6%96%B9::9%E3%81%A4%E3%81%AE%E5%AE%9A%E7%90%86

**Comment by hfu** [comment]
UNIX 関連で #55 をスピンアウト

**Comment by ubukawa** [comment]
1. なるほどなるほど、と拝読させていただきました。ありがとうございます。

1. 相手がウェブ地図のプロを目指している職員なのか、あるいは自国に帰って管理職（実務を担当しない）になるのかによっても目指す内容が変わってくるのかもしれないと思いました。

1. 例えばJICA研修であれば、参加者の一番の関心は、自分たちの持っているデータをベクトルタイルにして、ウェブ地図として提供するというところでしょうから、スタート地点としての数時間の講義であれば、小規模のデータを変換してスタイル付けをするというくらいの内容から始める今の形はよいのではないかと思います。

1. 能力構築に、DockerやGithubなど、便利に使えるツールを活用されている点は素晴らしいと思います。

1. 私自身も、ベクトルタイルを作る、スタイルを編集する、ホスティングを試す、という経験を通じて、Linuxのコマンドやjavascriptをなんとなく使える（？）ようになってきました。 @smellman さんのJICA講義資料にも大変助けていただきましたし、あの内容は必要な人にとって素晴らしいものだと思います。OJTという感じで進めると、取り組みのモチベーションをキープしつつ段階的に理解を深めていけるのではないかと思います。

1. と感想ばかりで恐縮ですが、私自身はまだレベルが低いので、もう少しUNIXやウェブについて勉強が必要だなと実感しました。私の業務環境の観点では、将来に向けてはクラウド（特にAzure）でのサーバー管理なども含めてウェブ技術が求められるのかもしれないと思っています。

1. 最後に、オープンＧＩＳの取り組みということでもあるので、自分で試したことや同僚に伝えたことはなるべくオープンに発信しようと心がけています。ＱＩＩＴＡのカレンダーなど、よい機会だったと思います。ありがとうございました。

**Comment by hfu** [comment]
基本的には、これがスマート地図伝習所につながっています。いずれ、サブスタンスも回収していこうと思います。

**Comment by hfu** [comment]
いったんクローズ。
