### ISSUE TITLE
[READING] 世界を変えるはずだった 「デザイン思考」とは 何だったのか？（MIT Tech Review）

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#380]
## Source

- https://www.technologyreview.jp/s/299075/design-thinking-was-supposed-to-fix-the-world-where-did-it-go-wrong/

## Points

- 「デザイン思考はまた、「デザイン」の概念そのものを広げ、デザイナーを単なる空間や実際の製品、あるいは画面上の体験を生み出すだけの存在から、システムを再構築し、システムを使う人々の欲求を満たすことのできる、一種の霊媒師のような存在にまで昇華させた。」
- 「こうしてデザイナーは、付箋で埋め尽くされた6段階からなるイノベーション手法の最初の段階でもある、ユーザーの悩みに共感することで、あらゆる難問に挑めるようになった。」
- 「これは、デザイン思考をビジネス界に売り込むための巧妙な戦略だった。企業自身がデザインに特化した専門チームを雇用するのではなく、一時的にコンサルティング企業を雇い、デザイン思考の方法論を学べるからだ。」
- 「しかし近年、さまざまな理由から、デザイン思考の輝きは失われつつある。」
- 「時を経るにつれ、意味のある変革を実現することなく一連の項目にチェックを入れるだけの「イノベーション劇場」が企業内で常態化し、事例研究で取り上げられたさまざまな社会的インパクトのある取り組みが、試験プロジェクトの枠を超えられずに苦戦している。」

**Comment by yuiseki** [comment]
[私の考え]
- 「デザイン思考」は、この世界に無数にあるプロダクト設計戦略のひとつにすぎない
- 一世を風靡した戦略ではあるが、決して銀の弾丸ではないので、期待しすぎないほうがよい
- 自分がバキバキにコーディングしたりバキバキにハンダ付けしたりできない人が良く言ってるのを目にする印象である
- ハッカー思考とデザイン思考は相反する面があり、そのバランスが重要である
- 「ユーザーのニーズを観察して深く理解しましょうよ」「私ならそんな時間があれば100個のプロトタイプを作り上げて市場に投入してよりリアルなユーザーの反応を知ることができる」

**Comment by hfu** [comment]
ありがとうございます。オブジェクト指向やオブジェクト指向スクリプト言語や統一モデリング言語やWeb 3.0、Web3等と似て、規模の大きなハイプサイクルに乗ってしまうと毀誉褒貶があるということなのだなと理解しました。技術者それぞれの目的や特性に即して、使える者は使い、使う必要のないものには惑わされず、バランスを大切に、ということなのだなと思いました。本件はクローズします。
