### ISSUE TITLE
2024-06-16/21: 👥Understanding Risk Global Forum@Himeji City

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#381]
https://understandrisk.org/ur24/

I have heard that our sibring WG - OpenDroneMap - will be presenting if I remember correctly.

**Comment by hfu** [comment]
FYI: @mapconcierge will be joining OpenDroneMap meetup there with Stephen!

**Comment by hfu** [comment]
UN Smart Maps Group has not interactied with this event. Closing.

**Comment by mapconcierge** [comment]
We have done!
https://speakerdeck.com/fullfull/opendronemap-global-meet-up-ur24

<img width="952" alt="スクリーンショット 2024-06-30 17 42 21" src="https://github.com/UNopenGIS/7/assets/416977/857a50cb-ec71-4c74-8c5d-524d6d02faa3">
<img width="947" alt="スクリーンショット 2024-06-30 17 42 15" src="https://github.com/UNopenGIS/7/assets/416977/0a3e92d8-b6d7-4383-b209-90fb62d51be1">

**Comment by hfu** [comment]
@mapconcierge Thank you for sharing!

**Comment by hfu** [comment]
@yuiseki Maybe we can import "Sample Mosaic XYZ tile" https://apps.kontur.io/raster-tiler/oam/mosaic/{z}/{x}/{y}.png into FOIL4G. 

Example image: https://apps.kontur.io/raster-tiler/oam/mosaic/10/908/403.png

![example](https://apps.kontur.io/raster-tiler/oam/mosaic/10/908/403.png)
