### ISSUE TITLE
2024-04-24/26: 👥7th Annual International Humanitarian Mapathon 2024

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#385]
As @albertkun has mentioned, there may be 7th Annual Humanitarian Mapathon in April. 

We can check https://mapathon.la/ for updates.

**Comment by hfu** [comment]
Inputs from @albertkun via #371: 
- It is **7th Annual Interntional Humanitarian Mapathon 2024**
- Start time 2024-04-26 @ 9pm EST.
- Smart Maps members are invited as Judges. 
- ... (I will update)

**Comment by yohman** [comment]
![mapathon3day](https://github.com/UNopenGIS/7/assets/825990/936c9aa6-52c5-40ba-83d7-106a09b4a6e3)
Here's a draft of the three day agenda for the 2024 Humanitarian Mapathon. 

@hfu, Albert has mentioned that your team will be our judges! Thank you, we are so delighted! We are also hoping that the UN Smartmaps team can provide a data package for Day 2, the Crisis Map Challenge. This will be a hackathon, where all the participants from different regions of the world (Japan, USA, Mexico, Philippines) would receive the **same** package, and will be asked to produce maps to be judged by your team.

Perhaps then, you can think of a data package for a "real" project area? Happy to discuss and hear your thoughts.

**Comment by hfu** [comment]
@yohman, thanks for sharing your great idea. Although my schedule is not to be confirmed until April, I am sure several from UN Smart Maps Groups will be there to serve as judges. 

In the Crisis Map Challenge of Day 2, are we, participants, going to do OpenStreetMap mapping probably on HOT Tasking Manager? In that case, I think that the data package should be some reference imagery on which participants can digitize bulidings or roads. 

Another possibility is that we share vector data as data package and participants are supposed to enjoy DIY web map development. This way is more like our Smart Maps activities, but technical difficulty will be more high...

I agree it would be great to work on "real" data package. Maybe we can find good open data from OCHA HDX, GSI, or others. 

Here is a list of our GitHub issues possibly related with the idea. 

- #359 
- #358 
- #353 
- #339 
- #295
- #403

**Comment by hfu** [comment]
As far as I understand, @mapconcierge from Crisis Mappers Japan continuously providing HOT Tasking Manager tasks based on images from GSI. This would be one way to work on "real" data. 

## Crisis Mappers Japan on HOT Tasking Manager
https://tasks.hotosm.org/organisations/crisis-mappers-japan

**Comment by hfu** [comment]
We of course have UN Mappers in HOT Tasking Manager! 

## UN Mappers on HOT Tasking Manager
https://tasks.hotosm.org/organisations/un-mappers

**Comment by hfu** [comment]
I am also very interested in YouthMappers! 

## YouthMappers on HOT Tasking Manager
https://tasks.hotosm.org/organisations/youthmappers

... anything else we should be checking out?

**Comment by yohman** [comment]
Thank you @hfu for great thoughts! Day 1 is dedicated to HOTOSM mapping, and we will use the task manager for that. Participants will be trained to digitize buildings on HOTOSM. Day 2 is the other possibility you mention, a DIY map day. What we want to do, given that many regions will be joining this mapathon, is to provide everybody with the _same_ data package. This makes it a "friendly" competition, to see which groups can produce meaningful maps.

Many users will be introduced to GIS for the very first time, so hopefully we can put together a data package for a specific region. An example would be a region in crisis, data layers for crisis boundaries, danger zones, IDP camps, locations of food/water and other resources, medical facilities, and perhaps "action" layers, like migration and/or troop movements. I know that @mapconcierge has worked extensively in the Ukraine, so would a Ukraine package be possible? Any other ideas?

**Comment by hfu** [comment]
@yohman Thank you for clarification. What kind of GIS are we going to introduce to the participants? The background of this question is that it would affect the design of the data package. As for me I am a command-line geospatial data user and not so used to desktop GIS. 

MapAction has a concept of Integrated Humanitarian Data Package (IHDP) and they provide a pilot package at https://maps.mapaction.org/dataset/south-sudan-pilot-integrated-humanitarian-data-package.

**Comment by hfu** [comment]
Another thing to discuss is about the scale of the data package. Small scale, such as 1 to 1 million, is not very suitable for humanitarian mapping. Small scale mapping is rather political mapping. Do we want to work on large scale data package, in such as 1:5000 which is similar to the standard scale of the OpenStreetMap mapping?

**Comment by hfu** [comment]
## GIS - How about interactive visualization using Observable?
My favorite "GIS" is of course MapLibre! I suggest using Observable for interactive visualization. 

Here is very basic map view using OSMFJ PMTiles (maintained by @smellman!): https://observablehq.com/d/31ac74262c101181

**Comment by yohman** [comment]
@hfu Wow, great resources! I especially like the Sudan data package. Maybe this can be the one we use. I'll find some time to download it and check it out.

I also don't use desktop GIS! Mostly python and javascript. I have followed Mike Bostock for quite some time (D3 creator) so have heard of observable, but never really used it. Please teach me!

For this mapathon though, there needs to be a "no coding required" option. The focus may be on designing simple, compelling maps, using available tools like Google Earth and Kepler. That can be an entry point for many users. Advanced users can of course choose tools of their choice (ArcGIS, QGIS, Python, javascript, etc), but I believe that given the audience, this will be a small minority. Overall, I want to encourage complete beginners (ie, never coded before) to join the session. For this reason, I like the Sudan package, which appears to be data that has already been cleaned up and ready to go. This is ideal!

And yes, I agree with the scale. Let's work on a regional scale that vibes with Open Street Map standards👍🏼.

**Comment by yohman** [comment]
@hfu I just had a look at the Sudan data. It premises the use of ArcGIS of QGIS, as the data package is presented in file formats for immediate desktop GIS use. Thus I wonder if this may not be the right data for our mapathon. Any other ideas? Maybe @mapconcierge Taichi, do you have any data package ideas?

**Comment by hfu** [comment]
OK. Let's discuss the session standard tools first so that we can explorer data package options based on the choice of tools. 

### kepler.gl
Kepler looks promising but I haven't used it yet. 
https://kepler.gl/

### geojson.io
Do we think https://geojson.io/ is a tool for the session, too? 

### play.placemark.io
https://play.placemark.io/

**Comment by hfu** [comment]
How about this? If it is OK, I am interested in preparing along this line. 

1. We use FSQ Studio as a "next generation GIS".
2. We use some simple data from OCHA HDX.
3. We develop an example on FSQ Studio and create a document on HackMD.

**Comment by hfu** [comment]
I created https://github.com/UNopenGIS/7/discussions/417 to capture my idea.

**Comment by albertkun** [comment]
@hfu sorry you couldnt make the event, but it went well! I prepared these slides:

https://hackmd.io/@smartmaps/unsmartmapawards2024

I was asked by @yohman to see if we could create certificates for each of the winners of the awards:

![image](https://github.com/UNopenGIS/7/assets/8574425/85f1548b-54f2-48d0-ae3e-f52e2d0f2f5e)

I think it'd be great if we can get Diego, Timur, or you to sign them! Let me know what you think is possible! Thank you!

**Comment by hfu** [comment]
Thank you, @albertkun. I am happy to work on the idea of certificates. Can we create a draft? Depending on the contents of the certificate, I believe that some of us can sign. 

Again, thank you very much to everyone who made this event happen. I respect all your positive efforts.

**Comment by albertkun** [comment]
@hfu thank you for the reply and supporting the idea!

@yohman what did you have in mind for the certificate format?

**Comment by yohman** [comment]
@hfu @albertkun Thanks! I'll get started on the certificate. First, permission to use the UN SmartMaps logo (https://unopengis.github.io/smartmaps/about/brand), and also, if so, is it possible to get the logo with a transparent background?

**Comment by yohman** [comment]
<img width="935" alt="image" src="https://github.com/UNopenGIS/7/assets/825990/583e9f1a-f867-4ca5-ab68-6926128f0447">
Here is a draft

**Comment by albertkun** [comment]
> @hfu @albertkun Thanks! I'll get started on the certificate. First, permission to use the UN SmartMaps logo (https://unopengis.github.io/smartmaps/about/brand), and also, if so, is it possible to get the logo with a transparent background?

Here is a transparent version of the logo:
![un-smart-maps-logo](https://github.com/UNopenGIS/7/assets/8574425/22b31dea-56fb-49b9-b6e5-7f1a81afa0c8)

**Comment by yohman** [comment]
@albertkun Thanks Alby! Any chance you can give me a higher resolution?

**Comment by hfu** [comment]
@yohman and @albertkun, thank you for your efforts for certificates. 

We discussed on this in #460. @k96mz and @hfu agrees on the draft certificate provided that my name and organization is updated as below. 

## before correction
Hidenori
JICA
United Nations

|
v

## after correction
Hidenori Fujimura
co-lead
UN Smart Maps Group

**Comment by albertkun** [comment]
> @albertkun Thanks Alby! Any chance you can give me a higher resolution?

Unfortunately, there is no higher resolution, sorry!

**Comment by yohman** [comment]
[the best map awards.pdf](https://github.com/UNopenGIS/7/files/15162095/the.best.map.awards.pdf)
Here are the awards. Please check for accuracies. 

If all is good, @hfu and Koji, can you sign them? Though I noticed that Koji is not in this group, can @albertkun forward to him?

Thanks!

**Comment by yohman** [comment]
Fixed by adding a space in Smart Maps
[the best map awards (1).pdf](https://github.com/UNopenGIS/7/files/15162695/the.best.map.awards.1.pdf)

**Comment by k96mz** [comment]
I pasted my sing to the file. If @yohman  has some problems, please let me know.
[the.best.map.awards.1.pdf](https://github.com/UNopenGIS/7/files/15168154/the.best.map.awards.1.pdf)

**Comment by hfu** [comment]
[the.best.map.awards.1.pdf](https://github.com/UNopenGIS/7/files/15177189/the.best.map.awards.1.pdf)

Added my signature, too! 

@yohman, please go ahead. 

Thanks, @albertkun, @k96mz and @yohman.

**Comment by hfu** [comment]
We will be closing this issue once the cetificates are disseminated.
