### ISSUE TITLE
Link presentations of 2024-02-20 on the documentations site

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#398]
Yuiseki and I delivered presentations in #372. 

@albertkun and @asahina820, could we link these presentations below from the documentation site? 

- https://speakerdeck.com/hfu/smart-maps-and-bazaar
- https://speakerdeck.com/yuiseki/shi-jian-nokomiyuniteitositeno-un-smart-maps-group

**Comment by albertkun** [comment]
@hfu I added a deployment script (https://github.com/UNopenGIS/smartmaps/pull/88) that reads in the presentations.csv file here:

https://github.com/UNopenGIS/smartmaps/blob/main/presentations.csv

So as long as you update that CSV file (`presentations.csv`) the presentations should update using this script automatically when the website is being built:

https://github.com/UNopenGIS/smartmaps/blob/main/package.json

```
{
  "name": "smartmaps",
  "scripts": {
    "update-presentations": "node generate-presentations-index.js",
    "docusaurus": "docusaurus",
    "start": "docusaurus start",
    "build": "yarn update-presentations && docusaurus build",
}
```

It will show up in this table both in Japanese and English:

https://unopengis.github.io/smartmaps/resources/presentations

https://unopengis.github.io/smartmaps/ja/resources/presentations/

@asahina820 let me know if you'd like to make any changes to this script or the Japanese text:

- https://github.com/UNopenGIS/smartmaps/blob/main/generate-presentations-index.js

Thank you!

**Comment by hfu** [comment]
Thank you @albertkun for your kind guidance. 

Before linking the presentations in this issue, I linked the presentation for the UN Open GIS Monthly of 2024-02. 

I confirmed I can do it! 
https://unopengis.github.io/smartmaps/resources/presentations/

I will close this issue once I add the presentations of 2024-02-20 (and 2024-02-19).

**Comment by albertkun** [comment]
> Thank you @albertkun for your kind guidance. 
> 
> Before linking the presentations in this issue, I linked the presentation for the UN Open GIS Monthly of 2024-02. 
> 
> I confirmed I can do it! 
> https://unopengis.github.io/smartmaps/resources/presentations/
> 
> I will close this issue once I add the presentations of 2024-02-20 (and 2024-02-19).

Great! Glad to hear it worked! 🎉 Feel free to let me know if you have any questions about it!

**Comment by hfu** [comment]
I added two presentations on 2024-02-20. And it works! 
https://unopengis.github.io/smartmaps/resources/presentations/

**Comment by albertkun** [comment]
Nice! Thank you for confirming! :)

**Comment by hfu** [comment]
@albertkun I agree! The URL should be `href` of the title text.
