### ISSUE TITLE
Anatomy of Mapping における「explore / 探索する」は教育における「inquiry / 探究する」と同義なのか

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#400]
2020-02-20のイベントで気がつきました。

## @hfu のスライド
<img width="825" alt="image" src="https://github.com/UNopenGIS/7/assets/18297/4fbf6640-8011-4535-9884-f7ab63f9280f">

ここでいう「explore / 探索する」は教育における「探究する」と同義なのでしょうか。

c.f. [IBの学習者像](https://ibconsortium.mext.go.jp/wp-content/uploads/2019/04/IB%E5%AD%A6%E7%BF%92%E8%80%85%E5%83%8F.pdf)

**Comment by Kenyat1989** [comment]
私の仮説でしかないのですが、こういうことなのかなと思っております。

![探究と表現](https://github.com/UNopenGIS/7/assets/7357639/e977839f-4fac-4bd4-ae7a-517f37af6ce9)

**Comment by hfu** [comment]
[IB learner profile](https://www.ibo.org/contentassets/fd82f70643ef4086b7d3f292cc214962/learner-profile-en.pdf) での INQUIRERS の描写は次のとおりでした。

> We nurture our curiosity, developing skills for inquiry and
research. We know how to learn independently and with others.
We learn with enthusiasm and sustain our love of learning
throughout life.

ポイントは、次のようなところかなと思います。

- 単独で、そして他者と共に学ぶ方法を知っている。
- 情熱を持って学ぶ。
- 学習への情熱を持続する。

**Comment by hfu** [comment]
inquiry-based learning について調べてみました。

## Inquiry-based learning 探究型学習

### 基本的なステップ
- orientation
- conceptualization
  - questioning
  - hypothesis generation
- investigation
  - exploration and experimentation
    - planning and observation
  - data interpretation
    - analysis
- conclusion
- discussion
  - communication
  - reflection

### 探究型学習の型
- structure inquiry
- controlled inquiry
- guided inquiry
- free inquiry

**Comment by hfu** [comment]
概ね、https://github.com/unvt/portable/discussions/28 で回収できてきましたので、本件はクローズします。引き続き、**ウェブ地図 x 探究型学習** というテーマについては UN Smart Maps Group が携わるべき範囲内と思って進めていくつもりです。
