### ISSUE TITLE
UNVT Portable の技術要件を聞いてみてどう？

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#41]
https://github.com/UNopenGIS/7/issues/29 では UNVT Portable の技術要件をざっくばらんに共有しました。
共有された技術要件を踏まえての分析やコメントを yuiseki さん中心に聞いてみたいと思っています。

- ユースケースが複数あるということが分かった
- ひとつのプロダクトを作るというよりは、ツールキットとノウハウという感じになるのかも

**Comment by hfu** [comment]
本件については、さらに深めるべきか、とりあえず close するか、考えると良いと思います。

**Comment by yuiseki** [comment]
私なりにユースケースを整理した文章を書いてみます。認識が間違っている点などあったらご指摘ください。

- 災害時の自治体での利用
  - 災害によってインターネットへ繋がる通信網が断絶された状況で、
  - 災害対応のための様々な地理空間情報を集約し、配信・表示できるようにするために、
  - Raspberry Piを仮設的なサーバー兼アクセスポイントとして立ち上げている。
  - タイルの構築は、より高速なPCとより高速なプロプライエタリ・ソフトウェアでやっている。
  - タイルは複数種類あり、必要に応じて随時追加、更新される。
  - 最も重要となるのは、様々なタイルの格納形式の共通化？
- プライベートクラウドとしての利用
  - パブリッククラウドを使うことが難しい事情がある状況で、
  - 様々なソフトウェアの試験や実験のために、
  - Raspberry Piで必要な時に必要なだけのサーバーを立ち上げている。
  - 最も重要となるのは、セットアップの容易さ？
- JICAでの教育ツールとしての利用
  - 経済的にクラウドの導入が難しく、また、通信や電力が不安定な地域もある状況で、
  - そうした地域の人々がタイル地図を最大限活用できるようになってもらうために、
  - Raspberry Piを使って、自分自身でタイル地図を構築し、カスタマイズし、運用するノウハウを伝授したい。
  - 最も重要となるのは、capacity building？
- 国連フィールドミッションでの利用（検討段階）
  - これも通信や電力が不安定な地域もある状況で、
  - 活動の現場にデジタル地図を持ち出せるようにするために、
  - Raspberry Piを持ち運び可能なサーバー兼アクセスポイントにする可能性を検討している。
  - この場合も、タイルの構築は、高速なPCでやったほうが速いだろう。
  - タイルは複数種類あり、特に基本地物は、毎日更新される。
  - 最も重要なのは、現場での信頼性？

こうして整理してみると、4つのユースケースで重なってくる点もあるのではないかと感じています。

- セットアップの容易さを高め、維持しつづけることは、どのユースケースであってもありがたいはず
- セットアップ時にはインターネットが必要なのは仕方ないとして、運用時は可能な限りスタンドアロンで動作させたい
- 実際には、一種類ではなく、複数種類のタイルを扱うことのほうが多い。そのため、様々なタイルの格納形式は、共通化できると良さそう
- また、実際には、他のPCで構築したタイルを転送することのほうが多い。そのため、ファイル転送UIなどがあると良いかもしれない

**Comment by hfu** [comment]
本件、 #43 で取り扱ってみたいと思います。

技術の分析に入ってしまうと話がズレるかもしれませんが、タイルのストレージへの保存に関連して、タイルは PMTiles で出していく方向を伸ばしていければと思います。そうすると、タイルの格納形式の共通化やファイル転送などについてかなり簡単になってくるのではないかと思っています。

**Comment by hfu** [comment]
もしかすると、こういった構造があるかもしれないと思いました。

![image](https://user-images.githubusercontent.com/18297/208218299-5af4668a-be16-4891-add6-d6f189fa8872.png)

**Comment by hfu** [comment]
さらに言えば、こうかもしれません。自家用クラウドの先には**本番環境**があります。自家用クラウドで満足できる場合もあるかもしれないが、自家用クラウドは必ずしも目的地ではない。

![image](https://user-images.githubusercontent.com/18297/208218425-effd3c32-603a-44cd-9f50-4c2cc4bee78c.png)

**Comment by hfu** [comment]
**資源が限られた環境対応**は、オフライン志向では**目的**の一部ですが、オンライン志向では**手段**になります。
手段であろうが目的であろうが、対応できていると幅が広がる、という形になっているのだと思います。

**Comment by yuiseki** [comment]
私の現在の考えとアプローチを共有します

- 現在作業中のリポジトリ
  - https://github.com/yuiseki/unvt-pi-gen

### 考え

- Raspberry Piのセットアップを超爆速にしたい
  - 特定用途に特化した、設定済みのRaspberry Pi OSのイメージを、簡単に構築できるようにする
    - タイル地図のホスティングに特化するもよし
    - プライベートクラウドに特化するもよし
  - 用意されたOSイメージを、microSDカードに書き込んで、Raspberry Piの電源を入れるだけでよくする


### アプローチ

- Raspberry Pi開発チームが公式で公開している `pi-gen` を使う
  - https://github.com/RPi-Distro/pi-gen
- `pi-gen` を実行するための依存関係をすべて含んだDockerfileを用意する
- 上記のDockerfileからDockerイメージをビルドして、 `pi-gen` を実行するMakefileを用意する
- `.env` を編集して `make` を実行したら、カスタマイズ＆セットアップされたRaspberry Pi OSのイメージができあがる

**Comment by yuiseki** [comment]
`pi-gen` によるRaspberry Pi OSのカスタマイズ方法が把握できてきました。

`pi-gen` は非常に面白くて、

- Linuxのrootfsを、Dockerのレイヤーのように複数のステージに分けて構築できる
- 各ステージで任意のaptパッケージインストールやシェルスクリプトの実行ができるが、それらの結果はDockerのRUNと同様に、冪等なrootfsになる

ということを、シェルスクリプトのみで実現しています。

Dockerほどシンプルではありませんが、OSの構成を、コードで宣言的に記述できるようになっています。

[yuiseki/unvt-pi-gen](https://github.com/yuiseki/unvt-pi-gen) では、ひとまず以下を実現しようとしています。。

- [ ] 初期ユーザーとパスワードとホスト名とSSHと上流Wi-Fiを事前にカスタマイズ・セットアップ
- [ ] `unvt/equinox` と `unvt/nanban` を参考に、定番のaptパッケージを事前にインストール
- [ ] Dockerを事前にインストール・セットアップ
- [ ] Nginxを事前にインストール
- [ ] Node.jsを事前にインストール
- [ ] Raspberry Pi ImagerでmicroSDに書き込んでRaspberry Piに挿入して起動するだけで上記が動くことの動作確認

Sambaもインストール・セットアップしようとしてみたのですが、設定がややこしい割にはあまり便利でもないので、scpで良い気がしてきました。

Raspberry PiのカスタムOSが作れるとしたら、こんなものがほしい！という要望があったら教えていただきたいです。

**Comment by yuiseki** [comment]
`unvt-pi-gen` でカスタムRaspberry Pi OSイメージを構築する際に、上記全てに加えて、 `unvt-pi-gen` そのものも事前にセットアップしておいて、すぐに使える状態にできました。
つまり、、カスタムRaspberry Pi OS上で、新たなカスタムRaspberry Pi OSイメージを作れます。

**Comment by hfu** [comment]
こちらもいったんクローズ。
また議論する時にはためらわずリオープンしましょう。
