### ISSUE TITLE
💡[INFO] The Open Source AI Definition - HackMD

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#412]
- https://hackmd.io/@opensourceinitiative/osaid-0-0-5

- https://opensource.org/blog/open-source-ai-establishing-a-common-ground
  - Open Source AI: Establishing a common ground

**Comment by hfu** [comment]
情報ありがとうございます！OSIっぽいクレバーでまずまずタイムリーな動きと思いました。GNUから引っ張ってきているというのも今っぽいのかなと私は思います。
引き続きウォッチし、取り込める考えは取り込んでいくという感じでしょうか。ご一緒に見て行ければと思います。

**Comment by yuiseki** [comment]
この文書は「人類にとってフリーダムなAIシステム」を定義しようとしています。
自律的なAIシステムの可能性を過剰に大きく見積もった場合、「AIシステムにとってのフリーダム」について考えることになるだろうという思考実験が頭をよぎりました。

あえて書き残しておきたいのですが、
基本的人権という概念は、いずれ更新を迫られるでしょう。
基本的人権を前提としている国連憲章や世界人権宣言も、いずれ更新を迫られるでしょう。

自律的なAIシステムが台頭すれば、ジャン＝ジャック・ルソーやイマヌエル・カントのような革新的な思想家や、それに強く影響を受けた、フランス革命、アメリカ独立宣言、世界人権宣言、そして国連の、2.0が、いずれ発生するだろうというのが私の考えです。

（いま進んでいる UN 2.0 は、基本的人権という根底は全く変更していないので、後方互換性があるため、[セマンティック・バージョニング](https://semver.org/lang/ja/)に則ったら、せいぜい UN 1.5 とか表現するのが適切なんじゃないかとも思っています）
- https://www.un.org/two-zero/en
- https://un-two-zero.network/

**Comment by yuiseki** [comment]
情報共有の目的は達成できたと思うので閉じます
