### ISSUE TITLE
`ollama` and `continue`: Free and Without-Internet alternative of GitHub Copilot!

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#415]
## Information

- https://github.com/ollama/ollama
  - Basically, It is a wrapper for llama.cpp
  - It keeps llama.cpp server running in the background as a service of the system
  - In addition, multiple LLMs can be switched to perform inference without stopping the server
  - ollama manages LLMs in repositories with a Docker-like concept, so that models can be handled simply by pulling them
- https://github.com/continuedev/continue
  - VSCode Extension, Free and Without-Internet alternative of GitHub Copilot
  - Smooth integration with ollama

## Message

- **I have confirmed that ollama works perfectly fine on my Raspberry Pi**
- This means that it is possible to provide coding assistance with LLMs at extremely low cost and without Internet connectivity

**Comment by hfu** [comment]
ollama すごいですね！私の手元の Raspberry Pi 4B 8GB でもゆっくりとですが動きました。

<img width="737" alt="image" src="https://github.com/UNopenGIS/7/assets/18297/65705d6d-02dd-4fb9-9555-8eab01e17158">

**Comment by yuiseki** [comment]
情報共有の役目は果たせたと思うので閉じます 🚀
