### ISSUE TITLE
UN EC Hackathon の成果として UN Open GIS Monthly で報告する

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#42]
ベスト8に Smart Maps にご縁のある皆様が2組、という快挙になったので、報告してみたいです。

@naogify と @ibuki76 のインプットをいただけると嬉しいと思っているところです。

（お詫び）メンションでミスしました。修正しましたすみません。

**Comment by naogify** [comment]
@hfu
言及ありがとうございます! 是非お願いできればと思います。
インプットはどのような形式が良いでしょうか? テキストでお送りする？等教えて頂けると嬉しいです。

**Comment by ibuki76** [comment]
@hfu 
ありがとうございます。ぜひよろしくお願いします！

**Comment by yuiseki** [comment]
関連？：
- https://github.com/furuhashilab/README/issues/33#issuecomment-1281762516

**Comment by hfu** [comment]
ありがとうございます。本件、 #34 でも少し議論しました。月例ミーティングについては、概ね次の戦略で対応しようと思っています。

1. 月例ミーティングは比較的長時間にわたる会議になっているので、本件に関する報告自体はスライド1, 2枚程度のシンプルなものにする。DWG7 Smart Maps の立場から、 @naogify と @ibuki76 が発表したという事実を紹介する。

実際の月例ミーティングまであと一週間程度の時間があるようです。スライドの案を作ってこちらで共有するということでどうでしょうか。特段のご希望がなければ、私からまとめてお話しさせていただこうと思っています。

**Comment by naogify** [comment]
@hfu ありがとうございます。どうぞよろしくお願いします！

**Comment by ibuki76** [comment]
@hfu かしこまりました。よろしくお願いいたします！

**Comment by ubukawa** [comment]
（DWG7からハッカソンの報告をすることをオム課長に話しておきました。OKということでした！
WGレポートの中で触れると説明してあります。次回は21日（水）ですが、MS Teams のリンクが来ていなければお知らせください。）

**Comment by ubukawa** [comment]
お世話になります。
DWG7に参加されている方どなたでも大丈夫ですが、もし21日（水）のUN Open GIS Monthly meetingの参加希望があればMS Teamsに招待するのでお知らせください。

お名前、所属（個人的な専門性で参加されるというのでもOKです）、MS Teamsに招待してよいメールアドレスを taro.ubukawa@un.org まで送ってください。お願いします！　（特に、@yuiseki さん、先日希望をお聞きしていたのでフォローアップさせてください。）

毎月の定例会は進捗報告などが多いので、毎回参加する必要はないですし、気軽な感じでOKです。よろしくお願いします。

**Comment by hfu** [comment]
@naogify, @ibuki76 すみません、結局スライドの事前照会をせずにシンプルな紹介のみにしてしまいましたが、お二人の活躍を伝えることができ、オム課長ほか皆様から高い評価を得ているのが確認できてよかったです。

実施完了ということで、イシューとしてはクローズとさせてください。引き続きよろしくお願いします。

**Comment by naogify** [comment]
@hfu 
紹介の時間とって頂きありがとうございました！
MTGにも参加させて頂き光栄です。引き続きどうぞよろしくお願いします。

**Comment by ibuki76** [comment]
@hfu @ubukawa ありがとうございました！
