### ISSUE TITLE
🤖`infinite-tinyllama`: You can create an infinite number of TinyLlamas by just writing YAML files

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#424]
- https://github.com/yuiseki/infinite-tinyllama

**Comment by yuiseki** [comment]
ToDo:
- [ ] 日本語のデータセットを叩き込んだらちゃんと日本語が喋れるようになるのか検証
- [ ] TinyLlama自身が半自律的あるいは完全自律的に新しいTinyLlamaを生成するためのYAMLファイルを出力できるようにする
  - 無量TinyLlama
- [ ] https://github.com/UNopenGIS/7/issues/258 の再挑戦
  - [ ] https://huggingface.co/datasets/allenai/c4

**Comment by hfu** [comment]
@yuiseki ありがとうございます。これは、Smart Maps の他のアクティビティとの相乗効果も高そうで素晴らしいですね。私もフォローしたいので、 priority/SHOULD に整理させていただきました。

**Comment by hfu** [comment]
@takano32 のアドバイスに沿って、 #258 を Discussion に変換してみました。

LLMs 支援による多言語対応、チャレンジングだとは思いますが、test new technologies がミッションである国連スマート地図グループとして、できる限り盛り上げてみたいと思います。

**Comment by yuiseki** [comment]
infinite-tinyllamaリポジトリは無事に100以上のTinyLlamaを産み出したのでIssueとしては閉じます
