### ISSUE TITLE
2024-03-20T22:00/23:30+09:00: UN Open GIS meeting (monthly)

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#430]
As received from Timur: 

Dear Members of UN Open GIS,

The meeting will take place on Wednesday, 20 March 2024 at 9:00am (New York time) 2:00 PM (Rome time).

The tentative agenda is as follows: 
 
1. Opening by Co-Chairs (Ki-Joune Li, Maria Brovelli and Joseph Parareda)
2. Introduction of new members
3. Open Q&As and discussions
4. Working Group report
. DWG-1 Hybrid GIS platform (Timur, Zeeshan, Epa/Rodwell, Akbar, #Cung);
  - Integration of Azure AD with GeoServer/GeoNode (Timur, Eddy)
  - Mobile GIS Solutions, including integration with Azure AD (Epa/Rodwell, Zeeshan, Cung)
- UNMISS Story Map (Zahurul/Akbar/Debasish, Timur, Eddy):
. DWG-2 Capacity Building (Ivan, Susan, Diego);
. DWG-5 Geo-AI & Analytics (Zhongxin, Maria, Andrea, #Cung)
. DWG-6 OpenDroneMap & 3D (Catalina, Davide, #Cung)
. **DWG-7 Smart Maps (Hidenori, Diego, #Timur)**
5. Any other business (AOB)

**Comment by hfu** [comment]
- I will be covering #385 in the report. What else? Please let me know if you have any idea. 
- I will be preparing the report on HackMD as always. I will share the link when ready.

**Comment by hfu** [comment]
Dear all, 

I created a [draft presetation](https://hackmd.io/@smartmaps/2024-03#/) ([editable page](https://hackmd.io/TAjOD_PFTHGNyBuR9atktA?both)). Any ideas or additions are welcomed. 

- Awaiting for further input about LLM from @yuiseki. 
- Do you have any additions? @albertkun, @yohman, @asahina820, @mapconcierge, @ShogoHirasawa, among others? 

Thanks, 
Hidenori @hfu

**Comment by yuiseki** [comment]
# 日本語Version

## AI (LLM) を国連のためにカスタマイズするチャンスです

---

### 国連で活用可能なAI、TinyLlamaを複数作成可能
- **目的**: 国連の厳しい情報統制基準に適合する、インターネット接続が不要で情報流出の懸念がない軽量LLM、TinyLlamaのカスタマイズ
- **方法**: 明日から10日間 (240時間) 、A5000 * 7 (VRAM 168GB)のGPU計算資源を無料で提供してくれるスポンサーが現れた
- **制限**: カスタマイズしたTinyLlamaは必ずオープンソースライセンスでリリースします

### 現在認識しているニーズ
- 感情分析、フェイクニュース検出、ヘイトスピーチ検出
- 低リソース言語への対応

### ご協力のお願い
- **更なるニーズの探求**
  - 国連スタッフの皆様から、上記のタスク以外にTinyLlamaを活用して解決したい具体的な課題やニーズがありましたら、教えてください。
- **フィードバックの方法**
  - 本日のミーティングで直接ご意見をお聞かせいただくか、後ほどメール等でのご連絡をお願いします。

### 目指すは、国連のミッションと業務を効果的にサポートするカスタマイズされたLLMの実現です。

**Comment by hfu** [comment]
いいですね！もしかすると、yuisekiさんに発言を譲る形で進めたほうが良いでしょうか？iPhoneから送信2024/03/19 20:53、yuiseki ***@***.***>のメール:﻿
日本語Version
AI (LLM) を国連のためにカスタマイズするチャンスです

国連で活用可能なAI、TinyLlamaを複数作成可能

目的: 国連の厳しい情報統制基準に適合する、インターネット接続が不要で情報流出の懸念がない軽量LLM、TinyLlamaのカスタマイズ
方法: 明日から10日間 (240時間) 、A5000 * 7 (VRAM 168GB)のGPU計算資源を無料で提供してくれるスポンサーが現れた
制限: カスタマイズしたTinyLlamaは必ずオープンソースライセンスでリリースします

現在認識しているニーズ

感情分析、フェイクニュース検出、ヘイトスピーチ検出
低リソース言語への対応

ご協力のお願い

更なるニーズの探求

国連スタッフの皆様から、上記のタスク以外にTinyLlamaを活用して解決したい具体的な課題やニーズがありましたら、教えてください。


フィードバックの方法

本日のミーティングで直接ご意見をお聞かせいただくか、後ほどメール等でのご連絡をお願いします。



目指すは、国連のミッションと業務を効果的にサポートするカスタマイズされたLLMの実現です。

**Comment by yuiseki** [comment]
@hfu 5分だけでも時間を頂ければ自分の言葉で話せそうです。スライドも準備できます！

**Comment by yuiseki** [comment]
スライドできました。3分で喋れます

https://hackmd.io/@yuiseki/ryoVAlv0a#/

**Comment by hfu** [comment]
@yuiseki ありがとうございます！では、繋いでいく感じで進めます。最初私がお話しして繋ぎますね。

**Comment by hfu** [comment]
@yuiseki ゆいせきさんにリレーするモデルで私のプレゼンも書き換えました！
https://hackmd.io/@smartmaps/2024-03#/

**Comment by hfu** [comment]
@yuiseki さんのおかげで、今回とても良いインプットができたので、このイシューで振り返りを書きましょう。

## 振り返り by @hfu 
- UNGIS の @k96mz という形が公式になりました。ベクトルタイル・プロジェクトを再開するということ以上に、UN Open GIS と UN Smart Maps Group のマネジメントにおいて、だんだんと @k96mz の存在感が増してくる感じになってくると素晴らしいと思っています。
- @asahina820 の参加も大変ありがたかったです。良い形でデビューしていただけたと感じています。いずれ、今回の @yuiseki さんのようにプレゼンしていただける機会ができると素晴らしいとも思いますし、 @asahina820 の存在は、Smart Maps Group の FOSS4G 2025 / OSGeo への参加を強化する意味でも重要だと改めて感じています。
- @yuiseki のインプットの破壊力が大変素晴らしかったです。UNGIS Chief の Josep の高い関心をいただくことができましたし、GeoAI の DWG-5 との接続関係ができそうになってきているのは、UN Smart Maps Group にとっては非常に光栄あるメリットだと思っています。ラジオやソーシャルメディアへの展開、特に通常の環境では手を出せないであろうラジオへの展開は、少なくとも潜在的には面白いと思いました。
- [マリのラジオ](https://en.wikipedia.org/wiki/Mass_media_in_Mali#Radio)というのは、私にとっては非常に新しい世界です。他方で、ラジオで放送されている情報をしっかり拾って分析をするということは、とても重要なことであるように感じます。（電波の話でもあり、ここでも Raspberry Pi が役立ちうるのかもしれないと思います。）
- 実は、 @albertkun と @asahina820 それから @yohman や Chloe のラインからは DWG-2 Capacity Building にもつながり得るのですが、DWG-2 は QGIS や GeoNode、GeoServer のようなプロダクトを対象にしていて、我々は MapLibre や PMTiles を対象にしているところが明確に違います。今後、相乗効果が得られるような形になれば、おそらく @k96mz による調整を通じて DWG-2 との連携関係を強めるということも考えうるところだと思います。
- DWG-6 がサイレントになった結果、現在「3D」が静かな状態です。私もしばらくは 3D をやる方向が少ないのですが、mago3D Tiler を活用するといった方向を通じて、UN Smart Maps Group から 3D を巻き返していくという方向も考えうるところだと思います。ここは、リソースとコンテキストとの見合いだと思います。やれることはあると思います。
- 全般に、我々 UN Smart Maps Group は、UN Open GIS Initiative の同僚たちの活動と「被っているようで、被っていない」傾向があると思っています。これは、我々グループは全体としてウェブに親和性が高く、他方でエンタープライズサイドでは直接的には打ち出していないということによるように思います。結果的に、UN Smart Maps Group は引き続きオープンな実践コミュニティとしてのインテグリティを保ちつつも、Group の外の同僚たちの活動に浸透していくことが可能であろうと思っています。
- 全体的に、今後の見通しにつながる、良い月例会議だったと私は思っています。

**Comment by hfu** [comment]
## Extension Wonderland
### Software Defined Radio (SDR)
Raspberry Pi でソフトウェアラジオ、という話を検索してみていました。普通に、できそうです。
Extension Wonderland というコンセプトの内側に入れられる気がしていて、たまにはコンセプト整理もしてみるものだと思いました。

https://jp.mathworks.com/help/comm/ug/fm-reception-with-rtl-sdr-radio-on-raspberry-pi-hardware.html

### Sense HAT
Extension Wonderland 繋がりでは、Sense HAT を手に入れました。セットアップが実質不要で、良い設計だと思います。

https://www.raspberrypi.com/products/sense-hat/

**Comment by hfu** [comment]
振り返ってみますと、プレゼンで使用した下図は、割とよくできているように感じています。しばらくこの図式で考えることができるような気がします。私の居場所も、皆さんと共創して行きたいところも、見渡しやすい気がします。

```mermaid
flowchart LR
  %%subgraph .
    osm((OpenStreetMap Ecosystem))
    rapid[Rapid Editor]
    fsq[FSQ Studio on the web]
    go[Observable on the web]
    rapid --> osm
  %%end
  
  %%subgraph .
    osmfj[OSMFJ PMTiles]
    t[Data Package]
  %%end
  
  osm --> osmfj
  osmfj --> go
  osmfj --> sl
  t --> sl
  t --> fsq
  t --> go
  go --> rapid
  
  %%subgraph .
    sl[Observable Framework on Raspberry Pi]
    ipfs[IPFS]
    llm[LLM]
    routing[Routing]
    dev[Devices]
    sl --- ipfs
    sl --- llm
    sl --- routing
    sl --- dev
  %%end
```

**Comment by asahina820** [comment]
@hfu @yuiseki 発表お疲れさまでした！たくさんフィードバックを頂けていて、素晴らしい発表でした。
定例会議はとても刺激的でした、私の英語力が低いのもあり十分に理解できませんでしたが、少しずつ慣れて、いずれは お二人のような素晴らしいプレゼンができるようになりたいです。頑張ります！

**Comment by hfu** [comment]
個人主義・学習重視という特徴が今のスマート地図グループにはあるように思っていて、ChatGPTに手伝ってもらって一つドラフトコンセプトを作ってみました（ブレストネタ）。

<img width="1099" alt="スクリーンショット 2024-03-20 23 48 30" src="https://github.com/UNopenGIS/7/assets/18297/dd72fd3a-e53f-4974-a65d-4126a2f138e4">

https://hackmd.io/@smartmaps/fopc#/

**Comment by k96mz** [comment]
### 振り返り by @k96mz 
会議お疲れ様でした！
- 会議後にUNGIS ChiefのJosepと話しましたが、UN Open GIS Initiativeは素晴らしい取組だという認識をお持ちです。ただ、それぞれのDWGの方向性が一つになっていないので、より一体感を持って出来ればさらに良いのではないかという問題意識を持っているようでした。
- @asahina820 Timurにあさひなさんが出席されることは事前に伝えていて、挨拶するかしないかはあさひなさん次第という話もしていたのですが、Timurが気を利かせて挨拶を振ってくれました。突然の事でしたが、対応ありがとうございました。
- @yuiseki yuisekiさんのプレゼンが素晴らしく会議出席者から高い関心が示されました。今後DWG5の会議にも参加されるかと思いますが、国連側の調整等が必要な場合などあれば、お気軽にご連絡ください。
- 私もUNGISのDiego Gonzarezに存在を知ってもらえて、UNVTのプロジェクト再開のきっかけになり良かったです。


### スマート地図グループのウェブページについて

Albert作成のスマート地図グループページ。

https://unopengis.github.io/smartmaps

UN Open GIS Initiative公式ページ

http://www.unopengis.org/unopengis/what/what05.php

各DWGから情報を集めることになっている同僚のロイに情報聞きました。

- サーバは韓国にあり、HaeKyong Kangが担当している。HaeKyong Kangが直接ウェブサイトを管理しているわけではなく、さらに誰かに頼んでいる。
- ロイはウェブサイトの一部の変更（テキスト追加、画像追加等）権限を持っているのみ。
- ロイ自身はウェブには詳しくはなく、勉強しながらやろうとしている。
- 2月くらいにHaeKyong Kang、ロイ、Timurで本件について打合せがあった。

スマート地図グループのウェブページに関して、以下のような方法があるかなと思っています。

- 「UN Open GIS Initiative公式ページ」に「Albert作成のスマート地図グループページ」のリンクを貼る

一番簡単です。

- 「Albert作成のスマート地図グループページ」から要素を抜き出して、「UN Open GIS Initiative公式ページ」を作成

できると思います。

- 「Albert作成のスマート地図グループページ」を「UN Open GIS Initiative公式ページ」に完全移行する。

出来るか不明です。出来たとしても、イベントの追加など迅速に更新できるか不明です。

この件については、またご相談させてください。

**Comment by hfu** [comment]
おつかれさまでした！
