### ISSUE TITLE
UN Open GIS Website update (Deadline: 2024-04-01)

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#435]
In following up #430 last night, Roy from UNGIS invited @hfu and @diegonfer to submit UN Smart Maps contents for updating the [UN Open GIS website](http://unopengis.org/unopengis/what/what05.php).

Roy said: 
> Dear Hidenori and dear Diego,
Good afternoon. Could you please send us the word document with updated content so we can update the Open GIS Website. It is appreciated if you could send us the information by April 1st so we can update website on time.
Thank you. 

[DWG7.docx](https://github.com/UNopenGIS/7/files/14675811/DWG7.docx)

Any volunteer updating the content? @albertkun, @asahina820, @k96mz, @ShogoHirasawa or anyone? 
Otherwise I will be drafting the input and get back to you on Tuesday meetup. 

As Ki-Joune said, we will be provided opportunities to update the content frequently.

**Comment by albertkun** [comment]
@hfu how about we use this thread to make changes and proposals for what we would like to see on that page?

My  main question is what is the goal of that UN Smart Maps page on the UN Open GIS site, in terms of what we want to get across and the call to action for visitors. 


If we don't want to use this github issues thread can also use a Google doc or maybe hackmd.io for more realtime?

**Comment by asahina820** [comment]
I'd like to use realtime document tools.
I think those would be easy to write and edit👍

**Comment by albertkun** [comment]
@asahina820 Thank you for your input! I went ahead and created a Google Doc with the UN Smart Maps account:

https://docs.google.com/document/d/13q-xPpsYwOlwY_95ocByP9eceS3OjCCnyfAcN9ZBKT4/edit?usp=sharing

@hfu Looking for your advice to proceed forward!

**Comment by hfu** [comment]
@albertkun, @asahina820 Thank you for your feedback!

## The Goal
As far as I understand, the goal of that UN Smart Maps page on the UN Open GIS site, from the UN Open GIS secretariat point of view, would be to provide a broad overview of the activities of each DWGs. 

On the other hand, in terms of what we want to get across and the call to action for visitors, would be in our hands. I would suggest: 

- UN Smart Maps Group would like to provide visitors a good link to UN Smart Maps documentation web site, and ultimately expand our open community of practice. 

## Collaboration methods
How about this: 

- We make use of this Issue to exchange views and discuss what to do. 
- We make use of the Google Docs to draft the input. 

I mean we can make use of both!

**Comment by hfu** [comment]
Of course I think we can mention related activities like:

- International Humanitaran Mapathon.
- FOSS4G 2025 and other FOSS4G family of events. 
- GRF Pledges and its implementation plan.
- LLM / NLP activities led by @yuiseki

If it is strategically beneficial! :-)

**Comment by hfu** [comment]
Oh, I realized that @k96mz has some comment on the website at https://github.com/UNopenGIS/7/issues/430#issuecomment-2010476071, too.

**Comment by hfu** [comment]
# Default draft

The UN Smart Maps Group (SMG) is the 7th domain working group (DWG) of the UN Open GIS Initiative. SMG is designed to be an open community of practice (CoP) with the vision "keep web maps open" and the mission "test new technologies for future geospatial operations". SMG is participated by many talented volunteers from private sector, academia, and public sector, but we would like to have wider participation specially from young professional and large langage models (LLMs)! 

[we can add some specific information items here if it is good to do so.]

Please access [SMG website](https://unopengis.github.io/smartmaps) if you are intested in participating us! Again, we are an open community of practice.

**Comment by hfu** [comment]
[DWG7.docx](https://github.com/UNopenGIS/7/files/14845935/DWG7.docx)

I submitted the update today. Thanks to @albertkun for your kind input. My idea is that we appreciate participation from LLM users but also LLMs themselves, based on the idea expressed by @yuiseki at https://speakerdeck.com/yuiseki/shi-jian-nokomiyuniteitositeno-un-smart-maps-group?slide=21.
