### ISSUE TITLE
📻Software Defined Radio (SDR)

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#437]
As discussed in #430.

**Comment by yuiseki** [comment]
私も前からSDRに興味はあったけど手を出せていなかったので良い機会だと思ってself-assignしました。

デバイスとしてはこのあたりが定番みたいです：
- https://akizukidenshi.com/catalog/g/g112353/
- https://www.amazon.co.jp/dp/B0BZNGKT4J

ソフトウェアとしては我らがGNUがGNU Radioというものを作っているんですね
- https://www.gnuradio.org/

**Comment by hfu** [comment]
いったん閉じてみます。
