### ISSUE TITLE
🤖チームyuisekiがLOCAL AI HACKATHONで金賞を受賞

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#443]
- https://twitter.com/sald_ra/status/1774792645803679886
- 成果概要：
  - https://scrapbox.io/YuisekinAI/LOCAL_AI_HACKATHON_2024-03_成果概要
- 金賞の賞品：
  - MDL保有のGPUクラウドサーバーの一ヶ月占有権
- サーバースペック
  - https://scrapbox.io/YuisekinAI/LOCAL_AI_HACKATHON_2024-03_環境
- Request for Comments
  - 「こういうTinyLlamaほしい」
  - 「こういうLLMほしい」
  - 「こういうマルチモーダルモデルほしい」
  - などアイデアありましたら検討するので教えてください！
  - ※作成したモデルはオープンライセンスで公開する必要があります

**Comment by yuiseki** [comment]
GeoAIのDWGの人々に、期間限定でめっちゃGPUあるけど、なんかやりたい学習ある？というのを丁寧に伝えたいです

**Comment by hfu** [comment]
@yuiseki Source Cooperative の件で、チェアに報告しようと思っているところ、この件も合わせて報告してみます。

GPU使用について、開始や終了の具体的な期限は切られていますか。

DWG-5 との窓口について、なんらか案内をもらったりしていますか？もしもらっていなければ、そのことにも言及できればと思っています。可能であればわたしも DWG-5 への連絡者に加わろうと思っています。

**Comment by hfu** [comment]
@yuiseki Teams への追加について調整始めました。

UNのデジタル系、情報系、安全管理系のノウハウが全部叩き込まれている LLM とかいてくれていると嬉しいですね。下記の文書が思い当たります。

- UN Digital Strategy
- UN Geospatial Strategy
- (あとで書く)

- USAID Geospatial Strategy

**Comment by k96mz** [comment]
@yuiseki 横からすいません。DWG-5にhfuさんを加える話ですが、yuisekiさんをDWG-5に招待したのは誰か分かりますでしょうか？Teamsのアクティビティのところに、誰から招待されたのかが、記載されているのではないかと思っています。国連地理空間情報課のメンバーから招待されているのなら、私からhfuさんも招待してもらえないかその方に頼んでみる予定です。

**Comment by yuiseki** [comment]
@k96mz ありがとうございます！

- 誰が私を招待してくれたのかは遡ることはできないので確かなことはわからないのですが、
- [Cung Thang - Geospatial Information Officer - United Nations](https://www.linkedin.com/in/cthang)
- この方がGeoAIのグループ内でアナウンスなどをしてくださっているようです

**Comment by yuiseki** [comment]
あ！アクティビティのところを確認したらどなたが招待してくれたのかわかりました！
Cung Thangさんのようです！！

[![Image from Gyazo](https://i.gyazo.com/c310cb50077ac9e3795cac56f14e79de.png)](https://gyazo.com/c310cb50077ac9e3795cac56f14e79de)

**Comment by k96mz** [comment]
@yuiseki ありがとうございます。Cungに頼んで、hfuさんとk96mzをDWG-5に追加してもらいました。

**Comment by yuiseki** [comment]
現在Smart Maps界隈で関わることがありそうな言語を、以下のように大雑把でいいので、至急教えて頂けないでしょうか。

- 中央アフリカ共和国
  - Sango language
- etc

**Comment by hfu** [comment]
Shall we be closing this?

**Comment by yuiseki** [comment]
Yes, let's close this Issue!
