### ISSUE TITLE
🤖[info] Geographic Information Extraction from Texts (GeoExT)

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#444]
こういう研究分野があり、LLMと相性が良さそうです

- https://geo-ext.github.io/GeoExT2024/
- https://geo-ext.github.io/GeoExT2024/scope/

**Comment by hfu** [comment]
面白そうですね！しかも、ISPRS Commission IV が関連しており、私からもリーチしやすいところがありそうです！

**Comment by yuiseki** [comment]
こちら気にはなっているので、一旦閉じます
