### ISSUE TITLE
🖥UNVT Portable for PC and Mac

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#445]
文脈
国際協力の文脈での現場はハードな場合が多く、中古のPCを使ったほうがラズベリーパイを使うよりも優位な場合がある。
特にラップトップがバッテリーを内蔵しているのは魅力である。

仮説
Raspberry Pi Desktop for PC and Mac の上に UNVT Portable を載せる。

https://www.raspberrypi.com/software/raspberry-pi-desktop/

Pros
コロナ期に大量に導入された学校用ラップトップの中古品が安価に入手できる、といったことがあれば、費用対効果も高いかもしれない。

Cons
インストール時点でのトラプルに泣かされる可能性がある。

**Comment by mapconcierge** [comment]
中古のPCでもHDDだけは、安価なSSDに換装したほうがよさそうですね。それだけでそこそこパフォーマンスがでると思います。研究室に古いノートPCがいくつかあるので試してみます！！

**Comment by smellman** [comment]
Thinkpad X220+SSD+OSGeo Liveという組み合わせでPlanetのデモをジオ展で展開する予定です。
ただ、QGISのデモなのでtileserver-glから配信になりますが。

あと、古いLaptopだけどeMMCだと換装できない可能性が高いので注意が必要。
最悪OSのインストールでコケるパターンもあります(UbuntuインストールしようとしたらコケたLaptopが手元にあります)。

**Comment by hfu** [comment]
とりあえず私は、現役で使っている MacBook Pro を USB boot することで Raspberry Pi OS for Desktop 機にすることを考えてみたいと思いました。時間見つけてやってみます！

**Comment by hfu** [comment]
#453 を先行させたので、私による本件の進捗は遅滞すると思います。

**Comment by hfu** [comment]
いったん閉じてみます。
