### ISSUE TITLE
[INFO] スマートシティアプローチの適用性に係る情報収集・確認調査ファイナルレポート　抜書き

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#447]
JICA によるレポートを読み込みながら抜書きしています。レポートのリンクも、下記抜書きの冒頭に入れています。
https://hackmd.io/hzcPsAzET86U9P4BNVY8Hg?both

**Comment by hfu** [comment]
情報共有の目的を終了したので、クローズします。

**Comment by yuiseki** [comment]
目を通しました。Decidimは知っていましたがSentiloとOpenGridは初めて知りました。興味深い内容でした。共有ありがとうございました！
