### ISSUE TITLE
[INFO]Open Mapping towards Sustainable Development Goals - Voices of YouthMappers on Community Engaged Schalarship

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#448]
Following #447 and recommended by @tosseto. 

https://www.springerprofessional.de/open-mapping-towards-sustainable-development-goals/23765034?tocPage=1

**Comment by hfu** [comment]
@yuiseki このコンテンツ、かなりボリュームがあります。もしかしたらオープンソース LLM に読み込ませても面白いのかも？私も、これからまずは章立てを把握するというところですが。

**Comment by hfu** [comment]
## @hfu がチェックしてみたいと考えている章

- [ ] 9. Seeing the world through maps: an inclusive and youth-oriented approach.
- [ ] 15. Assessing YouthMappers contributions to the generation of open geospatial data in Africa
- [ ] 26. Open mapping with official cartographies in the Americas (Belize, Colombia, Costa Rica, the Dominican Republic, Jamaica, Mexico, and Panama)
- [ ] 27. [Cities of the future needs to be both smart and just: how we think open mapping can help](https://www.springerprofessional.de/content/pdfId/23765080/10.1007/978-3-031-05182-1_27?canonical=https%3A%2F%2Fwww.springerprofessional.de%2Fopen-mapping-towards-sustainable-development-goals%2F23765034%3FtocPage%3D1)
- [ ] 28. Mentoring experiences in YouthMappers chapters
- [ ] 29. [The ecosystem where YouthMappers live and thrive](https://www.springerprofessional.de/content/pdfId/23765086/10.1007/978-3-031-05182-1_29?canonical=https%3A%2F%2Fwww.springerprofessional.de%2Fopen-mapping-towards-sustainable-development-goals%2F23765034%3FtocPage%3D1)
- [ ] 30. [A free and open map of the entire world: opportunities for YouthMappers within the unusual partnership model of OpenStreetMap](https://www.springerprofessional.de/content/pdfId/23765090/10.1007/978-3-031-05182-1_30?canonical=https%3A%2F%2Fwww.springerprofessional.de%2Fopen-mapping-towards-sustainable-development-goals%2F23765034%3FtocPage%3D1)
- [ ] 31. Youth and humannitarian action: open mapping partnerships for disaster response and SDGs
- [ ] 33. [Reflecting on the YouthMappers movement](https://www.springerprofessional.de/content/pdfId/23765098/10.1007/978-3-031-05182-1_33?canonical=https%3A%2F%2Fwww.springerprofessional.de%2Fopen-mapping-towards-sustainable-development-goals%2F23765034%3FtocPage%3D1)

**Comment by yuiseki** [comment]
@hfu [FYI] https://www.perplexity.ai/ というやつにPDFを突っ込むと、かなり巨大なPDFでも適切に要約したり質問に答えてくれたりします

**Comment by yuiseki** [comment]
こんな具合です

[![Image from Gyazo](https://i.gyazo.com/f694624f073dc0abcb3bb33b56a24f44.png)](https://gyazo.com/f694624f073dc0abcb3bb33b56a24f44)
