### ISSUE TITLE
[Info] あなたは地図を今すぐタダで作る 個人開発祭り 2024-04

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#456]
- https://scrapbox.io/yuiseki/あなたは地図を今すぐタダで作る_個人開発祭り_2024-04
- YouTube録画（開始位置、1:13:12あたり）
  - https://www.youtube.com/live/NcNE6JumvrQ?si=YRmka_rODYHTjfE_&t=4392

**Comment by yuiseki** [comment]
※最後の方で音が入っていないのは機材トラブルでした

**Comment by hfu** [comment]
共有ありがとうございます！音声が入っているところまでクイックに視聴しました。
いいですね。

「個人開発祭り」の雰囲気も伺えて、良かったです。

**Comment by yuiseki** [comment]
情報共有の役目は果たしたので閉じます。フィードバックありがとうございました！
