### ISSUE TITLE
🖐️2024-05-20/24 UN Maps Conference

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#468]
@k96mz and @ubukawa will be participating in the UN Maps Conference from remote. 
We may be able to receive further information.

**Comment by hfu** [comment]
Koji has kindly shared his draft slides at https://github.com/UNopenGIS/7/issues/473#issuecomment-2107803626

**Comment by k96mz** [comment]
Schedule
![schedule(UN Maps Conference)](https://github.com/UNopenGIS/7/assets/65704916/c8b6a1d7-4c44-4503-a66e-4349af5c5686)

**Comment by hfu** [comment]
I found the conference site at https://maps.un.org/conference/2024. 

Koji's presentation was titled "UN Street Map & UN Vector Tile Toolkit"
