### ISSUE TITLE
🔥FOSS4G 2023 に投稿する（2023-02-19まで）

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#47]
FOSS4G 2023 Prizren に、Smart Maps コミュニティから一人でも多くの参加者を出そう！という話題です。

**Comment by ubukawa** [comment]
Call for paperの締め切りが2月19日中（UTC0）なので、メモしておきます！

https://2023.foss4g.org/call-for-papers/general-sessions/

**Comment by hfu** [comment]
#43 の結果、@hfu が中心で call for paper に応じていくことにしました。

**Comment by hfu** [comment]
[コソボについて](https://scrapbox.io/unopengis7/%E3%82%B3%E3%82%BD%E3%83%9C%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)（一般情報）

**Comment by hfu** [comment]
[FOSS4G 2023 General Track 募集要項](https://scrapbox.io/unopengis7/FOSS4G_2023_General_Track_%E5%8B%9F%E9%9B%86%E8%A6%81%E9%A0%85)

**Comment by hfu** [comment]
# 現時点の検討内容
## 発表の外的要件
General Track - 20分の口頭発表
## 選択するテーマ
- Community and Foundation (Community and participatory FOSS4G)
## 方針
- 割と思想・理念・ビジョンよりの発表にしつつ、場の雰囲気に合わせて技術の内容も短時間入れていく。
## タイトル
- Smart Maps for the UN and All - keeping web maps open
## ロジックモデル書きかけ
```mermaid
graph LR;
    コストが安い-->ウェブ地図のオープン性が維持される;
    楽に作れる-->ウェブ地図のオープン性が維持される;
    実践できる-->ウェブ地図のオープン性が維持される;
    体験がよい-->ウェブ地図のオープン性が維持される;
```

### キーワード
- 反復
- Adopt Geodata

### 技術
- Raspberry Pi
- PMTiles
- COPC
- COG

## 共著者募集戦略
- 共著者になるメリットがある方になっていただく
- 実際に共著者になると、論文投稿システムへの登録等が期待されてくるので、そういった操作を行うインセンティブのある方との取引関係でやることにする。必ずしも DWG7 内部でのバランスを追求しない。（DWG7はメリットで評価する、という原則の適用）
- 結果として、発表の内容もバランス型ではなくて著者のアイディアを反映していくものにする。
- なお、バランス型の発表が必要な具体的な理由が生じれば、上記の方針を変更する可能性もある。

**Comment by hfu** [comment]
## 言及しようと思っている技術要素
- 模擬国連
- ipfs でホストする話 https://github.com/amx-project/0/issues/29

**Comment by hfu** [comment]
## 行政的観点から盛り込むことを考えているメッセージ（素案）
（DWG7|日本|国土地理院|あなた)は、

- 平和維持における技術パートナーシップの趣旨に賛同し
- 国土地理院の国内実施と国際協力を一体で進める観点を持って

国連オープンGISイニシアティブに参加している。

当該イニシアティブにおいて、

- 平和維持における技術の発揮と、
- パートナーとの knowledge co-creation を

できる機会を与えられていることを誇りに思っている。

DWG7 on Smart Maps は、

- 効率的で efficient
- 可搬性のある portable

技術を co-create することができている。幅広い参加を得られていることも誇りである。

### オプショナルパート
日本政府もデジタル改革を進めており、Smart Maps 技術は三次元地理空間情報の活用推進や地方公共団体と連携しての地方展開の文脈で国内でも有望と考えている。

国連事務局においてもデジタル戦略・データ戦略を進めておられると伺っており、引き続き、同じく公共の利益に資するパートナーとして技術的卓越性を co-create していきたい。

**Comment by hfu** [comment]
メモ: @smellman が別枠でご検討中とのこと。すばらしいです！

**Comment by hfu** [comment]
# アブストラクトを作ってみた

## 英語
Do you want to broaden your horizons by learning about geospatial support for the United Nations operations? Or are you interested in developing highly efficient and portable geospatial apps which make use of PMTiles, COPC, COG, Raspberry Pi, and a cool Web3 technology named IPFS (Inter-planetary File System)? We are doing both in the Domain Working Group 7 (DWG 7) on Smart Maps of the UN Open GIS Initiative. 
In this participatory and voluntary DWG established in Firenze in August 2023, participants bring in their objectives and combine efforts within the Partnership for Technology in Peacekeeping to bring greater involvement to peacekeeping through innovative approaches and technologies that have the potential to empower UN global operations. In addition to our core objective to support the use of UN Vector Tile Toolkit in the UN Global Service Centre, we are expanding to support domestic and campus-level service operations, and to support 3D including point clouds and 3D city models. We are combining efforts to define and implement the concept of Smart Maps. 
We are happy to share with you our new effort named Model UN Development and Operations (MUNDO) that simulates geospatial support for the United Nations operations by making use of existing open geospatial data and our Smart Maps technologies. MUNDO project is not only useful for demonstrating the technology for the UN staff, but also useful for learning about the situation and the UN’s effort. We are also happy to share with you our new concept of WebMaps3, which introduces Web3 technology for web maps. By combining IPFS and cloud optimized formats like PMTiles, COPC, and COG, we were successful in hosting a vector tiles service from a newly released nation-wide cadastre dataset on a Raspberry Pi, within 10 days after the release, by producing a 14GB PMTiles file.

## 機械翻訳
国連の活動に対する地理空間サポートについて学ぶことで、視野を広げたいですか? または、PMTiles、COPC、COG、Raspberry Pi、および IPFS (Inter-planetary File System) というクールな Web3 テクノロジを利用する、非常に効率的でポータブルな地理空間アプリの開発に興味がありますか? UN Open GIS Initiative の Smart Maps に関する Domain Working Group 7 (DWG 7) で両方を行っています。 2023 年 8 月にフィレンツェで設立されたこの参加型かつ自発的な DWG では、参加者はそれぞれの目的を持ち寄り、平和維持における技術のためのパートナーシップ内での取り組みを組み合わせて、国連のグローバルな活動に力を与える可能性のある革新的なアプローチと技術を通じて、平和維持により大きな関与をもたらします。 国連グローバル サービス センターでの UN Vector Tile Toolkit の使用をサポートするという主な目的に加えて、国内およびキャンパス レベルのサービス運用をサポートし、点群や 3D 都市モデルを含む 3D をサポートするように拡張しています。 私たちは、Smart Maps の概念を定義し、実装するための取り組みを組み合わせています。
既存のオープンな地理空間データとスマート マップ テクノロジを利用して、国連の活動に対する地理空間サポートをシミュレートする、Model UN Development and Operations (MUNDO) という名前の新しい取り組みを共有できることをうれしく思います。 MUNDO プロジェクトは、国連スタッフが技術を実証するのに役立つだけでなく、状況や国連の取り組みについて学ぶのにも役立ちます。 また、Web マップに Web3 テクノロジを導入する WebMaps3 の新しい概念を共有できることを嬉しく思います。 IPFS と PMTiles、COPC、COG などのクラウドに最適化されたフォーマットを組み合わせることで、リリース後 10 日以内に Raspberry Pi で新しくリリースされた全国規模の地籍データセットからベクター タイル サービスを、14GBのPMTilesファイルによりホストすることに成功しました。

**Comment by hfu** [comment]
## アブストラクトをリポジトリに置いた
https://github.com/UNopenGIS/7-foss4g-2023/blob/main/ABSTRACT.md

## いずれにせよ、今週中に提出してしまおうと思います

**Comment by hfu** [comment]
提出しました。締め切りまで修正は可能だそうです。
https://talks.osgeo.org/foss4g-2023/talk/review/M9W73HELNYTDKSHBCUUMPTRQ3JEFQVYK
