### ISSUE TITLE
🤖[info] yuiseki challenges Backdrop Build v5 with TRIDENT

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#484]
## What is Backdrop Build?

- https://backdropbuild.com/
- Backdrop Build is a support program for intensive software development 
- 4 weeks for the challenge of building and launching a crazy idea
- A grant of $50,000+ will be offered to the most outstanding challenge that is recognized as worthy of continuous development support

## What is Backdrop Build v5?

- Backdrop Build v5 is 5th phase of the Backdrop Build
- Starts on June 24
- Ends on July 21 (maybe)

## What are the challenges?

- Enhance TRIDENT
  - Get away from dependency on OpenAI API
  - Handle a variety of dynamically changing data sources beyond OpenStreetMap
  - Implementation of appropriate visualization methods for different purposes
  - Implementation of user authentication and content sharing (public and limited sharing)

## Links

- https://backdropbuild.com/builders/yuiseki
- https://backdropbuild.com/builds/v5/trident

**Comment by hfu** [comment]
Great! Looks like a great challenge for the UN Smart Maps agenda, too. 
Let me know if there is anything I can help.

**Comment by yuiseki** [comment]
こちらは時差の関係であんまりコミットできなかったです。閉じます
