### ISSUE TITLE
💡📗FOIL4G (Free and Open Information Library for Geospatial)

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#486]
https://hackmd.io/@smartmaps/2024-05#/0/12 で紹介した、私が invent した用語である FOIL (Free and Open Information Library) について、Li 先生が高く評価してくださりました。

Free and Open Data Library とするのがシンプルかもしれませんが、アクロニムが通常の英単語になるようにひねって Free and Open Information Library としています。

口頭説明する中で、オープンな地理空間情報のパブリック・ライブラリーがあったら、ソフトウェアをデモするのにもいいですよね、と言っています。

Smart Maps Bazaar のような hosting efforts の延長線上に FOIL があるという考え方は、割と有望なように思いました。

**Comment by hfu** [comment]
@yuiseki セルフアサインしてくださり、ありがとうございます。良い感じで進めていきましょう！

**Comment by hfu** [comment]
ChatGPT の支援を受けて、練ってみました：

ベンジャミン・フランクリンの図書館コンセプトを「Free and Open Information Library for Geospatial (FOIL4G)」に結びつけることで、スマート地図の価値と利用可能性をさらに広げることができます。このフレーズを引用して、FOIL4Gのコンセプトを説明するための日本語訳を提供します。

---

「私たちの議論の中でしばしば参照される本があるため、それらを集まる場所にすべて集めておけば、必要なときにすぐに参照できるので便利だろうと考えました。さらに、私たちの本を共有の図書館に集めることで、皆がその場に置いておくことを好む間、それぞれが他のメンバーの本を利用することができるので、まるで全員が全ての本を所有しているかのように便利になるのです。」

---

この引用は、FOIL4Gの理念を強調するのに非常に適しています。FOIL4Gが目指すのは、地理空間情報のオープンライブラリを通じて、全てのメンバーが自由に情報にアクセスし、共同で活用することです。このようにすることで、個々のメンバーが所有するリソースを共有し、全体としての知識と能力を向上させることができます。

具体的には、以下のような要素をFOIL4Gに取り入れることが考えられます：

1. **共有リソースの集約**：スマート地図や地理空間データ、関連ドキュメントなどを一箇所に集め、誰もがアクセスできるようにする。

2. **共同作業と学習**：メンバーが集まって議論し、必要な情報をその場で参照できるようにすることで、効果的な意思決定と問題解決を促進する。

3. **知識の拡大**：共有ライブラリを利用することで、個々のメンバーが他のメンバーの知識やリソースを活用し、自己の能力を向上させる。

このように、FOIL4Gはベンジャミン・フランクリンの図書館コンセプトを現代の地理空間情報システムに応用することで、参加者全員が互いに協力し、成長できるプラットフォームを提供することができます。

**Comment by hfu** [comment]
## English version of the idea above
We incorporate Benjamin Franklin’s library concept into the idea of the Free and Open Information Library for Geospatial (FOIL4G):

---

"Since our books were often referred to in our disquisitions upon the queries, it might be convenient to have them all together where we meet, so that they might be consulted when needed. Additionally, by pooling our books into a common library, we would, while we liked to keep them together, have the advantage of using the books of all the other members, which would be nearly as beneficial as if each owned the whole."

---

This quote is highly relevant to emphasize the philosophy behind FOIL4G. FOIL4G aims to create an open library of geospatial information, allowing all members to freely access and collaboratively utilize the data. By doing so, it leverages individual resources to enhance the collective knowledge and capabilities of the entire community.

Specifically, FOIL4G can incorporate the following elements:

1. **Aggregation of Shared Resources**: Collect smart maps, geospatial data, relevant documents, and more in one place where everyone can access them.
2. **Collaborative Work and Learning**: Facilitate discussions among members, enabling them to consult necessary information on the spot for effective decision-making and problem-solving.
3. **Expansion of Knowledge**: By utilizing the shared library, each member can benefit from the knowledge and resources of others, thus enhancing their own capabilities.

In this way, FOIL4G applies Benjamin Franklin’s library concept to modern geospatial information systems, providing a platform where all participants can cooperate and grow together.

**Comment by yuiseki** [comment]
@hfu `UNopenGIS/foil4g` というリポジトリを作成することを提案します

また、サブディレクトリ内に多数のMakefileを設置する、Makefile内にコメントでYAMLでメタデータを書く、というアイデアを思いついて試作してみたので、FOIL4Gのアプローチのひとつとして提案します

https://github.com/yuiseki/foil4g-proposal

**Comment by hfu** [comment]
@yuiseki いいですね！提案ありがとうございます！

yuiseki/foil4g-proposal を良い時期で、あるいは今、unopengis/foil4g にリネームするような形でどうでしょうか。

Makefile で連鎖的にライブラリーが構築され、更新もされるというコンセプトかなと思いました。LLMの支援を受けた雑な形でもよいので、Makefile でやっていくというコンセプトとテキストにできればいいなと思っています。

**Comment by yuiseki** [comment]
- `yuiseki/foil4g-proposal` を `yuiseki/foil4g` にRenameしました
- `yuiseki/foil4g` に `LICENSE` ファイルを追加しました（ライセンスは個人的な好みでWTFPLとなっていますが、MITやApacheやCC-0でもよいかとは思っています）
- Makefile一本打法は（生成AI、LLMにとっても）イマイチかなと思ったので、全体的な構成も変更しています
  - lib/data ディレクトリに、データの情報のみを簡潔にあつめる
  - lib/skills ディレクトリに、データを処理するためのスキルを簡潔にあつめる
  - lib/recipes ディレクトリに、lib/dataのデータとlib/skillsのスキルを組み合わせて地理空間情報処理をする具体的なレシピをMakefileで置く
- 私には `UNopenGIS` にtransferする権限がないみたいです

**Comment by hfu** [comment]
@yuiseki ありがとうございます！

- ライセンスに好みを反映いただくのも国連スマート地図グループらしいと思っており、yuisekiさんのご判断で WTFPL であってもよいと思います。もちろん、MIT、CC-0、Apacheにしてもらって参加しやすくするという判断もありかと思います。
- 構成法についてもご案内ありがとうございます。私のほうでも理解を進めるようにします。
- yuiseki さんに unopengis organization へのインバイトを送りました。

**Comment by yuiseki** [comment]
https://github.com/yuiseki/foil4g を https://github.com/UNopenGIS/foil4g にtransferしました！

私は[GitHub Copilot Workspace](https://githubnext.com/projects/copilot-workspace)を使えているので試してみているのですが、Issue Templateに従ってIssueを書いて数回ボタンを押すだけでYAMLファイルを追加してくれています！！

**Comment by hfu** [comment]
内部プロジェクトとして継続・定着しているのでイシューとしてはクローズします。
ありがとう、@yuiseki！
