### ISSUE TITLE
QGIS Optimized Vector Tile Style

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#49]
QGIS がサポートする Vector Tile Style は限定的です。
ベクトルタイルの QGIS での活用を推進するために、QGIS Optimized Vector Tile Style というものを考えてみたいなと思います。

**Comment by ubukawa** [comment]
もう一年半くらい前ですが、QGISでのベクトルタイル消費を試したことがあります。
https://speakerdeck.com/ubukawa/2021-05-20-vector-tile-in-qgis-in-english

当時の一番のハードルは、QGISがglyphsのフォントを参照せず、どうやらシステムフォントを参照しているようだったことです。（なので、パソコンの環境によってtext-fontの対応可否が異なる可能性があった。）
あと、スタイルレイヤが多いと読み込めなかったのが問題でした。今度、最新のQGISで試してみる機会があれば報告します！

UN Clear Mapで試してみる価値はあるかなと思っています。（ESRI版の200レイヤ以上のものは公開されていますし、私が作った20レイヤ以下のデータも早く公開できるといいなぁと思います。←クリアランス待ちなので時間かかりそうですが・・・）

**Comment by ubukawa** [comment]
年末年始に思ったほど時間が取れなかったのですが、QGISで使える表現を実験して少しまとめました。

https://qiita.com/T-ubu/items/e5fa4d12ef429b35ebc3

**Comment by hfu** [comment]
@ubukawa ありがとうございます。いただいた情報を踏まえて、私は次のような方針で動くようにしてみたいと思っています。

## 当面の方針
1. 3.28 Firenze 以降の QGIS を相手にする。
2. Vector Tiles Reader は 2019-12 以降更新されていないようなので、3.14 以降のベクトルタイル・ネイティブ・ローディングを相手にする。
3. `match` expression は使わない。`get` expression が有効ではないようだからだ。
4. `step` / `zoom` で色を変えることはできないのでしない。やむをえない場合は、`stops` を使って変える。
5. `symbol`, `sprite`, ラベルを使う時には、十分に注意する。
6. 保守的かつシンプルに、また、ゆっくりと、時間を味方につけるような感じで不可逆に進めていく。

**Comment by ubukawa** [comment]
@hfu さん、ありがとうございます。
私も、当面はClear Map Vectorを対象にすると思いますが、ゆっくりと時間をかけながら、でも着実にQGISでの実装を試していこうかなと思います。
（レイヤ数をコンパクトにしたClear Map Vector が公開できるか見極めつつスタイルを準備していきたいと思います。）

QGISもどんどん進歩しているので、「時間を味方につける」という観点は素晴らしいと思います！

**Comment by hfu** [comment]
いったんクローズ。まさに、時間を味方につけていきましょう。
プリズレンの結果として本件に戻ってきたりすることはあるかもしれません。
