### ISSUE TITLE
📗OpenCelliD PMTiles

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#497]
Maybe I should develop PMTiles for OpenCelliD. 
https://www.opencellid.org/

**Comment by yuiseki** [comment]
@hfu `foil4g` で、OpenCelliDのCSVをPMTilesに変換するタスクを実装しました
- https://github.com/UNopenGIS/foil4g/blob/main/lib/tasks/opencellid_full/pmtiles/Makefile

PMTilesに変換後のデータは4.6GBもあります！
[![Image from Gyazo](https://i.gyazo.com/d8f913625946a6d5e8aab4b413d0839f.png)](https://gyazo.com/d8f913625946a6d5e8aab4b413d0839f)

UN Smart MapsのSource Cooperativeに置かせていただきたいです 🙏

**Comment by hfu** [comment]
@hfu ありがとうございます！私の方でフォローアップして、 cell_towers.pmtiles を Source Cooperative の smartmaps の下にアップロードするようにします！

**Comment by hfu** [comment]
実際にやってみましたところ、私の手元では表示がうまくいかなかったこともあり、tippecanoe のパラメータを調整しつつ、csv.gz から直接 tippecanoe に行くような方式で変換する参考用プロトタイプを作ってみました。

## Makefile
As in https://github.com/optgeo/opencellid/blob/main/Makefile:

```Makefile
SRC_PATH = ../foil4g/tmp/opencellid.org/cell_towers.csv.gz
DST_PATH = cellid.pmtiles
GZCAT = gzcat

all: 
	$(GZCAT) ${SRC_PATH} | \
	tippecanoe -o ${DST_PATH} -f \
	-L'{"file": "", "format": "csv"}'
```

## PMTiles file on Source Cooperative
### Data page
https://beta.source.coop/smartmaps/opencellid/cellid.pmtiles

### Direct access (for PMTiles Viewer, MapLibre GL JS, etc.)
https://data.source.coop/smartmaps/opencellid/cellid.pmtiles

## On PMTiles Viewer
https://pmtiles.io/?url=https%3A%2F%2Fdata.source.coop%2Fsmartmaps%2Fopencellid%2Fcellid.pmtiles#map=13.78/35.69938/139.77238

**Comment by hfu** [comment]
※ 上記 PMTiles Viewer の表示を拡大すると、いかにも桁を丸めているような表示になります。精査はできていませんが、OpenCellid の CSV ファイルの時点で桁を丸めていらっしゃるという理解です。

<img width="804" alt="image" src="https://github.com/UNopenGIS/7/assets/18297/c4032a9e-a55a-466d-b7b4-9cff2045f64d">

**Comment by hfu** [comment]
I am closing this as successfully completed!
