### ISSUE TITLE
Monitor NSDI Bangladesh and NSDI Base Maps

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#509]
# Motivation 
@hfu would like to contribute to more stable platform hosting of NSDI Bangladesh and its basemay by SoB. 

# What I want
I want to monitor the status of NSDI Bangladesh and NSDI Base Maps. 

# What URLs to monitor
- NSDI Platform: https://geoportal.nsdi.gov.bd/
- NSDI Topographic Basemap: https://server.nsdi.gov.bd/iserver/services/map-zxytiles-TopographicBasemapFebruary2024/wmts100/Topographic_Basemap_February_2024/default/GoogleMapsCompatible_Topographic_Basemap_February_2024/11/883/1538.png
  - Requested from https://observablehq.com/d/87810c1000a1bd5c

# My questions
What is the best/standardized way to monitor these URLs?

**Comment by yuiseki** [comment]
- Statuspage は情報を一般に公開するのであれば無料でもそこそこ使えます
  - https://www.atlassian.com/ja/software/statuspage
  - Atlassianが自分自身でStatuspageをドッグフーディングしているので信頼感があります
    - https://status.atlassian.com/
- 同じようなWebサービスは探せば他にもあるはず

**Comment by hfu** [comment]
@yuiseki ありがとうございます！Statuspageのスキルを身につけてみたいと考えています。

## 将来イメージ
将来的には、常時 on の Raspberry Pi 上の cron で呼び出される一つの ruby コマンドで、監視先の URL に GET を出してそのステータスコードを取得し、それを使って Statuspage の API のポストするようにしようかなと思っています。

## とりあえずの成果
### Statuspage
Statuspage としては機能していませんが、https://unsmartmapsgroup.statuspage.io/ を作りました。

### UptimeRobot
さしあたり UptimeRobot にアカウントを作って、無料の範囲内で監視してもらったりしています。お礼とご参考までに、スクリーンショットを共有します。

<img width="773" alt="image" src="https://github.com/UNopenGIS/7/assets/18297/e48b56fe-27cc-4716-ab15-0dbd1323b3f8">

<img width="779" alt="image" src="https://github.com/UNopenGIS/7/assets/18297/e09c3b0a-650b-4667-b18b-6736e5e7d367">

**Comment by hfu** [comment]
モニタリングサイトをオープンにする方法が理解できたので、オープンしてみました。

https://stats.uptimerobot.com/qB6wqULMK5

![image](https://github.com/user-attachments/assets/bde6da16-aea7-48bc-9f80-5285ebe030e0)

**Comment by hfu** [comment]
モニタリングサイトは安定して動いている（モニタリング対象が安定していない状況が安定して把握できる）状態なので、イシューとしてクローズします。

ありがとうございました！
