### ISSUE TITLE
Meet Santosh from Nascent in Japan in 2024-10

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#510]
I have heard from @santoshgaikwad23 that he is visiting Japan this August! 

He is interested in further contribution to UN Smart Maps Group exploring revitalizing the Smart Campus project using their CityLayers technology with @mapconcierge for Aoyama Gakuin University. He is also interested in expanding our collaboration in several different contexts. One of his interest includes finding a business-to-business relatinship with private company in Japan. 

We may be setting up a meeting in Japan in August. I will update you once I receive details from @santoshgaikwad23.

**Comment by hfu** [comment]
Regarding the Smart Campus sub-project, please refer to https://github.com/UNopenGIS/7/wiki/Project-Document#objective-4-smart-campus.

**Comment by albertkun** [comment]
@hfu very exciting! i actually was planning on trying to meet with Venka-sensei in August too! Would be nice if we can time the meeting together! I will be in Kansai around 8/2-8/5!

**Comment by hfu** [comment]
## Points for consideration / discussion 
1. Nascent is interested in having an in-person meeting in Tokyo most probably in August 2024. 
1. @hfu will guide Nascent on the UN SmartMaps initiative for longer collaboration and to fulfill the objective of a Smart Campus.
1. @santoshgaikwad23 and @hfu would like to discuss @mapconcierge regarding the completion of the Smart Campus objective. 
1. @santoshgaikwad23 also appreciate suggestions (by @hfu) to involve Mr. Sanghee Shin, if possible, for the Smart Campus project.
1. @santoshgaikwad23 would like to arrange a meeting with a local Japanese company for collaboration with Nascent. For that purpose, @hfu suggested that we can make use of existing meetup arrangements (both weekly and monthly).
1. @santoshgaikwad23 and @hfu decided to meet with Prof. Venkatesh Raghavan from Osaka City University regarding stronger involvement of Nascent in OSGeo.
1. @santoshgaikwad23 is thinking about arranging an in-person meeting with Mr. Pongsakorn from Thailand regarding the Geospatial Metaverse, with which Nascent is interested in collaborating.
1. @santoshgaikwad23 mentioned that the MD of Nascent, Mr. Maulik Bhagat, will be present for a couple of days to attend some of the meetings in person.
1. @santoshgaikwad23 suggested that Nascent express an interest in collaborating with JICA for GIS.
1. @santoshgaikwad23 will confirm the dates for the visit to Tokyo probably in the first week of July 2024 and will try to schedule it as per your availability.

**Comment by mapconcierge** [comment]
Our campus has 3D models as open data. Those data are useful, I think. :-)

https://sketchfab.com/mapconcierge/collections/b4d7c2f179534d1daf5118ebbb83c6e1-df275ec44c0943cc9b031075cd1bccac

**Comment by hfu** [comment]
I heard from Santosh recently that they will be visiting Japan in the first week of October 2024. 👍

**Comment by hfu** [comment]
I forgot to close this. Santosh and his team visited Korea, but I could not make it to invite him to Japan due to my time constraint. Maybe next time!
