### ISSUE TITLE
[Note] Hacker Mindset x UN Smart Maps Group (communication and culture)

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#515]
### Japanese language version
#507 の続きの検討として、UN Smart Maps Group のコミュニケーション方式と文化は、次のとおりと考えるに至りましたので、共有します。このイシューは、次の週例ミートアップで紹介して閉じる予定です。

1. コミュニケーション方式は、[Manage like an Engineer](https://ben.balter.com/2023/01/10/manage-like-an-engineer/) のようにする。
2. 文化は、[Cathedral Bazaar Management](https://ben.balter.com/2023/12/08/cathedral-bazaar-management/) にいう Bazaar People Management になる。（ただし、UN Smart Maps Group は、完全にボランティアベースのオープンな実践のコミュニティなので、そもそも management という言葉がそぐわないとは考えています。）

### English language version
As a continuation of the discussion in #507, I have come to the conclusion that the communication methods and culture of the UN Smart Maps Group should be as follows. I would like to share this with you, and I plan to introduce and close this issue at the next weekly meetup.

The communication method will follow the approach described in [Manage like an Engineer](https://ben.balter.com/2023/01/10/manage-like-an-engineer/).
The culture will align with the Bazaar People Management approach outlined in [Cathedral Bazaar Management](https://ben.balter.com/2023/12/08/cathedral-bazaar-management/) (However, considering that the UN Smart Maps Group is a completely volunteer-based, open practice community, I believe the term "management" itself is not entirely appropriate).

**Comment by yuiseki** [comment]
いずれも、とても良いエッセイだと思いました。
UN Smart Maps Group は、明らかに Bazaar people management をするべきでしょう。
