### ISSUE TITLE
2024-06-26T17:00/18:00, 21:00/22:00+09:00: AI for Good: GeoAI Discovery "Leveraging LLMs for advanced spatial decision support: The case of SATGPT", GeoAI & Analytics Working Group Monthly Meeting

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#525]
https://aiforgood.itu.int/event/leveraging-llms-for-advanced-spatial-decision-support-the-case-of-satgpt/

Wow, Hamid is speaking!

**Comment by hfu** [comment]
@hfu も一般参加で登録できました。仮に @yuiseki の発言機会があった場合は、スクリーンショットを撮って UN Open GIS Monthly meeting で報告できればと思っています。

**Comment by yuiseki** [comment]
@hfu 私が招待されているのは同じ時間の別のMTGかもしれません。
Title: Invitation to GeoAI & Analytics Working Group Monthly Meeting

[![Image from Gyazo](https://i.gyazo.com/34d3876aee469b9e306554475a615233.png)](https://gyazo.com/34d3876aee469b9e306554475a615233)

**Comment by hfu** [comment]
@yuiseki おお、素晴らしいですね！支障のない範囲で上記 Monthly meeting に参加いただけると嬉しいです。

私は、可能な限り ITU のオープンイベントを見てきます。

**Comment by hfu** [comment]
ITU のイベントは、大略、ChatGPT で Google Earth Engine のコードを書く、という話のようでした。
