### ISSUE TITLE
COG とどう付き合うか Take 2

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#53]
COPC の扱いに慣れてきた 2023-01 の段階で、改めて COG (Cloud optimized GeoTIFF) との付き合い方を考えてみたいと思います。
私は、次のように思います。

1. COPC と同様、「タイルのようにシームレス」なのではなく、「一つのシーンをサクサクと」という使い方をするように思う。なので、**COG は画像タイルの代替ではない**。
2. COG 対応が進んでいるのはデスクトップGIS（QGIS）であってウェブ地図ではないように思える。**ウェブからデスクトップGISに各シーンをお届け**するというユースケースを、我々は狙うべきではないだろうか。
3. 逆に言えば、ウェブアプリケーションを攻めるべき時期ではないように思える。
4. **多数のシーンを、シームレス化することなくお届けしたい**というニーズに COG を当てていくのが適切だと思う。

**Comment by hfu** [comment]
## See Also
https://bertt.wordpress.com/2023/01/12/cloud-optimized-geotiff-cog/

**Comment by wata909** [comment]
「タイルのようにシームレス」というところが，ちょッとわかりにくいと思いました。Z毎に扱うデータをシームレスに変える，ということでしょうか。
というか，そもそもクラウドでなくても有効な技術に「Cloud optimized」とつけるのは，どうなんだろうと，思っています。
近年，多くを占めるようになってきたClound技術者には，わかりやすいのかもしれませんが

**Comment by hfu** [comment]
ありがとうございます。**タイルのようにシームレス**は、隙間なく敷き詰められているイメージでした。COG は、スケールごとに解像度を変えることはしつつ、隣とつながり続けることは考えないフォーマットだなと思います。

クラウドに慣れている技術者にも、今の状況は分かりにくいと思います。名前をつけるのは親の特権なので、もっといいもの、分かりやすいものを生んで、いい名前をつけていきたいですね！

**Comment by hfu** [comment]
で、さっくりと実験を進めてみました！

https://github.com/optgeo/handa-2020-cog

![demo](https://user-images.githubusercontent.com/18297/212474212-3516fd4c-d348-455f-a8ba-bed7740a044e.jpg)

私はとことん QGIS と相性が悪いようで、せっかく作った COG ファイルが QGIS でうまく読めなくて困っていたのですが、逆に Development Seed さんとはとことん相性が良いようで、彼らが作ったウェブベースのビューアに救ってもらいました。

QGIS は武田信玄のように英雄なのですが、たまたま私が上杉家のような位置にいるようです（笑）。

**Comment by hfu** [comment]
いったんクローズします。いつでもリオープンしましょう。

**Comment by wata909** [comment]
ありがとうございます。シームレス，理解できました。半田市のCOGは，私の環境（M1 Air，QGIS 2.28）では読めした。なぜでしょう・・・。

https://cogeo.xyz/ 初めて知りました。Desktop環境なしにさっくりCOGを確認できるので，QGISよりもいいのではと思います。

>QGIS は武田信玄のように英雄
いろいろな意味で，名言だとおもいました（信玄ではあっても，信長ではないという点も）。
