### ISSUE TITLE
UCDP GEDのPMTilesをSource CooperativeにDeployしてほしい

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#543]
- UCDP GED = ウプサラ紛争データプログラム 地理参照事件データセット
- https://github.com/UNopenGIS/7/issues/338 でDeployされた
- https://smb.optgeo.org/ipfs/Qmeguu9vsViuKh5m4rc1zhCsYuzwjMxEwa7YYRvKrgGQ5C
- には、現在、アクセス不能
- PMTilesがSource CooperativeにDeployされれば、FOIL4Gで活用可能

**Comment by hfu** [comment]
リストアしてみています。次の場所においてみているところで、私の方で PMTiles Viewer で動作確認をこれからしてみます。

https://ipio.nchc.org.tw/ipfs/QmV33dC8kFHNdoncsSeoEKGR6otSJtNSKqYk9GGyj3t4qZ

**Comment by hfu** [comment]
CORS ヘッダがうまくついていないかも。PMTiles Viewer でうまく見えていませんね...。

**Comment by hfu** [comment]
https://smb.optgeo.org/ipfs/QmV33dC8kFHNdoncsSeoEKGR6otSJtNSKqYk9GGyj3t4qZ
これで CORS ヘッダがうまくついているかも。

**Comment by hfu** [comment]
https://pmtiles.io/?url=https%3A%2F%2Fsmb.optgeo.org%2Fipfs%2FQmV33dC8kFHNdoncsSeoEKGR6otSJtNSKqYk9GGyj3t4qZ#map=5.2/44.352/21.554
これで、ビューアでうまく見ることができることがわかりました。Source Cooperative にデプロイします。

**Comment by hfu** [comment]
https://data.source.coop/smartmaps/uppsala-conflict/a.pmtiles にアップしました。
PMTiles Viewer でチェックします。

**Comment by hfu** [comment]
https://pmtiles.io/?url=https%3A%2F%2Fdata.source.coop%2Fsmartmaps%2Fuppsala-conflict%2Fa.pmtiles#map=6.71/44.027/19.135
動作確認できました！ご活用いただけると嬉しいです。

@yuiseki さんから反応をいただいたのち、このイシューもクローズしようと思います。

**Comment by yuiseki** [comment]
FOIL4Gに取り込み完了しました!!

## https://unopengis.github.io/foil4g/?path=/story/components-combined-armedconflictwithbasemap--preview
