### ISSUE TITLE
全球をカバーしたNASA DEMのPMTilesをSource CooperativeにDeployしてほしい

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#544]
- 標高とその他様々な地理空間情報との関係を可視化したい
  - 武力衝突は平地で多いのか？高地で多いのか？
  - 携帯電話基地局は平地で多いのか？高地で多いのか？
  - 各国、各地域は、どのような地形におかれていて、どのような戦略で幹線道路を作っているのか？
- 現在Source CooperativeにDeployされているDEM1Aは東北地方の太平洋側のみ？
  - 東北地方の太平洋側においては非常に興味深い可視化ができた
    - https://unopengis.github.io/foil4g/?path=/story/components-combined-opencellidwithdem1aandoverture--preview
    - 東北地方の太平洋側においては、山脈の谷間を切り開いて幹線道路を作っている
      - そして、幹線道路沿いに集中して携帯電話基地局がある
- @smellman さんがDeployしてくれたOverture Mapsの交通網と、UCDPの武力衝突データの組み合わせからも興味深い可視化ができた
  - https://unopengis.github.io/foil4g/?path=/story/components-combined-armedconflictwithoverture--preview
  - 少なくとも、南スーダンにおいては、幹線道路沿いにおいて武力衝突が発生している傾向にある
- ルワンダの標高、道路、武力衝突を組み合わせた地図
  - https://unopengis.github.io/foil4g/?path=/story/components-combined-armedconflictwithrwanda10andoverture--preview
- ルワンダの標高、道路、携帯電話基地局、武力衝突を組み合わせた地図
  - https://unopengis.github.io/foil4g/?path=/story/components-combined-rwandamap--preview
- 全球をカバーしたNASA DEMのPMTilesをSource CooperativeにDeployしていただけないでしょうか
  - これによって、地形、道路網、武力衝突の相互関係がわかる

**Comment by hfu** [comment]
NASA DEM の標高タイル PMTiles、こちらに置いてあります。こちらでいかがでしょう。

https://beta.source.coop/repositories/smartmaps/gel/description/

**Comment by hfu** [comment]
ルワンダの 10m DEM もここにおいてあります。unlisted になっているしドキュメントも充実していないのですが、必要の応じて充実させていきたいと思います。

https://beta.source.coop/repositories/smartmaps/rwanda10/

**Comment by yuiseki** [comment]
@hfu ありがとうございます！！
 `rwanda10` の存在には気づいていたのですが、 `gel` の存在には気づいていませんでした！！
FOIL4Gでカタログ化する意義が高まったように感じます。

一方で、 `https://data.source.coop/smartmaps/gel/gel.pmtiles` は、以下のように、PMTiles Viewerで表示することができません。

- https://pmtiles.io/?url=https%3A%2F%2Fdata.source.coop%2Fsmartmaps%2Fgel%2Fgel.pmtiles#map=22/0/0
- https://unopengis.github.io/PMTiles/?url=https%3A%2F%2Fdata.source.coop%2Fsmartmaps%2Fgel%2Fgel.pmtiles#map=22/0/0

Source CooporativeのPreviewページでも表示することができません。

- https://beta.source.coop/smartmaps/gel/gel.pmtiles


古いバージョンのPMTilesコマンドで作成されたために壊れている可能性を感じます。

こちらも同様に作って終わりではなくてFOIL4Gのような形で収録して継続的に活用していくことで壊れていることに気付く意義が高まったように感じます。

**Comment by yuiseki** [comment]
すみません！！ `https://data.source.coop/smartmaps/gel/gel.pmtiles` は壊れていませんでした！！！


ここで動くようになりました

- https://unopengis.github.io/foil4g/?path=/story/components-datasets-gel--preview


ただ、やはり、このようなデータが、作り手にしか使い方がわからない状態で放置されているのは問題があると思いました。

**Comment by yuiseki** [comment]
南スーダンとスーダンの国境線、abyei boxの北東における武力衝突は、特に高地で起きていることがわかりました。
また、南スーダンとスーダンの国境付近における幹線道路は貧弱です。


http://localhost:6006/iframe.html?id=components-combined-armedconflictwithelevationandoverture--preview&viewMode=story#8.14/10.466/29.14/0/58
[![Image from Gyazo](https://i.gyazo.com/8a3c6896f1b73dfc5884ca6129c79665.png)](https://gyazo.com/8a3c6896f1b73dfc5884ca6129c79665)

**Comment by yuiseki** [comment]
タイトルにある要望は解決されたのでCloseします

**Comment by hfu** [comment]
GEL は @ubukawa さんのノウハウと @k96mz のドキュメンテーション支援に恵まれましたが、それでも、私の方でしっかりドキュメントしてやれず、うまく盛り上げていくことができていませんでした。なかなか良いデータだと思うので、FOIL4G のコンセプトや、さらには @albertkun の Smart Map Challenges コンセプトをつなぎ合わせて、バズらせていければと思います。

Source Cooperative に対しても、もう少し深く根を下ろしても良いかもしれません。
