### ISSUE TITLE
Create a simple MapLibre GL JS site with hash and PMTiles enabled, which takes style.json URL. 

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#548]
FOIL4G で style.json の URL を改めてリソースとしてとらえやすくなっていることを踏まえ、@hfu の実用的モチベーションもあり、次の要件を満たすシンプルな MapLibre GL JS サイトを作りたいと思っています。

- hash が enalbed になっている。
- PMTiles が enabled になっている。
- style.json の URL を ?style=https://server/somewhere/style.json で指定できる。

MapLibre GL JS は最新のものに自動的に追従するようにしたいです。

このようなサイトを作るにあたり、注意するべきこと、その他コメントなどあればいただけますか。

@asahina820 @yuiseki @smellman @albertkun @k96mz 

## 私のユースケース
- https://observablehq.com/d/e66dd18a3be303c7 から style.json をエクスポートし、GitHub Pages なりにアプロードして、その URL を ?style に指定して地図を共有する。
- Observable では hash が上手く使えないと思っており、ピンポイントを指定して地図を共有することができないのが、このサイトの構築を考えているきっかけです。

**Comment by hfu** [comment]
https://optgeo.github.io/terrain22/style.json をサンプルに使っていただければと思います。日本の地形分類も入っています。

**Comment by asahina820** [comment]
> MapLibre GL JS は最新のものに自動的に追従するようにしたいです

CDNを使ってMapLibre のライブラリを読み込む場合に、バージョンを指定しないと最新バージョンが適応されます。
https://zenn.dev/asahina820/books/c29592e397a35b/viewer/0200eb#%E8%A7%A3%E8%AA%AC

**Comment by hfu** [comment]
ChatGPT と相談して書いてみました。（PMTiles の扱いを除く。）

```html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>style view</title>
<link href="https://unpkg.com/maplibre-gl/dist/maplibre-gl.css" rel="stylesheet" />
<style>
  body { margin: 0; padding: 0; }
  #map { position: absolute; top: 0; bottom: 0; width: 100%; }
</style>
</head>
<body>
<div id="map"></div>
<script src="https://unpkg.com/maplibre-gl/dist/maplibre-gl.js"></script>
<script>
document.addEventListener('DOMContentLoaded', function () {
    const urlParams = new URLSearchParams(window.location.search)
    const styleUrl = urlParams.get('style') || 'https://optgeo.github.io/terrain22/style.json'

    const map = new maplibregl.Map({
        container: 'map',
        style: styleUrl,
        hash: true
    })
})
</script>
</body>
</html>
```

夕食後、リポジトリを作って本格に始めてみます。

**Comment by albertkun** [comment]
多分、pmtilesのことはこのmaplibre.glのドキュメントでいいかな？　https://maplibre.org/maplibre-gl-js/docs/examples/pmtiles/

@hfu がレポジトリー作った後で僕が調べって見ようかも！

**Comment by hfu** [comment]
@albertkun ありがとう！Observable 上では https://observablehq.com/d/e66dd18a3be303c7 で

```javascript
maplibregl = {
  let m = await require("maplibre-gl")
  let p = await import("https://cdn.skypack.dev/pmtiles")
  let protocol = new p.Protocol()
  m.addProtocol('pmtiles', protocol.tile)
  yield m
}
```

という形でロードできているので、これに沿って ES モジュールとして pmtiles をインポートするコードを書いてみます。

**Comment by hfu** [comment]
```
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>style view</title>
<link href="https://unpkg.com/maplibre-gl/dist/maplibre-gl.css" rel="stylesheet" />
<style>
  body { margin: 0; padding: 0; }
  #map { position: absolute; top: 0; bottom: 0; width: 100%; }
</style>
</head>
<body>
<div id="map"></div>
<script src="https://unpkg.com/maplibre-gl/dist/maplibre-gl.js"></script>
<script type="module">
import { Protocol } from 'https://cdn.skypack.dev/pmtiles'

document.addEventListener('DOMContentLoaded', function () {
    maplibregl.addProtocol('pmtiles', (new Protocol()).tile)
    const urlParams = new URLSearchParams(window.location.search)
    const styleUrl = urlParams.get('style') || 'https://optgeo.github.io/terrain22/style.json'

    const map = new maplibregl.Map({
        container: 'map',
        style: styleUrl,
        hash: true
    })
})
</script>
</body>
</html>
```
これで進めてみます。

**Comment by hfu** [comment]
unopengis/stylehub という名前でリポジトリ作ります。

**Comment by hfu** [comment]
うまくいきました！

https://unopengis.github.io/stylehub/#9.55/14.0564/101.1642/-133/59

<img width="1240" alt="スクリーンショット 2024-07-10 20 43 21" src="https://github.com/UNopenGIS/7/assets/18297/8efe160b-ffa8-455d-8634-655bad5ce740">

**Comment by hfu** [comment]
より設計通りの URL は、https://unopengis.github.io/stylehub/?style=https://optgeo.github.io/terrain22/style.json#9.55/14.0564/101.1642/-133/59 です。

**Comment by hfu** [comment]
リポジトリは https://github.com/unopengis/stylehub でした。うまくいっているようなのでイシューはクローズします。
ありがとうございました！

**Comment by hfu** [comment]
ここで作ったシンプルサイトをベースに、Observable から terrain22 の凡例を表示するコードを追加し、 https://optgeo.github.io/terrain22/index.html にする。

**Comment by hfu** [comment]
実装できました！
https://optgeo.github.io/terrain22/#10.85/32.8637/131.0435/47.2/59
<img width="1506" alt="スクリーンショット 2024-07-11 21 32 13" src="https://github.com/UNopenGIS/7/assets/18297/89f1589b-adc6-4f56-9898-99e1275042ca">
