### ISSUE TITLE
[info] ウィキメディア運動憲章への批准

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#550]
[![Image from Gyazo](https://i.gyazo.com/56e8901d78951f3f7011805bd1da40a1.png)](https://gyazo.com/56e8901d78951f3f7011805bd1da40a1)

[![Image from Gyazo](https://i.gyazo.com/86117a4f0b3d2814297c00a7ecb86434.png)](https://gyazo.com/86117a4f0b3d2814297c00a7ecb86434)

- https://meta.wikimedia.org/wiki/Movement_Charter
- https://meta.wikimedia.org/wiki/Movement_Charter/ja

[![Image from Gyazo](https://i.gyazo.com/04d1d193dedbc02e84cf6e25fb7ec295.png)](https://gyazo.com/04d1d193dedbc02e84cf6e25fb7ec295)

[![Image from Gyazo](https://i.gyazo.com/fd852d681c39ec4d8a300c19994f3ec6.png)](https://gyazo.com/fd852d681c39ec4d8a300c19994f3ec6)

***投票できないのになんで投票のバナー表示されてるん！？***

**Comment by hfu** [comment]
なるほど。憲章のテキストについて理解をしておこうと思います！

https://meta.wikimedia.org/wiki/Movement_Charter/ja
