### ISSUE TITLE
Create FlatGeobuf of power line data from optimal_bvmap-v1.pmtiles

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#554]
- source: https://cyberjapandata.gsi.go.jp/xyz/optimal_bvmap-v1/optimal_bvmap-v1.pmtiles
- source zoom level: 16 (= maxzoom)
- target repository: https://github.com/optgeo/flatgeobuf-powerline

@office-shirado, please review.

**Comment by office-shirado** [comment]
日本語でスミマセン。

私の環境は、Windows11 DockerでTippecanoeを動かしています。

PMTilesから、「送電線」・「建築物」などを取り出し、GeoJSONからogr2ogrでFlatGeobuf（.fgb）を作成しました。

【Tippecanoe】
tippecanoe-decode /data/test/optimal_bvmap-v1.pmtiles -l PwrTrnsmL -Z 16 | tippecanoe-json-tool > /data/test/optimal_bvmap-v1.geojson

optimal_bvmap-v1.pmtiles：国土地理院からダウンロードしたPMTiles
PwrTrnsmL：送電線のレイヤ
optimal_bvmap-v1.geojson：tippecanoe-decodeで抽出して保存したGeoJSON

optimal_bvmap-v1.geojsonができたら、次のコマンドを流します。
※コマンドプロンプトはそのまま利用
【ogr2ogr】
ogr2ogr -f FlatGeobuf /data/test/test.fgb /data/test/optimal_bvmap-v1.geojson
test.fgb：作成されるFlatGeobuf（.fgb）

建築物はかなり数が多い（6,700万ポリゴン）ので、注意してください。

レイヤ名・ズームレベル等は、
https://maps.gsi.go.jp/help/pdf/vector/optbv_featurecodes.pdf
が参考になるかと思います。

また、PMTiles Viewer
https://pmtiles.io/
で、絵柄を見ながら確認するのもありかと思います。

**Comment by hfu** [comment]
@office-shirado ありがとうございます！

※unopengis/7 の issues は言語自由なので、日本語も大歓迎です！
