### ISSUE TITLE
Include Google Open Buildings into FOIL4G

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#559]
@yuiseki Do you think we can include Google Open Buildings (PMTiles) into FOIL4G?

PMTiles data is available from https://beta.source.coop/cholmes/google-open-buildings/google-open-buildings.pmtiles and we can preview the data as in: 

https://unopengis.github.io/PMTiles/?url=https%3A%2F%2Fdata.source.coop%2Fcholmes%2Fgoogle-open-buildings%2Fgoogle-open-buildings.pmtiles#map=16.94/13.35968/103.881549

Same apply for Overture Buidings and Microsoft Buildings, but I think they should be handled in separate issues.

**Comment by yuiseki** [comment]
@hfu Sure! Thank you for your suggestion! and I've done!

- https://unopengis.github.io/foil4g/?path=/story/components-datasets-googleopenbuildings--preview

Feel free to make pull request to change initial lang, lat and zoom level!

- https://github.com/UNopenGIS/foil4g/blob/main/src/components/Datasets/GoogleOpenBuildings/index.tsx

**Comment by hfu** [comment]
Thank you @yuiseki! I also create a pull request. It was a good opportunity for me to learn!
