### ISSUE TITLE
Can we automate weekly/monthly meetup issue creation with GitHub Actions?

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#561]
## きっかけ
7/issues を整理して見通しをよくしようとしていたところ、weekly meetup の issues を貯めているところが見通しを悪くしているのではないかと感じました。

## ヒント
Ben Balter の https://github.com/benbalter/schedule-discussion-posts-action がヒントになるかもしれないと思っています。

### 週例ミートアップについて
1. 毎週火曜日の15時ころに、来週火曜日の issues が自動的にオープンされる。そのイシューでは、@hfu がアサインされており、meepup のラベルが付与されている。
1. 同火曜日の14時ころに、今週のミートアップ issue が自動的にクローズする。

### 月例ミートアップ (Smart Maps Meetup Pacific) について
@albertkun 何か考えありますか？

## 課題
- @hfu には GitHub Action のノウハウがない。

**Comment by albertkun** [comment]
@hfu いいアイデアと思う！ミットアップのイッシューの内容説明したら（タイトルとか番号とか）、僕がテンプレート作ります！

**Comment by hfu** [comment]
@albertkun ありがとう！GitHub Action 化したイシューの内容は、こんな感じになるといいと思います。
第何回かということは、調べたい時に調べればいいかなと思ったので、ドラフトのような形で十分だなと思いました。

- meetup のラベルも自動でつくといいなと思います。
- 接続アドレスを書き換える方法が分かっていると安心です。

# ドラフト

## 202x-xx-xxT12:30/12:55+09:00 🖐Smart Maps Meetup Weekly
### 接続アドレス
https://teams.microsoft.com/l/meetup-join/19%3ameeting_YWNjZDBlNDMtY2RiNi00YjE5LTkyMzYtMWI5MjE2NzM3NTU5%40thread.v2/0?context=%7b%22Tid%22%3a%22eba9fc42-5588-4d31-8a4e-6e1bf79d31c0%22%2c%22Oid%22%3a%22265cf6f7-5673-4ef0-93bc-ebb87d669a75%22%7d

会議 ID: 429 235 468 444 
パスコード: EZycz3 

毎週火曜日に実施しています。

**Comment by hfu** [comment]
本件の実施は、10月1日までで大丈夫。急ぐ必要はないと思っています。

**Comment by albertkun** [comment]
Sorry, I will try to have this up tonight! Currently traveling in Japan with family!

**Comment by albertkun** [comment]
@hfu can confirm if automation is working?

**Comment by hfu** [comment]
@albertkun Sorry for a late response. I see some error happening... 

<img width="678" alt="image" src="https://github.com/user-attachments/assets/d50c1824-a991-431e-8489-b7ef8e366c39">

**Comment by albertkun** [comment]
@hfu ok, no problem! it should be fixed now! here's the automatically created issue https://github.com/UNopenGIS/7/issues/577

**Comment by hfu** [comment]
@albertkun Thank you! I confirmed that we have #577 now! This looks great!

**Comment by albertkun** [comment]
@hfu nice! i think we can mark this issue as resolved and closed then?

**Comment by hfu** [comment]
Yes, thank you. I close this issue as successfully resolved.
