### ISSUE TITLE
UN Open GIS Monthly meeting 2023-01-24T23:00/24:30+09:00（TBD）

### ISSUE THREAD

**Issue by ubukawa** [UNopenGIS/7#58]
1月のUN Open GISの月例会は24日（火）になる方向で調整が進んでいます。
まだ私のところにもMeeting invitation がきていませんが、ご参考にお知らせします。

またミーティングの招待は来ていないので、日時が確定してリンクがきましたら共有します。

**Comment by hfu** [comment]
情報ありがとうございます。その後、案内がありましたね。
今回、鵜生川さんの方で少しまとめて話をされたりしますか？その場合、そちらを中心にしたいと思います。
その後ろあたりに、FOSS4G 2023 Prizren への発表提案の話 #47 を入れようかなと思います。

**Comment by ubukawa** [comment]
ありがとうございます。
私の方では、いろいろと作業中のものが多いのですが、スライド1枚は出せると思います。
 Pre-productionの作業に加え、技術移転資料を２つ準備したこと、かなとイメージしています。
金曜の午後に作業してみます。

ラズベリーパイの実験結果の報告もやりたいことリストにはあるのですが、今回は間に合わないです。
（忘れないようにここに書いておきます。）

よろしくお願いします。

**Comment by ubukawa** [comment]
たたき台のスライドをシェアしました。よろしくお願いします。
（@hfu さん、 @yuiseki さん、模擬国連を紹介するかどうか、お考えがあればおしらせください！）

**Comment by hfu** [comment]
私は、模擬国連については急ぎすぎる必要はなく、大きく構えておいて最も効果的なタイミングでインパクトを出すということで良いように思っています。いかがでしょう。

**Comment by ubukawa** [comment]
お世話になります。模擬国連についての方針承知しました。今後、最も効果的なタイミングでとのことですね。引き続きよろしくお願いします。

**Comment by hfu** [comment]
## 発表資料
- https://hackmd.io/@hfu/dwg7-2023-01#/
- https://hackmd.io/sYF6zDTdRheWn8F8kG-n9w

**Comment by yuiseki** [comment]
お疲れ様でした！
今回も非常に勉強になり、刺激になりました…！！

本日のディスカッションに関連して、 #61 を立てました。
また、AOBで話題になった #62 も立てさせていただきました。
各Issueで詳細をお話していければと思います。
よろしくお願いします。

**Comment by hfu** [comment]
おつかれさまでした！
