### ISSUE TITLE
UNVT Portable Hands-on 2024 Oct 08 @ PoliMI

### ISSUE THREAD

**Issue by mapconcierge** [UNopenGIS/7#588]
# Updating now...
 * UNVT Portable repo. https://github.com/unvt/portable

## Making Sample Dataset...
 * 128GB SDcard: https://github.com/mapconcierge/unvtportable2024dataset4test

# Leaflet
![UNVTPortableHands-on2024PoliMI_final20240925a](https://github.com/user-attachments/assets/cab21e93-69a7-4c0c-bb06-9cbc0842c44c)

**Comment by hfu** [comment]
完了おつかれさまでした！
