### ISSUE TITLE
CaddyでRaspberry PiをSSL（https）化

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#592]
From:
- https://github.com/UNopenGIS/7/issues/586#issuecomment-2397155698

## Caddy
- https://caddyserver.com/
- https://caddyserver.com/docs/install

**Comment by hfu** [comment]
ローカルホストでも HTTPS をということを明示されているのはすごく嬉しいです！

「HTTPS を使える＝HTTP/2（以降）を使える＝HTTP 1.1を使うのと比べればウェブ地図が速くなる可能性がある」ということが期待できて、ワクワクします。

<img width="456" alt="image" src="https://github.com/user-attachments/assets/9c00be4a-0015-436c-8d5d-a71ba4545679">

source: https://caddyserver.com/

**Comment by hfu** [comment]
## Raspberry Pi OS 上でやってみました！
### 導入方法
```
sudo apt install caddy
```
### 素晴らしい点
- HTTP/3 で動いてくれるからか、busybox の httpd を使う場合と比べて、性能がかなり高まりました🚀
- 証明書の取得も問題なく実施してくれました🚀
### 認識しておくことが必要な点
- service で動かそうとすると、色々と細かな問題が起きます。例えば、証明書を作成するのに sudo するが、それでエラーになる、といったものです。systemctl service disable caddy をして、サービスとして動かすことは諦めました。
- 自分で `sudo caddy run --config /etc/caddy/Caddyfile` して動かす範囲ではとても快適です。
### /etc/caddy/Caddyfile
今のところ、このようにしています。共有まで。
```
portable.local {
    root * /home/local/h3log/docs
    file_server
    encode gzip
    header {
        Access-Control-Allow-Origin "*"
        Access-Control-Allow-Methods "GET, POST, OPTIONS"
        Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept"
    }
    tls internal
}
```

**Comment by hfu** [comment]
h3log で実用を開始したので、priority を上げます。

**Comment by hfu** [comment]
Smart Maps Portable の HTTPS 化（HTTP/3化）から勇気を得て、点群3D TilesをSmart Maps Portable でホストしたら速いのではないかと思い、現在 Source Cooperative からオープン・ナガサキ点群を里帰りさせつつ、実験を進めています。
多分、速いです。

<img width="1225" alt="image" src="https://github.com/user-attachments/assets/80862503-6d6f-45fb-a59a-6549e0592100">

**Comment by hfu** [comment]
すでに実用しているので、イシューとしては閉じることにします。
素晴らしい情報、ありがとうございました！
