### ISSUE TITLE
2024-10-24T09:15/10:00 ISPRS TC4 Symposium 基調講演

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#594]
See also: #391 

## 諸元（主催者側の案内）
- We have over 300 registrations and looking forward to welcome you to Fremantle.
- Wu Chen and Hidenory Fujimura: during the keynote 3 session, Thu 8:30 – 10:00 (so yours is 9:15 to 10:00)
- They are also listed in the program: https://www.conftool.pro/tc4-symposium2024/sessions.php
- All keynote sessions will take place in the Plenary room (Great Southern Ballroom).
- Please be at the speaker’s prep area/media room at least 15 minutes before the presentation. 
- The slides should be uploaded in the media room. You will be able to control your slides from the computer in the plenary.
- Please prepare a talk for about 30-35 minutes and leave 7-8 minutes for Q&A and discussion.

### UN Smart Maps: An Open Initiative for Data Fusion
What if we can limitlessly import geospatial data on the web without having a web server, and in addition make them portable to anywhere? Or what if there are natural language interface to the web map resources so that we can combine different geospatial data in a nicely styled way? The United Nations Smart Maps Group is a participatory initiative to test new technologies like Interplanetary File System (IPFS) or Large Language Models (LLMs) for future geospatial data operations with a vision to keep web maps open for a better world. We present the status of our community of practice.

## 概要（プレゼンに膨らませるために日本語にして書き足しているもの）
インターネットから自由に、地理空間情報を無制限に取り込み、ウェブ地図をどこにでも持ち運べるようにしたらどうでしょうか。ウェブ地図リソースに自然言語インタフェースがあり、様々な地理空間情報を美しくスタイル化して組み合わせることができたらどうでしょうか。国連スマート地図グループは、将来の地理空間情報の運用のために、クラウドネイティブフォーマットやIPFSやLLMsなどの新技術をテストする参加型イニシアティブです。ウェブ地図をより良い世界のためにオープンに保つことをビジョンとしています。クラウドネイティブな地理空間情報が様々なプラットフォームを自在に乗り換えられるようにすることで、地理空間情報の可用性を高めます。UN Smart Maps Portable は、Raspberry Pi 4B ベースのバッテリーで駆動するウェブサーバーです。JICAの技術協力プロジェクトにも対応し、衛星測位の能力を高めることを計画しています。皆様の参加を歓迎します。

## 方針案
基本、次の方向で進めようと思っていますが、提案・批判を歓迎します。
- ISPRS は研究者と実践家のイベントとして標榜されているが、私は実践家のポジションに徹する。学術的新規性を評価されるような話は基本的には行わない方向で考えてみたい。
- 旅費スポンサーの関係で、スライドのテンプレートは JICA のものを使わせていただきます。

## 皆様からのヘルプを得たい事項
- [x] LLM の話題で紹介するべきもののアドバイスがあればお願いします。すでに実施済みの話題から推薦いただいてもありがたいですし、ならばせっかくということで新ネタをいただいてもありがたいです。 > @yuiseki 

だんだんと充実させていきます。
この前日に FOSS4G Perth での講演があり、こちらでは UN Smart Maps Portable の実演と技術解説を中心にしたいと思っています。

**Comment by hfu** [comment]
@yuiseki LLM ラインの最新は、"Promote the automatic processing of geospatial information by generative AI" をゴールとしている FOIL4G である、というストーリーで組んでいこうかなと思っています。

**Comment by yuiseki** [comment]
## 用語について

- LLM、LLMsという用語は、そろそろ封印したほうが良さそうです
- 既にその傾向はありますが、今後は、言語のみを扱うのではない、マルチモーダルな生成AIが主流のトレンドになっていくと思われます
- 言語のみのAIは、むしろ、小規模言語モデル（SLM）のような形で普及していきそうです
- いずれにしても、今後は、生成AI、Generative AIあるいはGenAIといった表現に統一したほうが良さそうです

## ISPRSにおける、国連スマート地図グループとしての、生成AIに関する取り組みのアピール
- 国連スマート地図グループでは、新技術をテストするというミッションに基づいて、生成AIを地理空間情報分野にも積極的に活用するためのチャレンジを続けています
- Retrieval
  - 生成AIを活用して、自然言語に基づいて地理空間情報を取得する
    - TRIDENTがやっていること
- Visualization
  - 生成AIを活用して、自然言語に基づいて地理空間情報を可視化する
    - TRIDENTがやっていること
    - charites-aiがより深くやっていること
- Analysis
  - 生成AIを活用して、自然言語に基づいて地理空間情報を分析する
  - 現在重視している壁
  - DuckDB-Wasm + DuckDB-Spatialによって可能性が広がった
- 今後の更なる展望
  - 人工衛星データのオープン化が必要。せめて人道支援のためだけでも。データさえあれば私たちはやってみせます
  - 地理空間情報の異常検知や時系列分析、あるいは、地理空間情報と人々とのインターフェイスとして、生成AIを応用していけないだろうか
- まとめ
  - 国連スマート地図グループは、生成AIを、国際平和の維持、気候変動の影響による自然災害対応、感染症の対応といった、人類が直面する深刻かつ複雑な問題を、人類と共に乗り越えていく、心強い仲間としていくことを目指しています

**Comment by hfu** [comment]
貴重なコメントありがとうございます。今後、LLM として表現していたことを、Generative AI と表現していこうと思います。

これに連動させて、IPFS として表現していたことを、Portable Web と表現してみようかと考えています。cloud-native なフォーマットによって portable になった geospatial information を、IPFS も含む様々な技術を使って portable にしていくという考えを全面化してみようと思います。

人工衛星のオープン化については、ご案内の通り Landsat と Sentinel が熱いと思っています。私自身は、 https://apps.sentinel-hub.com/eo-browser/ をよく使っています。まずは自分の目で理解を進めていこうと思っています。他方で、機械向けのインタフェースは、多分 STAC なのだろうと思っており、この辺り掘り下げていけそうですね。

**Comment by yuiseki** [comment]
@hfu すみません、お恥ずかしいことに、 `ISPRS Technical Commission IV Symposium` の立ち位置を大幅に勘違いしていました！

ISPRSが `International Society for Photogrammetry and Remote Sensing` の略なので、上の私の投稿ではリモートセンシングの話題を無理にねじ込むような感じにしてしまっていたのですが、ISPRSのなかでも、 `Technical Commission IV` は `Spatial Information Science` 、空間情報科学に特化し、GISや空間データベース、空間データインフラストラクチャ、スマートシティや3D都市モデリングなど、 **地理空間情報技術の応用や統合** に焦点を当てているのですね。

であれば、「人工衛星データのオープン化が必要」のような主張を無理にねじ込まなくても良いかと考え直しました。お恥ずかしい限りです 😅 

また、STACについても調べてみたところ、ここ数年の人工衛星データのオープン化や機械可読かつ相互運用性を重視したデータフォーマットの標準化の取り組みが素晴らしく進展していることもわかりました。ここは私の知識のアップデート不足と実践不足でした！

**Comment by mapconcierge** [comment]
UNVT Portable @ ミラノ工科大学 資料（集合写真あり）
https://github.com/unvt/portable/issues/29

**Comment by mapconcierge** [comment]
# SDカード比較（512GBがターゲット）
https://github.com/unvt/portable/issues/30

**Comment by hfu** [comment]
この内容で実施しました。ご助言ありがとうございました！
[THU_KEYNOTE_FUJIMURA.pdf](https://github.com/user-attachments/files/17502246/THU_KEYNOTE_FUJIMURA.pdf)
