### ISSUE TITLE
2024-10-17: UN Open GIS VTC 17 October 2024

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#595]
資料作成を開始しました。
https://hackmd.io/@smartmaps/2024-10#/

## 2024-10-16 追記：アジェンダ
Please note that the UN Open GIS meeting will take place on Thursday, 17 October 2024, at 9 am New York time (3 pm Rome or 10 pm Seoul time)
 
The tentative agenda is as follows:
1. Opening by Co-Chairs (Ki-Joune Li, Maria Brovelli and Josep Parareda)
2. Introduction of new members
3. Open Q&As and discussions
4. Working Group report
•	DWG-1 Hybrid GIS platform (Timur, Zeeshan, Epa/Rodwell, Akbar, #Cung);
•	Mobile GIS Solutions, including integration with Azure AD (Epa/Rodwell, Zeeshan, Cung)
•	UNMISS Story Map (Zahurul/Akbar/Debasish, Timur)
•	DWG-2 Capacity Building (Ivan, Susan, Diego);
•	DWG-5 Geo-AI & Analytics (Zhongxin, Maria (optional), Andrea, #Cung)
•	DWG-6 OpenDroneMap & 3D (Catalina, Davide, #Cung)
•	DWG-7 Smart Maps (Hidenori, Diego, #Timur)
5. Any other business (AOB)
•	FOSS4G 2024 Conference

**Comment by yuiseki** [comment]
- https://github.com/UNopenGIS/7/issues/599

これはUN Open GIS Monthly Meetingで共有に値する情報だと思います

**Comment by hfu** [comment]
私の方でスライドをまとめて発表するのがデフォルトだと思っていますが、当日発言をされたい方はいらっしゃいますか？

おられる場合には私から振って発言をお願いしたいと思っています。

（私の想定では、@mapconcierge 、@yuiseki からはもしご発言のご希望があれば振りたいと思っています。）

**Comment by hfu** [comment]
とりあえずプレゼンの第一原稿を作ってみました。
（これまでは HackMD で作っていたのですが、試しに別のソフトウェアで作ってみました。やはり HackMD に戻すかもしれません。）

[2024-10-smart-maps-report.pdf](https://github.com/user-attachments/files/17355602/2024-10-smart-maps-report.pdf)

**Comment by hfu** [comment]
HackMD への転写を進めています。
これまで通り HackMD で実施しようかと思っています。
https://hackmd.io/@smartmaps/2024-10#/

**Comment by hfu** [comment]
割とサクッとした仕上がりにしましたが、月例はこのくらいの分量にしようかと思っているところです。
https://hackmd.io/@smartmaps/2024-10#/
もちろん、内容の追加や発言の立候補は引き続き歓迎します！

**Comment by yuiseki** [comment]
## DuckDB-Wasm + DuckDB-Spatial の重要性
- 近年、生成AIの地理空間情報への応用に取り組んできた
- 生成AIによる高度な地理空間情報分析をアプリケーションとして提供することには問題があった
  - 高度な地理空間情報分析のためには、地理空間インデックスや地理空間クエリをサポートした、PostGISのようなデータベースが必要
  - しかし、生成AIが生成したクエリをPostGISに直接投入するのは危険すぎる
  - また、ユーザーの要望ごとにPostGISにデータを投入していくと際限なくデータが増加していき、コストの問題もある
  - ユーザー自身のブラウザ上で動く、サンドボックス化されたデータベースを、ずっと探し求めていた
    - クセがあったり、実験的なものしかなかった
    - 地理空間インデックスや地理空間クエリをサポートしているものがなかった
- DuckDB-Wasm + DuckDB-Spatial は、これらのすべての問題を解決できる
  - ただし、DuckDB-SpatialはまだStableリリースではない
- もちろん、DuckDB以外の他の技術の動向も引き続き調査していく

**Comment by hfu** [comment]
@yuiseki ありがとうございます。重要性の説明について、概略を英文にしてみました。

Our group has been working on the application of Generative AI. One of the mains idea is that the AI generates an SQL query for information retrieval or analysis. One of the challenge is that we need a sandboxed spatial databases because we are not really sure about how safe it is to execute an SQL query generated by AI. 

That is why we are excited to test DuckDB in Web Assembly with Spatial extension enabled. Yuiseki has tested several functions and the result seems promising. We will be exploring along with this line including technologies other than DuckDB. 

少しずつ改善しながらデリバーしていこうと思います。

**Comment by hfu** [comment]
@mapconcierge のワークショップへの言及もマリア先生からありましたし、@yuiseki さんの https://yuiseki.github.io/study-duckdb-wasm-spatial/ のインパクトが非常に高かったです！

みなさんからのインプットのおかげで、大変誇らしい思いをさせていただきました。ありがとうございました！
