### ISSUE TITLE
DuckDB-Wasm + DuckDB-Spatial = Webブラウザ上で完結する地理空間情報分析

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#599]
## DuckDB-Wasm + DuckDB-Spatial

- Demo
  - https://yuiseki.github.io/study-duckdb-wasm-spatial/
- Source code
  - https://github.com/yuiseki/study-duckdb-wasm-spatial

https://github.com/user-attachments/assets/27c0c738-490f-48d6-9be5-12976d6eb0e5

https://gyazo.com/75ba58139f88732f4ba2dcaa5a987501

## 特筆すべき点 | Noteworthy Points

- ブラウザさえあればいい
  - データベースサーバーが不要
  - 特別なソフトウェアも不要
    - ターミナルでコマンドを実行する必要なし
    - Pythonでコードを書く必要なし

## 今後について | What's Next

- 生成AIが、与えられたデータと自然言語の指示に基づいて、地理空間情報分析クエリを書く
  - これまではOverpass APIを通じて地物を取得するだけだった
  - 「東京都で一番人口が多い区はどこ？」
  - 「台東区で一番広い公園はどこ？」
  - のような質問に応答させることが、技術的には可能なはず
- OpenStreetMapには掲載が禁じられている、一時的な地理空間情報を扱える可能性もある

## 参考文献 | References

- DuckDB-Wasm
  - https://duckdb.org/docs/api/wasm/overview.html
  - https://github.com/duckdb/duckdb-wasm
- DuckDB-Spatial
  - https://duckdb.org/docs/extensions/spatial/overview.html
  - https://github.com/duckdb/duckdb_spatial

**Comment by hfu** [comment]
本件、少し追っていきましょう。とりあえず SHOULD に priority づけしますが、今後の流れの中で priority を上げるかもしれません。ありがとうございます！

**Comment by yuiseki** [comment]
デモ及び情報共有の役割は果たして次のステップに進んでいるので、閉じます
