### ISSUE TITLE
Prepare for SotM Asia to present UNVT Portable

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#6]
2022-11-21/25

**Comment by hfu** [comment]
We may be able to combine efforts with #7 and #2.

**Comment by mapconcierge** [comment]
# Speakers
* Taichi Furuhashi, @mapconcierge 
* Shogo Hirasawa, @ShogoHirasawa

**Comment by hfu** [comment]
I congratulate the successful completion of SotM Asia 2022. 

I still appreciate any update from @mapconcierge and @ShogoHirasawa here, but I know we can discuss online in the upcoming https://github.com/UNopenGIS/7/issues/29. So I close this issue.
