### ISSUE TITLE
Remote sensing × Computer vision meta survey

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#600]
- https://hirokatsukataoka.net/temp/presen/241011RemoteSensing_MetaSurvey2024.pdf
- 日本のリモートセンシング分野において最先端のAIモデルが使われていないのはなぜかという考察が興味深かったです

**Comment by hfu** [comment]
共有ありがとうございます！
確かに、我々の近くの remote sensing は、①需要不足、②過剰計画に囲まれているような気がします。
MMLLMが出てくるところがカッコいい資料だ、と思いました。

**Comment by yuiseki** [comment]
情報共有の役割は果たしたので閉じます
