### ISSUE TITLE
OSC2024 Tokyo/Fall

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#603]
## 諸元
- https://event.ospn.jp/osc2024-fall/
- 10月26日(土) 10:00-16:00

## コメント
- OSGeoとして展示するならお手伝いします

**Comment by smellman** [comment]
@yuiseki 展示します！
あと非公式懇親会情報です: https://svrkcho.connpass.com/event/326766/

**Comment by smellman** [comment]
@yuiseki OSGeo.JPのslackに情報流しておきました。
ブースの大きさによりますが、wasm+duckdbのデモなど出来たらお願いしたい。

**Comment by yuiseki** [comment]
@smellman ありがとうございます！！wasm+duckdbのデモ、やれます、やらせてください、もっと面白いの作っておきます
