### ISSUE TITLE
OPFS: Origin Private File System

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#609]
## What

- https://developer.mozilla.org/en-US/docs/Web/API/File_System_API/Origin_private_file_system
- https://developer.mozilla.org/ja/docs/Web/API/File_System_API/Origin_private_file_system
- https://zenn.dev/cybozu_frontend/articles/origin-private-file-system
- https://webfrontend.ninja/js-file-system-access-origin-private-file-system/

## Demo

- https://yuiseki.github.io/study-opfs/
- https://github.com/yuiseki/study-opfs

## Why

- A chance for charites to be completed in the web browser?

**Comment by hfu** [comment]
本件 #613 に合流したということで、クローズしましょうか？

**Comment by yuiseki** [comment]
コメントありがとうございます！そうしましょう！
