### ISSUE TITLE
2024-12-19 UN Smart Maps Group懇親会🍺

### ISSUE THREAD

**Issue by k96mz** [UNopenGIS/7#614]
UN Smart Maps Groupの懇親会を計画しています！

日程：12/19（木）or 12/20（金）の夜（19時位開始？）
場所：都内のどこか集まりやすいところ

# やること
- [x] 日程確定（どちらの日程が良いか等教えてください）
- [x] 場所確定（都合の良い場所を教えてください）
- [x] お店予約（希望があれば教えてください）

**Comment by yuiseki** [comment]
- 前回同様、我が家も可能です

**Comment by smellman** [comment]
個人的には12/20(金)は弊社の忘年会があるため、19(木)が良いです。

**Comment by hfu** [comment]
私も、2024-12-19T19:00 のラインで参加できる可能性が高まりました。

**Comment by yuiseki** [comment]
- 日時：2024-12-19T18:00から開場
- 会場：yuiseki宅（台東区竜泉。最寄り駅：日比谷線三ノ輪駅）
- 備考：好きな時間に来て好きな時間に返ってヨシ

**Comment by yuiseki** [comment]
@smellman @hfu Google Calendarで招待を送りました。
@k96mz Google Calendar経由で住所を共有しますので、Googleアカウントのメールアドレスを yuiseki@gmail.com まで教えてください。

**Comment by k96mz** [comment]
@yuiseki 
ありがとうございます。先程、yuiseki@gmail.com 宛てに私のGoogleアカウントのメールアドレスをお送りしました！

**Comment by hfu** [comment]
- 開発用PCの持参を推奨

**Comment by yuiseki** [comment]
すみません、Gmailで送るよりもIssueのほうが手軽なのでこちらで改めて連絡します

- 2024-12-19 18:00からいつでも来てOK、いつ帰ってもOKです
- ピザを注文しようかと思っています
- お酒はウイスキーとジンしかないので、それ以外を飲みたい方がいたら持参をお願いしたいです
  - ウイスキーとジンは山ほどあります
  - 割るための炭酸もあります
- 開発用PCの持参推奨です！

本日はよろしくお願いします！

**Comment by hfu** [comment]
19:00前後に到着予定です

**Comment by hfu** [comment]
おつかれさまでした！
