### ISSUE TITLE
(Hackathon) Satellite Data Days

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#618]
- https://lu.ma/vnnro5q4?tk=VwQbqI
- 2024年11月11日から、2024年11月28日
- yuisekiが参加中
- 人工衛星データが触りまくれる
- アウトプット予定のリポジトリ
  - https://github.com/algomatic-inc/sd-team-nobushi

**Comment by hfu** [comment]
素晴らしいですね！

雑談までに、コンゴ民主共和国の国立リモートセンシングセンターの敷地内の施設の増え具合を調べるというタスクをやっていました。Sentinel-2 レベルではわかりにくいですが、Rapid Editor に提供されているレベルの画像を使うと、箱型の建物が増えている様子が分かりました。具体個別にモニタリングするようなタスクにはある程度ニーズがあるようです。

参考： https://rapideditor.org/edit#map=20.25/-4.31778/15.27952&background=EsriWayback_2023-10-11&datasets=fbRoads,msBuildings&disable_features=boundaries
参考： https://sentinelshare.page.link/Y5fA ← サイトのレスポンスは早くない

逆に言えば、タスクを自然言語でまともに記述できることが、もしかしたらとても重要なのではないかと思いました。情報要求がクリアになっていることで、やるべき作業がよくわかる気がします。

**Comment by yuiseki** [comment]
メモです

- https://rapideditor.org/edit#map=20.25/-4.31838/15.27952&background=EsriWayback_2020-10-14&datasets=fbRoads,msBuildings&disable_features=boundaries

**Comment by yuiseki** [comment]
```
https://wayback.maptiles.arcgis.com/arcgis/rest/services/world_imagery/wmts/1.0.0/default028mm/mapserver//tile/{バージョンID}/{ズームレベル}/{X座標}/{Y座標}
```

おそらくこう

**Comment by yuiseki** [comment]
完了しました。受賞ならずでした！
得られた知見はZennなどでアウトプットしていきたいと思います。

閉じます
