### ISSUE TITLE
Webinar about Smart Maps, 2023-03

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#62]
#58 に参加してのフィードバックとしてのIssueです。

- UN Open GISにおいて、3月上旬に、Smart Mapsに関する短いWabinarの開催を計画しているとのこと
- ぜひ参加したい！
- なんならできることがあればぜひ手伝いたい！
- ということでIssue化しておきます！

**Comment by hfu** [comment]
#60 で、引き続き情報共有するということになりました。
