### ISSUE TITLE
(event) 「オープンソースAIの定義 v1.0」リリース記念解説会

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#620]
- https://lycorptech-jp.connpass.com/event/335145/
- yuisekiが参加予定
- 残り枠10名

**Comment by yuiseki** [comment]
閉じます

**Comment by hfu** [comment]
スライドを読むことができました。明晰ですね。

ライセンスと利用規約の関係についても言及についても明晰だと思いましたし、オープンソースの定義が広がるかもしれないという観測についてもなるほどと思いました。
