### ISSUE TITLE
[info] Raspberry Pi AI HAT

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#622]
https://www.raspberrypi.com/products/ai-hat/

**Comment by yuiseki** [comment]
公式ブログ、公式ドキュメント

- https://www.raspberrypi.com/news/raspberry-pi-ai-hat/
- https://www.raspberrypi.com/documentation/accessories/ai-kit.html
- https://www.raspberrypi.com/documentation/computers/ai.html

これらによるとLLM関連の話題は見当たらない

Edge Intelligenceという概念を提案する論文

- https://ieeexplore.ieee.org/document/10669603

**Comment by hfu** [comment]
@yuiseki ありがとうございます！

Edge Intelligence という概念について、おぼろげに知ることができました。
そこで、閉じます。
