### ISSUE TITLE
GAUL (Global Administrative Unit Layers) について知りたい

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#63]
- UN Open GISのMicrosoft Teamsで `Information Technology Officer (Geospatial Analysis), P-2, at FAO (Rome, Italy)` のJob Detailを見ていて、GAULというものの存在を知った
- GAULはFAOが独自で~~運用している~~2015年まで運用していた？ようだが、
  - GAULは現在も更新され運用されているのかが気になる
    - Job Detailに書かれているということは更新され活用されてはいるのだろうが……
    - GAULはなぜ2015年までしか公開されていないのか知りたい
  - GAULはUNHQやUNGSCでも使われているのか知りたい
    - UNHQやUNGSCは、Administrative boundariesについて、GAULを継承したデータを構築し運用しているのか、あるいはGAULとは全く別でデータを構築し運用しているのかを知りたい
  - GAULに代わるようなデータセットがあるのなら教えていただきたい
- GAULの理解や活用は、UN Open GIS DWG-7のスコープに入るか知りたい

該当Job Detail:
https://unjobs.org/vacancies/1674764216945
> Key Functions
> • Supports the key agro-informatics geospatial datasets and services including keeping GAUL (Global Administrative Unit Layers) up to date and aligned with UN boundaries;

参考リンク：
- https://en.wikipedia.org/wiki/Global_Administrative_Unit_Layers
- https://data.apps.fao.org/map/catalog/srv/eng/catalog.search#/home
  - https://data.apps.fao.org/map/catalog/srv/eng/catalog.search#/metadata/9c35ba10-5649-41c8-bdfc-eb78e9e65654
- https://developers.google.com/earth-engine/datasets/catalog/FAO_GAUL_2015_level1

**Comment by hfu** [comment]
ありがとうございます。DWG7 運営の観点から見ると、GAUL がオープンデータであるようには見えない以上、GAULの理解や活用は、GAUL を用いている内部ユーザからの依頼とデータ利用に関する取り決めを作らない限りは、UN Open GIS DWG-7 のスコープには入らないように思います。

**Comment by hfu** [comment]
@hfu 説明用
https://www.casleyconsulting.co.jp/blog/engineer/4334/
