### ISSUE TITLE
2024-12-04: UN Open GIS VTC 4 December 2024

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#630]
Prev:
- https://github.com/UNopenGIS/7/issues/595

**Comment by yuiseki** [comment]
## yuisekiからの伝達事項

### DuckDB

- https://github.com/UNopenGIS/7/issues/608
- https://trident.yuiseki.net/duckdb
- DuckDBと生成AIの融合に成功
  - 与えられた地理空間情報データベースに対するWebブラウザ上の安全なサンドボックス環境での質問応答が可能


### OPFS（Origin Private File System）

- https://github.com/UNopenGIS/7/issues/613
- https://github.com/UNopenGIS/7/issues/617
- https://trident.yuiseki.net/charites
- OPFSという新技術を発見
  - Webブラウザ上のサンドボックス環境でファイルシステムを構築可能
    - charitesのような地図スタイル編集が、ブラウザのみで可能になる
  - 生成AIとの融合も成功
    - ベクトルタイル地図に対するWebブラウザ上の安全なサンドボックス環境での対話的スタイル編集が可能


### 現在進行中のアプローチ（開発コードネーム： `trident-overdrive` ）

- Webブラウザ上でのサンドボックス環境で、安全に複数の地理空間情報分析や可視化の処理が実行可能なことが判明
- 生成AIに、自然言語での質問や会話に応じて適切なツールを選ばせる、そのツールで実行するべきコードを生成させる
- 選択したツールで、生成されたコードを、Webブラウザ上の安全なサンドボックス環境で実行する
- 実行結果を生成AIに与えて、返答させる、あるいは、さらに次のタスクを実行させる



### OSAID（The Open Source AI Definition） v1.0

- https://github.com/UNopenGIS/7/issues/620
- UN Open GIS Initiativeで生成AIの可能性を提案しているSmart Maps Groupにとっては非常に重要なもの
- Bad news
  - 現時点では、OSAIDに適合する生成AIで、実用的なものは、存在していない
  - FOSS4GなどでGISシステムと生成AIの融合事例を紹介していく際に、大きなハードルとなる
  - 一方で、GISコミュニティとして、生成AIのポテンシャルを見過ごすこともできない
- Good news
  - パラメーターの小規模な生成AIであっても、特定の用途に限れば、高い性能を発揮することが明らかになっている
  - 私には、GISに特化し、かつ、OSAIDに適合する、パラメーターの小規模な生成AIを開発する、充分なスキルと経験がある
- 今後について
  - 私は、OSAIDに適合する、国際平和と人道支援および地理空間情報処理に特化した実用的な生成AIを、独自で開発するプロジェクトを立ち上げた
  - https://scrapbox.io/YuisekinAI/YuisekinGeoAI_(draft)
  - もっと良い名前があったら教えてください 🙏

**Comment by hfu** [comment]
@yuiseki ありがとうございます！

## スライドの準備
https://hackmd.io/@smartmaps/2024-12 に作りました。
必要に応じて、編集も歓迎です。

## 内容の準備
構成を次のようにして、いただいた/いただけるインプットを入れていきたいと思います。

### アウトプット
ISPRS, FOSS4G Perth, 国家測量研修などのアウトプットの実績に言及しようと思います。

### アクティビティ
開発関係、サービス関係のアクティビティを入れてみたいと思います。

## プレゼン者
プレゼンを実施するご希望があれば教えてください！

**Comment by hfu** [comment]
プロダクトベースで考えると、次のように整理できるでしょうか。

- Generative AI の統合系である trident-overdrive
- OSAID準拠地理空間情報特化AIである YuisekinGeoAI （名前募集中→確かに、キャッチーな名前をつけたいです！）
- Smart Maps Module
- xing（クロッシング）

**Comment by hfu** [comment]
命名権は @yuiseki さんにあるところ越権的ですが、YuisekinGeoAI の名前について、次のように提案させてください。

## 提案「Smart Maps Lisa」
「Lisa」は、"Locally Implementable Spatial AI" の略として考えています。地理空間情報の活用をローカルに実装可能な（Locally Implementable）地理空間情報に特化した（Spatial）AI、という意味を込めていますが、読みやすさを重視しています。

また、「LISA」という名前は、過去の技術的影響を受けた歴史的な名称にもあやかっています。例えば、Appleの初期の製品「Apple Lisa」や、人工知能の歴史における象徴的なプログラムである「ELIZA」などが挙げられます。これらの技術革新へのオマージュを込め、プロジェクト名「Smart Maps Lisa」は、革新と信頼性を兼ね備えた名前としてふさわしいと考えます。

さらに、並行して進行中のtrident-**overdrive**プロジェクトも参照し、「Mona Lisa Overdrive」からもインスピレーションを得ています。サイバーパンク的なニュアンスを含んだ名前により、革新的でありながらも親しみやすい印象を与えることを意図しています。

**Comment by yuiseki** [comment]
- 名前の提案ありがとうございます！
  - とはいえ、ちょっと先走りすぎました
  - 別Issueに切り出しました
    - https://github.com/UNopenGIS/7/issues/631
  - 今月のVTCでは、一旦「検討・構想中」という状態を正直に伝えたいです
- 今週火曜日のWeekly Meetupに参加できない予定が入ってしまったので、同期的にお話ができない予感がしています

**Comment by yuiseki** [comment]
@hfu 突貫ですがスライド作りました。こちらの内容で良ければ5分だけ私に時間をください

https://docs.google.com/presentation/d/1woYFnUggsBf28-eM2-7AfKF08I2aOnydR36XtdG0bYw/edit?usp=sharing

**Comment by hfu** [comment]
@yuiseki 素晴らしい！Yuiseki さんにパスする形でお願いします。
本日の Smart Maps プレゼンは hfu -> yuiseki -> hfu の順番でパス回しする感じでいきましょう！

**Comment by hfu** [comment]
私のパートは、現時点の https://hackmd.io/@smartmaps/2024-12#/ でほぼ完成としたいと思います。
xing の話は温存してもSmart Maps Group の 2024-12 のインプットとしては十分、と判断しました！

**Comment by hfu** [comment]
@yuiseki Yuiseki さんのスライドは、差し支えなければ私の方で開くようにします。next と言ってもらえばスライドを送るようにします。

**Comment by yuiseki** [comment]
@hfu 可能であれば実際にデモをしたいんですが、hfuさんにお願いできますか？私が画面共有したほうが良いでしょうか？

**Comment by yuiseki** [comment]
念の為にスライド内にデモのスクリーンショットを含めておきました

**Comment by yuiseki** [comment]
発表のお時間をいただきありがとうございました！！

**Comment by hfu** [comment]
@yuiseki すみません！デモについてのコメントを見ることができずに本番に入ってしまいました。スクリーンショットを含めておいていただいて良かったです。デモ支援をできず恐縮でした。
それでも、インパクトのある、しかしコンパクトなプレゼンだったと思います。ありがとうございました！
