### ISSUE TITLE
`unmik-map-vite` を立ち上げる

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/7#66]
Issue化して自分をアサインしておきます

- 達成するべきこと
  - https://github.com/yuiseki/unmiss-map-vite と同じようなものの、UNMIK版の、GitHub Pagesへのリリース
    - UNMIK ＝ United Nations Interim Administration Mission in Kosovo, 国際連合コソボ暫定行政ミッション
- 目的
  - FOSS4G 2023, Prizren, Kosovo までにUNMIKのField MapをOSSで開発して触れるようにしておくことで、注目を集める、こういうものがあるんだ、こういうことができるんだと意識して頂けるようにする
- 締切
  - 目的に準じて、なるべく早く

**Comment by hfu** [comment]
FOSS4G 2023 用に言葉を考えてみました。
MUNDO: Model United Nations Development and Operations, 模擬国連開発運用あるいは模擬国連DevOpsというコンセプトでいかがでしょう。この言葉を使ってアブストラクトを書いてみます。

![ 2023-02-12 5 55 56](https://user-images.githubusercontent.com/18297/218280920-e818701c-9fea-4587-8a6f-4a61acfb6c31.jpg)

**Comment by yuiseki** [comment]
とりあえずコソボを対象に地域を切り替えてリポジトリを作ってGitHub Pagesにデプロイまでしておきました。

- https://github.com/yuiseki/unmik-map-vite/
- https://yuiseki.github.io/unmik-map-vite/

UNMIKの基地や施設、あるいはコソボ国内の国連施設が、OpenStreetMap上で適切にタグ付けされていないようです。
公開情報を元にOpenStreetMapを編集できないか調べてみます。

**Comment by yuiseki** [comment]
コソボにおける国連の活動を調査。

国連公式の情報源：
- https://unmik.unmissions.org/
  - https://unmik.unmissions.org/find-us
    - UNMIK Headquarters, Industrial Zone, 10 000 Pristina, Kosovo
  - https://unmik.unmissions.org/united-nations-office-belgrade
    - UNITED NATIONS OFFICE IN BELGRADE (UNOB), Tolstojeva 47-49, 11040 Belgrade, Republic of Serbia
  - https://unmik.unmissions.org/unmik-mitrovica-regional-office
    - 住所が明記されていない
- https://peacekeeping.un.org/en/mission/unmik
- https://kosovoteam.un.org/
  - https://kosovoteam.un.org/en/contact-us
    - Office of the UN Development Coordinator, United Nations Kosovo Team, 58 Zagreb Street 10000, Pristina, Kosovo
- https://www.un.org/geospatial/content/unmik-deployment-march-2022
  - https://www.un.org/geospatial/unite-web-topic/peace-operationsdeployment から辿れる最新のDeployment
    - やはり、コソボ国内の主要なDeploymentはPristinaとMitrovicaのみのようだ

余談。
調べていて知ったけど国連ベオグラード事務所の所長が2020年12月22日から日本人だし、模擬国連も経験しているんだ
- https://www.unic.or.jp/news_press/info/40895/
- https://press.un.org/en/2020/sga2000.doc.htm
- https://ja.wikipedia.org/wiki/%E5%B1%B1%E4%B8%8B%E7%9C%9F%E7%90%86

**Comment by yuiseki** [comment]
調べて理解したことを共有しておきます

- コソボにおける安全保障・平和維持・治安維持は、国連とは別にNATOのKFORが展開
  - KFORは国連・UNMIKとは指揮系統が全く別
  - KFORのDeploymentは軽く調べてもわからなかった
  - KFORという概念は重要なので、OpenStreetMapにある情報を集めてみて地図上で可視化してみたい
- UNMIKはコソボ国内の「国連警察（UNPOL）」を監督している
  - OpenStreetMapから警察の情報を持ってくることで可視化できるかもしれない
- UNMIKは司法・法治も監視する立場にあるので、裁判所も可視化できると良いかもしれない

**Comment by hfu** [comment]
おかげさまで、運用に至っているように思いますので、クローズします。
