### ISSUE TITLE
The IPO (Inter-planetary Operation: 惑星間大作戦)

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#67]
I am working on MinIO-based in-house object storage and IPFS again! https://qiita.com/hfu/items/412e3e290d40e4459487

**Comment by hfu** [comment]
うっかり IPFS ゲートウェイを開いて PMTiles ベースでベクトルタイルの提供を始めてしまった例

https://amx-project.github.io/a/ipfs.html

**Comment by hfu** [comment]
UNVT Portable で動かしているサーバの最新のログ

![image](https://user-images.githubusercontent.com/18297/217138242-b3928094-ae6f-48fc-9ec6-e0e334e9a2b7.png)

**Comment by hfu** [comment]
作業としては落ち着いてきたので、ドキュメントを出してからクローズするか、単にクローズします。

**Comment by yuiseki** [comment]
ちょっと不安定ですが、IPFSのローカルノードで小さいPMTilesをピンして、パブリックゲートウェイ経由で取得して表示できました

- 該当PMTilesファイル
  - https://protomaps.github.io/PMTiles/stamen_toner(raster)CC-BY+ODbL_z3.pmtiles
- IPFS上でのCID
  - v0
    - QmZBfbNBnjL4mwJbJGCUGkY7boFdaSvq7HLbn4AotNTUDd
  - v1
    - bafybeifbenkakr5rydaimwakpzqcsqrtboyv5or3pxvhrdpuvfvgbzhb5a
- 表示されている様子
  - https://protomaps.github.io/PMTiles/?url=https%3A%2F%2Fbafybeifbenkakr5rydaimwakpzqcsqrtboyv5or3pxvhrdpuvfvgbzhb5a.ipfs.dweb.link%2F#map=0.69/0/0


スクリーンショット
[![Image from Gyazo](https://i.gyazo.com/32e6265dbaba0e9ecae95c66188ed82d.png)](https://gyazo.com/32e6265dbaba0e9ecae95c66188ed82d)

**Comment by hfu** [comment]
いいですね！パブリックゲートウェイだとレートリミットが厳しくて、複数のタイルを近接したタイミングで取りに行くウェブ地図と相性が悪いようです。自分たちのウェブ地図用にゲートウェイを作るのが成功パターンになるように思っています。

**Comment by hfu** [comment]
# 惑星間大作戦 (The Inter-planetary Operation)
私の中では amx-project のスピンオフのように生まれた IPFS 活用でしたが、「クラウド最適化された地理空間情報のストレージとして IPFS を使うオペレーション」として一般化していきたいと思います。

そのコンセプトとしてタイトルの名前を考えています。

**Comment by hfu** [comment]
- 一つの大作戦（本来は grand strategy と訳すのかな）というよりは個別の作戦（operation）の集合であるというようなイメージのほうが勝ってきたので、複数形の operations に変更してみました。
- 名前としてはあまりパンチが効かない、特に IPO という名前は新規株式公開と紛らわしい、ので、IPO は仮称と理解することにします。これを明示するため、(beta) という表示を加えておきます。

**Comment by hfu** [comment]
→ #47 に継続。本件はクローズとする。
