### ISSUE TITLE
2023-03-02 Smart Maps Online Seminar in New York

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#74]
- [x] 共有可能な情報をここで共有する。
- [x] #73 で直前の感覚を共有する。

**Comment by ubukawa** [comment]
Here are the provisional agenda and the invitation letter!

[SmartMapOnlineSeminar-provisional agenda.pdf](https://github.com/UNopenGIS/7/files/10794395/SmartMapOnlineSeminar-provisional.agenda.pdf)
[SmartMapOnlineSeminar-Invitation letter.pdf](https://github.com/UNopenGIS/7/files/10794396/SmartMapOnlineSeminar-Invitation.letter.pdf)

**Comment by ubukawa** [comment]
There is a minor revision in the agenda (registration deadline was modified (adjusted with the invitation letter).)
[SmartMapOnlineSeminar-provisional agenda-r.pdf](https://github.com/UNopenGIS/7/files/10813148/SmartMapOnlineSeminar-provisional.agenda-r.pdf)

**Comment by ubukawa** [comment]
2月21日の国連オープンGIS 月例会でご案内しましたが、3月2日（米国東部時間）にSmart Maps Online Seminarを開催します。
会議は英語で行われますが、ご興味のあるかたは是非ご参加ください。

ーーー
日時：　2023年3月2日午前 10:00-11:30（米国東部時間 UTC-5）
形態：　オンライン
主催：　国連地理空間情報課、国連オープンGISイニシアチブ
後援：　国際連合日本政府代表部
![2023-02-23-announcement](https://user-images.githubusercontent.com/59204379/220921572-2c0732a0-4d07-4124-a102-5e6f4198e918.png)
参加費・登録：　参加費は無料です。参加を希望される方は、Emailで taro.ubukawa@un.org に連絡をお願いします（2/28まで)

コンセプトノート・暫定アジェンダはリンク先のとおりです。
案内レター：　https://github.com/UNopenGIS/7/files/10794396/SmartMapOnlineSeminar-Invitation.letter.pdf
暫定アジェンダ：　https://github.com/UNopenGIS/7/files/10813148/SmartMapOnlineSeminar-provisional.agenda-r.pdf
ーーー

よろしくお願いいたします。

**Comment by hfu** [comment]
#73 時点の最新版
[smart-maps-2023-03-02.pdf](https://github.com/UNopenGIS/7/files/10846021/smart-maps-2023-03-02.pdf)

**Comment by yuiseki** [comment]
連絡遅れましたが、先程参加申し込みのメール送らせていただきました。よろしくお願いします！

**Comment by hfu** [comment]
日本在住の皆様へ

時刻を確認しました。日本時間に換算すると、確かに 2023-03-03T00:00/01:30+09:00 でした。
