### ISSUE TITLE
2023-04-01 Open Source Conference 2023 Tokyo/Spring

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#76]
# UNVT Portable にデモ用コンテンツを積むためのイメージを作る

## Context and Problem Statement

- OSC に OSGeo.JP として出展する機会がある。
- そこには物理的なスペースがあり、インターネット接続がない。
- @smellman は地理院デザイン版の UNVT Portable を一機持っている。
- Smart Maps のオフラインでもができるイメージがあれば、それを使ってデモができる。

## Considered Options

* 何もしない
* UNVT Portable を持ち込む

## Decision Outcome

- UNVT Portable を持ち込むつもりで、イメージを作ることを考える

## TODO

- [x] どのようなハードウェア構成になるか整理共有する > @smellman 
- [x] クライアント（ブラウザ）はどこで動かすか判断する（別途持ち込んだ普通のPC？RPi完結？）> @smellman ※ RPi 完結であれば、WebGL の性能をあまり期待しない前提でコンテンツを選定する。
- [x] どのようなコンテンツを入れると効果的か、候補をリストアップしてみる > @hfu 
- [x] 既存のイメージ化技術がどのように適用できそうか整理共有する > @yuiseki

**Comment by hfu** [comment]
イベント情報を特定しました。
2023-04-01T10:00/16:00 東京都立産業貿易センター台東館での実施ですね。
https://event.ospn.jp/osc2023-spring/

**Comment by yuiseki** [comment]
#73 で話したことをメモっておきます

- 展示概要
  - MUNDOのUNMISSがRaspberry Piでスタンドアロンで動くカスタムOSイメージを作って持っていく
- ソフトウェアリソース（以下をベースに展示できるように準備する）
  - https://github.com/yuiseki/unvt-pi-gen
  - https://github.com/yuiseki/unmiss-map-vite
- 準備するハードウェア（仮）
  - USB Type-C電源
  - Raspberry Pi
  - ノートPC（これでデモをする）

**Comment by smellman** [comment]
https://ospn.connpass.com/event/271221/
参加人数把握のため、出展者も参加申し込みをお願いいたします。

**Comment by smellman** [comment]
https://connpass.com/event/278510/
非公式懇親会です。KoedoLUGが中心ですが、OSGeoにも案内が流れてます。

**Comment by smellman** [comment]
https://www.dropbox.com/s/c9xj2z5pfm63fyt/OSC2023_TokyoSpring_event_guide.pdf
当日のガイドが流れてきたので共有します。

**Comment by smellman** [comment]
> https://connpass.com/event/278510/ 非公式懇親会です。KoedoLUGが中心ですが、OSGeoにも案内が流れてます。

非公式懇親会、増枠されました。
Geoloniaの宮内さんも参加予定です！

**Comment by hfu** [comment]
おつかれさまでした！
