### ISSUE TITLE
🔥FOSS4G 2023 Community Review に参加する

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#95]
https://talks.osgeo.org/foss4g-2023/p/voting/signup/ via https://2023.foss4g.org/call-for-papers/

共有出来る情報がありましたら、こちらで共有してもらえるとうれしいです。

**Comment by hfu** [comment]
締め切りは明確には示されていない気がします。
https://twitter.com/foss4g/status/1631594881377353728

**Comment by yuiseki** [comment]
FOSS4G 2023 Community Review、とても勉強になりました。
たくさん気付いたことがあってちゃんと言語化して共有したいと思っているのですが、
とりいそぎ、以下二点共有します

- 日本からの発表者がたくさんいて、そのうちの大多数がUN Open GIS DWG-7関係者なのはあらためてすごい！
- 個人的に一番気になって聞きたい！と思ったのは以下です！
  - [![Image from Gyazo](https://i.gyazo.com/b01328ccc70c61b764478b9ab19a5871.png)](https://gyazo.com/b01328ccc70c61b764478b9ab19a5871)

**Comment by hfu** [comment]
偶然、今参加している Decentralized Geospatial Web Working Group にも Volker Mische が参加されていました。確かに、私たちの課題意識と近く、興味深いですね。ぜひプリズレンでお会いできればと思いました。
https://easierdata.org/dgwwg
https://twitter.com/vmx

**Comment by hfu** [comment]
私は終わらせました :-)

**Comment by hfu** [comment]
#89 が終わったら、このイシューは閉じます。
